### ISSUE TITLE
Some text will fail to be captured by stop sequences.  

### ISSUE THREAD

**Issue by pohunghuang-nctu** [huggingface/text-generation-inference#10]
Hi, 
   If checking with stop sequence by tokens, it would cause a problem, for example:
the index of ";" is 30, but index of "j;" is 93585, therefore, even we thought it should stop, but actually they are never equal while comparing token index. (https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation/utils.py#L85)

Suggest compare text, not tokens (maybe some overhead, but I thought it would be less confused.)
for example:
`
class StoppingCriteria:
    def __init__(self, tokenizer, eos_token_id, max_new_tokens=20, stop_sequences=None):
        self.tokenizer = tokenizer
        self.eos_token_id = eos_token_id
        self.max_new_tokens = max_new_tokens
        self.current_tokens = 0
        self.stop_sequences = stop_sequences

    def __call__(self, all_ids):
        self.current_tokens += 1
        if self.current_tokens >= self.max_new_tokens:
            return True
        if self.eos_token_id is not None and all_ids[-1] == self.eos_token_id:
            return True
        if self.stop_sequences is not None:
            all_str = self.tokenizer.decode(
                all_ids.squeeze(-1), skip_special_tokens=True)
            for s_str in self.stop_sequences:
                # too short to compare
                if len(all_str) < len(s_str):
                    continue
                # ids.shape == (N, 1)
                if all_str[-1 * len(s_str):] == s_str:
                    return True
        return False
`

**Comment by OlivierDehaene** [comment]
Should be fixed by #11

**Comment by pohunghuang-nctu** [comment]
Thanks for taking it and great efficiency.
