### ISSUE TITLE
Hello，How can I run text-generation-benchmark in docker？Thanks！

### ISSUE THREAD

**Issue by babytdream** [huggingface/text-generation-inference#1005]
### Feature request

nothing

### Motivation

nothing

### Your contribution

nothing

**Comment by josephrocca** [comment]
1. Start the docker container
```bash
docker run --gpus all --shm-size 1g -p 8080:80 -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id abacaj/starcoderbase-1b-sft
```

2. Run `docker ps` to get the name of the container.
3. Use the command `docker exec -it <ContainerName> /bin/bash` to get a bash shell in the container.

4. Install requirements:
```bash
apt update

# install some stuff that's required for later commands
export DEBIAN_FRONTEND=noninteractive && TZ=Etc/UTC apt-get -y install tzdata
apt install -y git curl unzip libssl-dev pkg-config

# install protobuf:
PROTOC_ZIP=protoc-3.14.0-linux-x86_64.zip
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP

# install rust:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source "$HOME/.cargo/env"

# clone repo:
cd /usr/src
git clone --depth 1 --branch v1.0.3 https://github.com/huggingface/text-generation-inference

# remove parts of the repo that this docker image already has, then put the rest in its proper place
cd text-generation-inference
rm -r proto
rm -r server
mv * ../
cd ../
rm -r text-generation-inference

# build the benchmark binary:
make install-benchmark
```
5. Run the benchmark:
```
text-generation-benchmark --tokenizer-name abacaj/starcoderbase-1b-sft --sequence-length 1024 --decode-length 256
```
See all params for benchmark [here](https://github.com/huggingface/text-generation-inference/blob/main/benchmark/src/main.rs).

**Comment by babytdream** [comment]
@josephrocca Thanks for your help!
This is my docker command:
`docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id upstage/SOLAR-0-70b-16bit --max-input-length 6000 --max-total-tokens 6500  --max-batch-prefill-tokens 20000`
How much should I set should I set `--sequence-lengt`h and `--decode-length`?

**Comment by josephrocca** [comment]
I think it makes sense to set sequence length (i.e. number of tokens in the input) and decode length (i.e. number of tokens in the response) to whatever the average values of those numbers would be in your use case / application. If you expect very short inputs and long outputs, then e.g. you could set `--sequence-length 128` and `--decode-length 1024`. You can convert text to tokens here: https://huggingface.co/spaces/Xenova/the-tokenizer-playground Select the LLaMa-2 tokenizer and then try pasting some example input and outputs in there to see their size.
