### ISSUE TITLE
gptq support

### ISSUE THREAD

**Issue by FrankWhh** [huggingface/text-generation-inference#1006]
i try to set model-id as "*GPTQ", and it meet error " optimum, auto-gptq is requeired". the docker image version is 1.0.3, i check the pip list, both haven't installed.
```
  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2491, in from_pretrained
    raise ImportError(

ImportError: Loading GPTQ quantized model requires optimum library : `pip install optimum` and auto-gptq library 'pip install auto-gptq'
```
have you meet this issue？

**Comment by Narsil** [comment]
I think you forgot `--quantize gptq`.

Otherwise please fill in the full issue template.

**Comment by Narsil** [comment]
please fill in the full issue template.
