### ISSUE TITLE
Batch generate?

### ISSUE THREAD

**Issue by wj210** [huggingface/text-generation-inference#1008]
### System Info

Hi, i like to ask if it is possible to do batch generation? 

`client = Client("http://127.0.0.1:8081",timeout = 60)
gen_t = client.generate(batch_text,max_new_tokens=64)`

generate can only take strs, is there anyway I can do batch inference? or is tgi just meant for single queries?

Thanks!

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

shown above

### Expected behavior

single inference only instead of batch

**Comment by LopezGG** [comment]
I see a lot of code when I search for batch but cant find a way to do it. I thought if I send async calls, it would batch at the server automatically. But the runtime for 1200 requests did not reduce, so that obviously wasn't the way

**Comment by LopezGG** [comment]
A lot of folks talk about batch_size in the issues. I am not sure batching works. It might be good to have some documentation on it. In the meantime, based on https://github.com/huggingface/text-generation-inference/issues/736#issuecomment-1658559657 It looks like sending a list of prompts as a batch is not supported

**Comment by wj210** [comment]
I did try async calls and it was faster based on my implementation.

`def gen_text(text):
    return client.generate(text,max_new_tokens=128).generated_text
 with concurrent.futures.ThreadPoolExecutor(max_workers=bs) as executor:
        out = list(executor.map(gen_text,batch_text))`

Did you do something similar?

**Comment by LopezGG** [comment]
Thanks @wj210. I'll give it a try and get back to you

**Comment by Narsil** [comment]
TGI runs continuous batching: https://github.com/huggingface/text-generation-inference/tree/main/router#simple-continuous-batching

Therefore sending multiple requests concurrently can leverage it. We do no plan to support sending lists of requests (it messes up return types quite a bit and doesn't unlock any super valuable speedups)
