### ISSUE TITLE
PyTorch uses AVX2 even when loading onto GPU

### ISSUE THREAD

**Issue by Cyberes** [huggingface/text-generation-inference#1009]
### System Info

Version: `ghcr.io/huggingface/text-generation-inference:latest`
Model: `TheBloke/MythoMax-L2-13B-GPTQ:gptq-4bit-128g-actorder_True`
GPU: Nvidia A4000
Ubuntu 22.04

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Issue

In the course of debugging https://github.com/huggingface/text-generation-inference/issues/929, I discovered that PyTorch is using AVX2 instructions even when loading the model onto the GPU. `nvidia-smi` shows that the model appears to be loaded to the GPU and I assume that this exception is thrown immediately after the model is loaded. I tried disabling custom kernels.

`dmesg` shows this:
```
traps: text-generation[1713525] trap invalid opcode ip:7fb007be3a0e sp:7ffff8a730a0 error:0 in rotary_emb.cpython-39-x86_64-linux-gnu.so[7fb007bd3000+1d000]
```

I've used PyTorch extensively on this server and never encountered an illegal instruction error during the countless model loads.

It would be great if TGI could support older CPUs.

**Comment by Narsil** [comment]
> rotary_emb.cpython-39-x86_64-linux-gnu.so

That's `layer_norm` kernel from flash attention there.

> It would be great if TGI could support older CPUs.

I think you should try just rebuilding the CLI from source and everything should work out of the box if the compilation is not too bad. Unfortunately we cannot distribute a non AVX docker image since most users will actually have AVX.
