### ISSUE TITLE
Repeated response from falcon 40B

### ISSUE THREAD

**Issue by kbmlcoding** [huggingface/text-generation-inference#1011]
### System Info

tesla v100 32GB x 4 
248GB RAM
Centos 7
model=models--tiiuae--falcon-40b-instruct

I am getting below repeated repsone. Same goes for different prompt as well where i get one keyworkd repeated response.. What could be the reason. I did notice texte-generation-inference did converted weights file (.bin to safetensors) wonder if that might have caused this? I did not however encountered any error downloading or converting the files to safe tensors

 curl 127.0.0.1:8080/generate \
>     -X POST \
>     -d '{"inputs":" write python code to sort list  ","parameters":{"max_new_tokens":200}}' \
>     -H 'Content-Type: application/json'

{"generated_text":"\n and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and and"}

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

model=models--tiiuae--falcon-40b-instruct

docker run --gpus all --shm-size 4g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id $model 

### Expected behavior

output should be python code

**Comment by Narsil** [comment]
This is because you're using V100 and it falls back on the remote code: https://huggingface.co/tiiuae/falcon-40b/blob/main/modelling_RW.py which happens to be buggy.

If you can find a GPU > V100 that would be gone, we're also going to upgrade that code at some point, but it's taking a bit of time because of breaking backward compatiblity
