### ISSUE TITLE
cannot set "gptq" as model_id type 

### ISSUE THREAD

**Issue by FrankWhh** [huggingface/text-generation-inference#1012]
### System Info

text-generation-inference:latest
python：3.9.11
platform：centos、V100、CU117

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker run --gpus "device=0" --shm-size 1g -p 4011:80 -v /data1:/data1  
ghcr.io/huggingface/text-generation-inference:latest --model-id /data1/chat_model/Phind-CodeLlama-34B-v2-GPTQ --quanti
ze gptq 

### Expected behavior

  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2491, in from_pretrained
    raise ImportError(

ImportError: Loading GPTQ quantized model requires optimum library : `pip install optimum` and auto-gptq library 'pip install auto-gptq'

**Comment by FrankWhh** [comment]
and after install optimum and auto-gptq in docker, another issue appeared：

  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3245, in from_pretrained
    model = quantizer.post_init_model(model)

  File "/opt/conda/lib/python3.9/site-packages/optimum/gptq/quantizer.py", line 469, in post_init_model
    raise ValueError(

ValueError: Found modules on cpu/disk. Using Exllama backend requires all the modules to be on GPU.You can deactivate exllama backend by setting `disable_exllama=True` in the quantization config object

**Comment by FrankWhh** [comment]
set ```--model-id /data1/chat_model/Phind-CodeLlama-34B-v2```  is ok.

**Comment by manishiitg** [comment]
getting the same issue

**Comment by manishiitg** [comment]
any update on the fix

**Comment by mckbrchill** [comment]
same issue, while running like:
`sudo docker run --shm-size 1g --gpus all -p 8080:80 -v $volume/data:/data -e GPTQ_BITS=4 -e GPTQ_GROUPSIZE=32 -e HF_HUB_ENABLE_HF_TRANSFER=1 -e HUGGING_FACE_HUB_TOKEN=$token ghcr.io/huggingface/text-generation-inference:latest --model-id TheBloke/Phind-CodeLlama-34B-v2-GPTQ --revision gptq-4bit-32g-actorder_True --quantize gptq`

and with `TheBloke/WizardCoder-Python-34B-V1.0-GPTQ`
it hangs on:
`2023-09-20T06:57:58.471018Z  INFO download: text_generation_launcher: Starting download process.
2023-09-20T06:58:03.727667Z  INFO text_generation_launcher: Download file: model.safetensors`

**Comment by mckbrchill** [comment]
Any updates on the problem?
@FrankWhh Did you manage to solve this somehow?

**Comment by mckbrchill** [comment]
I guess it's because on V100 (which i'm currently using) Flash Attention is not supported - so all the backend falls into CasualLM, not into flash implenetation for different model formats (ExLLama for example).
Does this mean that I won't be able to load GPTQ models on V100?

**Comment by Narsil** [comment]
@FrankWhh V100 cannot use flash and it's unlikely to get there.

Not using flash means using padded tensors which have very adverse effect on overall usage for the GPU when you're going to have load/prompts of highly varying lengths.

You could use the raw CLI and just installing `optimum` and `autogptq` for it to work. We may add them as dependencies later, but this is not really a priority since this is considered graceful degradation code (not running flash is really not getting the most benefit of using vllm or tgi)

**Comment by HenryYuen128** [comment]
> and after install optimum and auto-gptq in docker, another issue appeared：
> 
> File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3245, in from_pretrained model = quantizer.post_init_model(model)
> 
> File "/opt/conda/lib/python3.9/site-packages/optimum/gptq/quantizer.py", line 469, in post_init_model raise ValueError(
> 
> ValueError: Found modules on cpu/disk. Using Exllama backend requires all the modules to be on GPU.You can deactivate exllama backend by setting `disable_exllama=True` in the quantization config object

Hi @FrankWhh , how do you install the optimum and  auto-gptq in docker, i am struggling in this, thanks

**Comment by FrankWhh** [comment]
@HenryYuen128 i turned to do inference with VLLM. Recently, I didn't try the TGI.

**Comment by HenryYuen128** [comment]
> @HenryYuen128 i turned to do inference with VLLM. Recently, I didn't try the TGI.

Thanks. I am trying to use this with PandasAI.
