### ISSUE TITLE
Support YaRN models (RoFormer implementation in rotary_embedding kernel)

### ISSUE THREAD

**Issue by kevaldekivadiya2415** [huggingface/text-generation-inference#1017]
### Feature request
@OlivierDehaene
Nous Research and EleutherAI have recently released the **YaRN** model, which comes in two versions with context sizes of 64k and 128k. This model utilizes RoFormer-style embeddings, distinguishing it from GPT-NeoX and GPT-J. It is built upon the foundation of the LLaMa 2 model, making it largely compatible with some minor adjustments required for optimal support.

### Motivation

The **YaRN** model's longer context length (up to 128k) is highly valuable for tasks involving extensive context, compared to the limited 4096 context length of the llama2 base model.

### Your contribution

YaRN paper: [YaRN: Efficient Context Window Extension of Large Language Models](https://arxiv.org/pdf/2309.00071.pdf)
YaRN Code: [YaRN Github](https://github.com/jquesnelle/yarn)

**Comment by Bec-k** [comment]
+1 that would be awesome
there are models The Bloke hub:
For **7b Llama 2**: https://huggingface.co/TheBloke/Yarn-Llama-2-7B-128K-GPTQ
For **13b Llama 2**: https://huggingface.co/TheBloke/Yarn-Llama-2-13B-128K-GPTQ

Both originating from:
https://huggingface.co/NousResearch/Yarn-Llama-2-7b-128k
https://huggingface.co/NousResearch/Yarn-Llama-2-13b-128k

**Comment by kir152** [comment]
+1

**Comment by zhongwei1968** [comment]
+1

**Comment by sadransh** [comment]
+1

**Comment by jqueguiner** [comment]
+1

**Comment by Narsil** [comment]
Just created a PR for it: https://github.com/huggingface/text-generation-inference/pull/1099

However the GPTQ models don't  seem to be working correctly (NousResearch ones seem ok).
If anyone can take this implementation for a spin that'll help figuring out the probable bug.
