### ISSUE TITLE
TGI change inference result 

### ISSUE THREAD

**Issue by PaynatPierre** [huggingface/text-generation-inference#1021]
Hello everyone,

I implement a TGI server with Rope scaling and my inference result are completely different with TGI and without TGI. do you know if it's a common problem and how can I solve it ?

**Comment by Narsil** [comment]
Without further information it's impossible to help you.

What are you doing, what's your reference, which is better ?

Also just fill in the classic template it really helps us understand your environment your are running on.

I will go ahead and close this, but please re-open an issue with the more complete information and we can look at what's going on.
