### ISSUE TITLE
Minimal MyPy support

### ISSUE THREAD

**Issue by Vinno97** [huggingface/text-generation-inference#1025]
### Feature request

I think it's  a good idea to add some (minimal) MyPy checks tot the project and CI. At least to check that functions are called with the correct arguments 

### Motivation

It's infeasible to check all code paths manually when adding a new feature. This is especially difficult as TGI implements custom code for many different models. Most recently, #1004 identified that the Galactica's batch overrode the `from_pb` function, which I didn't consider when implementing my `top_n_tokens` function. 

### Your contribution

Adding full "mypy-compliant" typing to a project like this, could be more of a hassle than it's worth. But I wrote a very minimal configuration which ignores all typing-related errors.

```toml

[tool.mypy]
disable_error_code = [
  "arg-type",
  "var-annotated",
  "import",
  "assignment",
  "method-assign",
  "index",
  "misc",
  "union-attr",
  "call-overload",
  "return-value",
  "operator",
  "attr-defined",
  "override",
  "has-type",
  "valid-type",
]
strict_optional = false
````

I used it to check the codebase and found a couple more potential issues. 

```sh
$ mypy text_generation_server/models/                                             
text_generation_server/models/custom_modeling/t5_modeling.py:1066: error: Name "__HEAD_MASK_WARNING_MSG" is not defined  [name-defined]
text_generation_server/models/custom_modeling/opt_modeling.py:446: error: Missing positional argument "weights" in call to "load" of "FastLinear"  [call-arg]
text_generation_server/models/custom_modeling/opt_modeling.py:453: error: Missing positional argument "weights" in call to "load" of "FastLinear"  [call-arg]
text_generation_server/models/custom_modeling/idefics_modeling.py:548: error: Name "logger" is not defined  [name-defined]
Found 4 errors in 3 files (checked 36 source files)
```

Later on, we could incrementally include some more rules like `valid-type`, which makes sure that if you explicitly opt into typing, the typing is at least correct.

---

If you agree on including this, I'll write a PR for the config

**Comment by Narsil** [comment]
I have mixed experience with mypy.

It's better than nothing, and did help find some bugs early (like the ones you're pointing to).
But it also have lots of false positives (especially when shadowing variable types), whih feel
