### ISSUE TITLE
Add Support for Cuda 12.1 and Pytorch 2.2

### ISSUE THREAD

**Issue by NiklasWilson** [huggingface/text-generation-inference#1032]
### Feature request

Upgrade the DockerFile to use or support CUDA 12.1 and Pytorch 2.2 to greatly improve performance for lovelace Nvidia graphics cards.

### Motivation

Lovelace nvidia graphics cards such as the H100, L40, and 4090 run slower than they should on the default text-generation-inference install due to the older version of CUDA and Pytorch. Upgrading to CUDA 12.1 and Pytorch 2.2 will increase tokens per second by about 20% based on my own testing.

### Your contribution

So far my attempts to do this myself have failed due to different compiling steps such as the Fast Attention V2 compile, if I solve this issue myself I will post a PR.

**Comment by Narsil** [comment]
Python 2.2 is not out yet afaik : https://pytorch.org/get-started/locally/ (are they going to skip 2.1 ?)

We're trying to stick with released versions of Pytorch, because tgi is run on many devices, and making sure it works correctly on all environments is already non trivial.

But thanks for sharing, I'm sure it can help others.

**Comment by NiklasWilson** [comment]
Yes it seems they are skipping 2.1. the nightly build is on 2.2
The pip3 and/or conda installs both uses 2.2 with cuda 12.1

conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch-nightly -c nvidia
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

2.0 lacks important improvements needed unlock the gains from the newer generation GPUs.
I have been unable to get the newer pytorch working with the Fast Attention build steps, if someone could help get this working it would be appreciated.

The Fast Attention Build also seems to be using a branch that was last updated over a year ago, which may also unlock more performance but that is just a theory.

**Comment by stefanobranco** [comment]
I believe the nightlies were on 2.2 already because 2.1 was already essentially finished. Since 2.1 is [out now](https://pytorch.org/blog/pytorch-2-1/), I'd love to see this happen, since more than just performance, some things just won't work on 2.0  (#1101 for example).

**Comment by Narsil** [comment]
We moved to 2.1 and Cuda 12.1.

Docker release 1.2.0 will be done today.
