### ISSUE TITLE
huggingface/tokenizers: The current process just got forked ...on calling the model

### ISSUE THREAD

**Issue by yairVanti** [huggingface/text-generation-inference#1035]
### System Info

text-generation-inference latest version (1.0.3)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

run on A100 machine on GCP this:

model=WizardLM/WizardCoder-Python-34B-V1.0
volume=$PWD/data
TOKENIZERS_PARALLELISM=false
token={my token here}
sudo docker run -d --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --max-total-tokens 4096 --max-input-length 3000 --quantize bitsandbytes --json-output --model-id $model

got this in the response (seems like warning) , even though i have set TOKENIZERS_PARALLELISM to false.
how can i avoid it ?

`huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)`

### Expected behavior

i expect no such warning/error in the response.

**Comment by Narsil** [comment]
Ohhh, it's forking because you're daemonizing docker. 

I don't undertand why it's a fork, but I think it's safe to ignore.

**Comment by Narsil** [comment]
(Also don't run docker as `sudo` it's quite dangerous)
