### ISSUE TITLE
Ability to cancel generation requests while they're underway

### ISSUE THREAD

**Issue by josephrocca** [huggingface/text-generation-inference#1040]
### Feature request

Kind of like continuous batching, but for removing items from the batch in real-time, I guess? Not sure how technically difficult this is. **Edit:** Although now that I think about it, it seems like it should be pretty easy - it's just "emulating" the situation where the LLM produces a stop token - and all the code for that is obviously already written.

### Motivation

The ability to stop an inference is useful in situations where the initial text being generated is clearly not what the user wanted, or where they suddenly changed their mind. Otherwise they have to wait up 20 seconds or so (in my case) for the previous generation to finish before they can submit another request.

### Design

Ideally I'd just be able to send a simple HTTP request with an ID that I passed to the original generation request, or something like that.

For example, starting the request:
```
curl http://localhost:8080 \
        -X POST \
        -d '{"inputs": "Once upon a time", "id":1234}' \
        -H "Content-Type: application/json"
```
and to cancel it:
```
curl http://localhost:8080/stop \
        -X POST \
        -d '{"id":1234}' \
        -H "Content-Type: application/json"
```
But maybe there's a better way - anything that's roughly as ergonomic as that would suit me.

### Your contribution

I likely won't be able to contribute to this unless there's an JS work that needs to be done.

**Comment by olegklimov** [comment]
> to cancel it: curl http://localhost:8080/stop

Usually this works with streaming on. You can hit Ctrl+C that stops curl, server in turn sees socket close (or HTTP/2 cancel in more serious applications). There is no need for a `/stop` with id.

To test this, you can try several other HTTP servers, FastAPI streaming hello world (cancel works even through ngnix for FastAPI), openai API.

(by streaming I mean `"stream": true` in the request, also known as server-side events)

**Comment by Narsil** [comment]
Indeed it' s already implemented on connection closed. So it also handles rogue connection cuts etc..

**Comment by SMAntony** [comment]
> Indeed it' s already implemented on connection closed. So it also handles rogue connection cuts etc..

I am using HuggingfaceEndpoint by Langchain, how do I implement this?
