### ISSUE TITLE
Huge memory allocation

### ISSUE THREAD

**Issue by Tejaswgupta** [huggingface/text-generation-inference#1051]
### System Info

Text generation Interface command: 
`sudo docker run --gpus all --shm-size 1g -p 8080:80 -e NVIDIA_DISABLE_REQUIRE=true -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id Tejasw1/votum-13b-v1 --quantize bitsandbytes-nf4 --max-input-length 4000 --max-total-tokens 4096`

Nvidia-smi:
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          On  | 00000001:00:00.0 Off |                    0 |
| N/A   37C    P0              62W / 300W |  79953MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1109      G   /usr/lib/xorg/Xorg                          130MiB |
|    0   N/A  N/A      1443      G   /usr/bin/gnome-shell                         12MiB |
|    0   N/A  N/A      9986      C   /opt/conda/bin/python3.9                  79780MiB |
+---------------------------------------------------------------------------------------+

Cloud: 
Azure , Ubuntu 20 , 

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

The model is 13B + quantized it should be around 11-12GB (when I was using on azure notebooks). Whereas running on VM it's using the entire GPU memory i.e 80GB. 

I am planning to run it on a smaller hardware(24GB) later on, would this issue still be there?

### Expected behavior

Utilizes only min required memory

**Comment by Vinno97** [comment]
TGI uses all available RAM for its cache. If you want to use less, you can use the `--cuda_memory_fraction` launcher option or `CUDA_MEMORY_FRACTION` env variable to limit it. 
For your situation: if you know the model fits on the GPU, it's fine
