### ISSUE TITLE
sequence_bias

### ISSUE THREAD

**Issue by vinnitu** [huggingface/text-generation-inference#1062]
### Feature request

can we use feature of huggingface sequence_bias

https://huggingface.co/docs/transformers/internal/generation_utils#transformers.SequenceBiasLogitsProcessor.sequence_bias

?

### Motivation

to get control generation through a bias

### Your contribution

I'd like to, but I don't know how.

**Comment by abhinavkulkarni** [comment]
Hey @vinnitu,

We are tracking a similar request at https://github.com/huggingface/text-generation-inference/issues/1062
