### ISSUE TITLE
Is there a way to get the logprobs of the prompt along with the generated tokens ?

### ISSUE THREAD

**Issue by codedecde** [huggingface/text-generation-inference#1069]
### Feature request

Is there a way to get the log probabilities of the prompt alongside with the completion (similar to the behaviour of `echo=True` from the OAI API). 

For example, consider the following payload

```json
{
    "inputs": "Is Deep Learning awesome? Yes.", "parameters":{"max_new_tokens":1, "details": true}
}
```
The current output would be 
```json
{
    "generated_text": "Is",
     "details": {
         "finish_reason": "length",
         "generated_tokens":1,
          "seed":null,
          "prefill":[],
           "tokens":[{"id":1317,"text":" Is","logprob":-1.1894531,"special":false}]
       }
}
```
Would it be possible to get the log probs of the "Is Deep Learning awesome" prompt ? 

### Motivation

The main motivation comes from trying to get log probs from the model after teacher forcing. This is particularly useful for Multiple Choice Questions (as done in lm eval harness). 
So in the above example, if I wanted to check the probability of "yes" vs "no", the (albeit roundabout way) to do that is 

```python
logp_yes = logprob("Is Deep Learning awesome? Yes.") - logprob("Is Deep Learning awesome?")
logp_no = logprob("Is Deep Learning awesome? No.") - logprob("Is Deep Learning awesome?")
logp_yes > logp_no
```

### Your contribution

Would need to take a look (am not very familiar with this codebase).

**Comment by Narsil** [comment]
`decoder_input_details`. This prevents some other flags but should fit your use case.

**Comment by krrishdholakia** [comment]
Hey @codedecde LiteLLM supports translation between openai's completion endpoint and tgi's generate endpoint (including support for echo=true)

```python
from litellm import text_completion
response = text_completion(
    model="huggingface/bigcode/starcoder", 
    prompt="good morning", 
    max_tokens=10, logprobs=10,
    echo=True
)
```

https://docs.litellm.ai/docs/providers/huggingface#viewing-log-probs
