### ISSUE TITLE
TGI Generating  garbage output for llama-2 7b 4 bit model.

### ISSUE THREAD

**Issue by evilc3** [huggingface/text-generation-inference#1072]
### System Info

`text-generation-launcher --env`

`2023-09-28T08:27:46.204623Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 2f51645ad7274f8d533a211804b74507263a946c
Docker label: N/A
nvidia-smi:
Thu Sep 28 13:57:46 2023`    

GPU : one v100 32gb

Command used to generate the quantised model. `text-generation-server quantize meta-llama/Llama-2-7b /GPTQ/Llama-2-7b_gptq`

Command used to start the server : `GPTQ_BITS=4 GPTQ_GROUPSIZE=128 text-generation-launcher --model-id Llama-2-7b_gptq/ --port 8080 --quantize gptq`

with an without `GPTQ_BITS=4 GPTQ_GROUPSIZE=128` output stays same.

TGI Version: installed from current main branch.

For simple query "why is the sky blue?"

Output generated : `iguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguiguigu`

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Follow the local installation section from

1. https://huggingface.co/docs/text-generation-inference/installation
2.  quantisation and running section from here: https://huggingface.co/docs/text-generation-inference/conceptual/quantization

### Expected behavior

not a gibberish answer.

**Comment by HarmonyTechLabs** [comment]
Try setting the flag --rope-scaling dynamic on launch.

**Comment by Narsil** [comment]
Have you tried using another already quantized version of GPTQ ?

We're going to deprecate this quantization script (it had it's purpose before the GTPQ ecosystem had settled, now we recommend using https://github.com/PanQiWei/AutoGPTQ which TheBloke is using.)
The trick is that the quantization itself has many knobs and switches, and some require more work to make the best possible quantization.
Although here it should definitely not output giberrish, we're not going to have time to investigate and fix since that scripts is going away anyway.
