### ISSUE TITLE
Support for HF Chat templates? 

### ISSUE THREAD

**Issue by krrishdholakia** [huggingface/text-generation-inference#1082]
Hi @Narsil @osanseviero @merveenoyan, 

Do models (e.g. mistral instruct 7b) come with support for hf chat templating? https://huggingface.co/docs/transformers/main/chat_templating

Wondering what the format of the prompt i need to pass to hf tgi is (i.e. do i do apply chat templates **before** calling the server or does the server handle it for me)

**Comment by krrishdholakia** [comment]
also if there was a list of models we can see support exists for chat templating, that'd be amazing (maybe via tag? on hf)

**Comment by Narsil** [comment]
No we don't.

We're currently set on not supporting it/using it. The chat template is very practical, but we know it's probably bound to have some limitations compared to the kind of templating that will likely be invented.

We also want to limit the feature creep in text-generation-inference, therefore for now we think it's a client thing to format the string according to the model.

We might revisit later at some point, but currently this is not going to be added.

**Comment by osilverstein** [comment]
@Narsil shortsighted i do think. scope creep here enables important features like guidance

**Comment by cringelord000222** [comment]
> @Narsil shortsighted i do think. scope creep here enables important features like guidance

I'm currently using TGI - Messages API (v1/chat/completions), but I certainly do hope TGI could apply the prompt template itself when calling "/generate".
