### ISSUE TITLE
Inference with  Llama 2 70B 8bit eetq causes entire server/operating system to crash

### ISSUE THREAD

**Issue by rimon15** [huggingface/text-generation-inference#1083]
### Command:
`model=/data/Llama-2-70b-chat-hf`
`volume=$PWD/models`

`docker run --gpus all --shm-size 50g -p 8888:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model --num-shard 4 --quantize eetq --max-input-length 3500 --max-total-tokens 4096 --cuda-memory-fraction 1.0`

### OS
CentOS Stream 9
kernel 5.14.0-344.el9.x86_64

### Hardware
4x NVIDIA 4090
![image](https://github.com/huggingface/text-generation-inference/assets/13021996/a82b7c05-4dbc-426d-8fb5-7b1fe69e3759)
CPU: AMD Epyc 7542 32 cores
RAM: 256GB

### Current version being used
Latest docker image with eetq fixed
https://github.com/huggingface/text-generation-inference/pull/1081

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

It seems that the entire system crashes if the context length is above a certain threshold. For example, I tried around 1500 tokens context, and it worked fine, however after increasing it to > 2000, the entire system crashes and the server shuts down. With other models (like 34B codellama), everything works as expected with no crashes with longer context length. 

### Expected behavior

The entire operating system does not crash, and the image fails gracefully...

**Comment by Narsil** [comment]
Do you have any kernel logs anywhere ?

The entire system crash seems to point to:

- Kernel bug
- Driver bug 

Both would be pretty bad anyway. At worst you should get some kind of segfault.
If you can provide any sort of log that might help.

**Comment by rimon15** [comment]
There was nothing useful in the journal log, and no crash coredump available. I'm certain the issue only occurs after a certain input sequence length is exceeded. Unfortunately I can't afford to keep crashing the system, but if I have some time later this week I will try to investigate further. Perhaps this can be replicated with the same GPU configuration by someone else?
