### ISSUE TITLE
LongLora Support

### ISSUE THREAD

**Issue by rokset3** [huggingface/text-generation-inference#1087]
### Model description

Is it possible to use LongLora implementation with TGI?

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://arxiv.org/pdf/2309.12307v1.pdf

**Comment by Narsil** [comment]
TGI doesn't "support" loras out of the box (yet, we have ideas, not sure if/when we will implement).

Loras are currently supported via `peft` and we simply load the entire model + LORA, fuse them and use the model directly.
When peft supports longlora then TGI will pretty much automatically https://github.com/huggingface/peft/issues/958 (Supposing the technique allows for fusion).
