### ISSUE TITLE
Allow setting max_new_tokens = 0 in order to tokenize only

### ISSUE THREAD

**Issue by LoganDark** [huggingface/text-generation-inference#1088]
### Feature request

Allow max_new_tokens = 0 rather than returning a "max_new_tokens must be strictly positive" error. Return all the prompt tokens in prefill as normal, but an empty tokens array, as the model was not actually executed.

### Motivation

For prepending information to the beginning of the context window, it is vital to be able to properly tokenize the context rather than just guessing based on character length. However, right now, it seems impossible to only tokenize text using this server, because you MUST request at least one additional token, even if that token is not needed yet. That requirement could probably easily be lifted - then clients could use a zero-token request in order to obtain the tokens of the prompt, which can be further processed before sending the final prompt for generation.

### Your contribution

This change sounds trivial enough that I might be able to open a PR without having to create a dev environment

**Comment by Narsil** [comment]
> For prepending information to the beginning of the context window, 

Could you expand on what you are doing exactly ?
Currently, we think if a user need tokenization on the client (for instance to count tokens) it's actually better done using the tokenizer directly in the client (avoids network which is good in general when it can be avoided).

If you expanded a bit what's the current problem you're trying to solve we might have a better way of doing it than sending queries just to get tokenized.

**Comment by Narsil** [comment]
> Being able to operate an LLM running remotely is a tangible benefit of separating client from server, and I'd hate to lose that just for tokenization.

Yet you are willing to do a lot of manipulation locally before sending requests to the server.

I am really empathetic with what you're trying to achieve, yet I still think we shouldn't implement it on our end (nor the generate 0 tokens hack).
We're currently already feeling the feature creep, and new cool features pop up literally every week and yet we do not have the time to implement everything. 

In the same vibe as your request we've been asked (even internally) to support chat format which we refused for the same reasons, and same for code/code-infilling. There's clearly a lot of clever pre-prompting that needs to be done to get the maximum out of LLMs, and yet the amount of possible ways to do this is exploding.
We feel it's not TGI's job to do them at all at this time. We're currently focusing on shipping things like new features/faster inference, more hardware support and that's already taking most of our time.

If said preprompting is relatively simple to do on the client side and doesn't hurt too much performance wise, we'd rather go with this. I hope you understand our stance.
Making the PR shouldn't be too hard btw, so if you want to create one and share it that could be a way for us to gauge interest and maybe merge later if there's enough demand.

Cheers !

**Comment by LoganDark** [comment]
> Yet you are willing to do a lot of manipulation locally before sending requests to the server.

That's not the same thing. This is pretty general - it doesn't matter how the tokenizer is implemented as long as it translates text into tokens. I just don't want to have to special-case every possible tokenizer, and either implement them all or depend on piles of Python for what is in the end a Rust project (just like this one).

Again, I don't mind doing token manipulations locally but I simply can't expect to be able to support every possible tokenizer like this server does, and it would be incredibly annoying and a waste of time to do so.

> If said preprompting is relatively simple to do on the client side and doesn't hurt too much performance wise, we'd rather go with this. I hope you understand our stance.

I have literally no idea how I am supposed to do this without implementing special cases for every possible model. This is not the same as assembling the prompts from pieces on the server, or supporting chat or anything - this is simply giving clients access to the tokenizer that is already running on the server, without forcing said clients to concern themselves with exactly which model is running and exactly which tokenizer they should run on their local machine in order to hopefully mirror the same tokenization that is happening on the server.

**Comment by LoganDark** [comment]
Hey, has any thought been put into this use-case lately? I want to be able to use this server for storywriting, but that won't be possible until there's an efficient way to use the full context, and that will require being able to tokenize the prompt. I don't want to have to add specialized client-side code for running the tokenizer locally when the server already has it loaded - even if this is not the best possible solution, it is certainly the easiest, as it would only require relaxing a single check that is stricter than it could be.

Is there anything else that you think could work, without causing undesirable feature creep / tech debt for the server?

**Comment by OlivierDehaene** [comment]
With the `details` and `decoder_input_details`args you get back the prompt tokens and completion tokens, so that's already a lot of info you can use.

My answer is the same as Nicolas: just write a WASM module that pings the `/info` route, get back the model ID and loads the corresponding tokenizer client side. 
We have a tutorial [here](https://github.com/huggingface/tokenizers/tree/main/tokenizers/examples/unstable_wasm) and you can just use `Tokenizer.from_pretrained(model_id)` to get the correct one.

**Comment by LoganDark** [comment]
> With the details and decoder_input_detailsargs you get back the prompt tokens and completion tokens, so that's already a lot of info you can use.

that's not what I am asking. Yes it's true that I can get the prompt tokens after the model has already generated a completion. But I cannot even know what context to send to be completed without being able to tokenize it first. Because I need to ensure things are present at both the beginning and end of the context window, and it's impossible to do that without knowing the tokens.

> My answer is the same as Nicolas: just write a WASM module that pings the /info route, get back the model ID and loads the corresponding tokenizer client side.

where does WASM come into this? This is a Rust client. I don't want to have to shell out to Python to run the tokenizer client-side when I should just be able to send a request to the inference server that already has the tokenizer loaded properly.

And then there's no possibility of desyncs where the client ever doesn't support the tokenizer that the server is using, because the server will always be the one doing the tokenization then.

Why is there so much pushback against this? BTW, if you're not going to solve my problem then mark the issue as won't fix, please.

**Comment by LoganDark** [comment]
I'm going to implement this anyway as it's necessary for my use-case.

if you don't want it because it's too much feature creep for the library then I don't care. I'll open a PR anyway, and you will be free to nuke it from orbit if you still think clients should still be required to do all the work themselves.

I just think it hurts the utility of an inference server if clients are still required to look up and download the models.

**Comment by OlivierDehaene** [comment]
First, calm down. 

>  I don't want to have to shell out to Python to run the tokenizer client-side

You don't have to. We have rust implemnetations of the tokenizers. You can bundle them in wasm or it seems you don't even have to build a WASM module, just use [Transformers.js](https://huggingface.co/docs/transformers.js/api/tokenizers) from my colleague @xenova.

> where the client ever doesn't support the tokenizer that the server is using

We use the same library in the server.

> The client should not have to care which model the server is using and load model-specific code! That's the server's job! 

We disagree.
Pinging a remote server to run a tokenizer is non-sense. Also the tokenizer is shared between all users. We do not want a noisy neighbor situation were apps start bottlenecking everybody to tokenize.

> download the models.

No, you only download a `tokenizer.json` file.

**Comment by LoganDark** [comment]
> First, calm down.

this just doesn't make much sense to me. I don't want to duplicate this code in the client or be tied to only huggingface models. Or make the user specify a tokenizer.json manually. That's a huge amount of trouble for what could have been a simple api request.

> We use the same library in the server.

Forward compatibility would not exist, because the client would only support the types of tokenizer that it was compiled with. And I don't want to check the server version and refuse to operate either, because that's also bad ux.

If another mistral appears, I don't want to have to update the client side tokenizers and recompile just because I want to add things to the end of the context window.

> Pinging a remote server to run a tokenizer is non-sense.

well unless you'd allow an endpoint to download the tokenizer json directly from the server I don't want to spend time and ux just to try to keep the client in sync. The alternative of only allowing models already hosted on huggingface is also basically nonsense.

**Comment by OlivierDehaene** [comment]
> (btw please don't tell me to "calm down". it basically never actually helps)

No. You actually need to understand that maintainers are not here for you to vent your frustrations at, even if they don't share your viewpoint.

The client does not need to contain a specific tokenizer. The `/info` route gives you the specific tokenizer name that is currently running on the endpoint. Then you can dynamically load the tokenizer with for example Transformers.js.

Here's what I mean:

```js
import { AutoTokenizer } from '@xenova/transformers';

// response = request on the /info route

let tokenizer = await AutoTokenizer.from_pretrained(response.model_id);

let { input_ids } = await tokenizer('I love transformers!');
// Tensor {
//   data: BigInt64Array(6) [101n, 1045n, 2293n, 19081n, 999n, 102n],
//   dims: [1, 6],
//   type: 'int64',
//   size: 6,
// }
```

Now, you can support any TGI endpoint, and you have forward compatibility + way better latency.

**Comment by LoganDark** [comment]
> No. You actually need to understand that maintainers are not here for you to vent your frustrations at, even if they don't share your viewpoint.

I *do*, because I'm not venting. I'm trying to explain why I think this way and why I don't think that the solutions you are proposing will work for me. If I said nothing then you would probably not even talk to me at all because it would be unclear what my constraints even are.

If the tone was not calm enough for you then that is because you told me directly that my request is nonsense and all I need to do is duplicate the work on the client instead, which is expressly and exactly what I set out *not* to do. It is the complete *opposite* of what I need TGI to support.

> The client does not need to contain a specific tokenizer. The /info route gives you the specific tokenizer name that is currently running on the endpoint. Then you can dynamically load the tokenizer with for example Transformers.js.

No, the model_id contains a HuggingFace repo identifier, and the client has to go download the json from huggingface & it has to be of an architecture that the client-side tokenizer actually supports. I'm aware that most tokenizers are basic BPE-esque stuff but if a new one ever pops up then the client won't support it until its library is updated and it is recompiled.

And if the tokenizer is not on huggingface or if it has been modified in any way, like when adding new tokens in finetuning, this won't work and it'll be impossible to actually get the json from the server anyway, so the best the client can do is complain I guess.

> way better latency

When I ping the server it usually completes in under 1 frame (under 16ms) so the latency is not even that bad in the first place.
