### ISSUE TITLE
Support other means of passing image to IdeficsImageProcessor

### ISSUE THREAD

**Issue by olehpidhi** [huggingface/text-generation-inference#1095]
### Feature request

IdeficsImageProcessor expects the image to be passed only in the form of a URL from which it can [fetch the image](https://github.com/huggingface/text-generation-inference/blob/7a6fad6aac67d9bf21fe75c034a6bcab5dbd88d2/server/text_generation_server/models/custom_modeling/idefics_image_processing.py#L182).

It would be beneficial to allow accepting images as base64 encoded strings.

### Motivation

We want to use IDEFICS on data not directly available under the HTTP endpoint. We either need to set up another server to unpack an image from our DVC and make it available under some URL or deploy a custom docker container with patched image download logic.

### Your contribution

We can submit a PR to accept images as base64 encoded strings. Roughly looking like this:

```python
if isinstance(image_url_or_urls, str):
    decoded_bytes = None
    try:
        decoded_bytes = BytesIO(base64.b64decode(image_url_or_urls))
    except:
        print("Not a base64 encoded image")
    if decoded_bytes is not None:
        return Image.open(decoded_bytes)
    else:
        response = requests.get(image_url_or_urls, stream=True, headers=headers)
        response.raise_for_status()
        return Image.open(BytesIO(response.content))
```

**Comment by Narsil** [comment]
FYI we made some more modifications, requiring to send `data:image/gif;base64,XXXX`  as in https://css-tricks.com/data-uris/

The other trick is that we're using a modified tokenizer so that the rust tokenizer counts the tokens correctly (`--revision refs/pr/10`) https://huggingface.co/HuggingFaceM4/idefics-80b-instruct/discussions/10/files

This is a temporary measure we're not sure what the best way to proceed to make everything streamlined (the current modification prevents correct tokenization of code like markdown formatting).

**Comment by vakker** [comment]
@Narsil could you provide an example for the client code? 
The linked PR was not merged, and the same change was reverted in [PR-9](https://huggingface.co/HuggingFaceM4/idefics-80b-instruct/discussions/9) from [PR-8](https://huggingface.co/HuggingFaceM4/idefics-80b-instruct/discussions/8).

I'm trying this:
```python
import argparse
import base64
from io import BytesIO

from PIL import Image
from text_generation import Client

API_TOKEN = ....
API_URL = ....

# Example query
# QUERY = [
#     "User: What is in this image?",
#     "![](https://upload.wikimedia.org/wikipedia/commons/8/86/Id%C3%A9fix.JPG)<end_of_utterance>\n",
#     "Assistant:",
# ]


def get_query(img_path):
    with Image.open(img_path) as img:
        img_rgb = img.convert("RGB")

    img_base64 = img_to_base64(img_rgb)

    query = [
        "User: What is in this image?",
        f"<fake_token_around_image>{img_base64}<fake_token_around_image>",
        "Assistant:",
    ]
    return query


def img_to_base64(img: Image.Image) -> str:
    img_buffer = BytesIO()
    img.save(img_buffer, format="PNG")
    img_str = base64.b64encode(img_buffer.getvalue()).decode("utf-8")
    return img_str


def main(args):
    client = Client(
        base_url=API_URL,
        headers={
            "x-use-cache": "0",
            # "Authorization": f"Bearer {API_TOKEN}",
        },
    )
    generation_args = {
        "max_new_tokens": 256,
        "repetition_penalty": 1.0,
        "stop_sequences": ["<end_of_utterance>", "\nUser:"],
        "do_sample": False,
    }

    query = get_query(args.image)
    query = "".join(query)
    generated_text = client.generate(prompt=query, **generation_args)
    print(generated_text)


if __name__ == "__main__":
    PARSER = argparse.ArgumentParser()
    PARSER.add_argument("-i", "--image", required=True, help="Path to the image")

    ARGS = PARSER.parse_args()
    main(ARGS)
```

But this gives:
```
Traceback (most recent call last):
  File "/home/user/workspace/scripts/run_idefics_api.py", line 69, in <module>
    main(ARGS)
  File "/home/user/workspace/scripts/run_idefics_api.py", line 60, in main
    generated_text = client.generate(prompt=query, **generation_args)
  File "/home/user/.pyenv/versions/env/lib/python3.10/site-packages/text_generation/client.py", line 153, in generate
    raise parse_error(resp.status_code, payload)
text_generation.errors.ValidationError: Input validation error: `inputs` tokens + `max_new_tokens` must be <= 2048. Given: 1332531 `inputs` tokens and 256 `max_new_tokens`
```
