### ISSUE TITLE
GPTQ doesn't use exllama for all layers

### ISSUE THREAD

**Issue by njhill** [huggingface/text-generation-inference#1098]
I can no longer contribute here and am not looking at any of the additions since the license change, to avoid contaminating myself because we have our own fork.

But I thought you guys would like to know that there's what I think was an oversight in the GPTQ impl. In `get_multi_weights_col` in `weights.py`, the last element of the `weights` tuple is hardcoded as `False`. I'm pretty sure should instead be something like `bits == 4 and HAS_EXLLAMA`.

Without this, half of the layers still use the slow triton kernel.

Fixing this gives a huge speedup, for example about 2.5x for llama-2-70b-GPTQ.

**Comment by Narsil** [comment]
Thanks A LOT for the tip ! somehow exllama still has a hard time at high throughput compared to the triton kernel.

AWQ is probably faster in the general case (FYI).

I feel a bit sorry you cannot contribute here, but again, thanks a lot for the tip.

**Comment by njhill** [comment]
Thanks @Narsil 

> I feel a bit sorry you cannot contribute here

Me too :-(

**Comment by njhill** [comment]
Also thanks to @cyang49 for helping to find this!
