### ISSUE TITLE
Feature: keep bitsandbytes 8 bit for better outlier handling on large >10B models

### ISSUE THREAD

**Issue by 0xymoro** [huggingface/text-generation-inference#1107]
### Feature request

I've been reading into Nvidia's research on FT and int8 weight only, because after serving it to a few users they did find it had a noticeable drop in accuracy for large models. As much as it speeds up throughput a lot, in practice I think int8 without smoothquant does poorly the bigger model it quantizes (the problem that int8 tried to solve with outliers) from my understanding, and that bitsandbytes int8 will have a higher quantization accuracy on larger models due to better handling of outliers where current EETQ w8a16 without smoothquant will fall short somewhat. 

What I think is happening is - EETQ is awesome for smaller models in the <10B, but loses in bigger model in accuracy due to lack of outlier handling. Please correct me if I'm wrong here (I'm a bit confused about the w8a16, does this mean it doesn't have as much of an outlier activations accuracy problem? if so is there no outlier degradation/then what might explain some of the accuracy loss?), but I tried EETQ in a production service and users saw noticeable degradations on context following on a >10B model. Would appreciate someone looking into it, and maybe I think both should be supported (I don't know anyone who really uses bitsandbytes int8 due to its slowness but it's probably good for coverage and proven accuracy at larger models)

### Motivation

EETQ accuracy drop (compared to nf4/fp16) on larger models is somewhat noticeable in a production service.

**Comment by Narsil** [comment]
Anyway we could reproduce/verify that claim ?
