### ISSUE TITLE
invalid max total tokens and max input length calculation

### ISSUE THREAD

**Issue by DeoLeung** [huggingface/text-generation-inference#1108]
### System Info

tgi `1.1.0`
linux + docker

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

using llama2 13b, with config

```
MAX_INPUT_LENGTH: 4095
MAX_TOTAL_TOKENS: 4096
```
it works in `1.0.3`, but in `1.1.0` it complains that 
```
`max_new_tokens` must be <= 1
```

### Expected behavior

same as `1.0.3`

**Comment by OlivierDehaene** [comment]
I'm not sure I understand you. If `MAX_INPUT_LENGTH: 4095` and `MAX_TOTAL_TOKENS: 4096`, you can only generate one token, hence the error.

**Comment by DeoLeung** [comment]
I thought they are two limits, which was the case in `1.0.3`
if I have input of 400 tokens, it satisfies `MAX_INPUT_LENGTH: 4095`, then there will be `4096 - 400` left for new tokens.

**Comment by OlivierDehaene** [comment]
See https://github.com/huggingface/text-generation-inference/commit/20ee71dcf55098bbef617e63ba1869ed6f206b48

**Comment by jtsai-quid** [comment]
I also encountered this error with `bigscience/bloomz-560m`.
Is this related to the upgrading of tokenizer 0.13.3 to 0.14.0 in tgi v1.1.0 ?
