### ISSUE TITLE
Error while running docker : Shard complete standard error output:rank=0

### ISSUE THREAD

**Issue by tonypius** [huggingface/text-generation-inference#1109]
### System Info

text-generation-version is 1.1.0
Ubuntu : 22.04
GPU is Nvidia A100 and nvidia-smi command gives 
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:01:01.0 Off |                    0 |
| N/A   32C    P0              57W / 300W |      4MiB / 81920MiB |     21%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Steps to reproduce

1. when i run the docker run command it tries to start the shard and exists with an error. 
2. 
<img width="1170" alt="Screenshot 2023-10-06 at 4 55 58 PM" src="https://github.com/huggingface/text-generation-inference/assets/3880829/1b451fbb-fb64-4788-8c6c-b08b87f773d8">

### Expected behavior

I've used it in the past and never faced this issue and there is very little information to go on. I;ve installed the nvidia toolkit as well and 
sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
gives me the right output.
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:01:01.0 Off |                    0 |
| N/A   32C    P0              61W / 300W |      7MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by Narsil** [comment]
Signal 4 is for illegal instructions.
Pretty worrying indeed.

Is this something new, introduced by a new version, or something that used to work before? Could you share the host information ? What CPU is it ?

**Comment by Narsil** [comment]
So 0.9.4 used to work, and now it doesn't ? 

Are you using the exact same CPU or some cloud provider one ? Is that AMD x86_64 ?
I don't think we changed or optimized anything in the toolchain though

**Comment by tonypius** [comment]
Yes, used to work on similar config. Not the exact same system, since this is a new vm with exact same config

**Comment by Narsil** [comment]
Could you try rebuilding from source the project see if that works ? It looks like maybe the build doesn't work on that particular CPU (maybe some AVX instruction that you don't have access or something)

**Comment by tonypius** [comment]
No luck. Build failed. 

error: failed to compile `text-generation-router v1.1.1 (/abc/text-generation-inference/router)`, intermediate artifacts can be found at `/abc/text-generation-inference/target`

**Comment by tonypius** [comment]
Ok. I was able to build it. It's up and running. Now how do I dockerise this build ? Because I still need to spin up multiple models.

**Comment by tonypius** [comment]
Got it too. Just used the Dockerfile in the folder to create a custom image. Thanks for the help guys.

Closing the comment.

**Comment by Kaschi14** [comment]
I had the same error, using a Ubuntu 22.04 VM on Proxmox.
After setting the VM Processor in Proxmox to "host" as described in the reddit below, it finally works. Maybe it helps someone else.
https://www.reddit.com/r/homelab/comments/yvo4jm/how_do_i_enable_avx_on_my_server/
