### ISSUE TITLE
Inference in Docker is causing computer reboot

### ISSUE THREAD

**Issue by angel-luis** [huggingface/text-generation-inference#1111]
### System Info

I'm using Docker Engine in Windows 11 (latest updates) with TGI 1.1.0 and `Mistral-7B-OpenOrca-AWQ-main`.

Sometimes Windows receives a Kernel-Power error and reboots when inferencing. Specially when I'm performing QA. But I can't say if it's a model problem, because it's the first time I'm using TGI with different techniques (QA, summarization...).

What kind of testing or monitoring can I do to try to find the problem?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
docker run --name "Mistral-7B-OpenOrca-AWQ-main" --gpus all --shm-size 1g -e -p 8080:80 -v "${PATH_DATA}:/data" "ghcr.io/huggingface/text-generation-inference:1.1.0" --model-id "${AUTHOR}/${NAME}" --max-total-tokens 4096 --max-input-length 1024 --quantize awq
```

### Expected behavior

Don't reboot.

**Comment by yixuantt** [comment]
+1
