### ISSUE TITLE
ValueError: Non-consecutive added token '<pad>' found. Should have index 106611 but has index 0 in saved vocabulary.

### ISSUE THREAD

**Issue by thusinh1969** [huggingface/text-generation-inference#1115]
### System Info

TIG 1.1.0
Flan-T5-large
Expanded vocab for Vietnamese and some special corpus vocab to 106611 .
Pre-trained with span corruption
Fine-tune with summary/abstraction and FAQ.

Works fine (summ/abstract/FAQ...) but slow with standard HF:

new_model = T5ForConditionalGeneration.from_pretrained(merged_finetune_model_dir,
                                                torch_dtype=getattr(torch, "bfloat16"),
                                                 device_map="auto",
)

new_tokenizer = T5Tokenizer.from_pretrained(tokenizer_merged_finetune_model_dir,
                                              cache_dir=None,
                                              use_fast=True,
                                              use_auth_token=None,
                                            )

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [x] My own modifications

### Reproduction

export HUGGING_FACE_HUB_TOKEN=my-secret-token
model=thusinh1969/flan-t5-large-sum-abstract-genQA
volume=/home/steve/sd-hatto/data/T5/models/flan-t5-large/finetune/sum-abstract-genQA-full/TIG_data
docker run --gpus all --shm-size 1g -p 8099:3000 \
-v $volume:/data -e HUGGING_FACE_HUB_TOKEN="my-secret-token" \
ghcr.io/huggingface/text-generation-inference:1.1.0 \
--model-id $model \
--revision 1.0 \
--num-shard 2 \
--trust-remote-code \
--dtype bfloat16 \
--max-top-n-tokens 5 \
--max-input-length 2048 \
--max-total-tokens 4096 \
--max-best-of 4 \
--hostname 0.0.0.0 \
--port 3000 \
--cuda-memory-fraction 0.8

**ERROR:**

 File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 271, in get_model
    return T5Sharded(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/t5.py", line 46, in __init__
    tokenizer = AutoTokenizer.from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 736, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1886, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2073, in _from_pretrained
    raise ValueError(

ValueError: Non-consecutive added token '<pad>' found. Should have index 106611 but has index 0 in saved vocabulary.
 rank=0
2023-10-07T06:21:08.002194Z ERROR text_generation_launcher: Shard 0 failed to start
2023-10-07T06:21:08.002302Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart

### Expected behavior

TIG should be able to load expanded tokenizer the same way that standard HF T5Tokenizer.from_pretrained(....)

Thanks,
Steve

**Comment by thusinh1969** [comment]
Found in the t5.py:

tokenizer = AutoTokenizer.from_pretrained(
            model_id,
            revision=revision,
            padding_side="left",
            truncation_side="left",
            trust_remote_code=trust_remote_code,
        )

But T5Tokenizer is "padding right":

T5Tokenizer(name_or_path='/home/steve/data01/T5/models/flan-t5-large/extended_VN_C_vocab_403030/hf', vocab_size=106611, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'eos_token': '</s>', 'unk_token': '<unk>', 'pad_token': '<pad>', 'additional_special_tokens': ['<extra_id_0>', '<extra_id_1>', '<extra_id_2>', '<extra_id_3>', '<extra_id_4>', '<extra_id_5>', '<extra_id_6>', '<extra_id_7>', '<extra_id_8>', '<extra_id_9>', '<extra_id_10>', '<extra_id_11>', '<extra_id_12>', '<extra_id_13>', '<extra_id_14>', '<extra_id_15>', '<extra_id_16>', '<extra_id_17>', '<extra_id_18>', '<extra_id_19>', '<extra_id_20>', '<extra_id_21>', '<extra_id_22>', '<extra_id_23>', '<extra_id_24>', '<extra_id_25>', '<extra_id_26>', '<extra_id_27>', '<extra_id_28>', '<extra_id_29>', '<extra_id_30>', '<extra_id_31>', '<extra_id_32>', '<extra_id_33>', '<extra_id_34>', '<extra_id_35>', '<extra_id_36>', '<extra_id_37>', '<extra_id_38>', '<extra_id_39>', '<extra_id_40>', '<extra_id_41>', '<extra_id_42>', '<extra_id_43>', '<extra_id_44>', '<extra_id_45>', '<extra_id_46>', '<extra_id_47>', '<extra_id_48>', '<extra_id_49>', '<extra_id_50>', '<extra_id_51>', '<extra_id_52>', '<extra_id_53>', '<extra_id_54>', '<extra_id_55>', '<extra_id_56>', '<extra_id_57>', '<extra_id_58>', '<extra_id_59>', '<extra_id_60>', '<extra_id_61>', '<extra_id_62>', '<extra_id_63>', '<extra_id_64>', '<extra_id_65>', '<extra_id_66>', '<extra_id_67>', '<extra_id_68>', '<extra_id_69>', '<extra_id_70>', '<extra_id_71>', '<extra_id_72>', '<extra_id_73>', '<extra_id_74>', '<extra_id_75>', '<extra_id_76>', '<extra_id_77>', '<extra_id_78>', '<extra_id_79>', '<extra_id_80>', '<extra_id_81>', '<extra_id_82>', '<extra_id_83>', '<extra_id_84>', '<extra_id_85>', '<extra_id_86>', '<extra_id_87>', '<extra_id_88>', '<extra_id_89>', '<extra_id_90>', '<extra_id_91>', '<extra_id_92>', '<extra_id_93>', '<extra_id_94>', '<extra_id_95>', '<extra_id_96>', '<extra_id_97>', '<extra_id_98>', '<extra_id_99>', AddedToken("
", rstrip=False, lstrip=False, single_word=False, normalized=True)]}, clean_up_tokenization_spaces=True)

Is that a problem ?
Steve

**Comment by thusinh1969** [comment]
Not working. Can someone please help !!!

Steve

**Comment by thusinh1969** [comment]
Fixed by adjust the Transformer tokenizer code-base !

**Comment by Alignment-Lab-AI** [comment]
hello, would you mind sharing the edits you made to the code? im having this same issue

**Comment by kunal0137** [comment]
FROM ghcr.io/huggingface/text-generation-inference:1.1.0

RUN apt-get update -y && \
 DEBIAN_FRONTEND=noninteractive apt-get install -y git && \
 apt-get clean && \
 rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir \
    "git+https://github.com/huggingface/transformers"
