### ISSUE TITLE
Special symbols appear

### ISSUE THREAD

**Issue by chailt** [huggingface/text-generation-inference#1117]
### System Info

I can start the service normally, but every time the answer starts with a "?“
![image](https://github.com/huggingface/text-generation-inference/assets/128781283/9f6c0d77-d546-4c87-ae33-c4c6eab26ad1)
![image](https://github.com/huggingface/text-generation-inference/assets/128781283/c5a10b2f-b222-4f4c-bb07-278cf30807b6)

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

docker run --gpus 2 --name tgi --shm-size 1g -p 8080:80 -v /home/ubuntu:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id /data/chinese_llama2_13b_16k_0920_full_weight
time curl 127.0.0.1:8080/generate \
    -X POST \
    -d '{"inputs":"糖尿病怎么治疗","parameters":{"max_new_tokens":512}}' \
    -H 'Content-Type: application/json'

### Expected behavior

Expecting a normal response

**Comment by luoziyong** [comment]
try to write the input end with "?"
