### ISSUE TITLE
Cannot start docker image on Fedora

### ISSUE THREAD

**Issue by bryonbaker** [huggingface/text-generation-inference#1120]
### System Info

**What am I trying to do?**
Start the LLM in docker using:
export volume=$PWD/data
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id tiiuae/falcon-7b-instruct

**What happens:**
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
ERRO[0002] error waiting for container: 

**What did I expect to happen?**
The container should start and I can call the model with curl

**System Info**
Fedora 38
Docker version 24.0.6, build ed223bc
NVIDIA Container Toolkit:  
  Version      : 1.14.2
  Release      : 1
  Architecture : x86_64
  Size         : 2.6 M
  Source       : nvidia-container-toolkit-1.14.2-1.src.rpm

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

export volume=$PWD/data
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id tiiuae/falcon-7b-instruct

### Expected behavior

The container should start and I can call the model with curl

**Comment by JaLnYn** [comment]
Same issue here. New install for Ubuntu 22.04.3 LTS having the exact same issue.

**Comment by OlivierDehaene** [comment]
Seems related to https://github.com/NVIDIA/nvidia-docker/issues/1746?

**Comment by olariuromeo** [comment]
try with sudo, it's a permission problem

**Comment by bryonbaker** [comment]
Thanks. I'll give it a crack. But just a comment - running a container with sudo breaks all of the security best practices. If the image needs to be run as root then that is a good reason to not use this project...

**Comment by OlivierDehaene** [comment]
`libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.` hints at a broken nvidia drivers/toolkit stack.

> If the image needs to be run as root
It does not.
