### ISSUE TITLE
Not support for code-llama infill mode 

### ISSUE THREAD

**Issue by leojames** [huggingface/text-generation-inference#1124]
### System Info

When I use TGI for inference, the local model uses the code llama 7b model, but I found that it does not support middle completion during inference. I printed detailed output information and found that the keyword <FILL_ME> was not recognized by the model. I found in the source code that stancoder has implemented related special word markers. Can this be resolved?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. run docker 
2. prompt is      public static String findShortestWord(String args[]) {
        String shortest = args[0];
        <FILL_ME>
        return shortest;
}
3.get wrong result
    public static String findShortestWord(String args[]) {
        String shortest = args[0];

        public static void main(String args[]) {
            System.out.println(findShortestWord(args));
        }
        return shortest;
}

### Expected behavior

    public static String findShortestWord(String args[]) {
        String shortest = args[0];
        for (int i = 1; i < args.length; i++) {
            if (args[i].length() < shortest.length()) {
                shortest = args[i];
            }
        }
        return shortest;
}

**Comment by Crisescode** [comment]
i has the same problem

**Comment by andyl98** [comment]
same here

**Comment by daanturo** [comment]
Same for me. For the starcoder model via HTTP requests, `"<fim_prefix>" "<fim_suffix>" "<fim_middle>"` used to work but now they don't anymore.
