### ISSUE TITLE
Do you have any plan to expand the scope to CPU?

### ISSUE THREAD

**Issue by mengniwang95** [huggingface/text-generation-inference#1125]
### Discussed in https://github.com/huggingface/text-generation-inference/discussions/1118

<div type='discussions-op-text'>

<sup>Originally posted by **mengniwang95** October  8, 2023</sup>
Hi, I find this repo mainly focus on LLM inference on GPUs currently.  Do you have any plan to expand the scope to CPU?

Our team develop the [Intel® Extension for Transformers](https://github.com/intel/intel-extension-for-transformers), which is an innovative toolkit to accelerate Transformer-based models on Intel platforms, in particular effective on 4th Intel Xeon Scalable processor [Sapphire Rapids](https://www.intel.com/content/www/us/en/products/docs/processors/xeon-accelerated/4th-gen-xeon-scalable-processors.html) (codenamed Sapphire Rapids). The toolkit provides the below key features:

- Seamless user experience of model compressions (include RTN, AWQ, GPTQ, bitsandbytes and other our own algorithms in the future for weight-only quantization) on Transformer-based models by extending [Hugging Face transformers](https://github.com/huggingface/transformers) APIs and leveraging [Intel® Neural Compressor](https://github.com/intel/neural-compressor)

- Advanced software optimizations and unique compression-aware runtime.

- Optimized Transformer-based model packages.

- [NeuralChat](https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/neural_chat), a customizable chatbot framework to create your own chatbot within minutes by leveraging a rich set of plugins and SOTA optimizations.

- [Inference](https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/llm/runtime/graph) of Large Language Model (LLM) in pure C/C++ with weight-only quantization kernels.

We want to make some contributions to LLM ecosystem sincerely and TGI is a really popular project. So, is there any chance to integrate part of our work into TGI?

Thanks</div>

**Comment by OlivierDehaene** [comment]
Does the throughput increase with batching on CPU? If that's the case, it would be interesting for sure. If not, I'm not sure why the scheduling from TGI would be needed.

TGI offers an internal gRPC interface to plug any backend. You can look at https://github.com/huggingface/optimum-habana/tree/main/text-generation-inference for an example.

**Comment by mengniwang95** [comment]
Could we start from integrating our weight-only quantization methods? We have unified quantization API and can provide more weight-only quantization methods, e.g., RTN which doesn't require dataset to do quantization.

**Comment by mengniwang95** [comment]
Candle is a Rust project and seems have nothing to do with our project. We only want to extend the model quantization functionality for TGI. 

Our quantization supports:
- better RTN method with full_range quantization
- INT4, NF4 and FP4
- AWQ, TEQ and Sign Round weight-only methods
- unified but extended API for SmoothQuant
