### ISSUE TITLE
Enhance Model Throughput by Supporting Multi-GPU Distributed Deployment

### ISSUE THREAD

**Issue by linkedlist771** [huggingface/text-generation-inference#1126]
### Feature request

I've been analyzing the throughput and request handling of the model and noticed that the current implementation seems to follow a queue structure. This means that asynchronous requests are queued and processed sequentially.

In my setup, I have multiple GPUs available, but the model appears to be running on a single A100 and is only about half-loaded. Given the available resources, I believe there's an opportunity to significantly improve throughput and responsiveness by supporting distributed deployment across multiple GPUs.

Would it be possible to enhance the system to utilize the full potential of multi-GPU environments? This could greatly benefit scenarios with high request rates and ensure better resource utilization.
There are my configurations:

- GPU Load:
![image](https://github.com/huggingface/text-generation-inference/assets/72634327/9e21fd62-a508-4ce4-81e5-1d8b26488528)
- Request status:
![image](https://github.com/huggingface/text-generation-inference/assets/72634327/8fe57610-7e24-4e18-983b-6e5ea22f9fd1)
![image](https://github.com/huggingface/text-generation-inference/assets/72634327/8f904a11-c05c-4f70-a37a-47fa6f8f87fa)
- Deploy parameters:
```bash
sudo /bin/docker run --gpus all --shm-size 1g -p 8090:80 -v /mnt:/mnt ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id /mnt/pretrained_models/open_llama_7b_v2/
```

### Motivation

Multi Requests and Distributed Deloyment Acceleration.

### Your contribution

 Nothing by now.

**Comment by OlivierDehaene** [comment]
Deploy multiple replicas, one for each GPU and add a load balancer on top.

**Comment by linkedlist771** [comment]
Hi, will you try to implement such balancer for the real caes' production environment. I found most of the current deployment framework does not have this feature which is quite import in the real use cases.

**Comment by OlivierDehaene** [comment]
What do you mean? You can use NGINX for example.

**Comment by linkedlist771** [comment]
Thank you, I found `FastChat` has doen that for me.  Thank for your response.

**Comment by TomasHradecky** [comment]
> Thank you, I found `FastChat` has doen that for me. Thank for your response.

@linkedlist771  could you please share how you solved it ?
looks like it could helps with my issue where i have 2x L4 on one node but LLM only use 1 for 98%

**Comment by linkedlist771** [comment]
what do u mean? what size of model are u loading? 7b,13b,or lager. do u want to load a single model instance on multiple gpus or do u want to load multiple instances and make a balancer.  I would like to help u if you could specify the issue you are facing now.

**Comment by linkedlist771** [comment]
> > Thank you, I found `FastChat` has doen that for me. Thank for your response.
> 
> @linkedlist771 could you please share how you solved it ? looks like it could helps with my issue where i have 2x L4 on one node but LLM only use 1 for 98%



> > Thank you, I found `FastChat` has doen that for me. Thank for your response.
> 
> @linkedlist771 could you please share how you solved it ? looks like it could helps with my issue where i have 2x L4 on one node but LLM only use 1 for 98%

what do u mean? what size of model are u loading? 7b,13b,or lager. do u want to load a single model instance on multiple gpus or do u want to load multiple instances and make a balancer. I would like to help u if you could specify the issue you are facing now.

**Comment by TomasHradecky** [comment]
> > > Thank you, I found `FastChat` has doen that for me. Thank for your response.
> > 
> > 
> > @linkedlist771 could you please share how you solved it ? looks like it could helps with my issue where i have 2x L4 on one node but LLM only use 1 for 98%
> 
> > > Thank you, I found `FastChat` has doen that for me. Thank for your response.
> > 
> > 
> > @linkedlist771 could you please share how you solved it ? looks like it could helps with my issue where i have 2x L4 on one node but LLM only use 1 for 98%
> 
> what do u mean? what size of model are u loading? 7b,13b,or lager. do u want to load a single model instance on multiple gpus or do u want to load multiple instances and make a balancer. I would like to help u if you could specify the issue you are facing now.

sorry, more details here:
i use GKE and TGI on g2-standard-24 node (24vCPU, 96GB RAM) and 2x L4 GPUs with 24GB vRAM each. Data are stored in chroma pod (300MB data) and we use python client with llama3.
My goal is to use both GPUs on node, I have configured
resources:
  limits:
    nvidia.com/gpu: '2'

and 
  env:
    - name: LLM_GPUCOUNT
       value: '2'
but each query generate load only on 1 GPU, also memory is used only on one of GPUs. I can see that both GPUs are dedicated to TGI pod based on information from dcgm metrics.
I was able to use both GPUs with test pod which generate gpu load so configuration of pod and EKS looks ok.

**Comment by linkedlist771** [comment]
So you want to load the `LLama3` model on the two GPUS and use it to do inference?  For `TGI`, that is simple :
```bash
--num_shard 2
```

**Comment by TomasHradecky** [comment]
Perfect !  I've totally missed that parameter. Thank you very much.
