### ISSUE TITLE
Using regex for stopping criteria

### ISSUE THREAD

**Issue by swarupsrini** [huggingface/text-generation-inference#1130]
### Feature request

Hi! I've deployed a model for inference but I find that the stopping criteria is quite limiting. Is there a possibility to expand this to allow for regex matching? I assume this would be done in this function: https://github.com/huggingface/text-generation-inference/blob/dd304cf14cc342e40eea83015489d0b136f85ed0/server/text_generation_server/utils/tokens.py#L118-L131

### Motivation

We would like to terminate the stream after a set number of sentences generated. This would involve a regex match which can't be achieved with the current stopping strings implementation.

### Your contribution

If this is something you all are open to receiving, we're more than happy to take a crack at it. Let us know if the tokens.py file is a good starting point!

**Comment by OlivierDehaene** [comment]
If you are using streaming, you can do this stopping logic in the client and drop the connection. The backend will automatically remove the request from the batch.

**Comment by swarupsrini** [comment]
> If you are using streaming, you can do this stopping logic in the client and drop the connection. The backend will automatically remove the request from the batch.

@OlivierDehaene Thanks for the fast reply! We are using streaming, and I tried to test this by interrupting a `generate_stream` call via CURL, but I wasn't sure if the backend actually stopped processing, since the logs showed up a bit later. Any chance you could point me to where this would happen? 

I'm mainly concerned about cost savings here since we run a sizeable model and often want to interrupt it much before it generates the max tokens.

**Comment by OlivierDehaene** [comment]
The logic is [here](https://github.com/huggingface/text-generation-inference/blob/3af1a1140141245c20df20a787831ec71b124eae/router/src/infer.rs#L492).
