### ISSUE TITLE
Getting tons of Error: unknown .loc sub-directive 

### ISSUE THREAD

**Issue by cmosguy** [huggingface/text-generation-inference#1135]
### System Info

I am attempting to install `text-generation-inference` on our local servers.  Things are blowing up when the install does: `cd router && cargo install --path .` command during the install process:

```
   Compiling unicode_categories v0.1.1
   Compiling rand v0.8.5
   Compiling nom v7.1.3
   Compiling nohash-hasher v0.2.0
   Compiling ordered-float v3.9.1
   Compiling clap_builder v4.4.6
   Compiling hostname v0.3.1
   Compiling crossbeam-deque v0.8.3
   Compiling utoipa-swagger-ui v3.1.5
   Compiling sha2 v0.10.8
   Compiling flume v0.11.0
   Compiling mime_guess v2.0.4
The following warnings were emitted during compilation:
warning: /tmp/ccULKIi9.s: Assembler messages:
warning: /tmp/ccULKIi9.s:13: Error: unknown .loc sub-directive `view'
warning: /tmp/ccULKIi9.s:13: Error: junk at end of line, first unrecognized character is `-'
warning: /tmp/ccULKIi9.s:15: Error: unknown .loc sub-directive `view'
warning: /tmp/ccULKIi9.s:15: Error: unknown pseudo-op: `.lvu1'
warning: /tmp/ccULKIi9.s:16: Error: unknown .loc sub-directive `view'
warning: /tmp/ccULKIi9.s:16: Error: unknown pseudo-op: `.lvu2'
````

Totally stuck on how to resolve this issue.

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Following the instructions: 

`BUILD_EXTENSIONS=True make install`

### Expected behavior

not erroring out

**Comment by McPatate** [comment]
Do the instructions in https://github.com/compiler-explorer/compiler-explorer/issues/3239 help?

**Comment by cmosguy** [comment]
Thanks @McPatate -

I see them say:
```
-gas-locview-support
Inform the compiler that the assembler supports view assignment and reset assertion checking in .loc directives.

This option will be enabled by default if, at GCC configure time, the assembler was found to support them.

-gno-as-locview-support
Force GCC to assign view numbers internally, if -gvariable-location-views are explicitly requested.
```

I have no idea how to use this with the `make` command in the `README`

**Comment by cmosguy** [comment]
@McPatate - it seems that I had to remove the `.cargo/registry` and start all over.

**Comment by cmosguy** [comment]
I gave up on this - too many problems, I guess i am forced to use docker.
