### ISSUE TITLE
what gpu cloud do you recommend to use?

### ISSUE THREAD

**Issue by naticio** [huggingface/text-generation-inference#1147]
trying to run docker image in vast.ai and it doesn't work!!

is aws the only option?? :(

docker run --gpus all --shm-size 1g -p 21033:80 -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id model/modelname

**Comment by ssmi153** [comment]
Runpod works well and makes it very easy to spin up new instances.

![image](https://github.com/huggingface/text-generation-inference/assets/129111316/e716f4cd-10a6-4b77-955a-6d40869c5130)

**Comment by naticio** [comment]
> Runpod works well and makes it very easy to spin up new instances.
> 
> ![image](https://user-images.githubusercontent.com/129111316/275362721-e716f4cd-10a6-4b77-955a-6d40869c5130.png)

thanks I did that but still I don't know why the http ports never get opened
![image](https://github.com/huggingface/text-generation-inference/assets/34293050/b94c9172-be48-465a-bf72-ab8b7a1f5025)


```
nat-serrano@Nats-MacBook-Pro-2 ~ % curl xx.xx.xx.xx:18492/generate \
-X POST \
-d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
-H 'Content-Type: application/json'
curl: (7) Failed to connect to xx.xx.xx.xx port 18492 after 468 ms: Couldn't connect to server
```

**Comment by ssmi153** [comment]
Are you loading an AWQ or GPTQ quantised model? If so, you need to set an additional parameter: QUANTIZE: gptq  (or awq)

**Comment by naticio** [comment]
> Are you loading an AWQ or GPTQ quantised model? If so, you need to set an additional parameter: QUANTIZE: gptq (or awq)

AWQ....maybe that's the issue????

**Comment by ssmi153** [comment]
Yeah. Try it with QUANTIZE: awq
That should do the trick. The http socket will only open once the model is downloaded, loaded into VRAM and warmed up, which in total will take a few minutes depending on the size of the model. You should be able to track this progress in the logs though.

**Comment by naticio** [comment]
thanks, a bit of progress, looks like text inference doesn't support the 30b awq model I am using, because the port 80 never warm up. I'll try with a different model to see if it works
![image](https://github.com/huggingface/text-generation-inference/assets/34293050/d0fa0fa8-8af4-44f2-b262-3a9602eecc40)

**Comment by ssmi153** [comment]
Yeah, that makes sense. I’ve been using LLama 2 and Mistral models successfully with TGI, but haven’t tried MPT. One other to thing I remembered is that for LLama 2 models I needed to halve all the values for MAX_INPUT_LENGTH, MAX_TOTAL_TOKENS and MAX_BATCH_PREFILL_TOKENS to match the smaller context size of the LLama 2 models. Mistral has a native 8k context length vs 4K for Llama 2.
