### ISSUE TITLE
Serving a finetuned Starcoder model as a supported model

### ISSUE THREAD

**Issue by rtwang1997** [huggingface/text-generation-inference#1148]
I have a model which has been finetuned on top of https://huggingface.co/bigcode/starcoderplus. I would like to run it as a supported model (so as to be able to use the parallel tensor feature). At the moment, it's trying to load the model onto a single A10G and failing.

Is this possible? I've looked through the docs and I'm not able to find any clues. 

Thanks!

**Comment by OlivierDehaene** [comment]
What's the error?
