### ISSUE TITLE
too long prompt could get different response from the same model

### ISSUE THREAD

**Issue by sundayKK** [huggingface/text-generation-inference#1159]
### System Info

i use 1.0.3 version
NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0 
model  llama2-13b-16k

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

i use the same request,prompt length>6000,and multiple requests can get different response,and i set temperature=1.0 or temperature=0.001 alse can get different response. 

### Expected behavior

it has some random parameters here?

**Comment by coder-xieshijie** [comment]
```
curl --location --request POST '127.0.0.1:8080/generate' \
--header 'Content-Type: application/json' \
-w "\n Time Total: %{time_total}\n" \
--data-raw '{
    "inputs": "def quicksort(nums):\n    ",
    "parameters": {
        "max_new_tokens": 60,
        "temperature": 0.9,
        "seed":5938575533597520045
    }
}'
```
You can ensure same generation results every time by adding the `seed` parameter.

**Comment by sundayKK** [comment]
> ```
> curl --location --request POST '127.0.0.1:8080/generate' \
> --header 'Content-Type: application/json' \
> -w "\n Time Total: %{time_total}\n" \
> --data-raw '{
>     "inputs": "def quicksort(nums):\n    ",
>     "parameters": {
>         "max_new_tokens": 60,
>         "temperature": 0.9,
>         "seed":5938575533597520045
>     }
> }'
> ```
> 
> You can ensure same generation results every time by adding the `seed` parameter.

but the sampling i set is false, so the seed should no function,right?

**Comment by sundayKK** [comment]
> ```
> curl --location --request POST '127.0.0.1:8080/generate' \
> --header 'Content-Type: application/json' \
> -w "\n Time Total: %{time_total}\n" \
> --data-raw '{
>     "inputs": "def quicksort(nums):\n    ",
>     "parameters": {
>         "max_new_tokens": 60,
>         "temperature": 0.9,
>         "seed":5938575533597520045
>     }
> }'
> ```
> 
> You can ensure same generation results every time by adding the `seed` parameter.

but the sampling i set is false, so the seed should no function,right?

**Comment by coder-xieshijie** [comment]
I don't know the underlying principles of the underlying model, and I'm not even sure whether different models have similar parameters. I verified this conclusion based on tgi's  [swagger api document](https://huggingface.github.io/text-generation-inference/) . When my seeds are the same, I can get the same output.

**Comment by sundayKK** [comment]
> different

ok，i’d try。thanks！
