### ISSUE TITLE
Does TGI have plans to support speculative sampling?

### ISSUE THREAD

**Issue by mintglobe0226** [huggingface/text-generation-inference#1169]
### Feature request

I see that transformer already supports speculative sampling in April. We would like to deploy starcoder1B and starcoder15.5B using a similar approach. We are wondering if TGI has any plans to support this feature, as we appreciate your support.

https://github.com/huggingface/transformers/commit/78cda46f17548d8739c354a07b00b3f2996773c7

### Motivation

Speculative sampling can improve overall inference performance at a lower cost.

### Your contribution

Sorry I'm a new student of the large-scale model and I don't know how to execute this modification yet.

**Comment by OlivierDehaene** [comment]
Yes we will add speculative sampling soon.

**Comment by flozi00** [comment]
https://github.com/huggingface/text-generation-inference/issues/314
https://github.com/huggingface/text-generation-inference/issues/729

**Comment by scse-l** [comment]
Any updates?

**Comment by RonanKMcGovern** [comment]
Yes, would be a great feature especially with guidelines around where it makes sense to use and where it doesn’t.

**Comment by OlivierDehaene** [comment]
TGI 1.3 now supports Medusa and n-gram speculative sampling.

**Comment by RonanKMcGovern** [comment]
That's phenomenal @OlivierDehaene . Any flags required to activate either?

**Comment by RonanKMcGovern** [comment]
@OlivierDehaene I've been reading around more about speculative decoding.

Where is TGI getting the n-grams from? Is it from the prompt? Is it from a look ahead approach?

Shouldn't there be a simple way to get some forward token estimates just by passing some blank embeddings at a position i in order to get an estimate of position i+1? (and/or mask the attention for that position).

**Comment by OlivierDehaene** [comment]
TGI gets the n-grams both from the prompt and from the already generated tokens (`all_input_ids` in the code).
n-gram is very good for code or very structured tasks and almost free at low batch sizes. 

Medusa is way better overall though. I think there is space in the community for someone like TheBloke but for Medusa heads. It should be easy to train new ones for new popular models. 

One could also train a medusa head at runtime. Afterall we are not compute bound so it is possible to use the wasted compute to train a head on the generated tokens.

**Comment by RonanKMcGovern** [comment]
Thanks @OlivierDehaene . Yeah makes sense to use prompt and all_input_ids for ngrams. It def gives some good speed up on summarization tasks where there's lots of prompt in the response.

Noted on Medusa - yeah, I guess it's a good way to look at it - kind of like having to make a GGUF/AWQ. Being able to make the heads in quant form would further be a benefit.

What are your thoughts on lookahead (i.e. using masks to look ahead for better guesses + also using those tokens for n-gram search)? It uses quite a bit of compute, but does give speedup and requires no training. https://github.com/hao-ai-lab/LookaheadDecoding/

**Comment by RonanKMcGovern** [comment]
Many thanks @OlivierDehaene , closing this out.
