### ISSUE TITLE
Can TGI host multiple models on one SageMaker instance?

### ISSUE THREAD

**Issue by ibicdev** [huggingface/text-generation-inference#1174]
Not sure if this is the right place to ask this question, but does TGI (or Hugging Face LLM DLC) supports multiple inference endpoints or multiple models on a single SageMaker instance?  For example, on a ml.p4d instance, can we use 4 A100 GPUs for llama-2 70b and the other 4 GPUs for code llama 34b?  This would be more cost-effective than using 2 instances if it works.

**Comment by OlivierDehaene** [comment]
@philschmid, do you know?

**Comment by philschmid** [comment]
@ibicdev TGI is only single container, single model and sagemaker is currently not supporting slicing of GPUs.

**Comment by ibicdev** [comment]
Thanks @philschmid @OlivierDehaene for the quick answer.
