### ISSUE TITLE
Multi gpu efficiency: many small nodes or 1 large node?

### ISSUE THREAD

**Issue by 0xymoro** [huggingface/text-generation-inference#1175]
For folks running inference at scale - do you use many smaller nodes with less/no sharding or a few large nodes with more sharding? I'm sometimes seeing performance that's better with smaller nodes with less sharding, and unsure if it's just a thing with   my compute hardware becoming compute limited rather than memory limited or if it's TGI. Would appreciate advice/thoughts on it!

**Comment by OlivierDehaene** [comment]
We do many smaller nodes as long as we have enough VRAM to batch heavily at HF.
Sharding can lead to some pretty bad perf and economics if you don't have nvlink on the nodes.

**Comment by jerryMeng100** [comment]
I see, empirically we're running smaller nodes as well. We'll be upgrading to H100s all linked together, and may do some benchmarking on 4x 2 H100 on a node, or 2x 4, of 1x 8, but the prefill seems to be the bottleneck in these larger ones. In previous tests we used A100 pcie so maybe that's what you ran into with bad perf, it really did not perform well with many strung together.

We've not had any nvlink A100s, and haven't tried on H100s at all to date, but does nvlink change the situation if you've tried them?

**Comment by jerryMeng100** [comment]
Also, separate but related issue is I think the deployment params mattered a lot more than I thought. We've moved the waiting-served ratio from 1.2 to 0.3 and it's made queues a lot better for the >30b models we serve, and lowered max waiting tokens to 6 from 20. Before these changes the queues would grow super long before it would process any new one. 

I think these issues are from serving very large models, and wonder if you have thoughts on this and if the default ones are the default at HF inference endpoints (even for larger, 30b+ models)? My setup above might be getting new tokens too aggressively at the benefit of lowering queue times.

**Comment by OlivierDehaene** [comment]
Yes waiting-served-ratio and max-waiting-tokens are very important parameters and the default may be very conservatives depending on your use case.
Especially if you have very short requests in terms of tokens you should for sure decrease both of them to make sure that the `decode` steps are running with a high enough batch size. This will have a dramatic effect on throughput without increasing latency too much. 
For longer requests, you should be more careful but it can still be decreased.
