### ISSUE TITLE
[Question]"resume_download" support in model download phase?

### ISSUE THREAD

**Issue by TommyLike** [huggingface/text-generation-inference#1192]
### System Info

Trying the hello world example within docker environment
```
docker run -d --gpus all -e NCCL_SHM_DISABLE=1 -e HF_HUB_ENABLE_HF_TRANSFER=1 -p 8080:80 -v ./inference_text:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id tiiuae/falcon-7b-instruct
```
but I always failed downloading the model in the half way due to the network(maybe), is there any way to resume the download from previous?
directory and file info when the download process seems get stuck
```
➜  inference_text ls -alh
total 7.2G
drwxr-xr-x  3 root root 4.0K Oct 24 09:25 .
drwx------ 11 root root 4.0K Oct 24 09:43 ..
drwxr-xr-x  6 root root 4.0K Oct 23 19:07 models--tiiuae--falcon-7b-instruct
-rw-------  1 root root 9.3G Oct 24 09:42 tmpt2a3f1qm
-rw-r--r--  1 root root    1 Oct 23 19:07 version.txt
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. launching the server via the instruction in README.

### Expected behavior

the server fully running.

**Comment by OlivierDehaene** [comment]
That's weird. The donwload should ignore the files that were already downloaded. 
Can you share the error that you got?
