### ISSUE TITLE
SharededLLaMA is failed to infer long context input in A100 80G * 8 environment.

### ISSUE THREAD

**Issue by hyunwoongko** [huggingface/text-generation-inference#1194]
We're currently using A100 80G * 8 machine, and when we tried 16k length inference using `meta-llama/Llama-2-7b-chat-hf` model with tp_size=8, it faied.

This error was already reported in https://github.com/huggingface/text-generation-inference/issues/883, and we got same error. (The issue reporter used LLaMA2-32k fine-tuned model, and I think he/she used long context input like us)

- client side
```
Traceback (most recent call last):
  File "/home/bc-user/kevin/lm-evaluation-harness/lm_eval/models/textgen.py", line 38, in generate
    return self.client.generate(**kwargs)
  File "/home/bc-user/.conda/envs/text-generation-inference/lib/python3.9/site-packages/text_generation/client.py", line 149, in generate
    raise parse_error(resp.status_code, payload)
text_generation.errors.GenerationError: Request failed during generation: Server error: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
```

- server side
<img width="1691" alt="스크린샷 2023-10-25 오전 12 57 49" src="https://github.com/huggingface/text-generation-inference/assets/38183241/4f788e99-32e4-4b82-9f60-d3c0f224c6b7">

```
infer:send_error: text_generation_router
::infer: router/src/infer.rs:554: Request failed during generation: Server error: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
```

However, we've succeed 16k length inference using other 13B models (e.g. BLOOM architecture) in the same environment.
If 13B model inference was succeed in the same environment, there's no clear reason to fail 7B model inference.
7B model's size is half of 13B model. But 13B model inference was succeed and 7B model is failed. This is weird.

One possible reason is Flash attention module. There's the following code in text-generation-inference.
```python
    elif model_type == "llama":
        if FLASH_ATTENTION:
            return FlashLlama(
                model_id,
                revision,
                quantize=quantize,
                dtype=dtype,
                trust_remote_code=trust_remote_code,
            )
        elif sharded:
            raise NotImplementedError(FLASH_ATT_ERROR_MESSAGE.format("Sharded Llama"))
        else:
            return CausalLM(
                model_id,
                revision,
                quantize=quantize,
                dtype=dtype,
                trust_remote_code=trust_remote_code,
            )
```

By this code, to use LLaMA model with tensor parallel sharding, we must use Flash Attention module.
But when we use other models like BLOOM, we don't need to use it.

Anyway, to short:
- We failed infer 16k length text using tensor parallel sharded LLaMA2 7B model with A100 80G * 8 machine.
- But we've succeed to infer same texts using other sharded 13B models (e.g. BLOOM) with same machine before.
- The one possible reason may be Flash attention. but I am not sure about it.

Nowadays, long context inference is very hot topic, in the mean time, LLaMA2 is also very popular model in community. Please consider to pay attention to this problem.

Thanks.

**Comment by hyunwoongko** [comment]
In addition, short text inference with same setting and environment (LLaMA2-7b) was succeed.
This problem only occurred in the long context evaluation test.

**Comment by Narsil** [comment]
I am not able to reproduce this.

Get 2xA10g:

```
text-generation-launcher --model-id togethercomputer/Llama-2-7B-32K-Instruct  --rope-scaling=linear --rope-factor=8.0 --max-input-length 17000 --max-total-tokens=18000 --max-batch-prefill-tokens=18000 --num-shard 2
```

Test: Take 1200 first lines of https://www.gutenberg.org/cache/epub/103/pg103.txt (Happens to be > 16k tokens for this model).

Curl it.
Current output: 
```
data:{"token":{"id":30015,"text":"“","logprob":-0.42626953,"special":false},"generated_text":"Passepartout, meanwhile, was being questioned by the detective.\n\n“","details":null}
```

Everything seems to be working normally, even the output seems OK.

Do you have any other input which might help reproduce ?
