### ISSUE TITLE
Causal LM modifies the input when returning text

### ISSUE THREAD

**Issue by thomasw21** [huggingface/text-generation-inference#12]
One of the issues if that Causal LM returns the entire `input + generated_text`. And `input` is actually `tokenizer.decoder(tokenizer.encode(input))`. The issue comes when that process is lossy, and causes weird behaviours such as this https://huggingface.co/bigscience/bloom/discussions/153#6397907b71eb2455d898e0a4 

We can instead either:
 - actually use the input instead of going through a potentially lossy mechanism.
 - change the API to always return "added" text. **BREAKING**

**Comment by thomasw21** [comment]
One hot fix concerning the specific BLOOM issue is to set `clean_up_tokenization_spaces=False`, but it's only because BLOOM tokenizer is lossless.

**Comment by OlivierDehaene** [comment]
Fixed on main.
