### ISSUE TITLE
Sharding Error: Not Enough CUDA Devices

### ISSUE THREAD

**Issue by ongmk** [huggingface/text-generation-inference#1204]
**Problem Description:** I'm encountering an error upon running a docker container for TGI with sharding enabled to utilize my two GPUs. Even though my container setup is correct and GPU enablement is confirmed (as per PyTorch and nvidia-smi insights from within the container), I'm still receiving the error: `Error: NotEnoughCUDADevices("``sharded`` is true but only found 1 CUDA devices")`
![image](https://github.com/huggingface/text-generation-inference/assets/23038332/7d4a0636-b2e1-4b3a-a3e9-699e6450bcd4)

**Environment:**
OS: Windows
GPUs: 2 * NVIDIA GeForce GTX 1080 Ti
Docker image: ghcr.io/huggingface/text-generation-inference:1.1.1

To illustrate, here's the output of PyTorch and nvidia-smi within the container, showing two GPUs.
**PyTorch Output**
![image](https://github.com/huggingface/text-generation-inference/assets/23038332/992ce80e-98a7-4846-870e-8f6c6af2cdae)

**nvidia-smi Output**
![image](https://github.com/huggingface/text-generation-inference/assets/23038332/01c8579e-4917-4462-8b62-45ca895cbd12)

I'd appreciate any guidance on troubleshooting this issue.

**Comment by OlivierDehaene** [comment]
Can you try setting the number of shards explicitely? 

```shell
podman run -it --device nvidia.com/gpu=all --shm-size 1g -p 8080:80 -v ./data:/data text-generation-inference:1.1-1 --num-shard 2
```

**Comment by ongmk** [comment]
@OlivierDehaene Thanks for the help. I think it solves the problem. (although I now see that it requires Flash Attention, and my hardware doesn't support that). But I thought NUM_SHARD defaults to use all GPUs available?

**Comment by OlivierDehaene** [comment]
It should yes but I'm not sure what env vars podman uses to specify the GPUs. I remember it not being the same one used by docker so that might be the reason.

**Comment by ongmk** [comment]
@OlivierDehaene I see. Thanks a lot!
