### ISSUE TITLE
H1100 4 GPUs (80GB memory on each GPU) - CUDA12.1 compatible docker image

### ISSUE THREAD

**Issue by jvemugunta** [huggingface/text-generation-inference#1205]
### System Info

when we inspected the latest ghcr.io/huggingface/text-generation-inference:1.1.0 image, It supports only pytorch 2.0.1 on cuda 11.8. When we use meta-llama/Llama-2-70b-chat-hf model with this docker image, the model can't shad for more than2 GPUs. 

We found a branch feat/cuda-12 with the right cuda and pytorch versions, but were unable to find the equal container image. 
Can anyone guide me on the right container image for feat/cuda-12 branch?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Unable to find the right docker image for feat/cuda-12 branch

### Expected behavior

Unable to find the right docker image for feat/cuda-12 branch

**Comment by OlivierDehaene** [comment]
1.2 now ships with cuda 12.
