### ISSUE TITLE
Performance: Consider mlc-llm as an inference backend

### ISSUE THREAD

**Issue by sa-** [huggingface/text-generation-inference#1212]
### Feature request

This project https://github.com/mlc-ai/mlc-llm seems to get a higher throughput than vllm or exllama (about 40% higher in the graphs on the README.md). They explain their approaches in great detail in book site here: https://mlc.ai/chapter_introduction/index.html

### Motivation

Fewer cloud costs & less electricity wasted.

### Your contribution

Happy to contribute, but since I'm new to the code base I would need some pointers on how to get started. Also worth noting that the readme link in the issue template leads to a 404

**Comment by OlivierDehaene** [comment]
Yeah I just ran their benchmark with CodeLlama34B FP16 on 4xA10g and we are actually on-par/faster than them at 25 tok/secs... This might explain why TGI is suspiciously not included in their blog post, don't you think?

**Comment by sa-** [comment]
That's good to know, and congrats on being faster!
