### ISSUE TITLE
AWQ does not reduce inference latency

### ISSUE THREAD

**Issue by Anditty** [huggingface/text-generation-inference#1217]
### System Info

**tgi version**：1.1.0
**flash-attention**： v2
**device**: A30(24G)*4
**model**：TheBloke/CodeLlama-13B-fp16 vs TheBloke/CodeLlama-13B-AWQ

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

**server(fp16)**：
  text-generation-launcher \
    --model-id CodeLlama-13B-fp16 \
    --port 8081 \
    --max-input-length 4096 --max-total-tokens 8192 --max-batch-prefill-tokens 8192 \
    --num-shard 4 \
**server(awq)**：
  text-generation-launcher \
    --model-id CodeLlama-13B-AWQ \
    --port 8080 \
    --max-input-length 4096 --max-total-tokens 8192 --max-batch-prefill-tokens 8192 \
    --quantize awq \
    --num-shard 4
**client**:
     output = client.generate('write a bfs algorithm', max_new_tokens=32,
                                            stop_sequences=[],
                                            do_sample=False).generated_text

The latency of the two models are almost identical. Then I tested both models on my test set (sending requests serially), but the latency of the two models was not significantly different.

### Expected behavior

According to the https://github.com/huggingface/text-generation-inference/pull/1019, with batch size=1, the model using awq quantization should have more than 1.6x improvement (25ms vs 15ms latency).

**Comment by xiaojiangzhang** [comment]
I also have this question

**Comment by xiaojiangzhang** [comment]
I also have this problem
