### ISSUE TITLE
Handling Concurrent Request

### ISSUE THREAD

**Issue by jerin-scalers-ai** [huggingface/text-generation-inference#1221]
How is TGI handles concurrent request ? Does it process all the concurrent requests in parallel ? 

I did a load test with 2000 concurrent requests and noticed that the average token latency remained around ~70ms, which is the same as when I initially tested with 150 concurrent requests. Why didn't the token latency increase as the number of concurrent requests went up?

**Comment by OlivierDehaene** [comment]
TGI has an internal queue of requests that it uses for batcing. If the queue is already filled by 150 concurrent requests, having more will not impact how TGI batches the requests together, leading to the same throughput.
