### ISSUE TITLE
TGI a049864 (1.1.0) has significantly lower throughput than 8672cad (1.0.3) 

### ISSUE THREAD

**Issue by vgod-dbx** [huggingface/text-generation-inference#1227]
### System Info

Tested both versions with the following docker images on 1 H100 GPU.
`docker run --gpus all --shm-size 1g -p 7860:7860 --env HUGGING_FACE_HUB_TOKEN=<REDACTED> ghcr.io/huggingface/text-generation-inference:sha-a049864  --port 7860 --max-input-length 2500 --max-total-tokens 4096 --dtype float16 --model-id meta-llama/Llama-2-7b-chat-hf`

`docker run --gpus all --shm-size 1g -p 7860:7860 --env HUGGING_FACE_HUB_TOKEN=<REDACTED> ghcr.io/huggingface/text-generation-inference:sha-8672cad  --port 7860 --max-input-length 2500 --max-total-tokens 4096 --dtype float16 --model-id meta-llama/Llama-2-7b-chat-hf`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I started TGI using the docker commands above and sent 64 concurrent requests to the service to benchmark the throughput and latency. Surprisingly, I found out TGI 1.1.0 performed much worse than 1.0.3. The throughput I got on 1.0.3 was about 1500 tokens/sec, but only 330 tokens/sec on 1.1.0.
From the server logs, I noticed that the queue time on 1.1.0 was much longer (up to 6.5 seconds) while the queue time on 1.0.3 is often less than 200ms~400ms.

I bisected the commits between 1.1.0 and 1.0.3, and found the culprit is  [a049864](https://github.com/huggingface/text-generation-inference/commit/a049864270aa44226ccc33f3b5ef929222307e9c), which upgraded many dependencies with some minor changes. I think it's one of the dependencies causing the issue but not sure which one.

### Expected behavior

The performance of 1.1.0 should be the same or better than 1.0.3.

**Comment by OlivierDehaene** [comment]
Thanks for reporting. We do not do regression tests on H100 so this went under the radar as we the issue is not present on Ampere. Can you make sure that `latest` suffer from the same issue?

**Comment by vgod-dbx** [comment]
yes, I can confirm `latest` still suffers from the same issue.

**Comment by vgod-dbx** [comment]
I tested this on A100 as well and confirmed that the issue didn't happen on A100.

**Comment by Narsil** [comment]
We just upgraded everything again to use Cuda 12.1 and Pytorch 2.1, and everything seems to be working properly.

~5k token/s on a single H100 (batch_size = 128).

We're releasing :1.2.0 which will include everything very soon.

**Comment by vgod-dbx** [comment]
That's great news! Looking forward to testing it out! Thank you.

**Comment by Narsil** [comment]
Could you confirm everything is working ? We tested on our end and everything seems working perfectly.

**Comment by vgod-dbx** [comment]
Hi, I tested `ghcr.io/huggingface/text-generation-inference:1.2` but still got the same issue. The throughput was only ~350 tokens/sec.
My test was sending 64 concurrent requests to the server where each request has one short prompt less than 50 tokens and max_new_tokens = 100. From the server logs, I can see the requests getting queued up (queue_time grew to ~7sec quickly) so maybe continuous batching was not working properly.
