### ISSUE TITLE
WQLinear is not defined

### ISSUE THREAD

**Issue by abhimasand** [huggingface/text-generation-inference#1234]
### System Info

text generation inference version 1.1.0
platform sagemaker

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Run the following script:

```
import sagemaker
import boto3
sess = sagemaker.Session()
# sagemaker session bucket -> used for uploading data, models and logs
# sagemaker will automatically create this bucket if it not exists
sagemaker_session_bucket=None
if sagemaker_session_bucket is None and sess is not None:
    # set to default bucket if a bucket name is not given
    sagemaker_session_bucket = sess.default_bucket()

try:
    role = sagemaker.get_execution_role()
except ValueError:
    iam = boto3.client('iam')
    role = iam.get_role(RoleName='sagemaker_execution_role')['Role']['Arn']

sess = sagemaker.Session(default_bucket=sagemaker_session_bucket)
role = 'arn:aws:iam::794016200254:role/global-ai-role'

print(f"sagemaker role arn: {role}")
print(f"sagemaker session region: {sess.boto_region_name}")

from sagemaker.huggingface import get_huggingface_llm_image_uri

# retrieve the llm image uri
llm_image = get_huggingface_llm_image_uri(
  "huggingface",
  version="1.1.0",
  session=sess,
)

# print ecr image uri
print(f"llm image uri: {llm_image}")

import json
from sagemaker.huggingface import HuggingFaceModel

# sagemaker config
instance_type = "ml.g5.2xlarge"
number_of_gpu = 1
health_check_timeout = 300

# Define Model and Endpoint configuration parameter
config = {
  'HF_MODEL_ID': "TheBloke/MistralLite-7B-AWQ", # model_id from hf.co/models
  'SM_NUM_GPUS': json.dumps(number_of_gpu), # Number of GPU used per replica
  'MAX_INPUT_LENGTH': json.dumps(12000),  # Max length of input text
  'MAX_TOTAL_TOKENS': json.dumps(12288),  # Max length of the generation (including input text)
  'MAX_BATCH_PREFILL_TOKENS': json.dumps(12288),  # Limits the number of tokens that can be processed in parallel during the generation
  'QUANTIZE': "awq", # comment in to quantize
}

# check if token is set

# create HuggingFaceModel with the image uri
llm_model = HuggingFaceModel(
  role=role,
  image_uri=llm_image,
  env=config
)

llm = llm_model.deploy(
  initial_instance_count=1,
  instance_type=instance_type,
  container_startup_health_check_timeout=health_check_timeout, # 10 minutes to be able to load the model
)

```

### Expected behavior

I am recieving the following error when trying to deploy ''TheBloke/MistralLite-7B-AWQ"

```
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 252, in get_model
    return FlashMistral(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_mistral.py", line 321, in __init__
    model = FlashMistralForCausalLM(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 486, in __init__
    self.model = MistralModel(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 422, in __init__
    [
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 423, in <listcomp>
    MistralLayer(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 357, in __init__
    self.self_attn = MistralAttention(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 230, in __init__
    self.query_key_value = load_attention(config, prefix, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 159, in load_attention
    return _load_gqa(config, prefix, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 192, in _load_gqa
    get_linear(weight, bias=None, quantize=config.quantize)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 332, in get_linear
    linear = WQLinear( 
```

As I understand AWQ models are supported, and I can deploy the original MIstral model, however, when i try to deploy this MistralLite model, it gives me the WQLinear error which I'm not sure why.

**Comment by abhatia-07** [comment]
Getting a similar error when trying to deploy [TheBloke/Llama-2-70B-Chat-AWQ ](https://huggingface.co/TheBloke/Llama-2-70B-Chat-AWQ)on sagemaker

**Comment by AwikDhar** [comment]
Getting the same error as well despite tgi 1.1.0, trying to deploy TheBloke/Llama-2-7B-Chat-AWQ on sagemaker. GPTQ version loads and works fine, AWQ does not.

**Comment by abhatia-07** [comment]
I had checked this with AWS and it was indeed a sagemaker issue. Using this image directly instead of one provided by AWS solved the issue for me

**Comment by AwikDhar** [comment]
As in, you ran locally the docker command, nothing to do with sagemaker? I need serverless inference, so kinda sucks for me.

**Comment by abhatia-07** [comment]
I was able to deploy it in sagemaker.

You can build a docker image of TGI version 1.1.0 and push it to ECR.
Then that can be used while deploying the sagemaker endpoint

Something like this:
```
# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
	image_uri=custom_image_uri,
	env=hub,
	role=role, 
)
```

Also make sure you're setting this parameter: `'HF_MODEL_QUANTIZE': 'awq'`

**Comment by angeligareta** [comment]
I am also having the same issue, can not deploy the following configuration

config = {
    "HF_MODEL_ID": "01-ai/Yi-34B-Chat-4bits",
    'SM_NUM_GPUS': json.dumps(4),
    'QUANTIZE': 'awq',
    'HF_MODEL_QUANTIZE': 'awq'
}

# ml.g5.12xlarge

Can I get some help?

**Comment by AwikDhar** [comment]
Hey, @abhatia-07 . I tried pulling and building the TGI image myself and then publishing to ECR. Firstly, the memory requirements to successfully build were insane(peaking at 100GB RAM usage). Secondly, deploying the model with the pushed image on ECR gives me the same error it does when I directly pull and push to ECR without building:

<img width="426" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/59658014/43ac0662-3dfe-4ccc-995e-74df2205a16a">

These are the commands I followed:
1) git clone   https://github.com/huggingface/text-generation-inference
2) docker pull ghcr.io/huggingface/text-generation-inference:latest
3) aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 819618691026.dkr.ecr.ap-south-1.amazonaws.com
4) docker build --build-arg TGI_IMAGE=ghcr.io/huggingface/text-generation-inference:latest -t 819618691026.dkr.ecr.ap-south-1.amazonaws.com/my-tgi-111 -f Dockerfile .
5) docker push 819618691026.dkr.ecr.ap-south-1.amazonaws.com/my-tgi-111

Did you do anything differently? Is this some entrypoint issue?

**Comment by abhatia-07** [comment]
I took the entry point script from the repo itself: sagemaker-entrypoint.sh

And this is the DockerFile content

`FROM ghcr.io/huggingface/text-generation-inference:1.1.0

COPY sagemaker-entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]`
