### ISSUE TITLE
'temperature' must be strictly positive

### ISSUE THREAD

**Issue by austinmw** [huggingface/text-generation-inference#1236]
### System Info

SageMaker DLC: `763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-tgi-inference:2.0.1-tgi1.1.0-gpu-py39-cu118-ubuntu20.04`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Deploying Mistral 7B and attempting to pass temperature parameter of 0.0.

### Expected behavior

0 should be a valid temperature, and is desirable for many use cases, however, an error is produced if it is not strictly positive.

CloudWatch logs:

> #033[2mtext_generation_router::infer#033[0m#033[2m:#033[0m #033[2mrouter/src/infer.rs#033[0m#033[2m:#033[0m#033[2m111:#033[0m `temperature` must be strictly positive

**Comment by OlivierDehaene** [comment]
In what case a temperature of 0 is desirable?

**Comment by Legion2** [comment]
We are facing the same problem, we want a deterministic output for our fine tuned model, no randomeness.

**Comment by james-deee** [comment]
This is so bizarre that this is closed. You can aboslutely positively (pun intended) send a temperature of `0.0` to these models. Why in the world is this restricted in this?

**Comment by VaradhKaushik** [comment]
You can set `top_k=1` (limits token selection to the top k highest-probability options) to get the same deterministic output as a temperature of 0. Hope that helps!
