### ISSUE TITLE
Support Dynamic SplitFuse

### ISSUE THREAD

**Issue by Rogerwyf** [huggingface/text-generation-inference#1237]
### Feature request

Adding support for dynamic splitfuse or at least look into it to see if it's worth adding :)

### Motivation

[Dynamic SplitFuse](https://github.com/microsoft/DeepSpeed/blob/master/blogs/deepspeed-fastgen/README.md#3-dynamic-splitfuse-a-novel-prompt-and-generation-composition-strategy) is a novel token composition strategy for prompt processing and token generation proposed by the Deepspeed group. They have reported faster speeds than vLLM.

I know new things come out every day and it's impossible to add everything single optimization all the time, but it seems that so far no one has mentioned about this here so I'd like to put this on your radar.

### Your contribution

Don't have a plan to work on it right away, but I can help running some benchmarks between TGI and deepspeed-fastgen to see how much performance difference there is.

**Comment by OlivierDehaene** [comment]
Hello
I would be happy to see benchmarks between Fastgen and TGI if you have the time to make them.
