### ISSUE TITLE
Does text-generation-router support dynamic batching across GPUs?

### ISSUE THREAD

**Issue by Stanislas0** [huggingface/text-generation-inference#124]
Hi! Thanks for the wonderful work! I have successfully run the router on a single GPU with multiple instances, and it works as expected. I wonder if this framework also supports running on multiple GPUs (each running multiple model instances, on a single machine, or across nodes). If so, how I can do this?

**Comment by OlivierDehaene** [comment]
Hi

If you want to have n replicas of the same model on the same node you can launch text-generation-launcher n times and add a HTTP load balancer on top. text-generation-inference does not do the load balancing itself.

**Comment by Stanislas0** [comment]
Thanks for the explanation! I'll have a try.
