### ISSUE TITLE
[Feature] Model Info Endpoint

### ISSUE THREAD

**Issue by ScientiaEtVeritas** [huggingface/text-generation-inference#125]
If it's not already possible in some way to get that information, I think it would be convenient to have a model info endpoint that exposes which model is currently running on it.

**Comment by OlivierDehaene** [comment]
Yes we are currently working on adding this as a tag on the hub.

**Comment by OlivierDehaene** [comment]
@ScientiaEtVeritas,

The list of models running with text-generation-inference is now exposed at `https://api-inference.huggingface.co/framework/text-generation-inference`.

You can also use the v5.0.0 python client to get the same info:

```python
from text_generation.inference_api import deployed_models

print(deployed_models())
```

**Comment by ScientiaEtVeritas** [comment]
@OlivierDehaene This is a great addition but not exactly what I meant with this issue. I was rather referring to a way to get the model that is running on a specific instance of `text-generation-inference`. For example, if I deployed the `bigscience/bloom-560m` model, I think it would be handy to be able to retrieve that info via `curl 127.0.0.1:8080/model_info` or something in a similar vein.

**Comment by OlivierDehaene** [comment]
Ah!
