### ISSUE TITLE
MPT model based not running for sealion7b-instruct-nc model

### ISSUE THREAD

**Issue by muhammad-asn** [huggingface/text-generation-inference#1251]
Hey! I'd like to verify is this [sealion7b-instruct-nc](https://huggingface.co/aisingapore/sealion7b-instruct-nc) model is supported or not? Because It's based on the MPT architecture, and I want to ensure there are no compatibility issues.

**Issues:**
Got error when running sealion7b-instruct-nc model
```

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 165, in get_model
    return MPTSharded(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/mpt.py", line 57, in __init__
    tokenizer = AutoTokenizer.from_pretrained(

  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 733, in from_pretrained
    raise ValueError(

ValueError: Tokenizer class SEABPETokenizer does not exist or is not currently imported.
 rank=0
2023-11-09T13:49:42.777519Z ERROR text_generation_launcher: Shard 0 failed to start
2023-11-09T13:49:42.777550Z  INFO text_generation_launcher: Shutting down shards
```

**Current actions taken:**
- Attempted to resolve the issue by updating the transformer library from version 4.33.2 to 4.34.1 still got the error

**Questions**:
* Do I need to create custom_modelling although it's MPT architecture(?) Also do I need create the SEABPETokenizer as well?

**Note (library version):**
```
Current TGI:
- transformers==4.33.2
- tokenizers==0.13.3

Required for running  sealion7b-instruct-nc
- transformers==4.34.1
- tokenizers==0.14.1
```

Gladly appreciate, for anyone looking into this. Thank you

**Comment by raymondng76** [comment]
Hi @muhammad-asn ,
The sealion tokenizer requires custom code execution, may I confirm if you had set `trust_remote_code=True` when you initalize the tokenizer?

The exact flag in question is as follows:
https://github.com/huggingface/text-generation-inference/blob/a5def7c222174e03d815f890093584f3e815c5ce/server/text_generation_server/models/mpt.py#L47C6-L47C6

**Comment by muhammad-asn** [comment]
Hello @raymondng76 thank you for your response.

Yes I follow your instruction to set the `trust_remote_code=True`,

In AutoTokenizer: https://github.com/huggingface/text-generation-inference/blob/a5def7c222174e03d815f890093584f3e815c5ce/server/text_generation_server/models/mpt.py#L47C6-L47C6

In AutoModel: https://github.com/huggingface/text-generation-inference/blob/a5def7c222174e03d815f890093584f3e815c5ce/server/text_generation_server/models/causal_lm.py#L485

but it shows another error.
```
File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/mpt_modeling.py", line 762, in _init_
    raise RuntimeError("no alibi no supported")

RuntimeError: no alibi no supported
```

**Comment by raymondng76** [comment]
Hi @muhammad-asn ,

That is unfortunate as sealion differs from MPT in that it does not use alibi and it seems like TGI had commented out the support for the embedding layers.

You might wish to modify the code below to enable the embedding layer, however, I am unsure if it would lead to further issues with TGI.

MPT model class in TGI:
https://github.com/huggingface/text-generation-inference/blob/a5def7c222174e03d815f890093584f3e815c5ce/server/text_generation_server/models/custom_modeling/mpt_modeling.py#L759

sealion config:
https://huggingface.co/aisingapore/sealion7b-instruct-nc/blob/019608cb2abd8173ffaa2b5fda7374a5bb8c1dba/config.json#L7

**Comment by Jason-CKY** [comment]
uncommenting that line of code will cause an `NotImplementedError` on this line: https://github.com/huggingface/text-generation-inference/blob/a5def7c222174e03d815f890093584f3e815c5ce/server/text_generation_server/models/custom_modeling/mpt_modeling.py#L31

I did a workaround by replacing https://github.com/huggingface/text-generation-inference/blob/a5def7c222174e03d815f890093584f3e815c5ce/server/text_generation_server/models/mpt.py#L87
with 
```python
from transformers import AutoModelForCausalLM
model = AutoModelforCausalLM.from_pretrained(model_id, trust_remote_code=trust_remote_code)
model.to("cuda")
```

However, i ran into a warning message from the rust webserver that `Could not find a fast tokenizer implementation for aisingapore/sealion7b-instruct-nc` and `Rust input length validation and truncation is disabled`. This causes input validation error whenever your `max_tokens` parameter is >= `MAX_TOTAL_TOKENS - MAX_INPUT_LENGTH`. I put another API layer on top of TGI so i could write my own validation logic to workaround this.

https://github.com/huggingface/text-generation-inference/blob/3238c49121b02432bf2938c6ebfd44f06c5adc2f/router/src/main.rs#L165-L169

To resolve this would most likely require a Pull Request to add support for `mpt` architectures without `alibi`, and would most likely require `FastTokenizer` support for sealion models as well.

Hopefully this comment helps anybody trying to deploy sealion models
