### ISSUE TITLE
RuntimeError: Not enough memory to handle 16384 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

### ISSUE THREAD

**Issue by jiangix-paper** [huggingface/text-generation-inference#1263]
### System Info

tgi version 1.0.3
GPU: 8*A100 80G
flash attn version: 2.3.2

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Hello, When I use the flash-attn==2.3.2, it has the error:
RuntimeError: Not enough memory to handle 16384 prefill tokens. You need to decrease `--max-batch-prefill-tokens`

But when I use the flash-attn following the version:
<img width="483" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/62198809/2c650a68-5f5f-4196-923e-678fd476a215">
 
It works!!!. Must we use the flash-attn above?

### Expected behavior

flash-attn 2.3.2 is not work

**Comment by GeorgeDittmar** [comment]
I'm running into similar issue as of version 1.1.1. previous version of 1.1.0 works fine loading llam2 13b model using bits and bytes on my 3080. Did something change in the latest version?

**Comment by gameveloster** [comment]
Is `1.1.0` the latest version without this memory problem?
