### ISSUE TITLE
unable to install TGI locally

### ISSUE THREAD

**Issue by poojitharamachandra** [huggingface/text-generation-inference#1264]
### System Info

hi,

 i am trying to install tgi locally using rust and protoc as describe in ur homepage.
but i get the following error:

(base)BMH:~$ BUILD_EXTENSIONS=True make install
make: *** No rule to make target 'install'.  Stop.
(base) BMH:~$ make run-falcon-7b-instruct
make: *** No rule to make target 'run-falcon-7b-instruct'.  Stop.

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

run the commands above

### Expected behavior

tgi must be installed locally

**Comment by poojitharamachandra** [comment]
hi, any solutions ?

**Comment by odellus** [comment]
You need to create a virtual environment for text-generation-inference. Also it doesn't look like you have changed into the text-generation-inference directory before running the commands?

**Comment by poojitharamachandra** [comment]
sorry what directory? should i download something?

even when i create and activate conda virtual env i get the same error

(base) prm9kor@BMH-C-001Q6:~$ conda activate text-generation-inference
(text-generation-inference) prm9kor@BMH-C-001Q6:~$ BUILD_EXTENSIONS=True make install
make: *** No rule to make target 'install'.  Stop.
(text-generation-inference) prm9kor@BMH-C-001Q6:~$

**Comment by odellus** [comment]
yes you need to `git clone https://github.com/huggingface/text-generation-inference && cd text-generation-inference` before running any of the commands in README.md

**Comment by poojitharamachandra** [comment]
mkdir text_generation_server/pb || true
mkdir: cannot create directory ‘text_generation_server/pb’: File exists
python -m grpcio-tools.protoc -I../proto --python_out=text_generation_server/pb \
        --grpc_python_out=text_generation_server/pb --mypy_out=text_generation_server/pb ../proto/generate.proto
/home/miniconda3/envs/text-generation-inference/bin/python: Error while finding module specification for 'grpcio-tools.protoc' (ModuleNotFoundError: No module named 'grpcio-tools')
make[1]: *** [Makefile:14: gen-server] Error 1
make[1]: Leaving directory '/home/prm9kor/text-generation-inference/server'
make: *** [Makefile:2: install-server] Error 2

**Comment by odellus** [comment]
Make sure you go through all the steps outlined in the README.md for [Local Install](https://github.com/huggingface/text-generation-inference#local-install). Looks like you don't currently have protocol buffers installed.

**Comment by poojitharamachandra** [comment]
ok, im able to install now. But make 'run-falcon-7b-instruct' is taking forever to run. it says downloading pytorch weights, but no progress even after hours

**Comment by odellus** [comment]
I always download the weights with `git lfs clone <huggingface model repo>` and pass a local file path, but there appear to be some issues doing that with tgi right now.

**Comment by poojitharamachandra** [comment]
do you have any suggestions on how to proceed?

**Comment by odellus** [comment]
I outline how I got around the problem many are having loading local weights in #1284. It's a total hack (you just comment out some code in `server/cli.py`), but I can load local weights. So I'd make sure it's not a problem with your ISP by downloading the weights. If you don't want to use git lfs clone you can also fire up an IPython REPL and download the weights with `.from_pretrained` with hf transformers.

**Comment by poojitharamachandra** [comment]
is it possible to give a folder reference containing the model files to run tgi?

**Comment by odellus** [comment]
yes it is. please check out the issue I referenced
