### ISSUE TITLE
Can't `docker pull ghcr.io/huggingface/text-generation-inference:1.1.1`

### ISSUE THREAD

**Issue by LetianLee** [huggingface/text-generation-inference#1265]
### System Info

`docker pull ghcr.io/huggingface/text-generation-inference:sha-5a1512c` succeeded
`docker pull ghcr.io/huggingface/text-generation-inference:1.1.1` failed

![image](https://github.com/huggingface/text-generation-inference/assets/73881739/6b340162-ce63-446c-9bcc-de7ab3967ce1)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker pull ghcr.io/huggingface/text-generation-inference:1.1.1

### Expected behavior

Sorry if I am being foolish here. I attempted to run the command as shown in the Quick Tour but encountered issues. So, I tried pulling the images, but unfortunately, I still faced failures.

```
model=tiiuae/falcon-7b-instruct
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.1 --model-id $model
```

```
docker pull ghcr.io/huggingface/text-generation-inference:1.1.1
```

**Comment by josephrocca** [comment]
It's stuck here:

* https://github.com/huggingface/text-generation-inference/actions/runs/6892130310/job/18749584534

```
INFO: Downloading bootstrap version 'v1.11.1' of cosign to verify version to be installed...
      https://storage.googleapis.com/cosign-releases/v1.11.1/cosign-linux-amd64
ERROR: Unable to validate cosign version: 'v1.13.1'
Error: Process completed with exit code 1.
```

**Comment by jimangel** [comment]
It's worth noting, looking at cosign's release pages: https://github.com/sigstore/cosign/releases it looks like `v2.2.1` is out and patches a CVE if someone is going to update the cosign job anyway.

**Comment by Narsil** [comment]
This was fixed since.
