### ISSUE TITLE
text_generation_inference client is getting HTTP POST response as dictionary not a list of dictionary and getting return Response(**payload[0]) keyerror

### ISSUE THREAD

**Issue by aiforfun007** [huggingface/text-generation-inference#1273]
### System Info

text-generation-inference = 0.6.0
pyhton=3.9

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

import text_generation
import os
os.environ['CURL_CA_BUNDLE'] = ''
c= text_generation.client.Client(base_url="https://xyz:4999/generate",
                             headers={"api_key": "1b5db624-0c85-4461-adab-260228784839","model_name": "llama"},
                                timeout=60)

c.generate(
    prompt='generate python code to read a file',
    do_sample= False,
    max_new_tokens = 20,
    best_of = 1,
    repetition_penalty = 1.03,
    return_full_text=False,
    seed = 12343,
    stop_sequences = ['\n'],
    temperature = 0.1,
    top_k = 20,
    top_p = 0.95,
    truncate = 1,
    typical_p = 0.95,
    watermark= False,
    decoder_input_details = True,
    top_n_tokens= 5
)

Getting below error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[20], line 8
      3 os.environ['CURL_CA_BUNDLE'] = ''
      4 c= text_generation.client.Client(base_url="https://xyz:4999/generate",
      5                              headers={"api_key": "1b5db624-0c85-4461-adab-260228784839","model_name": "llama"},
      6                                 timeout=60)
----> 8 c.generate(
      9     prompt='generate python code to read a file',
     10     do_sample= False,
     11     max_new_tokens = 20,
     12     best_of = 1,
     13     repetition_penalty = 1.03,
     14     return_full_text=False,
     15     seed = 12343,
     16     stop_sequences = ['\n'],
     17     temperature = 0.1,
     18     top_k = 20,
     19     top_p = 0.95,
     20     truncate = 1,
     21     typical_p = 0.95,
     22     watermark= False,
     23     decoder_input_details = True,
     24     top_n_tokens= 5
     25 )

File C:\ProgramData\Anaconda3\envs\Gen_AI\lib\site-packages\text_generation\client.py:154, in Client.generate(self, prompt, do_sample, max_new_tokens, best_of, repetition_penalty, return_full_text, seed, stop_sequences, temperature, top_k, top_p, truncate, typical_p, watermark, decoder_input_details, top_n_tokens)
    152 if resp.status_code != 200:
    153     raise parse_error(resp.status_code, payload)
--> 154 return Response(**payload[0])

KeyError: 0

### Expected behavior

Should get response without any error

**Comment by Sinth0** [comment]
I’d still be interested in a fix for this.

**Comment by PeterTucker** [comment]
Bump. Would also like a fix for this.

**Comment by PeterTucker** [comment]
Hack: change lines 154 & 402 in ```text-generation-inference/main/clients/python/text_generation/client.py``` to this:
```
    if isinstance(payload, list) and len(payload) > 0:
        return Response(**payload[0])
    else:
        return Response(**payload)
```

**Comment by Narsil** [comment]
I think the URL is wrong

https://huggingface.co/docs/text-generation-inference/basic_tutorials/consuming_tgi#consuming-text-generation-inference

You should be pointing the raw URL, NOT the `/generate`.
