### ISSUE TITLE
Is pipeline parallelism supported?

### ISSUE THREAD

**Issue by sleepwalker2017** [huggingface/text-generation-inference#1275]
### Feature request

pipeline parallelism

### Motivation

To support running model on multiple nodes.

### Your contribution

No.

**Comment by Narsil** [comment]
No and it's probably never going to land. Multi node inference increases the latency by too much.

Quantization should be the type of methods to reach for if a given model exceeds the hardware you have.

**Comment by sleepwalker2017** [comment]
> inference

Thank you!
