### ISSUE TITLE
Lookahead decoding

### ISSUE THREAD

**Issue by comaniac** [huggingface/text-generation-inference#1278]
### Feature request

Lookahead decoding: https://lmsys.org/blog/2023-11-21-lookahead-decoding/.

### Motivation

It seems promising and doesn't require a draft model. More importantly, its repo (https://github.com/hao-ai-lab/LookaheadDecoding/blob/main/) has illustrated that this can be integrated into transformers seamlessly. Thus, it would be great if TGI could support this feature.

### Your contribution

I could maybe take a look at how this should be integrated into TGI later, but I cannot provide any ETA ATM.

**Comment by shermansiu** [comment]
Related issues:

Integration into `transformers`: https://github.com/huggingface/transformers/issues/27649
Integration into `vllm`: https://github.com/vllm-project/vllm/issues/1742

LADE has been integrated into `llama.cpp`.

**Comment by shermansiu** [comment]
According to #1169, lookahead decoding was found to be too expensive for integration into TGI. This is likely a reference to Joao Gante's test in https://github.com/huggingface/transformers/issues/27649#issuecomment-1824621466.
