### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by iChristGit** [huggingface/text-generation-inference#1280]
### System Info

I am trying to run this in order to connect it to chat-ui and run it all locally.
I have docker installed but when running the install commands through terminal/command prompt/power shell 
I get this error:
'model' is not recognized as an internal or external command,
and 
'volume' is not recognized as an internal or external command,

How can I specify it? i tried to put it in a dockerfile but still not working for me.. how can it accept the variables?
what am i missing?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

not relevant

### Expected behavior

Its not a bug its my error

**Comment by Narsil** [comment]
Can you share more specifically exactly what you're doing ?

Seems from the error that you're doing the command quite wrong, the error ` 'model' is not recognized as an internal or external command,` usually means the shell is trying to run those as core command, where normally only the first item of a command should be the core program.

Also you seem to be on Windows, are you running WSL ?

Please paste the entire output of the recommended information that gets suggested when you open an issue.

**Comment by iChristGit** [comment]
> Can you share more specifically exactly what you're doing ?
> 
> Seems from the error that you're doing the command quite wrong, the error ` 'model' is not recognized as an internal or external command,` usually means the shell is trying to run those as core command, where normally only the first item of a command should be the core program.
> 
> Also you seem to be on Windows, are you running WSL ?
> 
> Please paste the entire output of the recommended information that gets suggested when you open an issue.

I use Windows11, Just opening Powershell/command prompt and writing the install commands, do i need to do it inside a different enviorment?
