### ISSUE TITLE
Error while running custom mistral: CUDA Error: device-side assert triggered /usr/src/flash-attention/csrc/layer_norm/ln_fwd_kernels.cuh 236 ../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by monksgoyal** [huggingface/text-generation-inference#1281]
### System Info

version - 1.1.0, 1.1.1
A100
mistral model

### Information

- [ ] Docker
- [x] The CLI directly

### Tasks

- [ ] An officially supported command
- [x] My own modifications

### Reproduction

While running mistral for some prompt, i am getting below error:
CUDA Error: device-side assert triggered /usr/src/flash-attention/csrc/layer_norm/ln_fwd_kernels.cuh 236
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

I am unable to debug it, how to correct it?
while running the same prompt and same model using standard huggingface it is working fine.

### Expected behavior

There should not in any cuda assertion error.

**Comment by monksgoyal** [comment]
more stacktrace.

    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_mistral_modeling.py", line 264, in forward
    self.rotary_emb(query, cos, sin)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 698, in forward
    rotary_emb.apply_rotary(x1, x2, cos, sin, x1, x2, False)
RuntimeError: CUDA error: device-side assert triggered

**Comment by arashdn** [comment]
I have the same issue and I am using a docker container.
Same environemnt as above.

**Comment by Narsil** [comment]
Reopen issues and include all the asked information.
It's impossible to help without the full context of what you're doing.

Notably here it's most likely a cuda version environment issue on your end.

**Comment by thincal** [comment]
> Notably here it's most likely a cuda version environment issue on your end.

But how to identify the cuda issue ? @Narsil
