### ISSUE TITLE
Support output_hidden_states as a parameter for text-generation-inference

### ISSUE THREAD

**Issue by ginihumer** [huggingface/text-generation-inference#1282]
### Feature request

Allow "output_hidden_states" (and similar parameters like "output_attentions") as optional parameters so that hidden states of a model can be retrieved in addition to the output sequence.
This would greatly improve the transparency of models and it would allow for analyzing a model's inner state in addition to the generated text.

### Motivation

There are currently no text generation models hosted online that provide hidden states in addition to generated output. This means that models are completely opaque and users have no chance to open the black box unless they run it locally on their own machine and code their own inference api. This can take resources that the average user does not have and runs the risk that the model setup diverges from a hosted model. 
I think this addition accords with huggingface's values regarding openness and transparency. It would also support future research and curious users to analyze text generation models.

### Your contribution

I think that the changes required to support this feature would be minor, but the impact would be huge. I'd be happy to help with the implementation!

**Comment by HendrikStrobelt** [comment]
That would be an amazing feature. Any thoughts, @sashavor and @srush ?

**Comment by sashavor** [comment]
Yeah, that would really help with the GLTR implementation we were talking about! :hugs:

**Comment by iarbel84** [comment]
+1 for that. I'm developing an application that uses RAG. With the RAG output, I'm providing few-shot context to the LLM. As both RAG and text-generation use the same model under the hood, if TGI can output hidden states, this means I only have to hold a single model in memory. Without this support, I either have to load two models, one via Transformers, and the other via TGI, or avoid using TGI at all if I'm using a small instance (T-4).

As RAG-bases applications are gaining more and more popularity this would be an amazing feature to have.

**Comment by SulRash** [comment]
Just wanted to bump this thread and ask if anyone found a home-brewed solution for doing this with any kind of inference framework?

**Comment by ahmed-moubtahij** [comment]
Thread bump because I have this exact need
