### ISSUE TITLE
Error While Loading Locally Saved Model

### ISSUE THREAD

**Issue by dawnik17** [huggingface/text-generation-inference#1283]
### System Info

Docker Image: docker pull ghcr.io/huggingface/text-generation-inference:sha-3c02262

While running docker run command, I use `--model-id /data/<PATH-TO-FOLDER>` as suggested [here](https://huggingface.co/docs/text-generation-inference/basic_tutorials/non_core_models)

I store the model in the `/data` (i.e. $volume) directory and use model_id as `/data/Llama-2-7b-chat-hf`

I get the following error:

`huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/Llama-2-7b-chat-hf'. Use repo_type argument if needed.`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. `docker pull ghcr.io/huggingface/text-generation-inference:sha-3c02262`
2. volume=$PWD/data
3. Save llama-7b weights in the data folder
4. `docker run --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:sha-3c02262 --model-id /data/Llama-2-7b-chat-hf`

### Expected behavior

I would want the model to load and the API to start listening on the designated port.

**Comment by Narsil** [comment]
Could you check all your paths from within the docker itself ? Most likely a misconfig here since I'm regularly using this mounted local option too without issue.

If you're pointing to your cache folder for instance, transformers (and therefore TGI) expect a folder directly containing `config.json` for instance, therefore in the cache it's in the form `~/.cache/huggingface/hub/models--XXXXX/snaphots/xxxxxxx/`  (you need to specify the actual snapshot)

**Comment by dawnik17** [comment]
Sure, Narsil. I'll give it a shot. Thanks! :)

I've temporarily switched to version `v1.1.1` for the Docker image I'm pulling. Interestingly, everything appears to function smoothly with this lower version.

**Comment by adinin** [comment]
Just wanted to add here that I experienced something similar. 
I have a local folder with .bin files. I tried to run the `latest` Docker container with `MODEL_ID=/app/model/check_points/test/` as environment variable and saw this error:


{"timestamp":"2023-11-30T16:16:06.903363Z","level":"ERROR","fields":{"message":"Download encountered an error: Traceback (most recent call last):\n\n  File \"/opt/conda/lib/python3.10/site-packages/peft/utils/config.py\", line 117, in from_pretrained\n    config_file = hf_hub_download(\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py\", line 110, in _inner_fn\n    validate_repo_id(arg_value)\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py\", line 158, in validate_repo_id\n    raise HFValidationError(\n\nhuggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/app/model/check_points/test/'. Use `repo_type` argument if needed.\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/peft.py\", line 16, in download_and_unload_peft\n    model = AutoPeftModelForCausalLM.from_pretrained(\n\n  File \"/opt/conda/lib/python3.10/site-packages/peft/auto.py\", line 69, in from_pretrained\n    peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)\n\n  File \"/opt/conda/lib/python3.10/site-packages/peft/utils/config.py\", line 121, in from_pretrained\n    raise ValueError(f\"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'\")\n\nValueError: Can't find 'adapter_config.json' at '/app/model/check_points/test/'\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"/opt/conda/lib/python3.10/site-packages/peft/utils/config.py\", line 117, in from_pretrained\n    config_file = hf_hub_download(\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py\", line 110, in _inner_fn\n    validate_repo_id(arg_value)\n\n  File \"/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py\", line 158, in validate_repo_id\n    raise HFValidationError(\n\nhuggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/app/model/check_points/test/'. Use `repo_type` argument if needed.\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py\", line 156, in download_weights\n    utils.download_and_unload_peft(\n\n  File \"/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/peft.py\", line 24, in download_and_unload_peft\n    model = AutoPeftModelForSeq2SeqLM.from_pretrained(\n\n  File \"/opt/conda/lib/python3.10/site-packages/peft/auto.py\", line 69, in from_pretrained\n    peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)\n\n  File \"/opt/conda/lib/python3.10/site-packages/peft/utils/config.py\", line 121, in from_pretrained\n    raise ValueError(f\"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'\")\n\nValueError: Can't find 'adapter_config.json' at '/app/model/check_points/test/'\n\n"},"target":"text_generation_launcher","span":{"name":"download"},"spans":[{"name":"download"}]}



Then, I tried using the `1.1.0` tag Docker image and the bin files were detected and converted to .safetensors.

**Comment by lpfhs** [comment]
Seem like this is an issue in TGI 1.2.0, probably due to this commit: https://github.com/huggingface/text-generation-inference/commit/e12c34bd25c8297c1df33493cbcedef8ffa1306f

The issue only manifests if you're trying to load a local model and the model doesn't have the safetensors weights. Here is how to reproduce:
```
git clone https://huggingface.co/distilgpt2
rm distilgpt2/model.safetensors
text-generation-launcher --model-id ./distilgpt2/
```

**Comment by walkacross** [comment]
> ~/.cache/huggingface/hub/models--XXXXX/snaphots/xxxxxxx/

@Narsil hi , could you please tell us more detail about how to mount the model locally?

if the parameters are in ~/.cache/huggingface/hub/models--XXXXX/snaphots/xxxxxxx/, how to set the params in docker command, since there is no detail doc for this.
~~~
model_param_in_local = "~/.cache/huggingface/hub/models--microsoft--phi-2/snaphots/xxxxxxx/"
model=<what to set?>
volume=$model_param_in_local/data #  is this right?

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.3 --model-id $<what to set?>
~~~
please give us detail doc or a concrete example. thanks

**Comment by BaiMoHan** [comment]
same issue

**Comment by Narsil** [comment]
`--model-id /data`

It's all linked to how docker works: `-v $volume:/data` 
https://docs.docker.com/storage/volumes/
