### ISSUE TITLE
`text-generation-benchmark` ignores `--max-batch-prefill-tokens` which may lead to unexpected OOM

### ISSUE THREAD

**Issue by fxmarty** [huggingface/text-generation-inference#1286]
### System Info

main

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

(quite low priority)

As per title, in my experience `text-generation-launcher` ignores `--max-batch-prefill-tokens` (default 4096), and may OOM due to this, as `CacheManager` is then initialized with too many blocs (https://github.com/huggingface/text-generation-inference/blob/3c02262f29fba3bf1096f22017f70d59ff4daa4d/server/text_generation_server/models/flash_causal_lm.py#L703), leaving not enough memory for the forward to run.

We may gracefully raise an error in case `text-generation-benchmark` is used with more tokens than specified in `text-generation-launcher`.

### Expected behavior

No OOM, explicit error message instead

**Comment by Narsil** [comment]
Kind of intended by the design. It bypasses the router in order to control with very fine precision the actual computation being run.

Only the router knows about input limits, the python backend doesn't do any sanitation.

Definitely inconvenient when you hit it though.

**Comment by Narsil** [comment]
Why the need to deactivate the router ?
