### ISSUE TITLE
Is there any tool / endpoint or any solution to collect metrics from TGI image and filter these metrics?

### ISSUE THREAD

**Issue by gireesh99** [huggingface/text-generation-inference#1288]
I am currently running a TGI container and collecting  metrics on its performance using /metrics endpoint. However, I only want to collect metrics for specific times and days. Is it possible to add a filtering feature to the TGI container that allows me to specify a time range and/or specific days of the week for which metrics should be collected?

For example, I would like to collect metrics between 9am-5pm, Monday through Friday. Will the metrics be reset each day, or will they continue to accumulate from the start time/day of the container? Additionally, are there any existing tools or methods that can be used to achieve this functionality?

**Comment by OlivierDehaene** [comment]
Usually, you scrape the `/metrics` route with Prometheus.
Then, you can use PromQL and/or Grafana to filter and display the metrics/aggregates you are interested in.

Tutorial: https://prometheus.io/docs/prometheus/latest/getting_started/#configure-prometheus-to-monitor-the-sample-targets
