### ISSUE TITLE
Using TGI as a library in serving app

### ISSUE THREAD

**Issue by dhritiman** [huggingface/text-generation-inference#1289]
### Feature request

From https://huggingface.co/docs/text-generation-inference/installation it looks like TGI can be installed as a standalone server. Is there a way TGI can be used as a library as part of a serving app ? This will be useful for use-cases that need to run their own serving application but use a TGI backend, without an extra network call.

If it doesn't exist, do you have this in the roadmap ?

### Motivation

Use TGI as backend in a serving app, without additional network call.

### Your contribution

Will wait for response from TGI team.

**Comment by rahuldshetty** [comment]
In an ideal scenario, I'd consider to keep the LLM backend separate from my prompt code for many good reasons. But if its a requirement to package application along with TGI, I'd run the TGI server as part of my application startup, and refer to the server in my code through REST API: http://localhost:8080/generate or libraries like [langchain](https://python.langchain.com/docs/integrations/llms/huggingface_textgen_inference).
