### ISSUE TITLE
Does TGI inference save data remotely without telling the user

### ISSUE THREAD

**Issue by manojsahoo250** [huggingface/text-generation-inference#1290]
We are planning to use TGI inference for our llama2 models .
All the required model and data are hosted locally and no data data can be transmitted anywhere else.
If anyone can help to understand if TGI only keeps the data in local environment or can collect some data for remote reportries will be of great help.

**Comment by OlivierDehaene** [comment]
We do not do any type or sort of telemetry. TGI can run in an air gapped environment as long as you download the model ahead of time.

**Comment by manojsahoo250** [comment]
Thanks a lot  for the response.
