### ISSUE TITLE
Entry Not Found for url: https://huggingface.co/org/model/resolve/main/adapter_config.json.

### ISSUE THREAD

**Issue by voatsap** [huggingface/text-generation-inference#1292]
### System Info

text-generation-launcher v1.1.1:
    image:
      repo: ghcr.io/huggingface/text-generation-inference
model_id: "openchat/openchat_3.5"  
text_generation_launcher: Args { model_id: "openchat/openchat_3.5", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 3096, max_total_tokens: 4048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "model-openchat-3-5-7cb48fb5fc-tqzn7", port: 8080, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/usr/src/openchat_3.5"), weights_cache_override: Some("/usr/src/openchat_3.5"), disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
AWS EKS 1.28

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

We have developed a Helm chart to deploy HF models and chat-ui in one shot: 
https://github.com/shalb/charts/tree/main/huggingface-model
It works pretty well for zephyr and some other models but when we try to use "openchat/openchat_3.5" and some other we got an exception:

2023-11-25T14:17:51.426721Z  INFO text_generation_launcher: Peft model detected.

2023-11-25T14:17:51.426755Z  INFO text_generation_launcher: Loading the model it might take a while without feedback

2023-11-25T14:17:52.160929Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):

  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()

  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/openchat/openchat_3.5/resolve/main/adapter_config.json

Error: DownloadError
    raise EntryNotFoundError(message, response) from e

huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6562020f-72fa4961455cda3259c7489e;a20e5ad2-c15d-421c-a728-c60554307b62)

Entry Not Found for url: https://huggingface.co/openchat/openchat_3.5/resolve/main/adapter_config.json.

I have a suspicions that even if we are passing model_Id and weights_cache_override:
huggingface_hub_cache: Some("/usr/src/openchat_3.5"), weights_cache_override: Some("/usr/src/openchat_3.5")
It still treats it like remote model and try to download this adapter_config.json from hugginface_hub:

https://github.com/huggingface/text-generation-inference/blob/b2b5df0e946cfcbb7c679d94c0642bc7a6ad8f5e/server/text_generation_server/cli.py#L122-L126

With 0.9.4 version it uses the files directly from storage, that I can see directly from logs, but this version can't work with mistral.

### Expected behavior

Logging should show that local model files are used explicitly and supported models could be launched with local weights.

**Comment by OlivierDehaene** [comment]
If don't use weights-cache-override and specify `MODEL_ID=/usr/src/openchat_3.5` directly, does it work?

**Comment by voatsap** [comment]
@OlivierDehaene thanks for noticing regarding deprecation of weights cache override.

Regarding your suggestion:

      containers:
      - args:
        - --model-id
        - /usr/src/openchat_3.5
        - --huggingface-hub-cache
        - /usr/src/openchat_3.5
        
 It treat it as peft model:
 
 ```
 2023-12-01T14:20:01.561702Z  INFO text_generation_launcher: Args { model_id: "/usr/src/openchat_3.5", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of
: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 3096, max_total_tokens: 4048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "model-openchat-3-5-74f457d846-xnw72", port: 8080, shard_uds_path: "/tmp/t
ext-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/usr/src/openchat_3.5"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, co
rs_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-12-01T14:20:01.561820Z  INFO download: text_generation_launcher: Starting download process.
2023-12-01T14:20:04.227298Z  INFO text_generation_launcher: Peft model detected.

2023-12-01T14:20:04.227336Z  INFO text_generation_launcher: Loading the model it might take a while without feedback

Error: DownloadError
2023-12-01T14:20:04.664771Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):

  File "/opt/conda/lib/python3.10/site-packages/peft/utils/config.py", line 117, in from_pretrained
    config_file = hf_hub_download(

  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)

  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/usr/src/openchat_3.5'. Use `repo_type` argument if needed.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/peft.py", line 16, in download_and_unload_peft
    model = AutoPeftModelForCausalLM.from_pretrained(

  File "/opt/conda/lib/python3.10/site-packages/peft/auto.py", line 69, in from_pretrained
    peft_config = PeftConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)

  File "/opt/conda/lib/python3.10/site-packages/peft/utils/config.py", line 121, in from_pretrained
    raise ValueError(f"Can't find '{CONFIG_NAME}' at '{pretrained_model_name_or_path}'")

ValueError: Can't find 'adapter_config.json' at '/usr/src/openchat_3.5'
```

**Comment by brian-dellabetta** [comment]
I am hitting this same issue. Providing `--model-id /data/mymodel`, where I've saved the pretrained model to that folder, results in the same logs indicating it's trying to download from an external source
```
2023-12-01T14:20:04.227298Z  INFO text_generation_launcher: Peft model detected.

2023-12-01T14:20:04.227336Z  INFO text_generation_launcher: Loading the model it might take a while without feedback
```
and a similar error related to `adapter_config.json`
```
ValueError: Can't find 'adapter_config.json' at '/data/mymodel'
```

This was working before for me, I would see in the logs that the model existed locally and it wouldn't try to download. I upgraded some deps and now it seems to have broken. Will keep investigating.

I agree with @voatsap, the ideal behavior would be:

> Logging should show that local model files are used explicitly and supported models could be launched with local weights.

**Comment by lyc728** [comment]
> I found that if I save a model with the latest version of transformers (4.35.2) it works. Saving the model with v4.33.3 (the current version on the latest text-generation-inference image) results in the errors posted above, so upgrading the version of transformers on the image ought to resolve your problem, @voatsap 🤞

hello I Upgrades the latest version of transformers (4.35.2) but I can not solve the problem

**Comment by lyc728** [comment]
> and a similar error related to `adapter_config.json`

hello Have you solved the problem？
