### ISSUE TITLE
docker run takes forever

### ISSUE THREAD

**Issue by poojitharamachandra** [huggingface/text-generation-inference#1293]
### System Info

python 3.11

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.1 --model-id $model

this runs forever saying downloading pytorch weights

### Expected behavior

pytorch weights should download and proceed

**Comment by fxmarty** [comment]
could make sense to update `huggingface_hub`, `hf_transfer` and use that to download weights & show progress bar.
