### ISSUE TITLE
Add ignore_eos_token to HTTP interface

### ISSUE THREAD

**Issue by NaCloudAI** [huggingface/text-generation-inference#1304]
### Feature request

We need ignore_eos_token  or min_length(better) for our use case

### Motivation

Our finetuned model is based on GPT dataset, many of which are truncated due to max_new_token. the model learned to randomly output eos.

In some case we are sure that the response should be at least 1500 token or 50 tokens after the final json field is generated, a min_length will come handy in this case.

### Your contribution

reviewed issue and found related PR is blocked, maybe merge them?

**Comment by achandrasekar** [comment]
Is there a plan to support this? I do see this field https://github.com/huggingface/text-generation-inference/blob/ac5a1c6f5142557333665c512cf4c1c8ca28d4d5/proto/generate.proto#L92. But it doesn't seem to apply if I send in a request like this:

```
curl -X POST http://$IP:8000/generate   -H "Content-Type: application/json"   -d @- <<EOF
{
    "inputs": "${USER_PROMPT}",
    "parameters": {
        "temperature": 0.90,
        "top_p": 0.95,
        "max_new_tokens": 1000
    },
    "stopping_parameters": {
        "max_new_tokens": 1000,
        "ignore_eos_token": true
    }
}
EOF
```
