### ISSUE TITLE
Tensor Parallelism on TGI

### ISSUE THREAD

**Issue by Rogerwyf** [huggingface/text-generation-inference#1315]
### System Info

Hi all, I have been running benchmark and testing myself to get a sense how an ideal setup for deploying some models is, and in the past a few months I've noticed an issue with Tensor Parallelism on TGI on A100-80G. With the v1.2 image I was able to run some benchmark on H100 observed this issue again, so I decided to raise this concern. (Some discussion & results I had previously can be found here https://github.com/huggingface/text-generation-inference/issues/1129)

I'm running the benchmarks on K8s with the v1.2 image on `codellama/CodeLlama-34b-Instruct-hf`. Each deployment shares the same spec except for the number of GPUs and thus the value for `--num-shard`. All of the requests are sent **non-concurrently** to eliminate any client-server factor, and the metric of interest here is simply **latency per token (in ms) for each request** (Each request generates ~100 tokens).

| GPU      | #GPU | Average | P50   | P99   |
| -------- | ---- | ------- | ----- | ----- |
| A100-80G | 1    | 46.79   | 46.07 | 55.25 |
| A100-80G | 2    | 29.39   | 28.71 | 34.95 |
| A100-80G | 4    | 32.06   | 30.83 | 50.18 |
| H100     | 1    | 27.98   | 27.56 | 30.68 |
| H100     | 2    | 28.02   | 27.82 | 30.81 |
| H100     | 4    | 31.77   | 30.50 | 47.52 |

I do notice there is an warning when deploying the model with v1.2 image on multiple GPUs
`WARN text_generation_launcher: Disabling exllama v2 and using v1 instead because there are issues when sharding`

Theoretically speaking, inference over more GPUs should be faster because of TP. I assume this performance degradation is in fact coming from exllama since that's the actual kernel used, but I am wondering if the HF/TGI team is aware of this. 

My guess is there could be probably something wrong with the TP implementation in exllama. I haven't tested with just exllama itself but will do in the near term, and will probably raise an issue there if I observe the same behaviour.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Deploy `codellama/CodeLlama-34b-Instruct-hf` with TGI v1.2.0 over multiple GPUs with default settings, send non-concurrent requests and measure the latency per token

### Expected behavior

I expect a deployment over 4 GPUs to have a lower latency per token than over 2 GPUs because of TP.

**Comment by OlivierDehaene** [comment]
> Theoretically speaking, inference over more GPUs should be faster because of TP.

It's complicated.

If you are compute bound, TP generally helps. However that is very rare for the decode steps which dominate your benchmark here. For prefill its more frequent. If you force the model to only generate one token in your tests, you sill see a very different behaviour. We recommend using the benchmarking tool to better investigate the thow phases (prefill and decode).

If you are not compute bound, it only adds a communication overhead. 

We cannot really make recommendations here as the optimal number of shards for the best latency is entirely dependant on the hardware and the model size + type.

**Comment by Rogerwyf** [comment]
@OlivierDehaene Thank you for the response and the explanation! I went ahead and reran some tests to including time-to-first token as you suggest and below are the results:

| GPU      | #GPU | Average | P50   | P99   |
| -------- | ---- | ------- | ----- | ----- |
| A100-80G | 1    | 136.2   | 125.0 | 387.4 |
| A100-80G | 2    | 94.91 | 65.21 | 267.4 |
| A100-80G | 4    | 336.6  | 338 | 494.9 |
| A100-80G | 8    | 530.7  | 525.4 | 674.7 |
| H100     | 1    | 67.06   | 54.89 | 162.3 |
| H100     | 2    |58.11  | 53.68 | 100.2 |
| H100     | 4    | 89.09  | 83.34 | 162.6 |
| H100     |  8    | 55.2  | 54.04 | 67.33 |

It just seems to me that beyond 2 GPUs, communication overhead overshadows the benefit from TP. I haven't got into the GPU profiling but the utilization rate when over 2 GPUs also show that some GPUs have low util rate due to having to waiting for others. This was mentioned in https://github.com/huggingface/text-generation-inference/issues/863 by @jameswu2014, and @Narsil has kindly responded there as well.

Not asking for a fix/recommendation but I was just trying to confirm if this issue only happens to me (bad gpus, bad node, who knows), but the development of Candle is surely exciting to hopefully solve this issue fundamentally!

**Comment by Rogerwyf** [comment]
Thought to share another set of results of the same benchmark on TGI versus vllm v0.2.6 docker - it's pretty clear to me that there's something wrong with TP when going above 4 GPU.

<img width="1442" alt="Screenshot 2023-12-24 at 9 12 21 PM" src="https://github.com/huggingface/text-generation-inference/assets/18731847/abe920e0-576d-468f-9b63-4634fa52ece5">

**Comment by Narsil** [comment]
Could you share your benchmarking code ? Doesn't look like anything it should...

I managed to reproduce on A100-80 something like your numbers (not quite tho, I get 45-30-40-35 using `text-generation-benchmark`).

I'm digging a bit more into it, since I was able to reproduce somehow. Definitely doesn't feel right if it holds. (We do use nccl for communication, which is not necessarily the best communicator across GPU, that's a potential target, but again).

I couldn't reproduce on lower models, or lower machines though

**Comment by Narsil** [comment]
I think we found the reason. 3 weeks ago vllm added cuda graphs to their execution engine.

Having a cuda graph makes CPU usage much smaller, leading to better consistency of timings across GPUs, which leads to speedups because NCCL syncs don't have to wait so long for each other.

We'll add cuda graphs here too @OlivierDehaene is on it. Also, using a compiled language would most likely have prevented the need for that (should cuda graphs be unusable for whatever reason)

**Comment by llan-ml** [comment]
Hi @Narsil @OlivierDehaene , any updates on this? I also had a problem that the deployment with 8 GPUs is not faster than with that with 4 GPUs. I'm using V100.
