### ISSUE TITLE
How can I get the log from the thirdparty library?

### ISSUE THREAD

**Issue by jameswu2014** [huggingface/text-generation-inference#1321]
### System Info

I know we can use logger.info in tgi to get the log.However, I have a thirdparty library, and I want to get the log from it.For example, I want to get some NCCL LOG. I add env variables NCCL_DEBUG=INFO to text-generation-launcher, But it is useless.My question is how can I get the log from the thirdparty library?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

As mentioned above.

### Expected behavior

Get the log info from thirdparty library

**Comment by ganyi1996ppo** [comment]
> LOG_LEVEL=info,text_generation_router=debug,text_generation_launcher=debug

Are those environment variables? I set those variables but seems its not work
