### ISSUE TITLE
tgi can use transformers==4.35.0? because if i use prompt_tokens>40k,transfromers has some bug if version is lower.

### ISSUE THREAD

**Issue by sundayKK** [huggingface/text-generation-inference#1324]
### System Info

tgi latest version

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

tgi can use transformers==4.35.0? because if i use prompt_tokens>40k,transfromers has some bug if version is lower.

### Expected behavior

i just see in requestments.txt, transfomers is require 4.33.3 .

**Comment by OlivierDehaene** [comment]
#1351 updates transformers to 4.36
