### ISSUE TITLE
unable to run docker image of tgi on port 8080

### ISSUE THREAD

**Issue by poojitharamachandra** [huggingface/text-generation-inference#1349]
### System Info

unable to run docker image of tgi on port 8080

2023-12-15T07:11:05.966985Z  INFO text_generation_router: router/src/main.rs:213: Warming up model
2023-12-15T07:11:11.868595Z  WARN text_generation_router: router/src/main.rs:224: Model does not support automatic max batch total tokens
2023-12-15T07:11:11.868626Z  INFO text_generation_router: router/src/main.rs:246: Setting max batch total tokens to 16000
2023-12-15T07:11:11.868630Z  INFO text_generation_router: router/src/main.rs:247: Connected
2023-12-15T07:11:11.868633Z  WARN text_generation_router: router/src/main.rs:252: Invalid hostname, defaulting to 0.0.0.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

model=/models/t5-small
volume=$PWD/data
sudo docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data -v /models/:/models/ -e HF_HUB_ENABLE_HF_TRANSFER=0 ghcr.io/huggingface/text-generation-inference:1.1.1 --model-id $model

### Expected behavior

to run on 127.0.0.1:8080

**Comment by jegork** [comment]
If I am not mistaken, your `-p` flag is incorrect. TGI is exposed on port 8080 by default. `-p 8080:80` means forward port 80 in container to port 8080 on host (outside of container) 
To fix, you would need to run `-p 80:8080` and you app will be availabe on port 80 from outside the container

**Comment by poojitharamachandra** [comment]
with -p 80:8080 also, the same error.

how to run the tgi on 127.0.0..<port>?

**Comment by jegork** [comment]
@poojitharamachandra but what is the error you are receiving?

**Comment by poojitharamachandra** [comment]
text_generation_router: router/src/main.rs:252: Invalid hostname, defaulting to 0.0.0.0

**Comment by jegork** [comment]
that is not an error, it says it is a warning `WARN`. that is expected behaviour and you don't have to do anything with it (it just defaults to using 0.0.0.0)

**Comment by poojitharamachandra** [comment]
where do i access the tgi then?

**Comment by jegork** [comment]
After running the command in your initial post: `sudo docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data -v /models/:/models/ -e HF_HUB_ENABLE_HF_TRANSFER=0 ghcr.io/huggingface/text-generation-inference:1.1.1 --model-id $model` 
TGI should be then available at port 8080

**Comment by jegork** [comment]
Just try 
```
curl 127.0.0.1:8080/generate \
    -X POST \
    -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}' \
    -H 'Content-Type: application/json'
```

**Comment by poojitharamachandra** [comment]
thanks!

**Comment by poojitharamachandra** [comment]
.
