### ISSUE TITLE
medusa support

### ISSUE THREAD

**Issue by jiangix-paper** [huggingface/text-generation-inference#1360]
### System Info

text-generation-inference 1.3.0
python 3.10

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

I want to know if the tgi 1.3.0 support the medusa decoding? Thanks a lot.

### Expected behavior

medusa support

**Comment by OlivierDehaene** [comment]
Yes it does.
