### ISSUE TITLE
the doc for the docker mount path is not clear

### ISSUE THREAD

**Issue by walkacross** [huggingface/text-generation-inference#1367]
### System Info

context: when use transformer library, the model params are in cache, for example, ~/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-hf/snapshot/<commit_id>/<model_params_tensor.bin>. 

if the model params has been in local, how to mount and how to set the model_id in TGI? the doc is not clear.

1. the mount  relative path is regarding the snapshot or the ultimate model parameter tensor?
2. in container, the model will load the parameters under the folder /data?  has no doc for the /data 
~~~
volume= <relative path for what?>  # for the snapshot or the ultimate model parameter tensor?

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.3 --model-id $<what_to_set????>
~~~

the doc for relationship between the mount volume and model_id is not clear

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

~~~
model = org_name/model_name #??
volume= <what_to_set??> #regarding the snapshot or the ultimate tensor.pth??
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.3 --model-id $<what_to_set????>
~~~

### Expected behavior

more clear doc for the docker mount path

**Comment by simplesisu** [comment]
Totally agree on this, a docker-compose.yml would be beneficial also! Great repo!

**Comment by geronimi73** [comment]
I am totally new to this docker stuff, also immediately failed trying to run a local model. 

this is what worked for me. assume your model dir is `./models` and there's `Mistral-7B-Instruct-v0.2` in there:
```
docker run --gpus all --shm-size 1g -p 8080:80 \
        -v ./models:/models \
        ghcr.io/huggingface/text-generation-inference:latest \
        --model-id /models/Mistral-7B-Instruct-v0.2
```
