### ISSUE TITLE
Why tgi with exllamav2 doesn't support model sharding?

### ISSUE THREAD

**Issue by westboy123** [huggingface/text-generation-inference#1369]
### System Info

any environment

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

I find utils/layers.py has following code lines:

if V2 and int(os.getenv("WORLD_SIZE", "1")) > 1:
    logger.warning(
        "Disabling exllama v2 and using v1 instead because there are issues when sharding"
    )
    V2 = False

It seems that tgi with exllamav2 can't support model sharding.

### Expected behavior

tgi with exllamav2 can support model sharding

**Comment by bob-just-bob** [comment]
Related issue about exl2 quant:
