### ISSUE TITLE
Can Endpoints be Protected with Authentication?

### ISSUE THREAD

**Issue by Jesus-session** [huggingface/text-generation-inference#1372]
### Feature request

I am interested in using the text-generation-inference repository for deploying and serving LLMs, however, I would like to know if exist a built-in feature to protect endpoints using some kind of authentication.

Thank you for your attention to this matter. I look forward to your response and potential implementation of this feature.

### Motivation

By implementing authentication, we can ensure that only authorized users can access the protected resources. This can be achieved using JWT tokens or other authentication mechanisms.

### Your contribution

.

**Comment by OlivierDehaene** [comment]
No. This is out of scope of this project. Auth should be handled by a component on top of TGI.
