### ISSUE TITLE
Unexpected OOM after warmup for request that has token less than max-batch-prefill-token

### ISSUE THREAD

**Issue by zch-cc** [huggingface/text-generation-inference#1374]
### System Info

text-generation-inference: 1.3.3
machine GPU: A100 40GB
cuda version: 11.8

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Command for running the model:
--model-id codellama/CodeLlama-34b-Instruct-hf --num-shard 1 --max-concurrent-requests 1 --max-input-length 6800 --max-total-tokens 6900 --max-batch-prefill-tokens 7000  --max-stop-sequences 20 --trust-remote-code --quantize eetq
The server is ready to serve but OOM for request with token 4000 and max_token=40

Request Error Trace:
`Traceback (most recent call last):
  File "a.py", line 21, in <module>
    response = client.generate(prompt=prompt, max_new_tokens=40)
  File "/home/chonghao/.local/lib/python3.8/site-packages/text_generation/client.py", line 153, in generate
    raise parse_error(resp.status_code, payload)
text_generation.errors.GenerationError: Request failed during generation: Server error: CUDA out of memory. Tried to allocate 42.00 MiB. GPU 0 has a total capacty of 39.39 GiB of which 31.94 MiB is free. Process 7529 has 39.23 GiB memory in use. Of the allocated memory 37.21 GiB is allo`

Server Error Trace
chat_inference-text_generation_inference-1  | 2023-12-22T00:21:24.202169Z  INFO compat_generate{default_return_full_text=true}:generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(40), return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None, top_n_tokens: None } total_time="2.458150804s" validation_time="13.678487ms" queue_time="184.26µs" inference_time="2.444288229s" time_per_token="61.107205ms" seed="None"}: text_generation_router::server: router/src/server.rs:289: Success
chat_inference-text_generation_inference-1  | 2023-12-22T00:21:35.318928Z ERROR batch{batch_size=1}:prefill:prefill{id=1 size=1}:prefill{id=1 size=1}: text_generation_client: router/client/src/lib.rs:33: Server error: CUDA out of memory. Tried to allocate 222.00 MiB. GPU 0 has a total capacty of 39.39 GiB of which 217.94 MiB is free. Process 862944 has 39.17 GiB memory in use. Of the allocated memory 37.10 GiB is allocated by PyTorch, and 1.57 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
chat_inference-text_generation_inference-1  | 2023-12-22T00:21:35.318933Z ERROR text_generation_launcher: Method Prefill encountered an error.
chat_inference-text_generation_inference-1  | Traceback (most recent call last):
chat_inference-text_generation_inference-1  |   File "/opt/conda/bin/text-generation-server", line 8, in <module>
chat_inference-text_generation_inference-1  |     sys.exit(app())
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
chat_inference-text_generation_inference-1  |     return get_command(self)(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
chat_inference-text_generation_inference-1  |     return self.main(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
chat_inference-text_generation_inference-1  |     return _main(
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
chat_inference-text_generation_inference-1  |     rv = self.invoke(ctx)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
chat_inference-text_generation_inference-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
chat_inference-text_generation_inference-1  |     return ctx.invoke(self.callback, **ctx.params)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
chat_inference-text_generation_inference-1  |     return __callback(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
chat_inference-text_generation_inference-1  |     return callback(**use_params)  # type: ignore
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
chat_inference-text_generation_inference-1  |     server.serve(
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 228, in serve
chat_inference-text_generation_inference-1  |     asyncio.run(
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
chat_inference-text_generation_inference-1  |     return loop.run_until_complete(main)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
chat_inference-text_generation_inference-1  |     self.run_forever()
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
chat_inference-text_generation_inference-1  |     self._run_once()
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
chat_inference-text_generation_inference-1  |     handle._run()
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
chat_inference-text_generation_inference-1  |     self._context.run(self._callback, *self._args)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
chat_inference-text_generation_inference-1  |     return await self.intercept(
chat_inference-text_generation_inference-1  | > File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
chat_inference-text_generation_inference-1  |     return await response
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
chat_inference-text_generation_inference-1  |     raise error
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
chat_inference-text_generation_inference-1  |     return await behavior(request_or_iterator, context)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 96, in Prefill
chat_inference-text_generation_inference-1  |     generations, next_batch, timings = self.model.generate_token(batch)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/contextlib.py", line 79, in inner
chat_inference-text_generation_inference-1  |     return func(*args, **kwds)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 825, in generate_token
chat_inference-text_generation_inference-1  |     raise e
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 822, in generate_token
chat_inference-text_generation_inference-1  |     out = self.forward(batch)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/flash_causal_lm.py", line 788, in forward
chat_inference-text_generation_inference-1  |     return self.model.forward(
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 431, in forward
chat_inference-text_generation_inference-1  |     hidden_states = self.model(
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
chat_inference-text_generation_inference-1  |     return self._call_impl(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
chat_inference-text_generation_inference-1  |     return forward_call(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 390, in forward
chat_inference-text_generation_inference-1  |     hidden_states, residual = layer(
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
chat_inference-text_generation_inference-1  |     return self._call_impl(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
chat_inference-text_generation_inference-1  |     return forward_call(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 334, in forward
chat_inference-text_generation_inference-1  |     mlp_output = self.mlp(normed_attn_res_output)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
chat_inference-text_generation_inference-1  |     return self._call_impl(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
chat_inference-text_generation_inference-1  |     return forward_call(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py", line 280, in forward
chat_inference-text_generation_inference-1  |     return self.down_proj(self.act(gate_up_states[:, 0]) * gate_up_states[:, 1])
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
chat_inference-text_generation_inference-1  |     return self._call_impl(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
chat_inference-text_generation_inference-1  |     return forward_call(*args, **kwargs)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/transformers/activations.py", line 150, in forward
chat_inference-text_generation_inference-1  |     return nn.functional.silu(input)
chat_inference-text_generation_inference-1  |   File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 2072, in silu
chat_inference-text_generation_inference-1  |     return torch._C._nn.silu(input)
chat_inference-text_generation_inference-1  | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 222.00 MiB. GPU 0 has a total capacty of 39.39 GiB of which 217.94 MiB is free. Process 862944 has 39.17 GiB memory in use. Of the allocated memory 37.10 GiB is allocated by PyTorch, and 1.57 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
chat_inference-text_generation_inference-1  | 
chat_inference-text_generation_inference-1  | 2023-12-22T00:21:35.320088Z ERROR compat_generate{default_return_full_text=true}:generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(40), return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None, top_n_tokens: None }}:generate:generate_stream:infer:send_error: text_generation_router::infer: router/src/infer.rs:608: Request failed during generation: Server error: CUDA out of memory. Tried to allocate 222.00 MiB. GPU 0 has a total capacty of 39.39 GiB of which 217.94 MiB is free. Process 862944 has 39.17 GiB memory in use. Of the allocated memory 37.10 GiB is allocated by PyTorch, and 1.57 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

script for getting request:

```
import random

from text_generation import Client
from transformers import AutoTokenizer

random.seed(5)


def generate_test_prompt(prompt_length: int, tokenizer: AutoTokenizer):
    max_vocab_index = tokenizer.vocab_size - 1
    prompt_tokens = [random.randint(0, max_vocab_index) for _ in range(prompt_length)]
    return tokenizer.decode(prompt_tokens)


client = Client("http://127.0.0.1:8080")
tokenizer = AutoTokenizer.from_pretrained("codellama/CodeLlama-34b-Instruct-hf")
prompt = generate_test_prompt(
    prompt_length=4000, tokenizer=tokenizer
)  # actual tokens should be greater than 4000 but should definitely lower than 6000.
print(len(tokenizer.encode(prompt)))
response = client.generate(prompt=prompt, max_new_tokens=40)
print(response)

```

### Expected behavior

Since the request token is smaller than max-batch-prefill-tokens and max-input-length. We should be able to generate request. I also tried previous tgi version for 1.1.1 and 1.1.0 but it also does not work.

**Comment by zch-cc** [comment]
script for getting request:
```
import random

from text_generation import Client
from transformers import AutoTokenizer

random.seed(5)


def generate_test_prompt(prompt_length: int, tokenizer: AutoTokenizer):
    max_vocab_index = tokenizer.vocab_size - 1
    prompt_tokens = [random.randint(0, max_vocab_index) for _ in range(prompt_length)]
    return tokenizer.decode(prompt_tokens)


client = Client("http://127.0.0.1:8080")
tokenizer = AutoTokenizer.from_pretrained("codellama/CodeLlama-34b-Instruct-hf")
prompt = generate_test_prompt(
    prompt_length=2000, tokenizer=tokenizer
)  # actual tokens should be greater than 2000 but should definitely lower than 6000.
print(len(tokenizer.encode(prompt)))
response = client.generate(prompt=prompt, max_new_tokens=40)
print(response)

```

**Comment by zch-cc** [comment]
Request Error Trace:
`Traceback (most recent call last):
  File "a.py", line 21, in <module>
    response = client.generate(prompt=prompt, max_new_tokens=40)
  File "/home/chonghao/.local/lib/python3.8/site-packages/text_generation/client.py", line 153, in generate
    raise parse_error(resp.status_code, payload)
text_generation.errors.GenerationError: Request failed during generation: Server error: CUDA out of memory. Tried to allocate 42.00 MiB. GPU 0 has a total capacty of 39.39 GiB of which 31.94 MiB is free. Process 7529 has 39.23 GiB memory in use. Of the allocated memory 37.21 GiB is allo`

**Comment by zch-cc** [comment]
I also observe some memory leaking after oom. For example, the program can give response on 3k tokens. but when I first run 5k tokens request(it will fail but 5k is still less than max-batch-prefill-token). When I rerun the 3k token request, it will oom.

**Comment by zch-cc** [comment]
after some time debugging, I found it should be eetq quantization problem. I disable it and everything work as fine. But still have no idea how we should fix eetq case.

**Comment by zch-cc** [comment]
I try the set up without the eetq quantization with command 
--model-id  codellama/CodeLlama-13b-Instruct-hf --num-shard 1 --max-concurrent-requests 2 --max-input-length 7700 --max-total-tokens 7900 --max-batch-prefill-tokens 10000 --max-stop-sequences 20 --trust-remote-code

This will  give oom on 7500 tokens.

After the oom error, it will not free the memory so even if the next request is 3k tokens, it will still oom, which makes me believe there is some bug during warm up.

**Comment by zch-cc** [comment]
solve by add env variable PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:64

**Comment by Narsil** [comment]
Thanks a lot for sharing your fix !
