### ISSUE TITLE
medusa test

### ISSUE THREAD

**Issue by jiangix-paper** [huggingface/text-generation-inference#1380]
### System Info

tgi 1.3.3

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

I want to try medusa decoding in tgi 1.3.3. Now I have two model folders: the first folder is as follows:
<img width="1204" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/62198809/31b72e46-221f-4949-96ad-5345f9f4dc44">
The second folder is as follows:
<img width="1204" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/62198809/e5fbe61d-d676-4152-adb7-2025045589b4">

Should I convert the ".pt" medusa model into safetensors?

### Expected behavior

medusa decoding

**Comment by Teddyang** [comment]
can you set --model-id=<your first folder> ?

**Comment by Teddyang** [comment]
would it be possible to set `--model=<your first folder>`?

**Comment by Teddyang** [comment]
would it be possible to set `--model-id=<your first folder>`?

**Comment by jiangix-paper** [comment]
Hi, I use --model-id = first folder, it has the errors:
<img width="715" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/62198809/244d5ecc-3df9-43f6-893a-000487b4f7e7">
