### ISSUE TITLE
Unable to use '--rope-scaling yarn' option.

### ISSUE THREAD

**Issue by calycekr** [huggingface/text-generation-inference#1382]
### Bug Report
PR: Adding yarn support https://github.com/huggingface/text-generation-inference/pull/1099

But, there is no yarn in possible values.

```
error: invalid value 'yarn' for '--rope-scaling <ROPE_SCALING>'
[possible values: linear, dynamic]
```

No yarn support in this file.
https://github.com/huggingface/text-generation-inference/blob/630800eed37b15c4b0c9eb8e6ab47212026720f7/launcher/src/main.rs#L99-L117

#1320 

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Use '--rope-scaling yarn' option.

### Expected behavior

Support yarn option.

**Comment by Narsil** [comment]
That's because yarn requires yarn enabled models, you can't make arbitrary models become yarn (that's what the other rope scaling methods are for).


Check out available models: https://huggingface.co/models?search=yarn

**Comment by Narsil** [comment]
(And simply use them, yarn will get detected and used automatically).
