### ISSUE TITLE
Caching in chat like scenarios

### ISSUE THREAD

**Issue by saiajaym** [huggingface/text-generation-inference#1404]
### Feature request

For applications like chatting, the common scenario is

**Turn 1:**
user request1 --> parallel forward with kv caching
llm response --> One token at a time and kv cache is updated with additional keys and values

**Turn2:**
 (Turn 1) + user request2 --> parallel forward with kv caching
llm response --> One token at a time and kv cache is updated with additional keys and values

In the above scenario,
 Do we keep the previous cache so that when turn 2 starts we only calculate the diff in parallel, i.e, user request 2 by using kv cache from Turn 1?
 
 If so how do we enable this?
 
 Else, can we please add this is a feature, like maintain a conversation id across turns and manage kv caching efficiently?
 
 Thanks

### Motivation

It's common in chat like applications and other scenarios where we re use previous context and add more tokens/context to for new generations.
It would be helpful if we have a mechanism to reuse previous kv cache in these scenarios to improve speed and compute efficiency

### Your contribution

I can help with submitting with coding if anyone wants to collaborate with me on this

**Comment by OlivierDehaene** [comment]
> Do we keep the previous cache so that when turn 2 starts we only calculate the diff in parallel, i.e, user request 2 by using kv cache from Turn 1?

No we don't.

It's interesting for sure especially for long convos but it's a big change and we are not too sure how we want to tackle it yet.

**Comment by erfanium** [comment]
@OlivierDehaene It's also very helpful in case of self-hosted AI coding tools, where the generation latency is crucial to be low.
