### ISSUE TITLE
Failed using local model

### ISSUE THREAD

**Issue by ahqzy** [huggingface/text-generation-inference#1405]
### System Info

Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 630800eed37b15c4b0c9eb8e6ab47212026720f7
Docker label: N/A
nvidia-smi:
Fri Jan  5 08:23:13 2024       
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 12.1     |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                               |                      |               MIG M. |
   |===============================+======================+======================|
   |   0  NVIDIA A100 80G...  On   | 00000000:81:00.0 Off |                  Off |
   | N/A   31C    P0    63W / 300W |      0MiB / 81920MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
                                                                                  
   +-----------------------------------------------------------------------------+
   | Processes:                                                                  |
   |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
   |        ID   ID                                                   Usage      |
   |=============================================================================|
   |  No running processes found                                                 |
   +-----------------------------------------------------------------------------+

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

When I use

#text-generation-launcher --model-id  /data/Llama-2-7b-chat-hf

to specify a local model,  it still download remote file(can see this process:  /root/anaconda3/envs/tgi/bin/python /root/anaconda3/envs/tgi/bin/text-generation-server download-weights /data/Llama-2-7b-chat-hf --extension .safetensors --logger-level INFO --json-output), 

and give a error info:
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/Llama-2-7b-chat-hf'. Use `repo_type` argument if needed.

### Expected behavior

So, how can I use a local model?

**Comment by seplee** [comment]
+1

**Comment by OlivierDehaene** [comment]
Should be fixed on "main". Can you try the latest commit?

**Comment by ahqzy** [comment]
OK. Must specify to the .safetensor folder. like  :
#text-generation-launcher --model-id  /data/Llama-2-7b-chat-hf/snapshots/dc24cabd13eacd3ae3a5fe574bd645483a335a4a/

Cannot only to /data/Llama-2-7b-chat-hf

**Comment by BaiMoHan** [comment]
> OK. Must specify to the .safetensor folder. like : #text-generation-launcher --model-id /data/Llama-2-7b-chat-hf/snapshots/dc24cabd13eacd3ae3a5fe574bd645483a335a4a/
> 
> Cannot only to /data/Llama-2-7b-chat-hf

I am confused.
My command is 
```shell
sudo docker run --gpus all --shm-size 1g -p 9090:80 -v /home/ubuntu/tgi:/data ghcr.io/huggingface/text-generation-inference:latest --model-id /home/ubuntu/llama2-v1-2357 --max-best-of 10 --hostname 0.0.0.0
```

**Comment by BaiMoHan** [comment]
> > OK. Must specify to the .safetensor folder. like : #text-generation-launcher --model-id /data/Llama-2-7b-chat-hf/snapshots/dc24cabd13eacd3ae3a5fe574bd645483a335a4a/
> > Cannot only to /data/Llama-2-7b-chat-hf
> 
> I am confused. My command is
> 
> ```shell
> sudo docker run --gpus all --shm-size 1g -p 9090:80 -v /home/ubuntu/tgi:/data ghcr.io/huggingface/text-generation-inference:latest --model-id /home/ubuntu/llama2-v1-2357 --max-best-of 10 --hostname 0.0.0.0
> ```

I always got the error
```shell
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/ubuntu/llama2-v1-2357'. Use `repo_type` argument if needed.
```
