### ISSUE TITLE
Can't using .bin for  model_id 

### ISSUE THREAD

**Issue by ahqzy** [huggingface/text-generation-inference#1406]
### System Info

(text-generation-inference) root@fe272a04cc00:~/text-generation-inference# text-generation-launcher --env
2024-01-05T13:25:35.774075Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: N/A
Docker label: N/A
nvidia-smi:
Fri Jan  5 13:25:35 2024       
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 12.1     |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                               |                      |               MIG M. |
   |===============================+======================+======================|
   |   0  NVIDIA A100 80G...  On   | 00000000:81:00.0 Off |                  Off |
   | N/A   32C    P0    64W / 300W |      0MiB / 81920MiB |      0%      Default |
   |                               |                      |             Disabled |
   +-------------------------------+----------------------+----------------------+
                                                                                  
   +-----------------------------------------------------------------------------+
   | Processes:                                                                  |
   |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
   |        ID   ID                                                   Usage      |
   |=============================================================================|
   |  No running processes found                                                 |
   +-----------------------------------------------------------------------------+

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

when I using
#text-generation-launcher --model-id  /data/Llama-2-7b-chat-hf/ 
to lauch the server,  it failed.  ls /data/Llama-2-7b-chat-hf/  result as in below:
# ls /data/Llama-2-7b-chat-hf/
config.json  generation_config.json  pytorch_model-00001-of-00002.bin  pytorch_model-00002-of-00002.bin  pytorch_model.bin.index.json  special_tokens_map.json  tokenizer.json  tokenizer.model  tokenizer_config.json

errer info is:

huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/Llama-2-7b-chat-hf/'. Use `repo_type` argument if needed.

It's seem to that tgi can't recongnize the .bin file.

### Expected behavior

So how can I using  local .bin file for text-generation-launcher?

**Comment by OlivierDehaene** [comment]
This is fixed by #1419
