### ISSUE TITLE
How to use local Medusa head?

### ISSUE THREAD

**Issue by eurus-ch** [huggingface/text-generation-inference#1415]
It is said that Medusa can significantly accelerate inference speed. During my attempts to utilize it, I have observed that it does not support the use of local Medusa config and head. The code fragment I discovered that pertains to this functionality is as follows, which I have modified. However, I do not comprehend the meaning of 'medusa_sf'. The training process of Medusa does not generate new safetensors. What is this? 
```python
medusa_config = f"{model_id}/config_medusa.json"
# medusa_config = hf_hub_download(
#     use_medusa, revision=revision, filename="config.json"
# )
with open(medusa_config, "r") as f:
    config = json.load(f)
medusa_head = f"{model_id}/medusa_lm_head.pt"
# medusa_head = hf_hub_download(
#     use_medusa, revision=revision, filename="medusa_lm_head.pt"
# )
medusa_sf = medusa_head[: -len(".pt")] + ".safetensors"
weights = Weights(
    [medusa_sf], device, dtype, process_group=self.process_group
)
lm_head = model.lm_head
model.lm_head = MedusaModel(config, weights, lm_head)
```

How should I employ TGI to access the local Medusa? A huge thank for your work!

**Comment by OlivierDehaene** [comment]
Linked to #1418  and #1420
