### ISSUE TITLE
Why does TGI-benchmark uses "batchsize / latency" as prefill throughput?

### ISSUE THREAD

**Issue by eurus-ch** [huggingface/text-generation-inference#1417]
### System Info

Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: f3aea78fb642967838e7b5b1940a25fe67f4f7a9

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

text-generation-benchmark

### Expected behavior

In `benchmark/src/generation.rs`, it uses `let throughput = batch_size as f64 / latency.as_secs_f64()`. 

And I am curiouts about that, why not `sequence_length / latency` or `sequence_length * batch_size / latency`? Since the output is `token/s`. Is there something that I missed?

Location: https://github.com/huggingface/text-generation-inference/blob/630800eed37b15c4b0c9eb8e6ab47212026720f7/benchmark/src/generation.rs#L157C2-L157C2

```rust
let batch = Batch {
    id: 0,
    requests,
    size: batch_size,
    max_tokens: batch_size * (sequence_length + decode_length),
};

// Run prefill
let start_time = Instant::now();
let (_, decode_batch, _) = client.prefill(batch.clone()).await?;

// Get latency
let latency = start_time.elapsed();

// Compute throughput from latency and batch size
let throughput = batch_size as f64 / latency.as_secs_f64();

// Decode batch cannot be empty
let decode_batch = decode_batch.expect("decode_batch is None. This is a bug.");

let step = Prefill {
    latency,
    throughput,
};

Ok((step, decode_batch))
```

**Comment by OlivierDehaene** [comment]
The `client.prefill` or `client.decode` methods only decode token one by one for each request that is part of the batch. Later in the code we decode the full sequence.
