### ISSUE TITLE
[Medusa] Router load Fast Tokenizer from base model

### ISSUE THREAD

**Issue by PYNing** [huggingface/text-generation-inference#1422]
### System Info

TGI Version：1.3.4（the latest）

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

model=FasterDecoding/medusa-vicuna-7b-v1.3

volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.3 --model-id $model

A warning from Router will be printed on service  launching：
**Could not find a fast tokenizer implementation for XX(Model ID of the Medusa Head)
Rust input length validation and truncation is disabled**

even if I have a fast version tokenizer on the **base model** folder (the folder "base_model_name_or_path" points to).

### Expected behavior

For medusa models, tokenizer should normally be stored in the base model folder. So Router should load tokenizer according to  "base_model_name_or_path" in config.json.

For example, for the test case in https://github.com/huggingface/text-generation-inference/blob/main/integration-tests/models/test_flash_medusa.py ，Router first parses the "base_model_name_or_path" field from the config.json of the **FasterDecoding/medusa-vicuna-7b-v1.3** sub model, and then loads tokenizer from its base model (**lmsys/vicuna-7b-v1.3**)

**Comment by OlivierDehaene** [comment]
#1424 fixes the issue. However in your case the base model does not have a fast tokenizer anyways.

**Comment by PYNing** [comment]
Thx.
