### ISSUE TITLE
ValueError: Error raised by inference API: Internal Server Error

### ISSUE THREAD

**Issue by BadrinathMJ** [huggingface/text-generation-inference#1431]
I have tried "mistralai/Mixtral-8x7B-Instruct-v0.1", For getting inference from PDFs for my query form it, instead of output or inference I am getting **ValueError: Error raised by inference API: Internal Server Error**,  I am using Free Inference API. This is happened from yesterday, Before this it was working fine. If anyone knows what is the problem, please let me know.

**Comment by Narsil** [comment]
Anyway we can reproduce the issue you're having ?

It's not entirely clear what you are doing here. Are you using hf.co/chat ?
