### ISSUE TITLE
Is it possible to allocate blocks on demand during the decoding phase?

### ISSUE THREAD

**Issue by liuyang-my** [huggingface/text-generation-inference#1435]
### Feature request

During the `prefill` stage, only the blocks required for tokens of length `input_length` are allocated. Additional blocks are dynamically added during the `decode` phase as needed.

### Motivation

We have observed that during the `prefill` stage, TGI preallocates blocks based on `input_length` and `max_new_tokens`, and then directly uses these preallocated blocks during the decoding phase. However, in our scenario, the actual number of generated tokens may be much smaller than `max_new_tokens`. This results in a higher number of preallocated blocks compared to the actual number of blocks used, leading to reduced participation of requests in batch grouping. When the concurrent number of requests exceeds the batch size, some requests have to wait in the queue.

Is it possible to allocate blocks on demand during the `decode` phase instead of preallocating them based on `max_new_tokens`? This approach would allow for more requests to participate in batch grouping, thereby improving throughput.

### Your contribution

For us, it may be difficult to provide this feature.

**Comment by Narsil** [comment]
This would have other consequences which makes it very impratical.

If you allow more users in the batch, and those requests *do* reach max_new_tokens... Then what do you do, you don't have enough room to fit those requests anymore, meaning you need to deallocate some requests, pose them somewhere, only to rerun them later, and repay the prefill cost etc.. Very wasteful.

What you can do on the other hand, is limiting the `max_new_tokens` allowed for your users. If you limit that way, you enforce that users are NOT running long requests unnecessarily and therefore you get the wins you expect without the downsides aforementionned.

Finding the flags to limit your users in such a way is really important to get the most of your servers, but doing like you suggested is most likely going to lead to worse consequences than the perceived benefit (whenever you hit the unhappy path). 

Does that make sense.
