### ISSUE TITLE
How can i get the log of model inputs?

### ISSUE THREAD

**Issue by Cucunnber** [huggingface/text-generation-inference#1440]
### Feature request

docker version tgi:1.1.0

When i do `docker logs xxx` , i can only get the INFO like
```
INFO generate{parameters=GenerateParameters { best_of: Some(1), temperature: Some(0.2), repetition_penalty: None, top_k: None, top_p: Some(0.95), typical_p: None, do_sample: true, max_new_tokens: 48, return_full_text: None, stop: ["<fim_pad>", "<|endoftext|>", "\n}", "<｜end▁of▁sentence｜>"], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None, top_n_tokens: None } total_time="667.179861ms" validation_time="11.640733ms" queue_time="129.535µs" inference_time="655.410281ms
```

How can I get more info in logs like input and outpu? If there's any setting already existing, please give me some clues, thank you.

### Motivation

Easier to debug new models.

### Your contribution

currently none

**Comment by rishu931997** [comment]
Hi, did you find out how to get logs for debug level?

**Comment by OlivierDehaene** [comment]
Set the `LOG_LEVEL` env var to `LOG_LEVEL="info,text_generation_router=debug"`
