### ISSUE TITLE
1.3.4 slow than 1.1.0?

### ISSUE THREAD

**Issue by NaCloudAI** [huggingface/text-generation-inference#1452]
### System Info

ghcr.io/huggingface/text-generation-inference:1.1.0 vs 1.3.4

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

test on runpod 2x 3090 using `text-generation-benchmark --tokenizer-name TheBloke/Llama-2-7B-AWQ -s 1000 -d 100 -b 4`

### Expected behavior

this is 1100 token contexts, according the change log we should see a speed up by two fold.

1.1.0
```


| Step           | Batch Size | Average    | Lowest     | Highest    | p50        | p90        | p99        |
|----------------|------------|------------|------------|------------|------------|------------|------------|
| Prefill        | 4          | 1205.76 ms | 1198.84 ms | 1213.61 ms | 1206.01 ms | 1213.61 ms | 1213.61 ms |
| Decode (token) |            | 14.22 ms   | 13.83 ms   | 14.50 ms   | 14.29 ms   | 14.50 ms   | 14.50 ms   |
| Decode (total) |            | 1407.46 ms | 1369.58 ms | 1435.73 ms | 1415.20 ms | 1435.73 ms | 1435.73 ms |


| Step    | Batch Size | Average            | Lowest             | Highest            |
|---------|------------|--------------------|--------------------|--------------------|
| Prefill | 4          | 3.32 tokens/secs   | 3.30 tokens/secs   | 3.34 tokens/secs   |
| Decode  |            | 281.43 tokens/secs | 275.82 tokens/secs | 289.14 tokens/secs |
```

1.3.4
```
| Step           | Batch Size | Average    | Lowest     | Highest    | p50        | p90        | p99        |
|----------------|------------|------------|------------|------------|------------|------------|------------|
| Prefill        | 4          | 1219.13 ms | 1204.34 ms | 1227.91 ms | 1219.52 ms | 1227.91 ms | 1227.91 ms |
| Decode (token) |            | 15.66 ms   | 15.42 ms   | 15.90 ms   | 15.67 ms   | 15.90 ms   | 15.90 ms   |
| Decode (total) |            | 1550.09 ms | 1526.40 ms | 1573.80 ms | 1551.16 ms | 1573.80 ms | 1573.80 ms |


| Step    | Batch Size | Average            | Lowest             | Highest            |
|---------|------------|--------------------|--------------------|--------------------|
| Prefill | 4          | 3.28 tokens/secs   | 3.26 tokens/secs   | 3.32 tokens/secs   |
| Decode  |            | 255.49 tokens/secs | 251.62 tokens/secs | 259.43 tokens/secs |

```
we got a slow down instead

**Comment by Narsil** [comment]
> this is 1100 token contexts, according the change log we should see a speed up by two fold.

Where did you read that ? If you're talking about speculation, then you need to activate it (`--speculate n`). https://huggingface.co/docs/text-generation-inference/basic_tutorials/launcher#speculate

The largest speedup will be with a fine-tuned medusa model https://github.com/FasterDecoding/Medusa

> we got a slow down instead

How many benchmark did you run ? It might be within noise range.
Also please note that 7B-AWQ sharded across 2 shards might be slower than 1 deployment on each GPU (it depends on the actual GPU setup, for example the presence of NVLink).

**Comment by NaCloudAI** [comment]
> > this is 1100 token contexts, according the change log we should see a speed up by two fold.
> 
> Where did you read that ? If you're talking about speculation, then you need to activate it (`--speculate n`). https://huggingface.co/docs/text-generation-inference/basic_tutorials/launcher#speculate
> 
> The largest speedup will be with a fine-tuned medusa model https://github.com/FasterDecoding/Medusa
> 
> > we got a slow down instead
> 
> How many benchmark did you run ? It might be within noise range. Also please note that 7B-AWQ sharded across 2 shards might be slower than 1 deployment on each GPU (it depends on the actual GPU setup, for example the presence of NVLink).

It was on change log in v1.3.3 `improve decode latency for long sequences two fold`

I will look into other solutions as well.

**Comment by maziyarpanahi** [comment]
@NaCloudAI 
> the slow down is a consistent result I got across all different machine.
Is this for specific model or you have tried different models? I recently updated a TGI server from `1.1.0` to `1.3.4`. Although, my local `1.3.4` has no issue, there are complaints that the updated server got slower. So I was wondering about your tests.
