### ISSUE TITLE
How to use a finetuned model from my local  directory 

### ISSUE THREAD

**Issue by pradeepdev-1995** [huggingface/text-generation-inference#1457]
### System Info

text-generation 0.6.1

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
from text_generation import InferenceAPIClient
client = InferenceAPIClient( "/mylocalpath/finetunedmodel")
test_prompt = """sample prompt"""
text = client.generate(test_prompt).generated_text
print(text)
```
it showing the
```
NotFoundError: Model "/mylocalpath/finetunedmodel" does not exist
```
This finetuned model is tuned in the base model - Mistral

### Expected behavior

Expect to  load the finetuned model from the local path

**Comment by ZQ-Dev8** [comment]
Recommend you try an absolute path if you haven't.

Also, it might help if you post a screenshot of the contents of your model's folder, so we can verify the contents look as they should (e.g. config files, pytorch_model.bin, etc. present).

**Comment by pradeepdev-1995** [comment]
This the content inside the finetuned models folder (MISTRAL_V3_CHECKPOINT_MERGED)
![Screenshot from 2024-01-20 09-39-39](https://github.com/huggingface/text-generation-inference/assets/41164884/84958de6-af64-4da8-b376-f9380ab4453f)
This is the error I am getting
![Screenshot from 2024-01-20 09-36-37](https://github.com/huggingface/text-generation-inference/assets/41164884/5019f6cf-ef3e-4906-95f2-68ddc63db20f)

**Comment by pradeepdev-1995** [comment]
@ZQ-Dev8 any updates on this?

**Comment by pradeepdev-1995** [comment]
![Screenshot from 2024-01-24 18-58-09](https://github.com/huggingface/text-generation-inference/assets/41164884/3f3c8f63-6afb-47ee-a4f9-3e7081de6fc7)
now I converted the safetensors to bin format. still, I am getting error
```
Model /data/MISTRAL_MERGED does not exist
``` 
and in the source code, I can see this code
```
def check_model_support(repo_id: str, headers: Optional[Dict] = None) -> bool:
    """
    Check if a given model is supported by text-generation-inference

    Returns:
        bool: whether the model is supported by this client
    """
    resp = requests.get(
        f"https://api-inference.huggingface.co/status/{repo_id}",
        headers=headers,
        timeout=5,
    )

    payload = resp.json()
    if resp.status_code != 200:
        raise parse_error(resp.status_code, payload)

    framework = payload["framework"]
    supported = framework == "text-generation-inference"
    return supported
``` 

which means it only supports the pre-trained models from the huggingface ?

**Comment by pradeepdev-1995** [comment]
also, I tried this code
```
from text_generation import Client
client = Client( "/mylocalpath/finetunedmodel")
test_prompt = """sample prompt"""
text = client.generate(test_prompt).generated_text
print(text)
```
but the given error showed
```
requests.exceptions.MissingSchema: Invalid URL /mylocalpath/finetunedmodel" No scheme supplied. Perhaps you meant https:////mylocalpath/finetunedmodel?
```

**Comment by Narsil** [comment]
You are showing code looking like using the CLIENT to make queries.

You should be using docker to launch your model: https://github.com/huggingface/text-generation-inference?tab=readme-ov-file#docker

Or the CLI but then you have more work to do to install : https://huggingface.co/docs/text-generation-inference/basic_tutorials/using_cli 
Not everything is covered in the docs, since our main layer of distribution is a docker container, since that solves many issues regarding custom kernels and/or compatibility.

**Comment by pradeepdev-1995** [comment]
@Narsil 
So whatever the way (docker/cli/client) is it able to inference from the finetuned model from my local folder path rather than a huggingface endpoint model-id?

**Comment by Narsil** [comment]
You need to follow the docs: https://github.com/huggingface/text-generation-inference?tab=readme-ov-file#docker

Docker is our recommended way of running the models, but you could also build locally and run the CLI.
Then follow this. : https://huggingface.co/docs/text-generation-inference/basic_tutorials/consuming_tgi#consuming-text-generation-inference

Does it make sense?

**Comment by oroojlooy** [comment]
I have the same question. I have a fine-tuned model available in my local machine and want to use it via TGI. 

> You need to follow the docs: https://github.com/huggingface/text-generation-inference?tab=readme-ov-file#docker
Docker is our recommended way of running the models, but you could also build locally and run the CLI.
Then follow this. : https://huggingface.co/docs/text-generation-inference/basic_tutorials/consuming_tgi#consuming-text-generation-inference

I could not find an answer to my question. Can you please explain it in more details?
