### ISSUE TITLE
Is there need to upgrade transformers to the latest version to support the LLaMa model?

### ISSUE THREAD

**Issue by hawgjmrd72** [huggingface/text-generation-inference#146]
But if I upgrade transformers to its latest version, I get these errors:
```
/data/tgi/text-generation-inference$ text-generation-launcher --model-id bigscience/bloom-560m --num-shard 2 --port 8899
2023-03-29T03:38:34.822927Z  INFO text_generation_launcher: Args { model_id: "bigscience/bloom-560m", revision: None, sharded: None, num_shard: Some(2), quantize: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: 32, max_waiting_tokens: 20, port: 8899, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None }
2023-03-29T03:38:34.822972Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-03-29T03:38:34.823231Z  INFO text_generation_launcher: Starting download process.
2023-03-29T03:38:40.229472Z ERROR text_generation_launcher: Download encountered an error: Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/text-generation-inference/bin/text-generation-server", line 5, in <module>
    from text_generation_server.cli import app
  File "/data/tgi/text-generation-inference/server/text_generation_server/cli.py", line 9, in <module>
    from text_generation_server import server, utils
  File "/data/tgi/text-generation-inference/server/text_generation_server/server.py", line 12, in <module>
    from text_generation_server.cache import Cache
  File "/data/tgi/text-generation-inference/server/text_generation_server/cache.py", line 3, in <module>
    from text_generation_server.models.types import Batch
  File "/data/tgi/text-generation-inference/server/text_generation_server/models/__init__.py", line 8, in <module>
    from text_generation_server.models.bloom import BLOOM, BLOOMSharded
  File "/data/tgi/text-generation-inference/server/text_generation_server/models/bloom.py", line 14, in <module>
    from transformers.models.bloom.parallel_layers import (
ModuleNotFoundError: No module named 'transformers.models.bloom.parallel_layers'
```

**Comment by OlivierDehaene** [comment]
Hello

Llama support is experimental at this stage. To use it: 

```shell
git clone git@github.com:huggingface/text-generation-inference.git
cd text-generation-inference
git checkout feat/flash_llama

make install

# launch server in background 
text-generation-server serve <path to your llama weights in transformer compatible format> &

# wait for server to start and then
text-generation-router --tokenizer-name hf-internal-testing/tiny-random-llama
```

On GPU, you can also use:

```shell
cd server && make install-flash-attention

FLASH_ATTENTION=1 text-generation-server serve <path to your llama weights in transformer compatible format> &
```

**Comment by lcw99** [comment]
> > ```shell
> > # launch server in background 
> > text-generation-server serve <path to your llama weights in transformer compatible format> &
> > ```
> 
> Thank you for your reply. I got some errors when I launch server in background. Such as **IndexError: piece id is out of range.**
> 
> ```
> (text-generation-inference) xxx@xxx-xxx-lpmsq-46420-worker-0:/data/tgi/text-generation-inference$ text-generation-server serve decapoda-research/llama-7b-hf &
> [1] 29289
> Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:14<00:00,  2.21it/s]
> Error when initializing model
> Traceback (most recent call last):
>   File "/home/xxx/miniconda3/envs/text-generation-inference/bin/text-generation-server", line 8, in <module>
>     sys.exit(app())
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
>     return get_command(self)(*args, **kwargs)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py", line 778, in main
>     return _main(
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py", line 216, in _main
>     rv = self.invoke(ctx)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
>     return callback(**use_params)  # type: ignore
>   File "/data/tgi/text-generation-inference/server/text_generation_server/cli.py", line 55, in serve
>     server.serve(model_id, revision, sharded, quantize, uds_path)
>   File "/data/tgi/text-generation-inference/server/text_generation_server/server.py", line 135, in serve
>     asyncio.run(serve_inner(model_id, revision, sharded, quantize))
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
>     self.run_forever()
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
>     self._run_once()
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
>     handle._run()
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
> > File "/data/tgi/text-generation-inference/server/text_generation_server/server.py", line 104, in serve_inner
>     model = get_model(model_id, revision, sharded, quantize)
>   File "/data/tgi/text-generation-inference/server/text_generation_server/models/__init__.py", line 99, in get_model
>     return llama_cls(model_id, revision, quantize=quantize)
>   File "/data/tgi/text-generation-inference/server/text_generation_server/models/causal_lm.py", line 297, in __init__
>     tokenizer.pad_token_id = (
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils_base.py", line 1217, in pad_token_id
>     self._pad_token = self.convert_ids_to_tokens(value) if value is not None else None
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils.py", line 903, in convert_ids_to_tokens
>     return self._convert_id_to_token(ids)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/models/llama/tokenization_llama.py", line 112, in _convert_id_to_token
>     token = self.sp_model.IdToPiece(index)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
>     return _func(self, arg)
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1038, in _func
>     raise IndexError('piece id is out of range.')
> IndexError: piece id is out of range.
> Traceback (most recent call last):
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/bin/text-generation-server", line 8, in <module>
>     sys.exit(app())
> 
>   File "/data/tgi/text-generation-inference/server/text_generation_server/cli.py", line 55, in serve
>     server.serve(model_id, revision, sharded, quantize, uds_path)
> 
>   File "/data/tgi/text-generation-inference/server/text_generation_server/server.py", line 135, in serve
>     asyncio.run(serve_inner(model_id, revision, sharded, quantize))
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
> 
>   File "/data/tgi/text-generation-inference/server/text_generation_server/server.py", line 104, in serve_inner
>     model = get_model(model_id, revision, sharded, quantize)
> 
>   File "/data/tgi/text-generation-inference/server/text_generation_server/models/__init__.py", line 99, in get_model
>     return llama_cls(model_id, revision, quantize=quantize)
> 
>   File "/data/tgi/text-generation-inference/server/text_generation_server/models/causal_lm.py", line 297, in __init__
>     tokenizer.pad_token_id = (
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils_base.py", line 1217, in pad_token_id
>     self._pad_token = self.convert_ids_to_tokens(value) if value is not None else None
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils.py", line 903, in convert_ids_to_tokens
>     return self._convert_id_to_token(ids)
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/models/llama/tokenization_llama.py", line 112, in _convert_id_to_token
>     token = self.sp_model.IdToPiece(index)
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
>     return _func(self, arg)
> 
>   File "/home/xxx/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1038, in _func
>     raise IndexError('piece id is out of range.')
> 
> IndexError: piece id is out of range.
> ```
This is probably because the pad_token_id is set to -1 in the Model's config.json. Replace it with a value like eos_token_id. 
However, after fixing this, the following error occurs.

```
2023-04-04T01:08:22.599803Z  INFO text_generation_launcher: Starting shard 0
2023-04-04T01:08:32.611117Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-04-04T01:08:34.412913Z  INFO text_generation_launcher: Shard 0 ready in 11.81133217s
2023-04-04T01:08:34.509918Z  INFO text_generation_launcher: Starting Webserver
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Model \"/home/chang/AI/llm/t5tests/gpt-j/Models/llama-7B-en-alpaca\" on the Hub doesn't have a tokenizer"', router/src/main.rs:101:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-04-04T01:08:35.511873Z ERROR text_generation_launcher: Webserver Crashed
2023-04-04T01:08:35.511926Z  INFO text_generation_launcher: Shutting down shards
2023-04-04T01:08:35.742511Z  INFO text_generation_launcher: Shard 0 terminated
```

**Comment by OlivierDehaene** [comment]
I think you are missing the fast tokenizer. You can either convert your tokenizer using the script in this PR: https://github.com/huggingface/transformers/pull/22264

Or you can launch Llama using the commands above:

```shell
# launch server in background 
text-generation-server serve /home/chang/AI/llm/t5tests/gpt-j/Models/llama-7B-en-alpaca &

# wait for server to start and then
text-generation-router --tokenizer-name hf-internal-testing/tiny-random-llama
```

**Comment by lcw99** [comment]
> I think you are missing the fast tokenizer. You can either convert your tokenizer using the script in this PR: [huggingface/transformers#22264](https://github.com/huggingface/transformers/pull/22264)
> 
> Or you can launch Llama using the commands above:
> 
> ```shell
> # launch server in background 
> text-generation-server serve /home/chang/AI/llm/t5tests/gpt-j/Models/llama-7B-en-alpaca &
> 
> # wait for server to start and then
> text-generation-router --tokenizer-name hf-internal-testing/tiny-random-llama
> ```
> 
> We are working on improving this setup.

Thanks for the answer, the way to create a fasttokenizer didn't work because the convert_slow_tokenizer function doesn't support LlamaTokenizer. Just put the tokenizer.json from hf-internal-testing/tiny-random-llama in the model folder, it works fine.

**Comment by hawgjmrd72** [comment]
> Just put the tokenizer.json from hf-internal-testing/tiny-random-llama in the model folder, it works fine.
Could you share the execution command, please? I did the same thins, but it does not work for me.

**Comment by lcw99** [comment]
> > Just put the tokenizer.json from hf-internal-testing/tiny-random-llama in the model folder, it works fine.
> > @lcw99
> > Could you share the execution command, please? I did the same thins, but it does not work for me.

Try it with the following command. Note that this model is actually in huggingface.

`text-generation-launcher --num-shard 1 --port 8081 --quantize --max-total-tokens 2048 --model-id "lcw99/llama-7B-alpaca-30p"`

**Comment by lcw99** [comment]
Now, everyting works fine, but streaming returns every token with preceding space like as follows.

```
token=Token(id=530, text='  An', logprob=-0.38964844, special=False) generated_text=None details=None
token=Token(id=284, text='  al', logprob=-0.24169922, special=False) generated_text=None details=None
token=Token(id=29886, text='  p', logprob=0.0, special=False) generated_text=None details=None
token=Token(id=562, text='  ac', logprob=-0.12939453, special=False) generated_text=None details=None
token=Token(id=29874, text='  a', logprob=0.0, special=False) generated_text=None details=None
token=Token(id=338, text='  is', logprob=0.0, special=False) generated_text=None details=None
token=Token(id=263, text='  a', logprob=0.0, special=False) generated_text=None details=None

```

**Comment by hawgjmrd72** [comment]
> Try it with the following command. Note that this model is actually in huggingface.
> 
> `text-generation-launcher --num-shard 1 --port 8081 --quantize --max-total-tokens 2048 --model-id "lcw99/llama-7B-alpaca-30p"`

In my case,  I try [decapoda-research/llama-7b-hf](https://huggingface.co/decapoda-research/llama-7b-hf/tree/main) with the following command:
```
text-generation-launcher --num-shard 1 --port 8899 --quantize --max-total-tokens 2048 --model-id "decapoda-research/llama-7b-hf"
```
get the same error: "IndexError: piece id is out of range."
```
(text-generation-inference) liwen@liwen-liwen-mpj2n-46331-worker-0:/data/tgi/text-generation-inference$ text-generation-launcher --num-shard 1 --port 8899 --quantize --max-total-tokens 2048 --model-id "decapoda-research/llama-7b-hf"
2023-04-04T09:49:08.339341Z  INFO text_generation_launcher: Args { model_id: "decapoda-research/llama-7b-hf", revision: None, sharded: None, num_shard: Some(1), quantize: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 2048, max_batch_size: 32, max_waiting_tokens: 20, port: 8899, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None }
2023-04-04T09:49:08.340048Z  INFO text_generation_launcher: Starting shard 0
2023-04-04T09:49:18.354358Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-04-04T09:49:28.364767Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-04-04T09:49:36.436712Z ERROR shard-manager: text_generation_launcher: "Error when initializing model
Traceback (most recent call last):
  File \"/home/liwen/miniconda3/envs/text-generation-inference/bin/text-generation-server\", line 8, in <module>
    sys.exit(app())
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py\", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py\", line 1130, in __call__
    return self.main(*args, **kwargs)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py\", line 778, in main
    return _main(
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/core.py\", line 216, in _main
    rv = self.invoke(ctx)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py\", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py\", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/click/core.py\", line 760, in invoke
    return __callback(*args, **kwargs)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/typer/main.py\", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File \"/data/tgi/text-generation-inference/server/text_generation_server/cli.py\", line 55, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)
  File \"/data/tgi/text-generation-inference/server/text_generation_server/server.py\", line 135, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/runners.py\", line 44, in run
    return loop.run_until_complete(main)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py\", line 634, in run_until_complete
    self.run_forever()
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py\", line 601, in run_forever
    self._run_once()
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py\", line 1905, in _run_once
    handle._run()
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/events.py\", line 80, in _run
    self._context.run(self._callback, *self._args)
> File \"/data/tgi/text-generation-inference/server/text_generation_server/server.py\", line 104, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)
  File \"/data/tgi/text-generation-inference/server/text_generation_server/models/__init__.py\", line 99, in get_model
    return llama_cls(model_id, revision, quantize=quantize)
  File \"/data/tgi/text-generation-inference/server/text_generation_server/models/causal_lm.py\", line 297, in __init__
    tokenizer.pad_token_id = (
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils_base.py\", line 1217, in pad_token_id
    self._pad_token = self.convert_ids_to_tokens(value) if value is not None else None
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils.py\", line 903, in convert_ids_to_tokens
    return self._convert_id_to_token(ids)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/models/llama/tokenization_llama.py\", line 112, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py\", line 1045, in _batched_func
    return _func(self, arg)
  File \"/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py\", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.
" rank=0
2023-04-04T09:49:37.562215Z ERROR text_generation_launcher: Shard 0 failed to start:
/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/liwen/miniconda3/envs/text-generation-inference did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
Overriding torch_dtype=torch.float32 with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
This model has some weights that should be kept in higher precision, you need to upgrade `accelerate` to properly deal with them (`pip install --upgrade accelerate`).
Loading checkpoint shards: 100%|██████████| 33/33 [00:11<00:00,  2.88it/s]
Traceback (most recent call last):

  File "/home/liwen/miniconda3/envs/text-generation-inference/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/data/tgi/text-generation-inference/server/text_generation_server/cli.py", line 55, in serve
    server.serve(model_id, revision, sharded, quantize, uds_path)

  File "/data/tgi/text-generation-inference/server/text_generation_server/server.py", line 135, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize))

  File "/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/data/tgi/text-generation-inference/server/text_generation_server/server.py", line 104, in serve_inner
    model = get_model(model_id, revision, sharded, quantize)

  File "/data/tgi/text-generation-inference/server/text_generation_server/models/__init__.py", line 99, in get_model
    return llama_cls(model_id, revision, quantize=quantize)

  File "/data/tgi/text-generation-inference/server/text_generation_server/models/causal_lm.py", line 297, in __init__
    tokenizer.pad_token_id = (

  File "/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils_base.py", line 1217, in pad_token_id
    self._pad_token = self.convert_ids_to_tokens(value) if value is not None else None

  File "/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/tokenization_utils.py", line 903, in convert_ids_to_tokens
    return self._convert_id_to_token(ids)

  File "/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9-linux-x86_64.egg/transformers/models/llama/tokenization_llama.py", line 112, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)

  File "/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)

  File "/home/liwen/miniconda3/envs/text-generation-inference/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')

IndexError: piece id is out of range.


2023-04-04T09:49:37.562414Z  INFO text_generation_launcher: Shutting down shards
```

**Comment by lcw99** [comment]
@hawgjmrd72 look at [config.json](https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/config.json), pad_token_id is -1. need to change 1.

**Comment by OlivierDehaene** [comment]
@lcw99,
The issues should be fixed now on the PR branch.
