### ISSUE TITLE
parallel or concurrent requests

### ISSUE THREAD

**Issue by SDcodehub** [huggingface/text-generation-inference#1464]
I am using docker to host the model on to GPU -  `ghcr.io/huggingface/text-generation-inference:latest`

with following command - `--model-id TheBloke/openchat-3.5-0106-AWQ --port 8080 --max-input-length 7500 --max-total-tokens 8192 --max-batch-prefill-tokens 8192 --quantize awq --speculate 3`

due to context length limitation, I am using splitting of text.

How can I send requests parallelly in single batch? is there way to compile all requests into a list and at once as a single batch?
any document/example/tut which can help me in this?

**Comment by SDcodehub** [comment]
did not find a way to forcefully batch the requests and then send for scoring, may be community can help us here.

However, I figured post reading few threads, that concurrent request submission also does approximately same.

**Comment by tilmanbeck** [comment]
I would also be interested batched inference, using OpenAI API interface in TGI.
