### ISSUE TITLE
Support the legacy openai 'completions' API interface

### ISSUE THREAD

**Issue by spew** [huggingface/text-generation-inference#1468]
### Feature request

In https://github.com/huggingface/text-generation-inference/pull/1427, @Narsil added support for the Chat Completions API (`v1/chat/completions`). However, there's also a legacy API at [v1/completions](https://platform.openai.com/docs/api-reference/completions/create) which many tools and IDE extensions are using.

### Motivation

 If TGI supported the legacy OpenAI `v1/completions` API, then it could be a drop in replacement for OpenAI when using those tools. 

### Your contribution

I can possibly learn rust and submit a PR.

**Comment by spew** [comment]
First issue I would see is we would need another `template` value in `tokenizer_config.json` to know how to properly join up the `prompt` and `suffix`.

**Comment by OlivierDehaene** [comment]
What do you think @drbh?

**Comment by UniverseFly** [comment]
Really want this feature

**Comment by spew** [comment]
@OlivierDehaene would it be prohibitively difficult to get a new template value into all the various model's tokenizer_config.json to enable a translation from legacy completions api (prompt & prefix I believe are the two arguments) -> single string

**Comment by Narsil** [comment]
If we need to modify things on the original model repo, then yes it's most likely prohibitive.

**Comment by drbh** [comment]
Hi @spew thanks for the suggestion, after reviewing the legacy docs I believe it would only require adding one more request/response to TGI to handle the expected types. I've started a draft PR here https://github.com/huggingface/text-generation-inference/pull/1527
