### ISSUE TITLE
NotImplementedError: awq quantization is not supported for AutoModel

### ISSUE THREAD

**Issue by joaomsimoes** [huggingface/text-generation-inference#1472]
### System Info

When running I have the following error: 
NotImplementedError: awq quantization is not supported for AutoModel

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

`docker run --shm-size 1g --model-id TheBloke/Mistral-7B-OpenOrca-AWQ --quantize awq --max-input-length 3696 --max-total-tokens 4096 --max-batch-prefill-tokens 4096
`

### Expected behavior

Should start the container.

**Comment by Narsil** [comment]
You are most likely missing flash attention, otherwise the model would load just fine.

Could you fill in the entire template asked for. The logs for instance would help make sure that indeed it's that you are not loading flash attention properly (leading to loading using the transformers fallback which doesn't work)

**Comment by joaomsimoes** [comment]
`llm-1  | 2024-02-01T16:35:33.826006Z  INFO text_generation_launcher: Args { model_id: "joaomsimoes/zephyr_gema", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Awq), speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "4bc20e309e07", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, env: false }
llm-1  | 2024-02-01T16:35:33.826162Z  INFO download: text_generation_launcher: Starting download process.
llm-1  | 2024-02-01T16:35:38.509618Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.
llm-1  | 
llm-1  | 2024-02-01T16:35:39.034918Z  INFO download: text_generation_launcher: Successfully downloaded weights.
llm-1  | 2024-02-01T16:35:39.035185Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
llm-1  | 2024-02-01T16:35:43.710751Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2
llm-1  | 
llm-1  | 2024-02-01T16:35:44.014259Z ERROR text_generation_launcher: Error when initializing model
llm-1  | Traceback (most recent call last):
llm-1  |   File "/opt/conda/bin/text-generation-server", line 8, in <module>
llm-1  |     sys.exit(app())
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
llm-1  |     return get_command(self)(*args, **kwargs)
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
llm-1  |     return self.main(*args, **kwargs)
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
llm-1  |     return _main(
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
llm-1  |     rv = self.invoke(ctx)
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
llm-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
llm-1  |     return ctx.invoke(self.callback, **ctx.params)
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
llm-1  |     return __callback(*args, **kwargs)
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
llm-1  |     return callback(**use_params)  # type: ignore
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
llm-1  |     server.serve(
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
llm-1  |     asyncio.run(
llm-1  |   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
llm-1  |     return loop.run_until_complete(main)
llm-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
llm-1  |     self.run_forever()
llm-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
llm-1  |     self._run_once()
llm-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
llm-1  |     handle._run()
llm-1  |   File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
llm-1  |     self._context.run(self._callback, *self._args)
llm-1  | > File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
llm-1  |     model = get_model(
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 381, in get_model
llm-1  |     raise NotImplementedError("awq quantization is not supported for AutoModel")
llm-1  | NotImplementedError: awq quantization is not supported for AutoModel
llm-1  | 
llm-1  | 2024-02-01T16:35:44.642915Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
llm-1  | 
llm-1  | Traceback (most recent call last):
llm-1  | 
llm-1  |   File "/opt/conda/bin/text-generation-server", line 8, in <module>
llm-1  |     sys.exit(app())
llm-1  | 
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
llm-1  |     server.serve(
llm-1  | 
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
llm-1  |     asyncio.run(
llm-1  | 
llm-1  |   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
llm-1  |     return loop.run_until_complete(main)
llm-1  | 
llm-1  |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
llm-1  |     return future.result()
llm-1  | 
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
llm-1  |     model = get_model(
llm-1  | 
llm-1  |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 381, in get_model
llm-1  |     raise NotImplementedError("awq quantization is not supported for AutoModel")
llm-1  | 
llm-1  | NotImplementedError: awq quantization is not supported for AutoModel
llm-1  |  rank=0
llm-1  | Error: ShardCannotStart
llm-1  | 2024-02-01T16:35:44.741072Z ERROR text_generation_launcher: Shard 0 failed to start
llm-1  | 2024-02-01T16:35:44.741107Z  INFO text_generation_launcher: Shutting down shards
llm-1 exited with code 0`

Maybe has to do with this ` Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2`
I have CUDA 12.2
