### ISSUE TITLE
Crash service after call with empty input

### ISSUE THREAD

**Issue by snapshotpl** [huggingface/text-generation-inference#1485]
### System Info

Call openai API endpoint with empty input crash service.
```
thread 'tokio-runtime-worker' panicked at /usr/src/router/src/http/server.rs:683:42:
Jan 25 14:02:48 embeddings-00 docker[136688]: attempt to divide by zero
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Call OpenAI api endpoint with empty array of input:
```
POST /embeddings
{"model":"modelname","input":[]}
```

### Expected behavior

Response from API with 4xx error. No service crash

**Comment by OlivierDehaene** [comment]
Wrong repo.

**Comment by snapshotpl** [comment]
Which repo is correct for this issue?

**Comment by OlivierDehaene** [comment]
Well the repo related to this error? https://github.com/huggingface/text-embeddings-inference
