### ISSUE TITLE
Medusa-1 slow down the model

### ISSUE THREAD

**Issue by thuwyh** [huggingface/text-generation-inference#1493]
### System Info

I trained a Medusa model and inferenced it with the version: ghcr.io/huggingface/text-generation-inference:sha-9c320e2
What I found is the `time_per_token` and time to finish 50 requests increased by about 50% compared with the base model.

My medusa config is as follows:
{
  "base_model_name_or_path": "/data/exp/llama_13bf_0104",
  "medusa_num_heads": 3,
  "medusa_num_layers": 1,
  "transformers_version": "4.38.0.dev0"
}
where llama_13bf_0104 is my base model.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

CMD to start docker:
```
docker run --name medusa_test --gpus '"device=6"' -v $PWD:/data --shm-size 1g -p 8300:80 ghcr.io/huggingface/text-generation-inference:sha-9c320e2 --model-id /data/exp/medusa_13bf_0125 --dtype bfloat16 --max-total-tokens 4096 --sharded false --max-input-length 4095 --speculate 3
```

code to test
```
async def one_task(sem, prompt):
    async with sem:
        return await client_dpo.text_generation(prompt, max_new_tokens=512, stream=False, seed=42,
                                                    do_sample=True, temperature=0.7, top_p=0.95, top_k=40,
                                                    repetition_penalty=1.1,
                                                    return_full_text=False)


async def run_test():
    start = time.perf_counter()
    tasks = []
    sem = asyncio.Semaphore(5)
    for d in data:
        background = make_background(d['refs'])
        if 'date' in data and data['date'] is not None:
            date = data['date']
        else:
            date = datetime.now().strftime("%m-%d-%Y")
        input_prompt = get_template()
        
        tasks.append(asyncio.create_task(one_task(sem, input_prompt)))
        if len(tasks)==50:
            break
    print('total test samples:', len(tasks))

    results = await asyncio.gather(*tasks)
    print(f"finish in {time.perf_counter()-start}s")
```

### Expected behavior

should see speed up according the paper

**Comment by Narsil** [comment]
It's most likely because of how the medusa model was trained. We are working with the medusa authors to release tools which should generalize better than the current training loops.

There are issues in the formatting of the finetuning but also possibly how the model was trained altogether.

If you check out this model: https://huggingface.co/FasterDecoding/medusa-vicuna-7b-v1.3 then it will yield better results than the original one.

**Comment by truenorth8** [comment]
@Narsil would you be able to provide any more info on what's in the works? TGI's medusa implementation is also (slightly) slowing down inference in my case, with a custom trained model.

I do get a speedup with the FasterDecoding repo (but that one is of course lacking all of TGI's optimizations)
