### ISSUE TITLE
Sagemaker Mixtral AWQ returns empty string

### ISSUE THREAD

**Issue by p-christ** [huggingface/text-generation-inference#1500]
### System Info

**Huggingface llm image uri for Sagemaker version**: 1.3.3

when deploying Mixtral AWQ using the above docker on sagemaker, it builds correctly but when the model is called **only an empty string is returned back?**  

The call to the model takes a few seconds though which makes me think the model is working but for some reason it is only returning an empty string back - does anyone know what could be causing this?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Deploy to Sagemaker 

this model

```
    huggingface_model = HuggingFaceModel(
        image_uri=get_huggingface_llm_image_uri("huggingface", version="1.3.3"),
        env=hub,
        role=role,
    )
```

with 

HF_MODEL_ID='TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ,
HF_MODEL_QUANTIZE='awq',
INSTANCE_TYPE='ml.g5.12xlarge'

and then try to make a request to it and see the response

### Expected behavior

I'd expect text to be returned, not an empty string

**Comment by Narsil** [comment]
I think this model works better than TheBlock one: https://huggingface.co/ybelkada/Mixtral-8x7B-Instruct-v0.1-AWQ
