### ISSUE TITLE
Mixtral nf4 performance 2x slower than expected

### ISSUE THREAD

**Issue by timohear** [huggingface/text-generation-inference#1501]
### System Info

Latest version

### Information

- [x] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

Compare mistral-7b nf4 perf to mixtral nf4 perf

### Expected behavior

On a single a6000 using bitsandbytes nf4 quantization I'm seeing 17ms per token with Mistral-7b and 80ms per token with Mixtral.

My expectation is that Mixtral should have the performance of roughly 2x the 7b model (around 40ms per token). Current perf levels seem to negate the advantage over a large non-MOE model.

**Comment by nguyenhoanganh2002** [comment]
Same problem here

**Comment by Narsil** [comment]
This assumption is not necessarily True.

BNB-nf4 adds up some overhead by itself. It also has a quite peculiar latency/throughput graph, where adding a single batch can increase latency by more than 2x.

This performance gap does not exist for non BNB-nf4, therefore I think you should try and ask upstream about this, or try using an AWQ version of the model (which afaik has better latency, although I never tested on A600)

**Comment by timohear** [comment]
I ran some tests (time per token)

BnB 4bit
- Mixtral-8x7b:  80ms
- Mistral-7b:      18ms
- llama2-13b:    22ms
- llama2-34b:    52ms
- llama2-70b:    98ms

eetq 8bit
- Mixtral-8x7b:  80ms 
- Mistral-7b:      14ms
- llama2-13b:    22ms 
- llama2-34b:    56ms

So in both cases Mixtral seems to be performing more like a dense 50b than a 2x7b. Is the performance relatively better in 16bit?

AWQ Mixtral is a bit better at 60ms (but thebloke's version crashes and the quality of the other one is bad). It still seems like Mixral should be a lot faster for MoE to be worth it.

I see your point about BnB batching: performance with concurrent requests is poor. Eeqt and AWQ see virtually no slowdown with 2-3 concurrent requests

**Comment by timohear** [comment]
Possibly related: vllm made some mixtral specific optimizations to improve perf  https://github.com/vllm-project/vllm/pull/2090

**Comment by Narsil** [comment]
@timohear We've done it before them :).

The issue is BNB-4b with mixtral. The thing is that MoE custom kernels are actually quite slow, therefore everyone is now running the fully ranked matmul. And it's just because it's faster than using megablocks.

If you were to use megablocks, you would have to actually to implement yourselves the bnb/awq/eetq layers. And make ti faster than running the full matmul.

All of this is quite a challenge.

**Comment by timohear** [comment]
> @timohear We've done it before them :).
:-)

Thank you for taking the time to explain. I ran some fp16 tests (on 2xa6000 for Mixtral and 34b) and I'm also seeing Mixtral performance in line with a 50b dense llama2:

fp16
- Mixtral-8x7b:  74ms 
- Mistral-7b:      24ms
- llama2-13b:    42ms
- llama2-34b:    56ms

Is it possible that there are specific optimizsations that aren't being applied to a6000/a40 (maybe due to sm86 rather than sm80)?
