### ISSUE TITLE
Support for Mamba (SSM)

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/text-generation-inference#1507]
### Feature request

Allow inference (even if only in bf16) for Mamba architecture models.

### Motivation

Mamba architecture effectively allows for attention to be compressed into a state, allowing a per token time that is constant with context length.

Seems all of the benefits of attention are built into the trainable linear selection done within the state, so probably these models take over transformers?

### Your contribution

I'm not sure how complex it would be to integrate. Inference works well with transformers, but I know TGI isn't built on transformers.

**Comment by drbh** [comment]
Hi @RonanKMcGovern there is current a work in progress in this PR https://github.com/huggingface/text-generation-inference/pull/1480

The model still has a couple of issues to be resolved but should be included in the near future.

Going to close this issue for now, but please free to follow up on the PR 🙂
