### ISSUE TITLE
AssertionError: Out of available cache blocks: asked 111, only 39 free blocks

### ISSUE THREAD

**Issue by NaCloudAI** [huggingface/text-generation-inference#1513]
### System Info

1.3.4 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Unsure, happens with 70b models sometimes.
A6000 ada

### Expected behavior

should not have error

**Comment by Narsil** [comment]
Can you provide more information ?

Logs, environment and so on ?
What model ? What options are you using ?
Are you running anything else on your machine ?

If we cannot reproduce we cannot really help.
