### ISSUE TITLE
Router's validation behaves differently for models using different quantization approaches

### ISSUE THREAD

**Issue by ponshane** [huggingface/text-generation-inference#1519]
### System Info

text-generation-launcher 1.3.4

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I used two following commands to serve a model using different quantization approaches:

1. 2 GPUS (A40), Med42-70B (architecture: LlamaForCausalLM), eetq, dynamic rope scaling
```bash
model=m42-health/med42-70b
volume=MY_HFCACHE
token=MYTOKENS

sudo docker run --gpus '"device=4,5"' \
    --shm-size 20g \
    -e HUGGING_FACE_HUB_TOKEN=$token \
    -p 8080:80 \
    -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.3 \
    --model-id $model \
    --sharded true \
    --quantize eetq \
    --max-input-length 2048 \
    --max-total-tokens 4096 \
    --rope-scaling dynamic \
    --rope-factor 2.0 \
    --port 80
```

2.  1 GPUS (A40), Med42-70B (architecture: LlamaForCausalLM), awq, dynamic rope scaling

```bash
model=TheBloke/med42-70B-AWQ
volume=MY_HFCACHE
token=MYTOKENS

sudo docker run --gpus '"device=5"' \
    --shm-size 20g \
    -e HUGGING_FACE_HUB_TOKEN=$token \
    -p 8080:80 \
    -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.3 \
    --model-id $model \
    --quantize awq \
    --max-input-length 2048 \
    --max-total-tokens 4096 \
    --rope-scaling dynamic \
    --rope-factor 2.0 \
    --port 80
```

The issue is when I send a prompt (with 4194 tokens) for decoding 
- the first command does not throw any error and is able to decode as instructed
- however, the second command throws the error ```huggingface_hub.inference._text_generation.ValidationError: Input validation error: `inputs` must have less than 2048 tokens. Given: 4194```

### Expected behavior

I understand the length of the test prompt exceeds max-input-length and max-total-tokens, but why the validations for these two commands are different?

**Comment by Narsil** [comment]
I don't have access to both repos, but most likely there' s a difference in the tokenizers.

For instance the first one might NOT have a fast tokenizer (tokenizer.json), which prevents the router from actually counting tokens (meaning it will assume max tokens for the query and simply pass it along)

**Comment by ponshane** [comment]
After checking both repos, the first one does NOT have fast tokenizer (tokenizer.json) while the second one does have it. so as your guess, this might be the reason why the first one does not throw any error.

If this is the case, I'm a bit confused about the current way to activate the rope scaling. 

In this TGI's official [documentation](https://huggingface.co/docs/text-generation-inference/basic_tutorials/preparing_model#rope-scaling), it suggests making sure to pass `--max-input-length` to provide model’s original max sequence length for extension. I set `--max-input-length` as 2048 because it is the "max_position_embeddings": 2048 defined in the model's config.json. By setting `--rope-scaling dynamic` and `--rope-factor 2.0` it should be able to handle longer prompts (> 2048 tokens). However, it looks like the current router's validation will turn down those long prompts and throw the input validation error (assume that the used model has a fast tokenizer). Look forward to your verification on this. 

Thank you.

**Comment by Narsil** [comment]
> Make sure to pass --max-input-length to provide maximum input length for extension.

This should be understood as pass in 4096, no ?

**Comment by ponshane** [comment]
@Narsil Thank you for your clarification. I think I misunderstood the document at first. 

Now I'm clear that `--max-input-length` is for router's validation. I found in your [rope scaling implementation](https://github.com/huggingface/text-generation-inference/blob/0e97af456af3102ed4f927f7b7e870ec976079ae/server/text_generation_server/utils/layers.py#L777), TGI will read config.max_position_embeddings for `max_position_embeddings`. At first I thought `--max-input-length` is relevant to rope scaling, but just realize it is not.
