### ISSUE TITLE
Why I can't run a 6.48B AWQ model with 24GB of VRAM?

### ISSUE THREAD

**Issue by angel-luis** [huggingface/text-generation-inference#1525]
### System Info

Using Docker with Debian 12, and RTX 3090.
Model card: [https://huggingface.co/TheBloke/Nous-Hermes-2-Mixtral-8x7B-DPO-AWQ](https://huggingface.co/TheBloke/Nous-Hermes-2-Mixtral-8x7B-DPO-AWQ)

### Reproduction

I've reduced the prefill tokens as specified:

```bash
docker run --name "${NAME}" --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN} -p 8080:80 -v "${PATH_DATA}:/data" "ghcr.io/huggingface/text-generation-inference:1.4" --model-id "TheBloke/Nous-Hermes-2-Mixtral-8x7B-DPO-AWQ" --quantize awq --max-input-length 512 --max-batch-prefill-tokens 512
```

### Behaviour

It crashes before start:

```bash
ERROR warmup{max_input_length=512 max_prefill_tokens=512 max_total_tokens=2048}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 512 prefill tokens. You need to decrease `--max-batch-prefill-tokens`
```

**Comment by Narsil** [comment]
This model is 24GB https://huggingface.co/TheBloke/Nous-Hermes-2-Mixtral-8x7B-DPO-AWQ/tree/main

**Comment by angel-luis** [comment]
Perfect, then is an error in the model card. Thank you **Narsil**!
