### ISSUE TITLE
sagemaker compatible docker

### ISSUE THREAD

**Issue by pprokevin** [huggingface/text-generation-inference#1535]
### Feature request

How the TGI docker is compatible with sagemaker deployment ?

there is this one
**https://github.com/huggingface/notebooks/blob/main/sagemaker/27_deploy_large_language_models/sagemaker-notebook.ipynb**

https://huggingface.co/blog/sagemaker-huggingface-llm

Can we use the TGI docker directly for sagemaker inference deployment ?
thanks

### Motivation

Simplify the deployment on sagemarker.

### Your contribution

We should add a readme, sub-folder for sagemaker related deployment.

**Comment by ucyang** [comment]
Take a look at this repository: https://github.com/awslabs/llm-hosting-container
