### ISSUE TITLE
NCCL Error on multi-gpu setup with Nvidia driver 545

### ISSUE THREAD

**Issue by akowalsk** [huggingface/text-generation-inference#1559]
### System Info

OS: Ubuntu 22.04.3 LTS
Kernel: 5.15.0-91-generic

text-generation-inference:
{
  "model_id": "/model",
  "model_sha": null,
  "model_dtype": "torch.float16",
  "model_device_type": "cuda",
  "model_pipeline_tag": null,
  "max_concurrent_requests": 128,
  "max_best_of": 2,
  "max_stop_sequences": 4,
  "max_input_length": 3072,
  "max_total_tokens": 4096,
  "waiting_served_ratio": 1.2,
  "max_batch_total_tokens": 38544,
  "max_waiting_tokens": 20,
  "validation_workers": 2,
  "version": "1.4.0",
  "sha": "c2d4a3b5c7bb6a8367c00f7c797bf87f4b2fcef9",
  "docker_label": "sha-c2d4a3b"
}

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   25C    P8              10W / 350W |      3MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        Off | 00000000:21:00.0 Off |                  N/A |
|  0%   25C    P8              13W / 350W |      3MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

On a system with more than 1 GPU, with Nvidia driver 545.29.06 (the latest 545 driver in the ubuntu repo), I run this command:

`docker run --gpus '"device=0,1"' --shm-size 1g -v $(pwd):/model -p 8080:80 ghcr.io/huggingface/text-generation-inference:1.4 --model-id /model --quantize bitsandbytes-fp4 --trust-remote-code --port 80 --json-output --hostname 0.0.0.0 --max-input-length 3072 --max-total-tokens 4096`

I receive the following console output: 

`{"timestamp":"2024-02-13T22:17:59.304845Z","level":"INFO","fields":{"message":"Args { model_id: \"/model\", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(BitsandbytesFP4), speculate: None, dtype: None, trust_remote_code: true, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 3072, max_total_tokens: 4096, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: \"0.0.0.0\", port: 80, shard_uds_path: \"/tmp/text-generation-server\", master_addr: \"localhost\", master_port: 29500, huggingface_hub_cache: Some(\"/data\"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: true, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, env: false }"},"target":"text_generation_launcher"}
{"timestamp":"2024-02-13T22:17:59.304895Z","level":"WARN","fields":{"message":"`trust_remote_code` is set. Trusting that model `/model` do not contain malicious code."},"target":"text_generation_launcher"}
{"timestamp":"2024-02-13T22:17:59.304907Z","level":"INFO","fields":{"message":"Sharding model on 2 processes"},"target":"text_generation_launcher"}
{"timestamp":"2024-02-13T22:17:59.305006Z","level":"INFO","fields":{"message":"Starting download process."},"target":"text_generation_launcher","span":{"name":"download"},"spans":[{"name":"download"}]}
{"timestamp":"2024-02-13T22:18:01.846572Z","level":"INFO","fields":{"message":"Files are already present on the host. Skipping download.\n"},"target":"text_generation_launcher"}
{"timestamp":"2024-02-13T22:18:02.407969Z","level":"INFO","fields":{"message":"Successfully downloaded weights."},"target":"text_generation_launcher","span":{"name":"download"},"spans":[{"name":"download"}]}
{"timestamp":"2024-02-13T22:18:02.408183Z","level":"INFO","fields":{"message":"Starting shard"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:02.408583Z","level":"INFO","fields":{"message":"Starting shard"},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:12.415417Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:12.417509Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:22.421204Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:22.425835Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:32.427004Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:32.435364Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:42.432782Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:42.444084Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:52.438547Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:18:52.452346Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:19:02.444730Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:19:02.460619Z","level":"INFO","fields":{"message":"Waiting for shard to be ready..."},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:19:07.248791Z","level":"ERROR","fields":{"message":"Shard complete standard error output:\n\nThe argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.\nThe argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.\nYou are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.\n[E ProcessGroupNCCL.cpp:475] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60273 milliseconds before timing out.\n[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.\n[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.\n[E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60273 milliseconds before timing out.\nterminate called after throwing an instance of 'std::runtime_error'\n  what():  [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=60000) ran for 60273 milliseconds before timing out."},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:19:07.248832Z","level":"ERROR","fields":{"message":"Shard process was signaled to shutdown with signal 6"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}
{"timestamp":"2024-02-13T22:19:07.258333Z","level":"ERROR","fields":{"message":"Shard 0 failed to start"},"target":"text_generation_launcher"}
{"timestamp":"2024-02-13T22:19:07.258360Z","level":"INFO","fields":{"message":"Shutting down shards"},"target":"text_generation_launcher"}
{"timestamp":"2024-02-13T22:19:07.402113Z","level":"INFO","fields":{"message":"Shard terminated"},"target":"text_generation_launcher","span":{"rank":1,"name":"shard-manager"},"spans":[{"rank":1,"name":"shard-manager"}]}
Error: ShardCannotStart
`

The container then exits.

The exact command works on the same exact system when I downgrade the drivers to 535.  It also works with the workaround I found here: https://github.com/vllm-project/vllm/issues/1801#issuecomment-1847110199 (adding the `NCCL_P2P_DISABLE=1` environment variable)

### Expected behavior

I'm not sure if this is the right place for the issue, but it's the first place I encountered this (seems like it might be NVIDIA's problem more than anyone).  Other model training and inference tests passed with the new driver version (although I'm unsure how many of them actually utilize NCCL).  My expected behavior is that the TGI server would start without error on the latest NVIDIA driver version.

**Comment by Narsil** [comment]
Sorry to say but I don't think it's linked to the drivers. Currently running the same drivers without any issue.

Disabling P2P is odd... 
I'm guessing I'm using an NVLink which you don't have, or maybe something is broken in the drivers in the detection ?

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html

In any case we can't really disable P2P since it's quite necessary on NVLink machines.

**Comment by Narsil** [comment]
Thanks a lot for sharing the solution 
```
NCCL_P2P_DISABLE=1
```
really helpful for others that might stumble here.

**Comment by akowalsk** [comment]
> 'm guessing I'm using an NVLink which you don't have

You guessed right, I do not have an NVLink on that system.  Presumably then it's a problem with NCCL using/negotiating PCI-based P2P?  Do you have a suggestion on how I can follow up on that with NVIDIA (I don't really have an enterprise support contract, it's just a gaming machine I'm using locally)?
