### ISSUE TITLE
Question about sharding

### ISSUE THREAD

**Issue by njhill** [huggingface/text-generation-inference#156]
I was curious about how/why you use TP/sharding here for non-BLOOM/Galactica models i.e. GPT-NeoX and T5, since these fit in a single A100. Is it to be able to run them on smaller/cheaper GPUs? or because it provides latency advantages from the additional parallelism? or both?

Thanks!

**Comment by OlivierDehaene** [comment]
It's for both!
We don't use many A100s for our production inference workloads. We preffer using A10s or T4s. In this case it becomes mandatory to shard for larger models.

Also, you get latency improvements when sharding. We saw some pretty big improvements for the llama models for example.

So having this kind of flexibility is very important for us. + it is very easy to add Tensor Parallelism so why not.

**Comment by njhill** [comment]
Thank you @OlivierDehaene, that's very helpful!
