### ISSUE TITLE
Benchmarker Not Representative Of Real Performance?

### ISSUE THREAD

**Issue by mallorbc** [huggingface/text-generation-inference#1565]
### System Info

Docker, A100 GPU

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Deploy any model and benchmark it.  Take note of the throughput

### Expected behavior

More so a question.  When using the benchmarker, we can control things like the batch size, input size, output size, etc.

However, since TGI uses continuous batching, wouldn't the real-world results be better than the results given by using the model with a given batch size?  In other words, if I want a more accurate picture, I should write my own benchmarker?

Or does the benchmarker do continuous batching?

**Comment by vishnumadhu365** [comment]
would be great if someone from HF could comment on this query. Thanks
@OlivierDehaene
