### ISSUE TITLE
How to select specific gpu devices to be used in sharding, or a specific gpu device when sharding is false?

### ISSUE THREAD

**Issue by ZaDarkSide** [huggingface/text-generation-inference#157]
I would want to select what gpu devices can be used or not.
For example I have 2 gpu devices 0 and 1, and I would want to run only in gpu device 1 and let 0 to handle other operations.

**Comment by OlivierDehaene** [comment]
You can use the `CUDA_VISIBLE_DEVICES` env var to select the GPU you want to run on.

Example:

```shell
CUDA_VISIBLE_DEVICES=0 text-generation-launcher --model-id .... # run on GPU-0
CUDA_VISIBLE_DEVICES=0,3 text-generation-launcher --model-id ... --num-shard 2 # shard on GPU-0 and GPU-3
```

**Comment by ZaDarkSide** [comment]
Thank you very much, I missed this env var when looking at the code.

**Comment by OlivierDehaene** [comment]
It's not really part of text-generation-inference, it's an env var that is used by all machine learning frameworks. 
I will make the documentation clearer.
