### ISSUE TITLE
cli arguments max-input-length, max-total-tokens, max-batch-prefill-tokens result in crash

### ISSUE THREAD

**Issue by andysalerno** [huggingface/text-generation-inference#1572]
### System Info

I want to run an instance that can handle 1 concurrent request, using a model with a max context length of 8092.

Given the description of the args [here](https://github.com/huggingface/text-generation-inference/blob/4139054b82c7eedefcb401400d5ba4172a960ecc/launcher/src/main.rs#L124C1-L124C14) this should be pretty simple:

```
    /// The maximum amount of concurrent requests for this particular deployment.
    /// Having a low limit will refuse clients requests instead of having them
    /// wait for too long and is usually good to handle backpressure correctly.
    #[clap(default_value = "128", long, env)]
    max_concurrent_requests: usize,

    ...

    /// This is the most important value to set as it defines the "memory budget"
    /// of running clients requests.
    /// Clients will send input sequences and ask to generate `max_new_tokens`
    /// on top. with a value of `1512` users can send either a prompt of
    /// `1000` and ask for `512` new tokens, or send a prompt of `1` and ask for
    /// `1511` max_new_tokens.
    /// The larger this value, the larger amount each request will be in your RAM
    /// and the less effective batching can be.
    #[clap(default_value = "2048", long, env)]
    max_total_tokens: usize,
```

So I launch with `--max-concurrent-requests 1 --max-total-tokens 8092`.

Spawning the server with these options is **successful** but inference does **not** allow requests up to 8092 tokens (by design I suppose):

```
chat_completions:generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, frequency_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: true, max_new_tokens: Some(256), return_full_text: None, stop: [], truncate: None, watermark: false, details: true, decoder_input_details: true, seed: Some(42), top_n_tokens: None, grammar: None }}:generate:generate_stream: text_generation_router::infer: router/src/infer.rs:123: `inputs` must have less than 1024 tokens. Given: 1099
```

Apparently there's another parameter, `--max-input-length`, that defaults to 1024, so it must also be set.

So now I launch the instance with

`--max-total-tokens 8092 --max-input-length 8091`

Spawning the server with these options is **fails** (by design I suppose) with:
```
Error: ArgumentValidation("`max_batch_prefill_tokens` must be >= `max_input_length`. Given: 4096 and 8091")
```

Ok, so there's a *third* option `--max-batch-prefill-tokens` . Now I launch with:

`--max-total-tokens 8092 --max-batch-prefill-tokens 8092 --max-input-length 8091`.

Spawning the server with these options is **fails (not by design??)** with:

```
2024-02-18T20:14:16.034183Z  INFO text_generation_router: router/src/main.rs:291: Warming up model
2024-02-18T20:14:16.546446Z ERROR warmup{max_input_length=8091 max_prefill_tokens=8092 max_total_tokens=8092 max_batch_size=None}:warmup: text_generation_client: router/client/src/lib.rs:33: Server error: transport error
Error: Warmup(Generation("transport error"))
2024-02-18T20:14:16.607534Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [114,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
CUDA Error: device-side assert triggered /usr/src/flash-attention/csrc/layer_norm/ln_fwd_kernels.cuh 236 rank=0
```

I am running the latest Docker image with this launch settings:
```
    image: ghcr.io/huggingface/text-generation-inference:latest
    Args { model_id: "argilla/CapybaraHermes-2.5-Mistral-7B", revision: Some("a776472481d5b55241996bb9e729ba116b95958c"), validation_workers: 1, sharded: None, num_shard: None, quantize: Some(Eetq), speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 2, max_best_of: 1, max_stop_sequences: 4, max_top_n_tokens: 1, max_input_length: 8091, max_total_tokens: 8092, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 8092, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "80a1f4638f49", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }
```

**Note I am using EETQ quantization which may be relevant here?**

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Args { model_id: "argilla/CapybaraHermes-2.5-Mistral-7B", revision: Some("a776472481d5b55241996bb9e729ba116b95958c"), validation_workers: 1, sharded: None, num_shard: None, quantize: Some(Eetq), speculate: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 2, max_best_of: 1, max_stop_sequences: 4, max_top_n_tokens: 1, max_input_length: 8091, max_total_tokens: 8092, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 8092, max_batch_total_tokens: None, max_waiting_tokens: 20, max_batch_size: None, enable_cuda_graphs: false, hostname: "80a1f4638f49", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, tokenizer_config_path: None, disable_grammar_support: false, env: false }

### Expected behavior

The server should launch.

**Comment by prashantsolanki975** [comment]
Any updates on this ?

**Comment by kerthcet** [comment]
can you reproduce this? @prashantsolanki975
