### ISSUE TITLE
supporting LoRA checkpoint?

### ISSUE THREAD

**Issue by deep-diver** [huggingface/text-generation-inference#158]
I only see `model_id` to be specified. For the model with LoRA checkpoint, how can I specify LoRA checkpoint id(on HF Hub)?

**Comment by OlivierDehaene** [comment]
Hello!
This is not supported at the moment but it is something we will be working on in the coming weeks.

**Comment by deep-diver** [comment]
Sounds good! Looking forward to it 😀

**Comment by zhxgj** [comment]
We tried to merge the LoRA adaptor with the base model and saved the merged standalone model using the [merge_and_unload](https://github.com/huggingface/peft/blob/189a6b8e357ecda05ccde13999e4c35759596a67/src/peft/tuners/lora.py#L393) function. But the standalone model cannot be served. Do you have any idea how should the merged standalone be correctly served?

**Comment by sam-h-bean** [comment]
@OlivierDehaene any update on supporting fine-tuned lora matrices along with an llm backbone? I have a small additional feature request which would be to support many lora matrices with the ability to "hot swap" them based on characteristics of the request ie. different clients could be served with different loras.
