### ISSUE TITLE
OpenAI API: {"error":"Template error: template not found","error_type":"template_error"}

### ISSUE THREAD

**Issue by Rysias** [huggingface/text-generation-inference#1593]
### System Info

TGI Version: 1.4 (Docker)
Model Info: {
  "model_id": "TheBloke/Llama-2-7B-Chat-GPTQ",
  "model_sha": "d5ad9310836dd91b6ac6133e2e47f47394386cea",
  "model_dtype": "torch.float16",
  "model_device_type": "cuda",
  "model_pipeline_tag": "text-generation",
  "max_concurrent_requests": 128,
  "max_best_of": 2,
  "max_stop_sequences": 4,
  "max_input_length": 1024,
  "max_total_tokens": 2048,
  "waiting_served_ratio": 1.2,
  "max_batch_total_tokens": 20544,
  "max_waiting_tokens": 20,
  "max_batch_size": null,
  "validation_workers": 2,
  "version": "1.4.2",
  "sha": "9c1cb81cd8fc01c8f736c554f316ba42b0695717",
  "docker_label": "sha-9c1cb81"
}
Hardware: Tesla T4  (CUDA 12.2)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Run the below setup:
```bash
model=TheBloke/Llama-2-7B-Chat-GPTQ
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.4 --model-id $model --quantize gptq
```
2. Run the following command (from the docks):
```json
curl localhost:8080/v1/chat/completions \
    -X POST \
    -d '{
  "model": "tgi",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "What is deep learning?"
    }
  ],
  "stream": true,
  "max_tokens": 20
}' \
    -H 'Content-Type: application/json'
```

### Expected behavior

Some response, but instead I get the error: {"error":"Template error: template not found","error_type":"template_error"}. This is the same behaviour I get from running it using the OpenAI python library.

**Comment by 9876691** [comment]
See https://github.com/huggingface/text-generation-inference/issues/1545

**Comment by Rysias** [comment]
Thanks, I'll follow that:))
