### ISSUE TITLE
low temperature generated_text error

### ISSUE THREAD

**Issue by simplzyu** [huggingface/text-generation-inference#1602]
### System Info

tgi: 1.0.3 or 1.4.0
python: 3.10
pytorch: 2.0.1

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

text-generation-launcher --model-id deepseek-coder-33b-instruct --max-input-length 3000 --max-total-tokens 4096 --port 8001 --dtype float16

post parameter：
{
    "inputs": "You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer\n### Instruction:\n你好\n### Response:\n",
    "parameters": {
        "temperature": 0.0001,
        "max_new_tokens": 20,
        "do_sample": false,
        "repetition_penalty": 1.0,
        "presence_penalty": null,
        "top_k": 1
    }
}

1. result always generate '!' 
{
    "generated_text": "!!!!!!!!!!!!!!!!!!!!"
}

when temperature >= 0.001，the result is right

### Expected behavior

when temperature is too low, i hope the result is ok

@Narsil

**Comment by jiangix-paper** [comment]
I have the same error. Can you help it ? Thanks a lot. @OlivierDehaene

**Comment by simplzyu** [comment]
have been solved

**Comment by zju-lz** [comment]
> ### System Info
> tgi: 1.0.3 or 1.4.0 python: 3.10 pytorch: 2.0.1
> 
> ### Information
> * [ ]  Docker
> * [ ]  The CLI directly
> 
> ### Tasks
> * [ ]  An officially supported command
> * [ ]  My own modifications
> 
> ### Reproduction
> text-generation-launcher --model-id deepseek-coder-33b-instruct --max-input-length 3000 --max-total-tokens 4096 --port 8001 --dtype float16
> 
> post parameter： { "inputs": "You are an AI programming assistant, utilizing the Deepseek Coder model, developed by Deepseek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer\n### Instruction:\n你好\n### Response:\n", "parameters": { "temperature": 0.0001, "max_new_tokens": 20, "do_sample": false, "repetition_penalty": 1.0, "presence_penalty": null, "top_k": 1 } }
> 
> 1. result always generate '!'
>    {
>    "generated_text": "!!!!!!!!!!!!!!!!!!!!"
>    }
> 
> when temperature >= 0.001，the result is right
> 
> ### Expected behavior
> when temperature is too low, i hope the result is ok
> 
> @Narsil
