### ISSUE TITLE
Difference between docker image v1.4.3 and latest image

### ISSUE THREAD

**Issue by nguyenhoanganh2002** [huggingface/text-generation-inference#1612]
### System Info

tgi v1.4.3, latest

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

Run docker with TGI image v1.4.3 got Could not import FlashAttention, Cuda is not available, latest image isn't

### Expected behavior

Explain the difference between them
docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.4.3 --model-id /data/vistral_v2 --num-shard 1 --max-input-length 1536

docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id /data/vistral_v2 --num-shard 1 --max-input-length 1536

**Comment by OlivierDehaene** [comment]
Can you add `--pull always`?

```shell
docker run --gpus all --shm-size 1g --pull always -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id /data/vistral_v2 --num-shard 1 --max-input-length 1536
```
