### ISSUE TITLE
How to use the grammar support feature?

### ISSUE THREAD

**Issue by Stealthwriter** [huggingface/text-generation-inference#1615]
### Feature request

![image](https://github.com/huggingface/text-generation-inference/assets/126798556/74279ba2-3df8-4abd-8b7b-5459a5f209ec)

Can you please clarify how we can use this? what is it for?

### Motivation

![image](https://github.com/huggingface/text-generation-inference/assets/126798556/74279ba2-3df8-4abd-8b7b-5459a5f209ec)

Can you please clarify how we can use this? what is it for?

### Your contribution

![image](https://github.com/huggingface/text-generation-inference/assets/126798556/74279ba2-3df8-4abd-8b7b-5459a5f209ec)

Can you please clarify how we can use this? what is it for?

**Comment by drbh** [comment]
Hi @Stealthwriter grammar support allows callers to specify a grammar that will be used to constrain the generated text, (for example output a specific JSON format). Please see https://huggingface.co/docs/text-generation-inference/conceptual/guidance for more details
