### ISSUE TITLE
ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

### ISSUE THREAD

**Issue by coder-xieshijie** [huggingface/text-generation-inference#1620]
### System Info

FROM ghcr.io/huggingface/text-generation-inference:sha-7dbaf9e

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

I built a tgi image myself. The specific dockerfile is as follows: 
```
FROM ghcr.io/huggingface/text-generation-inference:sha-7dbaf9e

# Set the environment variable for PyTorch CUDA Allocator configuration
ENV PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
```
When I use this built image to load starcoder2-15b, the error is:
```
ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```
My command to start the model in the image is as follows:
```
text-generation-launcher --model-id starcoder2-15b_path --port 6006 --num-shard 1 --max-input-length 8000 --max-total-tokens 12000 --max-batch-prefill-tokens 12000 --disable-custom-kernels --cuda-memory-fraction 0.9
```
It is worth noting that for the same image, when I start starcoder1-15b, it is normal, but when I start starcoder2-15b, it fails. The full error message is as follows:
```

2024-03-04 10:54:22 | 2024-03-04T02:54:22.500277Z  INFO text_generation_launcher: Shutting down shards
-- | --
  |   | 2024-03-04 10:54:22 | 2024-03-04T02:54:22.500258Z ERROR text_generation_launcher: Shard 0 failed to start
  |   | 2024-03-04 10:54:22 | rank=0
  |   | 2024-03-04 10:54:22 | ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | raise ValueError(
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1119, in from_pretrained
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | config, kwargs = AutoConfig.from_pretrained(
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | model = AutoModelForCausalLM.from_pretrained(
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 509, in __init__
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | return CausalLM(
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 458, in get_model
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | model = get_model(
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | return future.result()
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | return loop.run_until_complete(main)
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | asyncio.run(
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | server.serve(
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | sys.exit(app())
  |   | 2024-03-04 10:54:22 | File "/opt/conda/bin/text-generation-server", line 8, in <module>
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | Traceback (most recent call last):
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | During handling of the above exception, another exception occurred:
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | KeyError: 'starcoder2'
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | raise KeyError(key)
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | config_class = CONFIG_MAPPING[config_dict["model_type"]]
  |   | 2024-03-04 10:54:22 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | Traceback (most recent call last):
  |   | 2024-03-04 10:54:22 | warn("The installed version of bitsandbytes was compiled without GPU support. "
  |   | 2024-03-04 10:54:22 | /opt/conda/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  |   | 2024-03-04 10:54:22 | return torch._C._cuda_getDeviceCount() > 0
  |   | 2024-03-04 10:54:22 | /opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449201336/work/c10/cuda/CUDAFunctions.cpp:108.)
  |   | 2024-03-04 10:54:22 |  
  |   | 2024-03-04 10:54:22 | 2024-03-04T02:54:22.401312Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:
  |   | 2024-03-04 10:54:21 |  
  |   | 2024-03-04 10:54:21 | ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
  |   | 2024-03-04 10:54:21 | raise ValueError(
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1119, in from_pretrained
  |   | 2024-03-04 10:54:21 | config, kwargs = AutoConfig.from_pretrained(
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
  |   | 2024-03-04 10:54:21 | model = AutoModelForCausalLM.from_pretrained(
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 509, in __init__
  |   | 2024-03-04 10:54:21 | return CausalLM(
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 458, in get_model
  |   | 2024-03-04 10:54:21 | model = get_model(
  |   | 2024-03-04 10:54:21 | > File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
  |   | 2024-03-04 10:54:21 | self._context.run(self._callback, *self._args)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
  |   | 2024-03-04 10:54:21 | handle._run()
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
  |   | 2024-03-04 10:54:21 | self._run_once()
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
  |   | 2024-03-04 10:54:21 | self.run_forever()
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
  |   | 2024-03-04 10:54:21 | return loop.run_until_complete(main)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
  |   | 2024-03-04 10:54:21 | asyncio.run(
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
  |   | 2024-03-04 10:54:21 | server.serve(
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
  |   | 2024-03-04 10:54:21 | return callback(**use_params)  # type: ignore
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
  |   | 2024-03-04 10:54:21 | return __callback(*args, **kwargs)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
  |   | 2024-03-04 10:54:21 | return ctx.invoke(self.callback, **ctx.params)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
  |   | 2024-03-04 10:54:21 | return _process_result(sub_ctx.command.invoke(sub_ctx))
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
  |   | 2024-03-04 10:54:21 | rv = self.invoke(ctx)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
  |   | 2024-03-04 10:54:21 | return _main(
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
  |   | 2024-03-04 10:54:21 | return self.main(*args, **kwargs)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
  |   | 2024-03-04 10:54:21 | return get_command(self)(*args, **kwargs)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
  |   | 2024-03-04 10:54:21 | sys.exit(app())
  |   | 2024-03-04 10:54:21 | File "/opt/conda/bin/text-generation-server", line 8, in <module>
  |   | 2024-03-04 10:54:21 | Traceback (most recent call last):
  |   | 2024-03-04 10:54:21 |  
  |   | 2024-03-04 10:54:21 | During handling of the above exception, another exception occurred:
  |   | 2024-03-04 10:54:21 |  
  |   | 2024-03-04 10:54:21 | KeyError: 'starcoder2'
  |   | 2024-03-04 10:54:21 | raise KeyError(key)
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
  |   | 2024-03-04 10:54:21 | config_class = CONFIG_MAPPING[config_dict["model_type"]]
  |   | 2024-03-04 10:54:21 | File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
  |   | 2024-03-04 10:54:21 | Traceback (most recent call last):
  |   | 2024-03-04 10:54:21 | 2024-03-04T02:54:21.674963Z ERROR text_generation_launcher: Error when initializing model
```

### Expected behavior

I hope to start starcoder2-15b normally through tgi, I ask for help, thank you very much

**Comment by coder-xieshijie** [comment]
I saw that pr already supports starcoder2, and the docker image I downloaded is also the latest, but I don’t know why the deployment of starcoder2 still failed.

**Comment by suyashhchougule** [comment]
@coder-xieshijie  
Uninstall the current version of the transformer and reinstall it from the source. 
i.e. 
`pip install git+https://github.com/huggingface/transformers.git
`

**Comment by OlivierDehaene** [comment]
I think the problem is your cuda driver version:

```
  |   | 2024-03-04 10:54:22 | /opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449201336/work/c10/cuda/CUDAFunctions.cpp:108.)
```

**Comment by coder-xieshijie** [comment]
> I think the problem is your cuda driver version:
> 
> ```
>   |   | 2024-03-04 10:54:22 | /opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449201336/work/c10/cuda/CUDAFunctions.cpp:108.)
> ```

@OlivierDehaene 

This is my docker image running log.
```
2024-03-04 10:41,INFO[0000] Retrieving image manifest ghcr.io/huggingface/text-generation-inference:sha-7dbaf9e 
2024-03-04 10:41,INFO[0000] Retrieving image ghcr.io/huggingface/text-generation-inference:sha-7dbaf9e from registry ghcr.io 
2024-03-04 10:41,INFO[0002] Built cross stage deps: map[]                
2024-03-04 10:41,INFO[0002] Retrieving image manifest ghcr.io/huggingface/text-generation-inference:sha-7dbaf9e 
2024-03-04 10:41,INFO[0002] Returning cached image manifest              
2024-03-04 10:41,INFO[0002] Executing 0 build triggers                   
2024-03-04 10:41,INFO[0002] Building stage 'ghcr.io/huggingface/text-generation-inference:sha-7dbaf9e' [idx: '0', base-idx: '-1'] 
2024-03-04 10:41,INFO[0002] Skipping unpacking as no commands require it. 
2024-03-04 10:41,INFO[0002] ENV PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
```
 I completely inherited it from the latest tgi image. The theoretical cuda version is also completely inherited from this image. I saw that tgi’s dockerfile file has a cuda version description from https://github.com/huggingface/text-generation-inference/blob/main/Dockerfile
```
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04 as pytorch-install

ARG PYTORCH_VERSION=2.1.1
ARG PYTHON_VERSION=3.10
# Keep in sync with `server/pyproject.toml
ARG CUDA_VERSION=12.1
ARG MAMBA_VERSION=23.3.1-1
ARG CUDA_CHANNEL=nvidia
ARG INSTALL_CHANNEL=pytorch
# Automatically set by buildx
ARG TARGETPLATFORM
```
 Is this version outdated?

**Comment by OlivierDehaene** [comment]
The driver version is related to your host running the container, not the docker image.

**Comment by HitSakhavala** [comment]
I'm facing the same issue but I do not have any error/warning related to GPU(except FlashAttantion).
here the logs, can you help me why it is failing?

Docker Image: ghcr.io/huggingface/text-generation-inference
model: bigcode/starcoder2-15b
also i'm quantizing the model using `--quantize bitsandbytes-fp4 `.

>   2024-03-05T11:55:52.160985Z  INFO download: text_generation_launcher: Starting download process.
    2024-03-05T11:55:59.440544Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

    2024-03-05T11:56:00.071391Z  INFO download: text_generation_launcher: Successfully downloaded weights.
    2024-03-05T11:56:00.071643Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
    2024-03-05T11:56:08.165844Z  WARN text_generation_launcher: Unable to use Flash Attention V2: GPU with CUDA capability 7 5 is not supported for Flash Attention V2

    2024-03-05T11:56:09.068702Z ERROR text_generation_launcher: Error when initializing model
    Traceback (most recent call last):
    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
        config_class = CONFIG_MAPPING[config_dict["model_type"]]
    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
        raise KeyError(key)
    KeyError: 'starcoder2'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/opt/conda/bin/text-generation-server", line 8, in <module>
        sys.exit(app())
    File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
        return get_command(self)(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
        return _main(
    File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
        rv = self.invoke(ctx)
    File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
    File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
        return callback(**use_params)  # type: ignore
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
        server.serve(
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
        asyncio.run(
    File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)
    File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
        self.run_forever()
    File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
        self._run_once()
    File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
        handle._run()
    File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
    > File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
        model = get_model(
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 458, in get_model
        return CausalLM(
    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 509, in __init__
        model = AutoModelForCausalLM.from_pretrained(
    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
        config, kwargs = AutoConfig.from_pretrained(
    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1119, in from_pretrained
        raise ValueError(
    ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

    2024-03-05T11:56:09.984085Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

    Traceback (most recent call last):

    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
        config_class = CONFIG_MAPPING[config_dict["model_type"]]

    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
        raise KeyError(key)

    KeyError: 'starcoder2'


    During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

    File "/opt/conda/bin/text-generation-server", line 8, in <module>
        sys.exit(app())

    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
        server.serve(

    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 235, in serve
        asyncio.run(

    File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
        return loop.run_until_complete(main)

    File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()

    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 196, in serve_inner
        model = get_model(

    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/__init__.py", line 458, in get_model
        return CausalLM(

    File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/causal_lm.py", line 509, in __init__
        model = AutoModelForCausalLM.from_pretrained(

    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
        config, kwargs = AutoConfig.from_pretrained(

    File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1119, in from_pretrained
        raise ValueError(

    ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
    rank=0
    2024-03-05T11:56:10.083000Z ERROR text_generation_launcher: Shard 0 failed to start
    2024-03-05T11:56:10.083033Z  INFO text_generation_launcher: Shutting down shards

**Comment by coder-xieshijie** [comment]
> The driver version is related to your host running the container, not the docker image.

Thank you for your opinion, I will give it a try and will get back to you with the results.

**Comment by BinBrent** [comment]
> @coder-xieshijie Uninstall the current version of the transformer and reinstall it from the source. i.e. `pip install git+https://github.com/huggingface/transformers.git `

It worked. "Successfully installed transformers-4.39.0.dev0", the transformers version matters
