### ISSUE TITLE
Multi-lora support

### ISSUE THREAD

**Issue by shikungo** [huggingface/text-generation-inference#1622]
### Model description

I have been using text generation reference for some time and found that TGI does not support multi lora mode. Currently, the latest version of vllm already supports multi lora. When can TGI support it?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available

**Comment by joaomsimoes** [comment]
x2

**Comment by thincal** [comment]
> This is definitely on our roadmap and will be tackled in the coming weeks. Here are the priorities right now:
> 
> 1. re-write the scheduling code and cache multi-turn conversations. This will have a huge impact on latency and throughput.
> 2. better support for grammar/tools
> 3. multi-modal
> 4. mulit loras
> 
> All of this will land in the coming month.
> 
> What are your use case for multi-loras btw? We are wondering if we should support them on the api-inference free tier.

@OlivierDehaene Amazing for this plan, and is there any concrete roadmap for production ready multi-lora support ?

**Comment by yb01** [comment]
Any update on this feature request?

**Comment by flozi00** [comment]
> Any update on this feature request?

https://github.com/huggingface/text-generation-inference/issues/1819#issuecomment-2127895659

If the tgi team wants so I could start with it

**Comment by NielsRogge** [comment]
This is WIP, progress can be seen at https://github.com/huggingface/text-generation-inference/pull/2010

**Comment by SMAntony** [comment]
> This is definitely on our roadmap and will be tackled in the coming weeks. Here are the priorities right now:
> 
>     1. re-write the scheduling code and cache multi-turn conversations. This will have a huge impact on latency and throughput.
> 
>     2. better support for grammar/tools
> 
>     3. multi-modal
> 
>     4. mulit loras
> 
> 
> All of this will land in the coming month.
> 
> What are your use case for multi-loras btw? We are wondering if we should support them on the api-inference free tier.

Hi, for us, we are using multiple fine-tuned lora adapters and are currently using transformers to implement the same. Multi-loras being supported by TGI would make a huge difference in latency and throughput.

**Comment by NielsRogge** [comment]
Looks like this issue can be closed as #2010 is now merged.

**Comment by thincal** [comment]
About the multi-Lora support, it seems that the Lora adapters should better preloaded explicitly when tgi starting up, then invoke with a specific id to specify which Lora be using. But if there are new Lora joined, need deploy new tgi instances containing this new Lora?
