### ISSUE TITLE
Failed when requesting generate_stream api with Qwen2 concurrently.

### ISSUE THREAD

**Issue by yangelaboy** [huggingface/text-generation-inference#1623]
### System Info

{
  "model_id": "/home/work/models/Qwen2_7b",
  "model_sha": null,
  "model_dtype": "torch.float16",
  "model_device_type": "cuda",
  "model_pipeline_tag": null,
  "max_concurrent_requests": 128,
  "max_best_of": 2,
  "max_stop_sequences": 4,
  "max_input_length": 2400,
  "max_total_tokens": 3000,
  "waiting_served_ratio": 0.5,
  "max_batch_total_tokens": 8192,
  "max_waiting_tokens": 16000,
  "max_batch_size": null,
  "validation_workers": 2,
  "version": "1.4.3",
  "sha": "e6bb3ff81fd670ad2f54904676f8165367dd47f8",
  "docker_label": "sha-e6bb3ff"
}

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1.start tgi with Qwen2-7B
2.concurrently request generate_stream api

### Expected behavior

success is expected, but get error:
![image](https://github.com/huggingface/text-generation-inference/assets/16263873/e435528b-74ce-4360-976b-e9bb046c9b14)

@Jason-CKY need your help, thx!

**Comment by yangelaboy** [comment]
when starting Qwen2-7B with flash_qwen2_modeling of tgi， but get error:
![image](https://github.com/huggingface/text-generation-inference/assets/16263873/16618dc5-9d0e-401c-b37f-8bedea647c6a)

**Comment by Jason-CKY** [comment]
Seems weird, Qwen2-7B has the specific weight key in [here](https://huggingface.co/Qwen/Qwen1.5-7B/blob/main/model.safetensors.index.json#L7)

**Comment by OlivierDehaene** [comment]
Did you save this model manually?
