### ISSUE TITLE
Support stop sequences for Messages API

### ISSUE THREAD

**Issue by gopalsarda** [huggingface/text-generation-inference#1631]
### Feature request

Thank you for the great work around enabling [Messages API](https://huggingface.co/docs/text-generation-inference/en/messages_api) and [Chat templating](https://huggingface.co/docs/transformers/main/en/chat_templating). This prevents a lot of code  duplication and the bugs that come with it. 

Is there a plan to support stop sequences (available as `parameters.stop` in `generate` api) as part of the Messages API? The parameter is available for the [Open AI Chat Completion API](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stop)

### Motivation

Stop sequences is an important feature needed to enable users to transition seamlessly from OpenAI models to open LLMs 

### Your contribution

I am not familiar with the code base but with some guidance, I can help submitting a PR

**Comment by drbh** [comment]
Hi @gopalsarda the `stop` sequence has been added in this PR https://github.com/huggingface/text-generation-inference/pull/1619 and is available on main, thanks for opening the issues 🙏
