### ISSUE TITLE
ExllamaV2 continuous batching supported?

### ISSUE THREAD

**Issue by SinanAkkoyun** [huggingface/text-generation-inference#1634]
### Feature request

This is just a question (if no, then it is a request):
Does Exllama V2 support have continuous batching? That's the only thing I find missing in all Exllama backends

### Motivation

better servability

### Your contribution

I tried to work on continuous batching at the exl2 repo but I couldn't get it to work

**Comment by clintonruairi** [comment]
also interested in the above @SinanAkkoyun if we could get this it would be great for scalable production inferencing

**Comment by SinanAkkoyun** [comment]
I think vLLM is trying to implement that
