### ISSUE TITLE
Unable to use '--rope-scaling yarn' option

### ISSUE THREAD

**Issue by calycekr** [huggingface/text-generation-inference#1649]
### Bug Report
PR: Adding yarn support
https://github.com/huggingface/text-generation-inference/pull/1099
We can find 'yarn' for rope_scaling type.
`elif rope_scaling["type"] == "yarn":`

But, there is no yarn in possible values in the tgi launcher.

```
error: invalid value 'yarn' for '--rope-scaling <ROPE_SCALING>'
[possible values: linear, dynamic]
```

No yarn support in this file.
https://github.com/huggingface/text-generation-inference/blob/23fba672e8156ce19cc518470a5452a9543c56b9/launcher/src/main.rs#L107-L119

#1320
#1382 

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Use '--rope-scaling yarn' option.

### Expected behavior

Support yarn option.

**Comment by rjmehta1993** [comment]
@calycekr Still same issue using tgi 3.0

(exl19) [ec2-user@ip-172-31-22-171 .gccc]$ docker run --gpus all --shm-size 1g -p 8080:80 \
>     -v $LOCAL_MODEL_PATH:/model \
>     -v $PWD/data:/data \
>     ghcr.io/huggingface/text-generation-inference:3.0.1 \
>     --model-id /model \
>     --max-total-tokens 65536 \
>     --max-batch-prefill-tokens $max_chunk_size \
>     --max-batch-total-tokens $max_attention_size \
>     --max-batch-size $batch_size \
>     --max-concurrent-requests 128 \
>     --cuda-memory-fraction 1.0 \
>     --trust-remote-code \
>     --num-shard 4 \
>     --rope-scaling 'yarn' \
>     --rope-factor 2.0
error: invalid value 'yarn' for '--rope-scaling <ROPE_SCALING>'
  [possible values: linear, dynamic]

For more information, try '--help'.
