### ISSUE TITLE
how to get the latest version number?

### ISSUE THREAD

**Issue by fancyerii** [huggingface/text-generation-inference#1677]
In the document, I use "docker run ghcr.io/huggingface/text-generation-inference:latest" to run the latest version of tgi. But in a production environment, I need to fix the version number. I can't find any webpage similar to [docker hub](https://hub.docker.com/r/pytorch/manylinux-cuda102). So how can I use docker command line to get the version list of huggingface/text-generation-inference?

**Comment by feifan-sun** [comment]
You can see it here: https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference

**Comment by spew** [comment]
You can use the github API to get the list of available releases and then assume the associated docker image is avialable.

**Comment by fancyerii** [comment]
> You can see it here: https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference

thanks.
