### ISSUE TITLE
Does text-generation-inference support macOS M1/M2(mps)?

### ISSUE THREAD

**Issue by danny-su** [huggingface/text-generation-inference#1683]
### Feature request

Screenshot from the documentation:
<img width="956" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/12178855/5e66cf0b-d447-4b29-b591-2c99b0428f17">

But I found it can't be built on macOS, and even if I modified the Makefile of the text-generation-server project and built it, it couldn't run successfully. I got an error; it seems that CUDA is a must:
<img width="1067" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/12178855/00a637b1-eec8-4bbe-83bf-ccaf18887f4b">

### Motivation

Run on macOS locally.

### Your contribution

N/A

**Comment by ArthurZucker** [comment]
cc @Narsil I can't transfer to `text-generation-inference`.
