### ISSUE TITLE
Support for Command-R models (by Cohere.AI)

### ISSUE THREAD

**Issue by calycekr** [huggingface/text-generation-inference#1684]
### Model description

https://huggingface.co/CohereForAI/c4ai-command-r-v01

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/CohereForAI/c4ai-command-r-v01

**Comment by huanhuanlaoda** [comment]
Why is the implementation of TGI Cohere Modeling different from the Transformers Cohere Modeling?
Is there any different version of Command-R models?

**Comment by OlivierDehaene** [comment]
It is already supported.

**Comment by 2016bgeyer** [comment]
@OlivierDehaene 

Does the supported models page need to be updated then?

https://huggingface.co/docs/text-generation-inference/supported_models
