### ISSUE TITLE
Couldn't instantiate the backend tokenizer

### ISSUE THREAD

**Issue by MohamedAliRashad** [huggingface/text-generation-inference#169]
I am unable to run the docker command with the title error
```
docker run --gpus all --shm-size 1g -p 8080:80 -v /home/mohamedr/cache:/data ghcr.io/huggingface/text-generation-inference:latest --model-id Tribbiani/vicuna-7b  --num-shard 1 --max-total-tokens 2048
```

how to fix the problem ?

**Comment by OlivierDehaene** [comment]
What's the error? Can you use `0.5.0` instead of `latest`? 
I'm unable to reproduce on my end.

**Comment by MohamedAliRashad** [comment]
@OlivierDehaene 

```bash
ValueError: Couldn't instantiate the backend tokenizer from one of: 
(1) a `tokenizers` library serialization file, 
(2) a slow tokenizer instance to convert or 
(3) an equivalent slow tokenizer class to instantiate and convert. 
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
```

**Comment by OlivierDehaene** [comment]
`docker run --gpus all --shm-size 1g -p 8080:80 -v /home/mohamedr/cache:/data ghcr.io/huggingface/text-generation-inference:0.5.0 --model-id Tribbiani/vicuna-7b  --num-shard 1 --max-total-tokens 2048`

**Comment by MohamedAliRashad** [comment]
@OlivierDehaene 
Still the same error

**Comment by OlivierDehaene** [comment]
Can you clear your model cache (in `/home/mohamedr/cache`) and re-try?

**Comment by MohamedAliRashad** [comment]
@OlivierDehaene 
Still the same problem

**Comment by MohamedAliRashad** [comment]
@OlivierDehaene 
It now gives me this error:
```
ModuleNotFoundError: No module named 'einops'
```

**Comment by MohamedAliRashad** [comment]
It worked somehow in the new versions
