### ISSUE TITLE
Support exllamav2 (exl2) quantized models models

### ISSUE THREAD

**Issue by sapountzis** [huggingface/text-generation-inference#1694]
### Feature request

Add support for exl2 quantization format via argument --quantization exl2 which will allow to load exllamav2 quantized models with various quantization schemes (not GPTQ).

### Motivation

There are lots of models on HF which are only offered in either F16 of exl2 format. Our use case particularly concerns role playing fine tuned models with domain specific calibration set.
The throughput and output quality difference between bitsandbytes nf4 and exllamav2 calibrated quantization is significant from our testing.

Implementing support for exl2 quantized models will increase the adoption of TGI as a serving framework.

**Comment by Narsil** [comment]
> There are lots of models on HF which are only offered in either F16 of exl2 format

Could you point to some ?

Exl2 is definitely on our todo list with Marlin.

**Comment by sapountzis** [comment]
@Narsil for example these models:

https://huggingface.co/LoneStriker
https://huggingface.co/zaq-hack

**Comment by sapountzis** [comment]
@Narsil Is there any way to contribute to accelerate progress of implementing this?

**Comment by RonanKMcGovern** [comment]
> > There are lots of models on HF which are only offered in either F16 of exl2 format
> 
> Could you point to some ?
> 
> Exl2 is definitely on our todo list with Marlin.

Yeah I think Marlin makes sense because the kernels are much better than AWQ, making it much faster (close to fp16).
