### ISSUE TITLE
AsyncInferenceClient - Unclosed client session

### ISSUE THREAD

**Issue by mhillebrand** [huggingface/text-generation-inference#1701]
I'm using TGI with Flan-T5 to process thousands of text extraction requests at a time, on a 4 x A6000 machine. My client class, which uses `AsyncInferenceClient`, can handle 900 requests at once, but when I try to process 1,000 at once, I receive this error:

```
Traceback (most recent call last):
  File "/home/matt/miniconda3/envs/vllm/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/vllm/lib/python3.11/asyncio/base_events.py", line 1086, in create_connection
    raise exceptions[0]
  File "/home/matt/miniconda3/envs/vllm/lib/python3.11/asyncio/base_events.py", line 1070, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/vllm/lib/python3.11/asyncio/base_events.py", line 951, in _connect_sock
    sock = socket.socket(family=family, type=type_, proto=proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matt/miniconda3/envs/vllm/lib/python3.11/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
...
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8003 ssl:default [Too many open files]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe02c2224d0>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe02c292650>
Unclosed client session
...
```

Here's my code:

```python
import asyncio
from huggingface_hub import AsyncInferenceClient

class ExtractorClient:
    def __init__(self):
        self.client = AsyncInferenceClient(model='http://127.0.0.1:8003')

    async def make_requests(self, prompts, temperature, max_new_tokens):
        tasks = [self.client.text_generation(prompt=prompt, temperature=temperature, max_new_tokens=max_new_tokens) for prompt in prompts]
        return await asyncio.gather(*tasks)

    def extract(self, prompts, temperature=0.001, max_new_tokens=512):
        if isinstance(prompts, str):
            prompts = [prompts]

        return asyncio.run(self.make_requests(prompts, temperature, max_new_tokens))
```

Docker bash script:

```bash
docker run \
   --runtime=nvidia --gpus all --shm-size 1g \
   -p 8003:80 \
   -v /opt/extract/model:/model \
   --pull always --rm -d ghcr.io/huggingface/text-generation-inference:1.4.5 \
   --model-id /model/final \
   --num-shard 4 \
   --max-concurrent-requests 4000 \
   --max-input-length 512 \
   --max-batch-total-tokens 3000000 \
   --dtype bfloat16
```

At first, the "Too many open files" error made me think I need to tweak the `ulimit` value in the OS, but Docker is inheriting my `1048576` value for that, I think. Regardless, I tried adding `--ulimit nofile=1048576:1048576` to my docker run script—with no luck.

Does the "Unclosed client session" error mean that I need to use a context manager with `aiohttp.ClientSession` somehow? If so, I'm not sure how to do that with `AsyncInferenceClient`. I tried adding a semaphore like this, but it didn't help:

```python
    async def make_requests(self, prompts, temperature, max_new_tokens):
        async with asyncio.Semaphore(100):
            tasks = [self.client.text_generation(prompt=prompt, temperature=temperature, max_new_tokens=max_new_tokens) for prompt in prompts]
        return await asyncio.gather(*tasks)
```

huggingface-hub==0.22.2
text-generation-inference==1.4.5
aiohttp==3.9.3
python==3.11.8
docker==26.0.0

**Comment by maziyarpanahi** [comment]
> enabled CUDA graphs.

I am really interested in this part, I haven't tried it yet. Overall, are you happy with `CUDA graphs` feature?

**Comment by sapountzis** [comment]
> > enabled CUDA graphs.
> 
> I am really interested in this part, I haven't tried it yet. Overall, are you happy with `CUDA graphs` feature?

When I enabled CUDA graphs my model is producing only <unk> tokens.

Has anyone else come across the issue?

**Comment by OlivierDehaene** [comment]
@sapountzis we had an issue in the past with cuda graphs + quantization. Where you using that by any chance? 
It should be fixed in v2.0.0.

**Comment by sapountzis** [comment]
@OlivierDehaene Yes! I was using bnb + cuda graphs. I will test again with 2.0!

**Comment by sapountzis** [comment]
I got
`{"timestamp":"2024-04-15T09:33:05.710145Z","level":"INFO","fields":{"message":"Bitsandbytes doesn't work with cuda graphs, deactivating them"},"target":"text_generation_launcher"}`

**Comment by OlivierDehaene** [comment]
@sapountzis, we are deprecating bnb in favour of eetq as it is way faster.

@mhillebrand, the "Too many open files" is hapenning for the client so tweaking the container ulimit will have no impact. Are you sure your user doesn't have a lower hard limit? 

```shell 
ulimit -Ha
```
