### ISSUE TITLE
TGI with c4ai GPTQ models

### ISSUE THREAD

**Issue by vitalyshalumov** [huggingface/text-generation-inference#1741]
### System Info

tgi latest docker

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

trying to serve:
alpindale/c4ai-command-r-plus-GPTQ results in :
AssertionError: Tensor-likes are not equal!
Missmatched elements:12160 / 12288

NEURALDEEPTECH/command-r-gptq  or Cyleux/command-r-gptq results in:
"AssertionError ("First input (bf16) and second input (fp32) must have the same dtypes!"

### Expected behavior

served models

**Comment by Narsil** [comment]
Can you show the command you're using ?

Also show all the logs here please, we can't help without actual information and reproducibility.
