### ISSUE TITLE
Template error occurs when using Messages API：{'error': 'Template error: template not found', 'error_type': 'template_error'}

### ISSUE THREAD

**Issue by wz0424** [huggingface/text-generation-inference#1743]
### System Info

tgi 1.4 
port: 80
model: llama2-7B-chat-hf
```
docker run -it -d --gpus '"device='0'"'   --name wz_tgi  --network host --hostname llama-inference         --shm-size 1g   --env LOG_LEVEL="info,text_generation_server=debug"       -v /[huggingface.co/meta-llama/Llama-2-7b-chat-hf:/huggingface.co/meta-llama/Llama-2-7b-chat-hf](http://huggingface.co/meta-llama/Llama-2-7b-chat-hf:/huggingface.co/meta-llama/Llama-2-7b-chat-hf)         ghcr.dockerproxy.com/huggingface/text-generation-inference:1.4         --model-id /[huggingface.co/meta-llama/Llama-2-7b-chat-hf](http://huggingface.co/meta-llama/Llama-2-7b-chat-hf)  --num-shard 1         --max-total-tokens 4096 --max-input-length 2048 --trust-remote-code --max-concurrent-requests 2048 --port 80
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
curl localhost:80/v1/chat/completions     -X POST     -d '{
  "model": "tgi",
  "messages": [
    {
      "role": "user",
      "content": "What is deep learning?"
    }
  ],
  "stream": true,
  "max_tokens": 20
}'     -H 'Content-Type: application/json'
```
return
{'error': 'Template error: template not found', 'error_type': 'template_error'}

### Expected behavior

There is no problem returning results with generate api, but with openai api style it reports template error, can tgi support openai api style similar to vllm?

**Comment by OlivierDehaene** [comment]
Yes it can.

Can you provide all of the logs of the container?

**Comment by wz0424** [comment]
here is the logs of the container，using tgi version 1.4.3
2024-04-15T08:09:20.611961Z ERROR chat_completions: text_generation_router::server: router/src/[server.rs:591](http://server.rs:591/): Template error: template not found
2024-04-15T08:09:26.071854Z ERROR chat_completions: text_generation_router::server: router/src/[server.rs:591](http://server.rs:591/): Template error: template not found

**Comment by drbh** [comment]
Hi @wz0424 I've just tested `meta-llama/Llama-2-7b-chat-hf` with the latest version and got the expected output without error. Would you be able to try a the latest version `2.0.1` was released yesterday 🤗

```bash
docker pull ghcr.io/huggingface/text-generation-inference:2.0.1
```

I hope this helps! please let us know if there are still issues

**Comment by wz0424** [comment]
Thank you for your suggestion. I haven't tested whether it takes effect on the new version yet. On the old version, I have solved this problem by adding chat_template to the tokenizer_config.json file. Adoption of reference #1545
