### ISSUE TITLE
Support HuggingFaceM4/idefics2-8b

### ISSUE THREAD

**Issue by pseudotensor** [huggingface/text-generation-inference#1752]
### Feature request

HuggingFaceM4/idefics2-8b

### Motivation

HF model, expected TGI will support already, but not done yet.

### Your contribution

None.

**Comment by dulacp** [comment]
This can be considered as done thanks to #1756

**Comment by pseudotensor** [comment]
You mean it's supported in TGI but not vLLM?  What's done exactly?

**Comment by dulacp** [comment]
Yes, it's working in TGI, though only for the `/generate` endpoint, not yet on the `/v1/chat/completions` yet (WIP).

I believe you've opened a similar but [separate issue](https://github.com/vllm-project/vllm/issues/4124) in the vLLM repo.
