### ISSUE TITLE
Llama-3 support

### ISSUE THREAD

**Issue by RomanKoshkin** [huggingface/text-generation-inference#1781]
### Feature request

I tried to run LLama-3 on TGI (1.3). The model kind of works, but it doesn't stop at the EOS tokens. I suspect TGI doesn't "understand" Llama-3's new tokenization scheme and prompt template. Please add support for that.

### Motivation

Llama-3 seems to be new state of the art in its weight category.

### Your contribution

Possibly.

**Comment by shuaills** [comment]
There is a mismatch between the tokenizer version used for training weights and the version used for loading?
I am not sure if this is a problem with my weights.
I get this
`Warning: Token '<|reserved_special_token_250|>' was expected to have ID '128255' but was given ID 'None'    
2024-04-21T06:06:48.861440Z  INFO text_generation_router: router/src/main.rs:471: Serving revision 561487d18c41c76bcb5fc6cfb73a324982f04f47 of model meta-llama/Meta-Llama-3-8B`

I tried
`prompt = """<|begin_of_text|>
<|start_header_id|>system<|end_header_id|>
You are a helpful assistant, providing informative and friendly answers to the user.
<|eot_id|>
<|start_header_id|>user<|end_header_id|>
Hello! Can you tell me how tall the Eiffel Tower is?
<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>
The Eiffel Tower is 324 meters tall and is an iconic landmark of Paris. It was built in 1889 and was once the tallest man-made structure in the world. Now, it is one of the most popular tourist attractions in France. The tower is named after its designer, Gustave Eiffel. It was originally constructed for the 1889 Paris World's Fair, showcasing the architectural capabilities of the late 19th century.
<|eot_id|>
<|start_header_id|>user<|end_header_id|>
How many visitors does the Eiffel Tower typically receive in a day? Do I need to book tickets in advance?
<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>"""
`
the response is 
`{'generated_text': "\nThe Eiffel Tower receives around 7 million visitors annually. While you don't need to book tickets in advance, I recommend booking them online to avoid long lines and to guarantee your spot. You can find more information about visiting the Eiffel Tower and booking tickets here: https://www.eiffeltower.paris/en/. If you have any other questions, feel free to ask!\nspNetesModuleGeneratedNetTitle: spnet\nuser pip install spnet\nूडुங투"}`
Which is a bit weird.

**Comment by n-imas** [comment]
I am facing the same issue as @shuaills

**Comment by oroojlooy** [comment]
Same here. It just keeps generating until it gets to its max-gen-limit.

**Comment by axenov** [comment]
It does not work with TGI v1.4 and v 2.0.1 as well.

**Comment by waderwu** [comment]
add stop parameter, it works for me 

```
data = {
    'inputs': prompt,
    'parameters' : {
        'max_new_tokens': 1024,
        'stop': ["<|start_header_id|>", "<|end_header_id|>", "<|eot_id|>", "<|reserved_special_token"]
    }
}
```

**Comment by Narsil** [comment]
Yes, llama3 has 2 eos tokens. eot_id for turn token, and. "real" eos_token (not sure when used).

Currently the config defines `<eos_token>` as the eos token, which if what you're seeing here.

**Comment by sa-** [comment]
Does huggingface still use this image to serve their production models? Is it used by the llama3-70b chat that is currently deployed on https://huggingface.co/chat/ ?

**Comment by Narsil** [comment]
Yes it is. And hf-chat sends that stop token currently.

**Comment by hooman-bayer** [comment]
@Narsil what version of TGI you recommend running Llama-3 models on? We noticed `2.0.1` seems to be a bit slow maybe you recommend earlier versions? We did not investigate much though

**Comment by waderwu** [comment]
> Yes it is. And hf-chat sends that stop token currently.

Why does my local deployment of llama3-70b-instruct perform worse than Hugging Chat when answering the same questions? Hugging Chat can provide correct answers, but my locally deployed version using TGI doesn't work as well.

Could you please tell me the deployment command for hf-chat?

**Comment by huwprosser** [comment]
I got this working by building the image from this blog post:
https://lavaraja-padala.medium.com/deploy-google-gemma-2b-and-gemma-7b-models-on-aws-sagemaker-f441914ccc6f

TGI 2.1.1 seems to be what must be being used internally. Weirdly, HF endpoints seem to be using 2.0.1

**Comment by Narsil** [comment]
Slow ? What do you mean ? What hardware, TP ? What is slow in this case?

**Comment by hooman-bayer** [comment]
Ok, by slow I meant, it was not respecting "Stop" and it was exhausting the `max_tokens` on every request. 

Ok, I did some investigation here, and it seems like it goes crazy when additional parameters beside `temperature` and `top_p` are provided, since it ignores `stop` tokens as well.

If you deployed using TGI v 2.0.1 it works fine but you need to make sure to avoid `presence_penalty` and `frequency_penalty` in your arguments otherwise it confuses the generation. Note that these are often set to `0` based on [OpenAI API](https://platform.openai.com/docs/api-reference/chat/create#chat-create-presence_penalty)

**Comment by Narsil** [comment]
The frequency penalty is being solved soon : https://github.com/huggingface/text-generation-inference/pull/1765.

For the stop token, yes it's unfortunate setup, we're solving changing the default in many places (basically there are 2 stop tokens ..)

**Comment by waderwu** [comment]
> > Yes it is. And hf-chat sends that stop token currently.
> 
> Why does my local deployment of llama3-70b-instruct perform worse than Hugging Chat when answering the same questions? Hugging Chat can provide correct answers, but my locally deployed version using TGI doesn't work as well.
> 
> Could you please tell me the deployment command for hf-chat?

Sorry, I used the wrong interface. Previously, I used 'generate', but after switching to 'v1/chat/completions', it started working normally.

**Comment by mjsteele12** [comment]
> > > Yes it is. And hf-chat sends that stop token currently.
> > 
> > 
> > Why does my local deployment of llama3-70b-instruct perform worse than Hugging Chat when answering the same questions? Hugging Chat can provide correct answers, but my locally deployed version using TGI doesn't work as well.
> > Could you please tell me the deployment command for hf-chat?
> 
> Sorry, I used the wrong interface. Previously, I used 'generate', but after switching to 'v1/chat/completions', it started working normally.

Would you be able to post your settings? I am unable to get llama3 to stop no matter what I try.

**Comment by jatkinson-CRL** [comment]
> add stop parameter, it works for me
> 
> ```
> data = {
>     'inputs': prompt,
>     'parameters' : {
>         'max_new_tokens': 1024,
>         'stop': ["<|start_header_id|>", "<|end_header_id|>", "<|eot_id|>", "<|reserved_special_token"]
>     }
> }
> ```

Great find, thanks for sharing this. This works for me when I include it in the `extra_body` dictionary when using the OpenAI chat completions API w/ a text-generation inference endpoint. 

I am hoping that huggingface could update their documentation though, seems that some documents are out of date or out of sync with the OpenAPI spec. This parameter is documented in the OpenAPI spec here: https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate but it was tough to find this before I came across this solution. The documentation that appears much more frequently when searching for this solutions to this problem is https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task, which does not contain all of the parameters listed in the OpenAPI spec.

**Comment by mohittalele** [comment]
facing same issue
