### ISSUE TITLE
The EETQ quantization model cannot be performed locally

### ISSUE THREAD

**Issue by Gongzai-SURE** [huggingface/text-generation-inference#1805]
### System Info

hardware : 4090
PyTorch  2.1.0 Python  3.10(ubuntu22.04) Cuda  12.1

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

CUDA_VISIBLE_DEVICES=0 text-generation-launcher --model-id 'llama2-7b/llama2-7b-eetq' --num-shard 1 --quantize eetq

The model was quantified by the local EETQ process and saved by the 'save_pretrained()' instruction.

There should be no major problem with the dependencies on my machine, and I can feed the quantized models of gptq and awq into the TGI instruction for inference , only eetq quantized model didn't work.

### Expected behavior

Error 1: cuda does not support 4-bit and 8-bit
![图片](https://github.com/huggingface/text-generation-inference/assets/78643224/0bda91cf-8bdc-4be4-9eb2-00b706a74162)

Error 2: transformers/quantizers/auto.py did not support eetq quantization type
![图片](https://github.com/huggingface/text-generation-inference/assets/78643224/9706b649-b2a5-46d2-a0ef-288c3c532cad)
![图片](https://github.com/huggingface/text-generation-inference/assets/78643224/7f9c606c-027c-4420-a113-c4d4083a707e)

**Comment by dtlzhuangz** [comment]
1. TGI cannot load a quantized eetq model but quantize it after loading the fp16 model. It is tough to load a quantized eetq model in TGI since the quantized weights cannot be concatenated or split owing to the cutlass [preprocess](https://github.com/NetEase-FuXi/EETQ/blob/main/csrc/cutlass_kernels/cutlass_preprocessors.cc#L497). It is possible to save a model by TGI and reuse it.
2. You should use transformers via source code installation.

**Comment by jiajinyu** [comment]
> It is possible to save a model by TGI and reuse it.

@dtlzhuangz, may I ask how to do that?

**Comment by dtlzhuangz** [comment]
> > It is possible to save a model by TGI and reuse it.
> 
> @dtlzhuangz, may I ask how to do that?

Sorry, we do not support loading a model in TGI. we only support loading a model in 'transformers'. (They are different since kernel fusion and tensor parallel of TGI will contribute to the quantized weight unable to be used from transformers. ).

**Comment by meitalbensinai** [comment]
So, is there a way to load the quantized model in TGI somehow?

**Comment by dtlzhuangz** [comment]
@Narsil Hi, is it possible to save an EETQ model and load it in TGI?
