### ISSUE TITLE
Take into account num_return_sequences to get multiple outputs

### ISSUE THREAD

**Issue by mauryaland** [huggingface/text-generation-inference#1806]
### Feature request

Take into account the parameter num_return_sequences to get multiple outputs

### Motivation

In order to propose multiple choices to a user, using the parameter num_return_sequences is very convenient. Unfortunately, we can't use it (or I didn't find a way to) in TGI.

### Your contribution

I can try to take a look. I guess we should also modify https://github.com/huggingface/huggingface_hub/blob/ff6c1f974af6830cc1990a35f330ee0f27a2da91/src/huggingface_hub/inference/_client.py#L1644

**Comment by Stealthwriter** [comment]
yea I had to move to vllm because TGI doesn't return more than one choice
