### ISSUE TITLE
Suport for InternVL-Chat-V1-5 

### ISSUE THREAD

**Issue by Iven2132** [huggingface/text-generation-inference#1821]
### Model description

OpenGVLab/InternVL-Chat-V1-2-Plus is a open source alternative to GPT-4V. Can we please have support for that? 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/OpenGVLab/InternVL-Chat-V1-2-Plus

**Comment by Iven2132** [comment]
Hi @Narsil  Can I currently deploy https://huggingface.co/OpenGVLab/InternVL-Chat-V1-2-Plus on TGI?

**Comment by edwardzjl** [comment]
Also interested in this model, it performs pretty good in my tests.

**Comment by heibaidaolx123** [comment]
also looking forward to it
