### ISSUE TITLE
Supporting OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5

### ISSUE THREAD

**Issue by nd7141** [huggingface/text-generation-inference#188]
How hard it would be to include `OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5` to `InferenceAPIClient`? 

If it's difficult, if there is an easy way to `generate_stream` from local weights?

**Comment by nd7141** [comment]
Thank you, @OlivierDehaene. It would be great to replace the previous version OpenAssistant/oasst-sft-1-pythia-12b with a new one.

**Comment by OlivierDehaene** [comment]
`OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5` is now available with the Inference API/
