### ISSUE TITLE
Gibberish generated with deepseek-ai/deepseek-coder-6.7b-instruct

### ISSUE THREAD

**Issue by chuaweien** [huggingface/text-generation-inference#1957]
### System Info

Tried to run TGI 2.0.3 and 2.0.4 with deepseek-coder-6.7b-instruct but the output generated was a bunch of `\n`. 
Deepseek-coder-6.7b-instruct is working with TGI 2.0.2 though

TGI Version: `2.0.3`, `2.0.4`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

```
"prompt" : "You are an AI programming assistant, utilizing the DeepSeek Coder model, developed by DeepSeek Company, and you only answer questions related to computer science. For politically sensitive questions, security and privacy issues, and other non-computer science questions, you will refuse to answer.\n###Instruction:\nexplain this python code:\nusername = u.rsplit(\".\",1)[-1].strip()\n### Response:\n"
"stop": ["</s>", "<|im_end|>"]
```

Output generated is 
```
"\n\n\n\n\n\n\n\n\n\n..."
```

### Expected behavior

Expecting the model to explain the line of code but it outputs a bunch of new line characters

**Comment by xiaojinchuan** [comment]
I encountered the same problem.

**Comment by lambert0312** [comment]
the same problem
