### ISSUE TITLE
ModuleNotFoundError: No module named 'dropout_layer_norm'

### ISSUE THREAD

**Issue by gokerguner** [huggingface/text-generation-inference#1961]
### System Info

cargo 1.78.0
H100 with MIG, 1/2 GPU, 40GB RAM
Debian

I take an import error: 

```
" File "/home/myusername/text-generation-inference/server/text_generation_server/layers/layernorm.py", line 37, in <module>
    import dropout_layer_norm

ModuleNotFoundError: No module named 'dropout_layer_norm'"
```
But as I see, there is no .py file named as dropout_layer_norm

[Related error line](https://github.com/huggingface/text-generation-inference/blob/8f22cb961ad1afaba1755b98fb4e5e81536c8971/server/text_generation_server/layers/layernorm.py#L37)

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I did follow the instructions: https://huggingface.co/docs/text-generation-inference/installation

### Expected behavior

When I enter `make run-falcon-7b-instruct` , I expect serve Falcon 7B Instruct model from the port 8080, which we can query. But I take the error mentioned in title.

**Comment by tfcoe** [comment]
`dropout_layer_norm` is a part of `flash_attention`. This has likely not installed correctly.

**Comment by gokerguner** [comment]
Here is my installation code.

```
#!/bin/bash

# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh
source $HOME/.cargo/env

# Create and activate the Conda environment
conda create -n text-generation-inference python=3.9 -y
source $(conda info --base)/etc/profile.d/conda.sh
conda activate text-generation-inference

# Install Protocol Buffers
PROTOC_ZIP=protoc-21.12-linux-x86_64.zip
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP

# Install required packages
sudo apt-get update
sudo apt-get install -y libssl-dev gcc

# Clone the repository
git clone https://github.com/huggingface/text-generation-inference.git
cd text-generation-inference

# Set CARGO_TARGET_DIR and run make install
export CARGO_TARGET_DIR=$(pwd)/target
BUILD_EXTENSIONS=True make install
```

What could have gone wrong? Is there anything in this bash script that does not comply with the HuggingFace link I shared in the issue?

**Comment by samin-batra** [comment]
I am also facing the same issue today.

**Comment by Semihal** [comment]
Build and install https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm

**Comment by Kkkassini** [comment]
still stucked using ghcr.io/huggingface/text-generation-inference:latest ModuleNotFoundError: No module named 'dropout_layer_norm'
can i just ignore and skip this package?
