### ISSUE TITLE
Add `response_format` to chat/completions

### ISSUE THREAD

**Issue by thomas-schillaci** [huggingface/text-generation-inference#1966]
### Feature request

Now that the / route supports `grammar`, it would be nice to have the somewhat similar `response_format` on the chat/completions route.
Right now I'm using a middleware to transform an OpenAI request into a /generate_stream request which reroutes `response_format` to `grammar`.
For example I can do:
- `client.chat.completions.create(..., response_format={"type": "json_object", "value": json_schema})`
- `client.chat.completions.create(..., response_format={"type": "regex", "value": regex})`
This works as `response_format` is a dict, and the client doesn't validate additional fields (`value`).

### Motivation

This would enable constrained decoding with regex and and json_object on the chat/completions route.

### Your contribution

If adding `response_format = {type, value}` suits you, even though the OpenAI spec doesn't define the `value` field, I can implement it.

**Comment by drbh** [comment]
@thomas-schillaci thanks for the feature request! This PR should add `response_format` as described https://github.com/huggingface/text-generation-inference/pull/2046
