### ISSUE TITLE
Low-Rank Adaptation of Large Language Models

### ISSUE THREAD

**Issue by mhou7712** [huggingface/text-generation-inference#1973]
### Feature request

[Low-Rank Adaptation of Large Language Models](https://arxiv.org/abs/2106.09685)

### Motivation

Please review the link:  https://docs.vllm.ai/en/stable/models/lora.html

It will be great that TGI can provide the LoRA feature.

### Your contribution

N/A

**Comment by ming-ddtechcg** [comment]
Another LoRA example can be found at https://github.com/predibase/lorax.

**Comment by mhou7712** [comment]
From another thread for LoRA: https://github.com/huggingface/text-generation-inference/pull/935

**Comment by mhou7712** [comment]
refer to: https://github.com/huggingface/text-generation-inference/pull/2010

**Comment by mhou7712** [comment]
closed for now.
