### ISSUE TITLE
Gemma not starting with tensor parallelism

### ISSUE THREAD

**Issue by arunpatala** [huggingface/text-generation-inference#1987]
### System Info

latest TGI docker image

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Use gemma latest model and TGI server (docker) with 4 GPUs, I am getting the following error

    FlashGemmaLayer(
    
    [rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_gemma_modeling.py", line 302, in __init__
    [rank2]:     self.self_attn = FlashGemmaAttention(
    
    [rank2]:   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/custom_modeling/flash_gemma_modeling.py", line 194, in __init__
    [rank2]:     self.num_groups = self.num_heads // self.num_key_value_heads
    
    [rank2]: ZeroDivisionError: integer division or modulo by zero
     rank=2
    2024-05-31T10:50:20.725230Z  INFO shard-manager: text_generation_launcher: shard terminated rank=3
    Error: ShardCannotStart

### Expected behavior

not throw an error. The model seemed supported in tensor parallelism page.

**Comment by lp-noel** [comment]
Same error here with Qwen2.5 on 4 GPUs, can this be re-opened?
