### ISSUE TITLE
API_KEY argument

### ISSUE THREAD

**Issue by nbroad1881** [huggingface/text-generation-inference#2026]
### Feature request

TEI has the `API_KEY` argument:

>        --api-key <API_KEY>
>           Set an api key for request authorization.
> 
>           By default the server responds to every request. With an api key set, the requests must have the Authorization header set with the api key as Bearer token.
> 
>           [env: API_KEY=]

It would be nice if TGI had this as well.

### Motivation

It enables custom authorization of the endpoint.

### Your contribution

sry

**Comment by KevinDuffy94** [comment]
Adding this [block](https://github.com/huggingface/text-embeddings-inference/blob/main/router/src/http/server.rs#L1657-L1676) in [here](https://github.com/huggingface/text-generation-inference/blob/main/router/src/server.rs#L1860) and appending the layer should achieve this. 

One negative effect of this is that the healthcheck and info endpoints get auth included. Is there a way this can be prevented. I could start a PR for this next week.

**Comment by KevinDuffy94** [comment]
https://github.com/huggingface/text-generation-inference/pull/2142

**Comment by ErikKaum** [comment]
fixed by https://github.com/huggingface/text-generation-inference/pull/2314
