### ISSUE TITLE
What is TGI's graceful shutdown behavior?

### ISSUE THREAD

**Issue by seongminp** [huggingface/text-generation-inference#2035]
When SIGKILL arrives, 

- does TGI process all pending inputs?
- does TGI blocks incoming inputs?

I saw a PR that adds graceful shutdown but it did not specify the exact program behavior.

**Comment by OlivierDehaene** [comment]
- does TGI process all pending inputs?

Yes all inputs in the queue until a timeout which is currently set at 90 seconds.

- does TGI blocks incoming inputs?

Yes
