### ISSUE TITLE
Not able to start the server using make server-dev

### ISSUE THREAD

**Issue by Codehackerone** [huggingface/text-generation-inference#204]
I replaced the server Makefile to serve gpt2 without sharding like
`SAFETENSORS_FAST_GPU=1 python -m torch.distributed.run --nproc_per_node=2 text_generation_server/cli.py serve gpt2`
Yesterday, the server and router worked fine, but the next time when I restarted the server, it doesn't work.
The issue I'm facing
<img width="252" alt="Screenshot 2023-04-19 at 8 33 48 PM" src="https://user-images.githubusercontent.com/64341057/233118072-6673c87d-92fc-4fdf-9937-22b673751031.png">

**Comment by OlivierDehaene** [comment]
You don't need to launch using `torch.distributed.run` when you are not sharding your model.
You can directly use `text-generation-server serve gpt2`.
