### ISSUE TITLE
Some typo error in the picture of flash_attention.md 

### ISSUE THREAD

**Issue by yejunjin** [huggingface/text-generation-inference#2057]
### System Info

The notation in last Write phase in Flash attention part of the picture, shoule be Write $O_i, l_i, m_i$ instead of $O_i, l_i, v_i$.
![image](https://github.com/huggingface/text-generation-inference/assets/25998993/3ee220ac-1d62-4bbe-b2bd-23d687f30f11)

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

No Need

### Expected behavior

Fix flash_attention.md

**Comment by LysandreJik** [comment]
Thanks for mentioning it @yejunjin!

@merveenoyan I believe you contributed this image initially, could you confirm? I'm happy to replace the image if so.
