### ISSUE TITLE
Add Environment Variable for OTLP Service Name

### ISSUE THREAD

**Issue by KevinDuffy94** [huggingface/text-generation-inference#2069]
### Feature request

Currently the Service Name for OTLP is hard-coded as "text-generation-inference.server"
Could an environment variable be added which could set this. Something like...

resource = Resource.create( attributes={"service.name": os.getenv("OTLP_SERVICE_NAME","text-embeddings-inference.server")} )

And similar in the [main.rs](https://github.com/huggingface/text-generation-inference/blob/093a27c528dccefe83316d3ef1ff03b85cacdb94/router/src/main.rs#L404) file in the router.

### Motivation

Currently I have multiple models deployed and will be collected into a single APM so this will be problematic.

### Your contribution

Unconfident in writing any rust code.

**Comment by LysandreJik** [comment]
WDYT @OlivierDehaene? Are you open for this addition?

**Comment by LysandreJik** [comment]
Seen with Olivier, sounds good! Would you like to open a PR similarly to https://github.com/huggingface/text-embeddings-inference/pull/285?
