### ISSUE TITLE
Sparse Marlin

### ISSUE THREAD

**Issue by flozi00** [huggingface/text-generation-inference#2098]
### Feature request

Sparse-Marlin, an extension of the [Mixed Auto-Regressive Linear (Marlin)](https://github.com/IST-DASLab/marlin/tree/master) dense kernel for 4-bit quantized weights, now with support for 2:4 sparsity.

Specifically, Sparse-Marlin is an extremely optimized GPU kernel performing a matrix multiply and accumulate operation, C=AxB, where A and C are FP16 matrices, and B is a 50% sparse matrix following the 2:4 format, whose values are quantized and stored in INT4 precision. Integrating a 2:4 sparsity scheme on top of the existing 4-bit quantized weight representation offers the opportunity to further enhance the FLOPS/Byte ratio, and push the baseline performance further. Sparse-Marlin boosts the close-to-ideal performance of dense Marlin, and provides near-optimal speedups of around 5.3x, while being more robust to larger batch sizes.

### Motivation

![image](https://github.com/huggingface/text-generation-inference/assets/47894090/b2543a18-a6d5-4131-9577-b38ce45857cd)
![image](https://github.com/huggingface/text-generation-inference/assets/47894090/29a7a4bb-a56c-4272-8b28-f3394a950d6e)

### Your contribution

https://github.com/IST-DASLab/Sparse-Marlin/blob/main/marlin/marlin_cuda_kernel_nm.cu

Pinging @danieldk since he did the initial marlin PR

I could give it a try if it is wanted, but would also be happy with it if you know

**Comment by danieldk** [comment]
2:4 sparsity was on my todo list for after wrapping up GPTQ-Marlin support. Neural Magic has also added support for 2:4 sparsity for GPTQ-Marlin. I'll look into it now...

**Comment by flozi00** [comment]
That sounds great, so i can delete it from my To-Do ?

**Comment by danieldk** [comment]
Yeah, working on it now, should be an easy extension to the existing Marlin support.
