### ISSUE TITLE
protobuf version not compatible

### ISSUE THREAD

**Issue by gx16377** [huggingface/text-generation-inference#2100]
The version of protoc recommended in readme is not compatible with protobuf version in server requirements

https://github.com/huggingface/text-generation-inference#local-install
PROTOC_ZIP=protoc-21.12-linux-x86_64.zip

[server/requirements_cuda.txt](https://github.com/huggingface/text-generation-inference/blob/main/server/requirements_cuda.txt)
protobuf==4.25.3

ref:
https://protobuf.dev/support/version-support/#python

**Comment by LysandreJik** [comment]
Thanks for the report @gx16377, indeed! Would you like to open a PR to update the version?
