### ISSUE TITLE
template_error in /chat/completions 

### ISSUE THREAD

**Issue by markVaykhansky** [huggingface/text-generation-inference#2112]
### System Info

2024-06-24T13:30:56.967705Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.78.0
Commit sha: f426a3398d12808f20c101487329e563d32bfbaf
Docker label: sha-f426a33
nvidia-smi:
Mon Jun 24 13:30:56 2024       
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
   | N/A   39C    P0              31W /  70W |  13465MiB / 15360MiB |      0%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+
                                                                                            
   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   |    0   N/A  N/A       128      C   /opt/conda/bin/python3.10                     0MiB |
   +---------------------------------------------------------------------------------------+
xpu-smi:
N/A
2024-06-24T13:30:56.967730Z  INFO text_generation_launcher: Args {
    model_id: "bigscience/bloom-560m",
    revision: None,
    validation_workers: 2,
    sharded: None,
    num_shard: None,
    quantize: None,
    speculate: None,
    dtype: None,
    trust_remote_code: false,
    max_concurrent_requests: 128,
    max_best_of: 2,
    max_stop_sequences: 4,
    max_top_n_tokens: 5,
    max_input_tokens: None,
    max_input_length: None,
    max_total_tokens: None,
    waiting_served_ratio: 0.3,
    max_batch_prefill_tokens: None,
    max_batch_total_tokens: None,
    max_waiting_tokens: 20,
    max_batch_size: None,
    cuda_graphs: None,
    hostname: "9966e3f04120",
    port: 80,
    shard_uds_path: "/tmp/text-generation-server",
    master_addr: "localhost",
    master_port: 29500,
    huggingface_hub_cache: Some(
        "/data",
    ),
    weights_cache_override: None,
    disable_custom_kernels: false,
    cuda_memory_fraction: 1.0,
    rope_scaling: None,
    rope_factor: None,
    json_output: false,
    otlp_endpoint: None,
    cors_allow_origin: [],
    watermark_gamma: None,
    watermark_delta: None,
    ngrok: false,
    ngrok_authtoken: None,
    ngrok_edge: None,
    tokenizer_config_path: None,
    disable_grammar_support: false,
    env: true,
    max_client_batch_size: 4,
}

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

On Linux Ubuntu with Docker installed,

Launch TGI as written in the docs:
`docker run -d --gpus all --shm-size 1g -p 8080:80 -v /opt/dlami/nvme/data:/data \
    ghcr.io/huggingface/text-generation-inference:2.0.4 \
    --model-id gpt2`
 
Then make the following POST request (which works on Chat GPT w/ appropriate model parameter):
`http://localhost:8080/v1/chat/completions`

`{
    "model": "gpt2",
    "messages": [
      {
        "role": "user",
        "content": "Hello"
      }
    ]
 }`

This results in `422` HTTP error (invalid input) with the following message:
`2024-06-24T12:59:56.520123Z ERROR chat_completions: text_generation_router::server: router/src/server.rs:1046: Template error: template not found`.

Calling that endpoint via open-ai's library with `http://localhost:8080` as base url results in the same error. 
Also going to `http://localhost:8080/docs` and trying that request results in the same error.

### Expected behavior

Should return a valid result from gpt2

**Comment by Hugoch** [comment]
Hi @markVaykhansky ! For chat completions to work you need to have a model that defines a `chat_template` in its`tokenizer_cnfig.json`. In the case of gpt2 that is not the case as it is not a chat model. You probably want to call the ` http://localhost:8080/v1/completions` endpoint.

**Comment by markVaykhansky** [comment]
Thanks!
