### ISSUE TITLE
Enable torch.float8_e5m2 for Ada lovelace

### ISSUE THREAD

**Issue by flozi00** [huggingface/text-generation-inference#2157]
https://github.com/huggingface/text-generation-inference/blob/d0225b10156320f294647ac676c130d03626473d/server/text_generation_server/layers/fp8.py#L4

@Narsil what do you think about enabling torch.float8_e5m2 too for ada lovelace architecture ?
Is there any specific reason why you didn't add both fp8 types ?

**Comment by dongs0104** [comment]
i think float8_e5m2 is more adapt for backward, tgi need to only forward pass, so i think e4m3fn is enough to tgi, 

> Typically forward activations and weights require more precision, so E4M3 datatype is best used during forward pass. In the backward pass, however, gradients flowing through the network typically are less susceptible to the loss of precision, but require higher dynamic range. Therefore they are best stored using E5M2 data format. https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html
