### ISSUE TITLE
Understanding how max-batch-prefill-tokens works

### ISSUE THREAD

**Issue by varad0309** [huggingface/text-generation-inference#2160]
Hi, I am trying to find an ideal size for `max-batch-total-tokens` for my hardware (A100 80GB) and model (LLaMA3 8B). To do this, I tried to minimize the size of `max-batch-prefill-tokens` by setting it to default (`max-input-length + 50`). However, I noticed that  `max-batch-prefill-tokens` consumes the memory very differently. It reaches maximum memory consumption when it kept default, which decreases with increasing `max-batch-prefill-tokens`, reaches a certain peak, and again starts increasing till you hit OOM.

My understanding:
We are allocating memory for prefill operation using `max-batch-prefill-tokens`. In case of the above model, 1 token is equivalent to 0.25 MB of KV cache, so 100 tokens will consume 25 MB. The base model itself consumes ~16 GB of memory, so for `max-batch-prefill-tokens=178`, the available memory should still be close to 16 GB, which is not the case here!

Here are my questions:
1. Is this an expected behavior? If yes, how to calculate the value of `max-batch-prefill-tokens` where I will obtain the least memory consumption. If no, what's going wrong (details regarding my code below)?
2. In order to maximize on throughput, minimizing on latency, what values should I keep for `max-batch-prefill-tokens`, `max-waiting-tokens`?

I am really thankful for any suggestions, and thanks for keeping up this awesome work !!

Execution command:
```
docker run -d \
        --gpus "\"device=1\"" \
        --shm-size 16g \
        -e HUGGING_FACE_HUB_TOKEN=$token \
        -p 8080:82 \
        -v $volume:/data \
        --name "llama3_8b" \
        ghcr.io/huggingface/text-generation-inference:sha-007d5e5 \
        --model-id $model \
        --max-batch-total-tokens 1024000 \
        --max-total-tokens 129 \
        --max-input-length 129 \
        --max-batch-prefill-tokens 10000 \
        --num-shard $num_gpus \
        --dtype bfloat16
```

Memory consumption:
1. At `max-batch-prefill-tokens=178` 
<img width="580" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/173095950/99baf11b-b151-4c80-941e-3b6936371fb6">

2. At `max-batch-prefill-tokens=10000`
<img width="588" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/173095950/e21287ae-fa57-4024-9499-3ee5c92fefad">

3. At `max-batch-prefill-tokens=240000`
<img width="591" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/173095950/56b95dae-36ec-4270-8410-cdee0d72cdf5">

**Comment by lp-noel** [comment]
@varad0309 curious to see what your conclusion was here?

**Comment by varad0309** [comment]
Hey @lp-noel, after further digging, I observed that they are by default allocating the `max-batch-total-tokens` according to the available memory on the GPU. Thus, this is not a parameter defined by user. And that's the reason changing `max-batch-prefill-tokens` fluctuates the memory available .. higher the value, less is the memory allocated to `max-batch-total-tokens`.
