### ISSUE TITLE
Is there any possibility to support `Phi-3-vision-128k-instruct`?

### ISSUE THREAD

**Issue by farzanehnakhaee70** [huggingface/text-generation-inference#2174]
### Feature request

Microsoft published its light-weight version of multi-modal model which also supports images. Is there any possibility to support this model in TGI?

### Motivation

Supporting multi-modal and scpecially models which will accept image as input in TGI.

### Your contribution

No.

**Comment by LysandreJik** [comment]
Thanks for your request @farzanehnakhaee70! I'm making sure the team sees it.

For now the model is using custom code and can be used with `transformers` and `trust_remote_code=True`.

Usually what drives a model addition to our toolkit is the community excitement for that model to be added to our modeling libraries. Getting a lot of :+1: on your message will show us that it's important for a lot of people :)
