### ISSUE TITLE
Question about the multi-Lora feature

### ISSUE THREAD

**Issue by thincal** [huggingface/text-generation-inference#2177]
About the multi-Lora support in tgi, it seems that the Lora adapters should be preloaded explicitly when tgi starting up, then invoke with a specific id to specify which Lora be using. But if there are new Lora created, need re-launch the existed or deploy new tgi instances containing this new Lora?

E.g.
```
LORA_ADAPTERS=predibase/customer_support,predibase/dbpedia \
text-generation-launcher --model-id mistralai/Mistral-7B-v0.1
```

**Comment by Hugoch** [comment]
Lora adapters will be loaded at startup (https://huggingface.co/docs/text-generation-inference/en/basic_tutorials/launcher#loraadapters). 
You need to restart TGI with the new adapter IDs if needed.

**Comment by thincal** [comment]
Why not choose loading the Lora adapters dynamically like the Lorax way?
