### ISSUE TITLE
load eetq model

### ISSUE THREAD

**Issue by meitalbensinai** [huggingface/text-generation-inference#2198]
### Feature request

hi,
I find the eetq quantization great and fit my needs, but the loading time is super slow.
I tried to quantize the model in advance and then load it directly with the hope of reducing the initialization times, but it seems that it is not possible. 
Can support be added for loading an already quantized eetq model to improve the init times?

thanks!

### Motivation

improve initialization times for eetq models

### Your contribution

I can try

**Comment by SunMarc** [comment]
Hi @meitalbensinai, as you experienced. It is not possible to load quantized eetq model yet in TGI. According to @Narsil, this should be pretty straightforward. https://github.com/NetEase-FuXi/EETQ/issues/10#issuecomment-2050213874. Feel free to give it a try. In transformers integration, we had no issue reloading the quantized model -> [here](https://huggingface.co/docs/transformers/main/en/quantization/eetq).
