### ISSUE TITLE
Description of Tools format within Documentation

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/text-generation-inference#2210]
### System Info

v2.1.1

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

With respect to training/fine-tuning models that are compatible with tool use with TGI (via the openai endpoint):
- It is unclear how "tools" are injected into the prompt that used for generation.
- It is unclear how the model's responses is parsed by the server from tokens (or string of tokens) into the openai formatted response that includes tool calls.

- I have reviewed the [messages documentation](https://huggingface.co/docs/text-generation-inference/en/messages_api)/
- I have tried to search within the server code to find out "tools" are handled by the server.

Would it be possible to provide links in documentation to each of these things.

### Expected behavior

1. How tools are injected into the prompt.
- It would be ideal to see code (or a code snippet) of how the prompt is formatted to include tools (if that is even the case).

2. How the tokens generated by the LLM are parsed into a response from the server.

What kind of regex matching or special token detection is the server using to parse the string from the LLM into tool calls and/or the model response.

**Comment by ErikKaum** [comment]
Hi @RonanKMcGovern!

Yeah the documentation is unfortunately up to the standard we'd like to be. Apologies from out side.
I don't want to give false promises of having bandwidth to improve the documentation this week but hopefully I'll get to it as soon as possible.

In the meantime, this is the server code that's responsible for the `tool`

The Tool struct:
https://github.com/huggingface/text-generation-inference/blob/dbb23fbfa868ad8f961c60896e346fad3d2ab440/router/src/lib.rs#L925

Which is part of the ChatRequest:
https://github.com/huggingface/text-generation-inference/blob/dbb23fbfa868ad8f961c60896e346fad3d2ab440/router/src/lib.rs#L812

Which is what's deserialised in the `v1/chat/completions` endpoint:
https://github.com/huggingface/text-generation-inference/blob/dbb23fbfa868ad8f961c60896e346fad3d2ab440/router/src/server.rs#L1009

Is this a good start on answering some of your questions?

**Comment by RonanKMcGovern** [comment]
Thanks Erik, I appreciate the response. That does help.

I've only spent a few minutes looking at this but I think I can see how a
chat template is used to serialise everything, and then there is extraction
logic to deserialise.

I don't see it yet, but I suppose there is a modified chat template that
handles tools that is being imported somewhere.

Understood it may take some time to have documentation ready. When you get
to it, it would be great if you can show some examples of a) calls to the
api, b) serialised prompts are used for generation, c) raw LLM responses,
d) de-serialised LLM responses, with the tool response extracted, e) the
full api response.

Many thanks

**Comment by ErikKaum** [comment]
Thank you for the feedback @RonanKMcGovern 🙌 
I'll note these and try to combine with other similar feedback, and see what way we could package it nicely.

If you don't object I'll close this issue for now. Of course, feel free to reopen it if you want 👍

**Comment by RonanKMcGovern** [comment]
Sounds excellent
