### ISSUE TITLE
`bitsandbytes==0.43.0` not supported on MacOS

### ISSUE THREAD

**Issue by wdoppenberg** [huggingface/text-generation-inference#2214]
## System Info:
```
Runtime environment:
Target: aarch64-apple-darwin
Cargo version: 1.79.0
Commit sha: 8511669cb29115bdf0bc2da5328e69d041030996
Docker label: N/A
nvidia-smi:
N/A
xpu-smi:
N/A
```

## Problem
The most recent version of `bitsandbytes` does [not support](https://pypi.org/project/bitsandbytes/0.43.0/#files) the MacOS platform at the time of writing. I managed to install `text-generation-inference` by manually downgrading the `bitsandbytes` requirement to `^0.42.0`, and am having no issues running the CPU variant. 

## Possible solutions
* Ignore the `bitsandbytes` dependency if on MacOS
* Downgrading the `bitsandbytes` version until an appropriate version is released (if ever).

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

1. Be on MacOS (ARM)
2. Clone repo and make sure you're on `8511669cb29115bdf0bc2da5328e69d041030996`
3. Run `BUILD_EXTENSIONS=True make install-cpu`

### Expected behavior

It should install

**Comment by Hugoch** [comment]
Hey @wdoppenberg,
I can reproduce on a ARM MacOS machine. I think we can remove bnb from non-cuda installs.
