### ISSUE TITLE
Model offloading (preparing for Llama3 405b)

### ISSUE THREAD

**Issue by flozi00** [huggingface/text-generation-inference#2229]
### Feature request

Native offloading Support for large models

### Motivation

Inspired by https://github.com/vllm-project/vllm/pull/6317 and accelerate auto mapping

Some numbers of expected costs:
https://x.com/osanseviero/status/1812763609807638878

### Your contribution

Consuming 🤗

Just a joke, can take a look after vacation, but would like to discuss it if it's a wanted feature.

**Comment by ErikKaum** [comment]
Hi @flozi00 👋 

I think this is a good suggestion 👍 Not sure if anyone from our side at the moment has bandwidth to take this on but once you've come back from vacation I suggest we take a look. Basically:

- if it's a feature we'd want to support (not 100% sure but leaning yes)
- implementation details and how we could support you

Does this sound like a plan?

**Comment by flozi00** [comment]
Definitely 💯 
I will be back in around three weeks to take this

**Comment by ErikKaum** [comment]
Sounds awesome, thank you!
