### ISSUE TITLE
Unable to load Vicuna-13b model.

### ISSUE THREAD

**Issue by sonsai123** [huggingface/text-generation-inference#224]
For some reason, I'm unable to run the vicuna 13b model (based on llama) using the below command

`text-generation-launcher --model-id path-to-vicuna --num-shard 1 --quantize --port 8010 --max-input-length 1538 --max-total-tokens 2048`

Getting below error:
`OverflowError: out of range integral type conversion attempted`

On EC2 g5.2xlarge A10G 24GB

Loading same model with below in python works fine without any issues
`AutoModelForCausalLM.from_pretrained(path-to-vicuna, device_map="auto", load_in_8bit=True)`

**Comment by sonsai123** [comment]
Above error is with accelerate 0.18.0.

When I downgrade to 0.15.0 there is a different error:

```
Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
```

**Comment by sonsai123** [comment]
I pulled latest code from `main` and installed `flash-attn` as well, and these issues are appearing now. However, there is issue with `vocab_file` in`tokenization_llama.py` and I manually hardcoded it with `tokenizer.model` path as a workaround.

**Comment by PenutChen** [comment]
For someone who may come here with this error: `OverflowError: out of range integral type conversion attempted`. 
In my case, it is because the pad token id of the Vicuna model is not set correctly. You can inspect this issue with the following code:

```python
from transformers import LlamaTokenizer as TkCls

tk = TkCls.from_pretrained('Models/Vicuna-7B')
print(tk.eos_token_id)
print(tk.bos_token_id)
print(tk.pad_token_id)
print(tk.unk_token_id)
```

I found that my `pad_token_id` is `None`. My solution is as follows:

```python
from transformers import LlamaTokenizer as TkCls

tk = TkCls.from_pretrained('Models/Vicuna-7B')
tk.pad_token_id = tk.eos_token_id
tk.save_pretrained('Models/Vicuna-7B')
```

After making these changes, my TGI launched successfully. I hope this helps someone.
