### ISSUE TITLE
OpenAI style endpoint does not take in chat template automatically

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/text-generation-inference#2295]
### System Info

v2.2.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Unless I'm mistaken, the openai style endpoint just applies the default chat template. This is different to vllm and most other openai style endpoints and adds friction because the user must somehow template the messages.

### Expected behavior

It would be better to automatically grab the jinja template from the tokenizer json.

**Comment by drbh** [comment]
Hi @RonanKMcGovern, the openai endpoint does not use a default template in any case. 

If a chat template is not available (via the hub or locally) the chat endpoint will return the error [TemplateNotFound](https://github.com/huggingface/text-generation-inference/blob/3905f854ed49b0bc50e6c983d3e6b254fcf02288/router/src/infer/mod.rs#L140) error

As you noted above, the jinja template is fetched from the tokenizer config and applied to request sent to the chat endpoint.

This functionality was added along with the initial openai api support in `v1.3.5` some time in January. Relevant code here: https://github.com/huggingface/text-generation-inference/blame/3905f854ed49b0bc50e6c983d3e6b254fcf02288/router/src/main.rs#L612-L629

I hope this helps! Please let me know if you have any followup questions

**Comment by RonanKMcGovern** [comment]
Yeah that helps, I think my fault on misunderstanding. If I see an issue I'll make a replicator.
