### ISSUE TITLE
Fixes #3908

### ISSUE THREAD

**Issue by Paxosgold** [huggingface/text-generation-inference#2305]
Fixes #3908

![image](https://github.com/user-attachments/assets/610b32e7-88cb-40fb-a3cc-a42e6fcff764)

_Originally posted by @urugator in https://github.com/mobxjs/mobx/pull/3909_

**Comment by Paxosgold** [comment]
> Fixes #3908
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/610b32e7-88cb-40fb-a3cc-a42e6fcff764)
> 
> 
> 
> _Originally posted by @urugator in https://github.com/mobxjs/mobx/pull/3909_

@Narsil

**Comment by drbh** [comment]
Closing. This is not related to TGI.
