### ISSUE TITLE
Improved Logging and Monitoring w/ Documentation

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/text-generation-inference#231]
I would love to be able to see inside my inference server the size of the dynamic batches that are getting made, the queue size to understand if we are falling behind, and maybe memory usage.

I understand that there is Open Telemetry metrics but it is pretty unclear based on the limited documentation what metrics are available to ingest into a downstream aggregator such as New Relic or Datadog to actually monitor one of these systems in production. Critical metrics that indicate server health that we could page on being documented would also be a big help.

You guys rock. Thanks.

**Comment by OlivierDehaene** [comment]
Here is a list of all exported metrics on the Prometheus scrapable `/metrics` route:

### Input Summaries 

- tgi_request_input_length_bucket: prom summary of the number of tokens inside each request prompt
- tgi_request_max_new_tokens_bucket: prom summary of the total token size of each request
- tgi_request_generated_tokens_bucket: prom summary of the number of generated tokens for each request
- tgi_batch_next_size_bucket: prom summary of the size of each new batch from the queue

### Latency Summaries

- tgi_request_duration_bucket: prom summary of the total end to end duration for each request
- tgi_request_validation_duration_bucket: prom summary of the duration of the validation step per request
- tgi_request_queue_duration_bucket: prom summary of the time spent waiting in the internal queue before a request is added to a batch 
- tgi_request_inference_duration_bucket: prom summary of inference duration for each request
- tgi_request_mean_time_per_token_duration_bucket: prom summary of the inference duration for each token of a request
- tgi_batch_inference_duration_bucket: prom summary of the model forward duration for each batch. You can filter by method = ["prefill", "decode"]

## Counters

- tgi_request_count: prom counter of the total number of request received.
- tgi_request_success: prom counter of the number of request that suceeded.
- tgi_request_failure: prom counter of the number of failed requests. You can filter by err.
- tgi_batch_concat: prom counter of the number of batch concatenates. You can filter by reason = ["backpressure", "wait_exceeded"]
- tgi_batch_inference_success: prom counter of the number of inference that suceeded.
- tgi_batch_inference_success: prom counter of the number of inference that failed. You can filter by method = ["prefill", "decode"]
- tgi_batch_inference_count: prom counter of the total number of inference.

## Gauges

- tgi_queue_size: prom gauge of the number of requests waiting in the internal queue
- tgi_batch_current_max_tokens: prom gauge of the number of maximum tokens the current batch will grow to
- tgi_batch_current_size: prom gauge of the current batch size

**Comment by usaxena-asapp** [comment]
Hi @OlivierDehaene - could you point me to where you add/increment/emit these? Basically, if I were trying to make/emit my own metrics, is there some code I could possibly look at? Thanks!

**Comment by Rogerwyf** [comment]
Following up on this as well - would be interested in adding output summary!

**Comment by OlivierDehaene** [comment]
Everytime you see `metrics::<something>` in the Rust router, that's where we modify the Prom metrics.
