### ISSUE TITLE
墙内用户如何不使用梯子运行docker容器.Chinese mainland users must use a proxy software when running Docker. How can they avoid using a proxy software?

### ISSUE THREAD

**Issue by zk19971101** [huggingface/text-generation-inference#2324]
### Feature request

我可以确认在huggingface上下载的模型权重文件没有问题，运行docker时还是需要翻墙才能正常运行。我猜测是代码中需要对文件进行检查，是否可以设置一个参数避免进行检查呢？
I can confirm that the weight files of the neural network models downloaded from the Hugging Face website are correct, but the container still needs a proxy software (to bypass the firewall) to run normally. I suspect that the code needs to check the files, and whether it is possible to set a parameter to avoid the check?

### Motivation

我下载了huggingface上的模型权重在本地，通过docker运行时还是需要开启梯子才能正常运行。我需要如何设置参数才能不用梯子呢？
I downloaded the weight parameters of the neural network model from the Hugging Face website and saved them on my local computer. However, when running the Docker container, I encountered an error related to network connection. After enabling a proxy software, I was able to successfully run the container.
docker run --gpus all -p8080:80 -v $HOME/.cache/huggingface/hub:/data ghcr.io/huggingface/text-generation-inference:2.0.4 --model-id lllyasviel/omost-llama-3-8b --max-total-tokens 9216 --cuda-memory-fraction 0.5
![企业微信截图_20240729155240](https://github.com/user-attachments/assets/05312f42-645b-45e0-9e5a-c56ceac4588b)
![企业微信截图_20240729155301](https://github.com/user-attachments/assets/8e9b1ed1-7972-4b10-85e5-cb3abf91bae0)
![企业微信截图_20240729155311](https://github.com/user-attachments/assets/77bf16a7-3ced-4e0a-bdd2-0ff9ec349278)

### Your contribution

None

**Comment by ErikKaum** [comment]
Hi @zk19971101 👋 

There's an env variable `HF_HUB_OFFLINE=1` that you can pass. I think that should alleviate the problem.
Could you try with that one? If the same error still persist let me know since TGI should be runnable without internet 👍

**Comment by zk19971101** [comment]
Just now, i followed your suggest to set the env variable HF_HUB_OFFLINE=1, but it dosen't seem to work and raise the same error .Did I set something wrong?
![企业微信截图_20240729170242](https://github.com/user-attachments/assets/ff38b454-8d84-424f-83a9-71f1f5065492)
![企业微信截图_20240729170257](https://github.com/user-attachments/assets/602e30ba-a6b1-4689-856b-6c4d52a3c950)
![企业微信截图_20240729170306](https://github.com/user-attachments/assets/ad7c92a5-3873-4278-85c6-e16177336df2)

**Comment by ErikKaum** [comment]
You'll need to pass the env var to the container in the start command as well. Hopefully this helps: https://docs.docker.com/reference/cli/docker/container/run/#env

**Comment by zk19971101** [comment]
It worked. Thank you very much！

**Comment by ErikKaum** [comment]
Awesome, glad to hear! 🙌
