### ISSUE TITLE
Add /v1/models API endpoint to be compatible with OpenAI APIs

### ISSUE THREAD

**Issue by ktrapeznikov** [huggingface/text-generation-inference#2369]
### Feature request

Add `/v1/models/` endpoint to list model information. This will basically same info as `/info` endpoint just compliant with OpenAI APIs

### Motivation

Lot of other tools expect `/v1/models` to list the available models.

### Your contribution

 I can try submitting a PR

**Comment by ErikKaum** [comment]
Hi @ktrapeznikov 👋 

To me this makes sense. If you have time making a PR please feel free to go ahead 🙌

**Comment by Simon-Stone** [comment]
This would be very helpful to my use case, too!

**Comment by ErikKaum** [comment]
Awesome 🙌 we're quite constrained on bandwidth at the moment. But once we get to this it should be a quick thing to implement.

Also, if you have the time please feel free to submit a PR 👍
