### ISSUE TITLE
Compilation fails for text-generation-benchmark

### ISSUE THREAD

**Issue by jlamypoirier** [huggingface/text-generation-inference#241]
I'm getting this error when I try to compile `text-generation-benchmark`
```
#11 326.6    Compiling tokenizers v0.13.3
#11 329.9    Compiling text-generation-benchmark v0.1.0 (/app/text-generation-inference/benchmark)
#11 330.2 error[E0063]: missing field `max_tokens` in initializer of `Batch`
#11 330.2    --> src/generation.rs:142:17
#11 330.2     |
#11 330.2 142 |     let batch = Batch {
#11 330.2     |                 ^^^^^ missing `max_tokens`
#11 330.2 
#11 330.3 For more information about this error, try `rustc --explain E0063`.
#11 330.3 error: could not compile `text-generation-benchmark` due to previous error
#11 330.3 warning: build failed, waiting for other jobs to finish...
```
I can't find where Batch is defined so no idea if the bug is justified.

Note: I messed around a bit with the code to get things to run with my setup (base image `nvcr.io/nvidia/pytorch:23.03-py3` with python 3.8, bigcode transformers instead of @OlivierDehaene 's fork):
https://github.com/jlamypoirier/text-generation-inference/pull/1
https://github.com/bigcode-project/bigcode-inference-benchmark/pull/22

**Comment by jlamypoirier** [comment]
I see this addition from yesterday, could it be the problem?
https://github.com/huggingface/text-generation-inference/blame/main/server/text_generation_server/models/causal_lm.py#L50

**Comment by OlivierDehaene** [comment]
Fixed on main.

**Comment by jlamypoirier** [comment]
Thanks!
