### ISSUE TITLE
Release 2.3.0 version

### ISSUE THREAD

**Issue by imran3180** [huggingface/text-generation-inference#2425]
### Feature request

Hi Team, I'm waiting for next version to be released. Could you let us know when are you guys planning to next version?

### Motivation

There are couple of features that multiple people are waiting to be released. For example - loading multiple local LORA adapters 

### Your contribution

None

**Comment by imran3180** [comment]
Related Issue: 
1. https://github.com/huggingface/text-generation-inference/issues/2143
2. https://github.com/huggingface/text-generation-inference/issues/2253
3. https://github.com/huggingface/text-generation-inference/issues/2400

**Comment by ErikKaum** [comment]
Hi @imran3180 👋 

I think we currently don't know the exact date of the next release. 

In the meantime there's a docker build that's based on main if you have a more urgent need to get the new features/fixes: https://github.com/huggingface/text-generation-inference/pkgs/container/text-generation-inference

Would that be a solution in your case?

**Comment by imran3180** [comment]
Yes, I was able to unblock myself using docker container build.

**Comment by ErikKaum** [comment]
Awesome, glad to hear 🙌 
I'll close the issue, feel free to reopen if you're blocked again 👍
