### ISSUE TITLE
Can not load local model by --model-id

### ISSUE THREAD

**Issue by paulcx** [huggingface/text-generation-inference#245]
try two methods to create container (ghcr.io/huggingface/text-generation-inference:sha-7de8a37) but no luck: 

```
docker run --gpus all --shm-size 1g -p 8080:80 ghcr.io/huggingface/text-generation-inference:latest --model-id ./output/checkpoint-400 --num-shard 2
docker run ghcr.io/huggingface/text-generation-inference  --model-id checkpoint-400 --num-shard 2
```

It seems trying download the model rather than use local model there.

![20230426181530](https://user-images.githubusercontent.com/738834/234546307-41662a0f-6458-4563-b93a-3608562f689b.png)

another reported issue [#99](https://github.com/huggingface/text-generation-inference/issues/99#issuecomment-1522497619)

**Comment by paulcx** [comment]
> 

Thanks for your reply. I did try your approch but it does not work?

![20230427080041](https://user-images.githubusercontent.com/738834/234727361-e2501a3b-6c58-4e65-8d02-01bcaf94edbd.png)

**Comment by paulcx** [comment]
> You can try mounting a directory from the host which contains the model, and then using `--model-id` with the complete path within the container. This worked for me:
> 
> ```shell
> $ pwd
> /mnt/huggingface
> $ ls
> opt-125m  version.txt
> $ ls opt-125m/
> config.json  generation_config.json  merges.txt  pytorch_model.bin  special_tokens_map.json  tokenizer_config.json  vocab.json
> 
> 
> $ docker run --gpus all --shm-size 1g -p 8080:80 --volume /mnt/huggingface:/data ghcr.io/huggingface/text-generation-inference:latest --model-id /data/opt-125m --num-shard 1
> ```

After several attempts, I found that the problem lies in the mapping path in docker run.

Now I can confirm that your approach works!

```
docker run --gpus all --shm-size 1g -p 8080:80 -v /root/huggingface:/data text-generation-inference:latest --model-id /data/checkpoint-400 --num-shard 2
```

However, the another error came out:

![20230427082335](https://user-images.githubusercontent.com/738834/234729483-4e18f48c-8674-4e7a-a535-6196ca75fb60.png)

**Comment by paulcx** [comment]
It works if I set --num-shard to 1. Then the question is what does the num-shard param mean here?

**Comment by paulcx** [comment]
other issues I have found:
1. when I use ab tool to test with c=2:
```
ab -n 10 -c 2 -p post_data.json -T application/json -H 'accept: application/json' http://localhost:8080/generate
```
a decode error has been rasied when batch_size = 2?

![20230427101032](https://user-images.githubusercontent.com/738834/234742138-872541d1-e6f8-48f4-8fbf-3dce1ddcc7f3.png)

**Comment by OlivierDehaene** [comment]
num-shard means GPU parallelization using tensor parallelism. This is needed for larger models as they don't fit inside a single device. However, for tensor parallelism to work, you need your embeddings and other linear layers inside the models to be dividable by the number of shards.

**Comment by gamepad-coder** [comment]
`--num-shard` and other arguments for TGI ("Text Generation Interface") are documented here:

https://huggingface.co/docs/text-generation-inference/en/basic_tutorials/launcher#numshard
