### ISSUE TITLE
What backend does TGI use?

### ISSUE THREAD

**Issue by brianyu-nexusflowai** [huggingface/text-generation-inference#2458]
Hi TGI team!

Just a quick question -- what backends does TGI use? e.g. TensorRT LLM, vLLM, etc. Curious to know which technologies are currently used :D

Cheers,
Brian

**Comment by ivoras** [comment]
AFAIK it uses the HuggingFace transformers one.

**Comment by ErikKaum** [comment]
Hi @brianyu-nexusflowai 👋 

Thank's for asking a good question 👍 We've made a lot of changes lately but in short:
- by default we use the `TGI python backend server` here https://github.com/huggingface/text-generation-inference/tree/main/server it's the one we've had "always".  It has all the bells & whistles with optimizes attention kernels etc.
- For this one if there isn't a optimized implementation of a model the fallback would be the transformers implementation.
- TensorRT LLM: https://github.com/huggingface/text-generation-inference/tree/main/backends/trtllm was recently added 

Hopefully this helps uncover this a bit :)

**Comment by brianyu-nexusflowai** [comment]
Hi @ErikKaum !

Yes it does, thank you so much for the response. Excited to see what you guys are cooking :eyes:

Brian
