### ISSUE TITLE
Directory check missing in FBGEMM Makefile

### ISSUE THREAD

**Issue by vamsivallepu** [huggingface/text-generation-inference#2485]
#### Overview:
When building the FBGEMM project using the provided makefile, the current implementation attempts to clone the `fbgemm` repository every time the build command is executed. If the `fbgemm` directory already exists (from a previous build attempt), the cloning step fails with an error, disrupting the build process.

#### Problem:
https://github.com/huggingface/text-generation-inference/blob/6cb42f49ae47a117e8f1bdfcdb5cbe42332dc360/server/Makefile-fbgemm#L3-L4
- The makefile does not currently check for the existence of the `fbgemm` directory before attempting to clone the repository.
- If the build process is interrupted or fails after the repository is cloned, any subsequent build attempt will encounter an error due to the existing `fbgemm` directory.

#### Proposed Solution:
- Modify the makefile to include a directory check before cloning the repository. If the `fbgemm` directory already exists, the script should skip the cloning step and proceed with the remaining build steps.

**Comment by ErikKaum** [comment]
Yes, thank you very much for raising the issue and submitting a PR 🙌
