### ISSUE TITLE
Installing without docker.

### ISSUE THREAD

**Issue by razvanab** [huggingface/text-generation-inference#2488]
### Feature request

Can you please support installing text-generation-inference without Docker?
Installing that Docker Cuda-toolkit in Windows is a f***** pain in the ass.

### Motivation

Llama-cpp support for the latest model is slow, and so is ollama and the rest that use llama-cpp.
I want to try Phi-3.5, for example, but there is no support in llama-cpp yet.

### Your contribution

Test it out.

**Comment by ErikKaum** [comment]
Hi @razvanab 👋 

It's possible to build TGI from source but there might be some sharp edges on windows (haven't tried myself). As for distributing native binaries I unfortunately think that's not at the moment something we have bandwidth to prioritize.

These are the instructions to build [locally](https://github.com/huggingface/text-generation-inference?tab=readme-ov-file#local-install)

Hopefully this helps 👍

**Comment by razvanab** [comment]
Thanks

**Comment by ErikKaum** [comment]
Anytime 🙌
