### ISSUE TITLE
Concurrent issue - batch size can not be greater than 1

### ISSUE THREAD

**Issue by paulcx** [huggingface/text-generation-inference#249]
1. when I use ab tool to test with c=2:
```
ab -n 10 -c 2 -p post_data.json -T application/json -H 'accept: application/json' http://localhost:8080/generate
```
a runtime error has been rasied when batch_size > 1?
```
data:{"error":"Request failed during generation: Server error: not enough values to unpack (expected 4, got 3)","error_type":"generation"}
```

![20230427101032](https://user-images.githubusercontent.com/738834/234742138-872541d1-e6f8-48f4-8fbf-3dce1ddcc7f3.png)

**Comment by OlivierDehaene** [comment]
@njhill

**Comment by njhill** [comment]
@paulcx what model are you using here?

**Comment by paulcx** [comment]
> @paulcx what model are you using here?

bigscience/bloom-7b1

**Comment by njhill** [comment]
@paulcx @OlivierDehaene OK I see it, my bad, fix incoming.

**Comment by paulcx** [comment]
> @paulcx @OlivierDehaene OK I see it, my bad, fix incoming.

It's fixed now. Thanks.
