### ISSUE TITLE
Run Locally instructions don't work

### ISSUE THREAD

**Issue by gabriel-peracio** [huggingface/text-generation-inference#2581]
The readme states this:

![image](https://github.com/user-attachments/assets/fdd2ff8d-4575-4058-a7d2-c71f379cc214)

However, the command does not work:

![image](https://github.com/user-attachments/assets/3bb9b6ca-d9a1-4a4f-9437-d695d3e94e4e)

Please fix the instructions, they are obviously incorrect

**Comment by hahmad2008** [comment]
@gabriel-peracio how did you install it? from source?

**Comment by gabriel-peracio** [comment]
I managed to run it, but really it ought to be explained that you should follow the local install instructions - it's not like vllm where you simply `pip install` and then the command becomes available in the PATH

Thank you
