### ISSUE TITLE
Add support for Llama 3.2 vision / Mllama

### ISSUE THREAD

**Issue by elliottlawrence** [huggingface/text-generation-inference#2598]
### Feature request

Llama 3.2 vision seems to have a new model type "mllama" which TGI does not natively support. I saw there's an open PR for this (#2585) but wanted to create an issue in case others were searching for this as well.

Also, any expected timeline for when this would be released?

### Motivation

transformers >= 4.45.0 supports this, so it seems that TGI should as well.

### Your contribution

#2585 is already open.

**Comment by Narsil** [comment]
This took a bit more time because TGI supports mllama with flash kernels without padding so it should end up being much faster than `transformers` and also alleviates some issues that `transformers` runs into.
