### ISSUE TITLE
Errors Encountered in Execution Log: Issues with LD_PRELOAD and Missing Shared Library

### ISSUE THREAD

**Issue by paulcx** [huggingface/text-generation-inference#2618]
### System Info

08T07:24:45.800673489Z ERROR: ld.so: object '/opt/conda/lib/python3.10/site-packages/nvidia/nccl/lib/libnccl.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

08T07:24:45.801550536Z text-generation-launcher: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker version: sha-f6e2f05

### Expected behavior

how to fix it?

**Comment by danieldk** [comment]
How are you starting Docker? `f6e2f05` is the 2.3.1 release and I don't the error when running the container using e.g.:

```shell
model=HuggingFaceH4/zephyr-7b-beta
# share a volume with the Docker container to avoid downloading weights every run
volume=$PWD/data

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data \
    ghcr.io/huggingface/text-generation-inference:2.3.1 --model-id $model
```

**Comment by paulcx** [comment]
> How are you starting Docker? `f6e2f05` is the 2.3.1 release and I don't the error when running the container using e.g.:
> 
> ```shell
> model=HuggingFaceH4/zephyr-7b-beta
> # share a volume with the Docker container to avoid downloading weights every run
> volume=$PWD/data
> 
> docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data \
>     ghcr.io/huggingface/text-generation-inference:2.3.1 --model-id $model
> ```

It's the same and I don't think there's an issue with the launch command since there's no problem in the previous version.

**Comment by jegork** [comment]
I managed to get past 
`text-generation-launcher: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory`
by removing `LD_LIBRARY_PATH` env variable (running on GKE)

**Comment by paulcx** [comment]
> I managed to get past `text-generation-launcher: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory` by removing `LD_LIBRARY_PATH` env variable (running on GKE)

how do you remove the LD_LIBRARY_PATH env variable? in docker image?

**Comment by jegork** [comment]
In my case we set it previously in the kubernetes pod spec

**Comment by paulcx** [comment]
You are right. It works by removing LD_LIBRARY_PATH!
