### ISSUE TITLE
[BUG] The bloom custom kernel is wrong !

### ISSUE THREAD

**Issue by AlongWY** [huggingface/text-generation-inference#263]
We test the bloom with/without the custom kernel, and the result is too different.

**Comment by Narsil** [comment]
What kind of hardware ?

As explained, the kernel was only tested on A100 and produced the same results (up to standard small differences which are to be expected when using different computation).

**Comment by Narsil** [comment]
We're going to need a lot more information if you want us to be able to do anything here btw.
The hardware is just the start, then what kind of differences, and provide reproducible examples if possible.

I will go ahead and close this, feel free to reopen when you have more information to provide so we can investigate.
