### ISSUE TITLE
Llama inference using docker.

### ISSUE THREAD

**Issue by saul-jb** [huggingface/text-generation-inference#265]
I am trying to run this through docker with a llama model (7B):

```
docker run --gpus all --shm-size 1g -p 8081:80 -v ./7B-transformed:/data/7B ghcr.io/yk/text-generation-inference:llama --model-id /data/7B --num-shard 1
```

And I am getting this error:

```
2023-05-01T23:17:01.028474Z  INFO text_generation_launcher: Starting Webserver
tokenizer_name: /data/7B
is_llama: false
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum NormalizerWrapper", line: 49, column: 3)', router/src/main.rs:103:73
```

I have transformed the model using the [transformer](https://github.com/huggingface/transformers/commits/d04ec99bec8a0b432fc03ed60cea9a1a20ebaf3c).

The `7B-transformed` directory contains the following files:

```
config.json
generation_config.json
pytorch_model-00001-of-00002.bin
pytorch_model-00002-of-00002.bin
pytorch_model.bin.index.json
special_tokens_map.json
tokenizer_config.json
tokenizer.json
tokenizer.model
```

Why is it saying `is_llama: false` shortly before crashing and what is causing this error?

**Comment by Narsil** [comment]
The `tokenizer.json` is probably malformed, which one are you using ? 

This one should be correct: https://huggingface.co/hf-internal-testing/llama-tokenizer

**Comment by saul-jb** [comment]
> The `tokenizer.json` is probably malformed, which one are you using ?
> 
> This one should be correct: https://huggingface.co/hf-internal-testing/llama-tokenizer

I was using the one produced by the transformer script. I have also tested with the files from the link you sent and got the same results.

I have also tried the files here: https://huggingface.co/decapoda-research/llama-7b-hf but get a different error:

`IndexError: piece id is out of range.`

**Comment by Narsil** [comment]
Could you try running this image ? 

```
ghcr.io/huggingface/text-generation-inference:latest
```

I just noticed you were running yk version and I have no idea how old it is or what it is doing.

**Comment by saul-jb** [comment]
> I just noticed you were running yk version and I have no idea how old it is or what it is doing.

Thanks, I missed that too, everything seems to work properly on the proper image.
