### ISSUE TITLE
Unable to load GPTQ LoRA Adapter

### ISSUE THREAD

**Issue by SMAntony** [huggingface/text-generation-inference#2653]
### System Info

text-generation-inference version: 2.3.1
OS version: Ubuntu 22.04
Model: TheBloke/WizardLM-13B-V1.2-GPTQ
GPU used:
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10G                    Off |   00000000:00:1E.0 Off |                    0 |
|  0%   29C    P0             62W /  300W |   20405MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      9579      C   /opt/conda/bin/python3.11                   20396MiB |
+-----------------------------------------------------------------------------------------+

Ubuntu deployment using docker.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Use LORA with TheBloke/WizardLM-13B-V1.2-GPTQ model revision (gptq-8bit-128g-actorder_False).
2. Says AttributeError: 'GPTQMarlinLinear' object has no attribute 'weight' rank=0

### Expected behavior

Expecting GPTQ LoRAs to be supported by TGI.
When run with LoRAs:
![image](https://github.com/user-attachments/assets/8682051f-82b0-4cf3-b646-14dbda243501)

When run without LoRAs:
![image](https://github.com/user-attachments/assets/7d0f62fc-80cd-49c8-8cfd-b590c04edd86)

**Comment by SMAntony** [comment]
I have tried disabling Marlin by setting sym=False in quantize_config. When I am loading just the base model through TGI, its working. When I tried to load with Adapter (QLORA), it throws the following error:

```
│ │               dtype=torch.int32))])                                      │ │
│ │ _parameters = OrderedDict()                                              │ │
│ │     modules = OrderedDict()                                              │ │
│ │        name = 'weight'                                                   │ │
│ │        self = QuantLinear()                                              │ │
│ ╰──────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'QuantLinear' object has no attribute 'weight' rank=0
2024-10-16T02:02:01.151366Z ERROR text_generation_launcher: Shard 0 failed to start
2024-10-16T02:02:01.151567Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

**Comment by SMAntony** [comment]
@danieldk could you please have a look?

**Comment by drbh** [comment]
Hi @SMAntony, at the moment TGI does not support GPTQ-quantized LoRA adapters, a non quantized adapter may resolve your issue. 

We'll be exploring adding qlora in the future but currently the kernels we're using do not support quantized operations.

**Comment by SMAntony** [comment]
On the side note, is it not possible to prompt saying "GPTQ Lora is not supported", if I am not wrong, it used to say that earlier. What's changed?
