### ISSUE TITLE
Optionally log input tokens/prompt

### ISSUE THREAD

**Issue by sam-ulrich1** [huggingface/text-generation-inference#2667]
### Feature request

Optionally log the input prompt/tokens for improved debugging.

### Motivation

I am currently attempting to debug why in a prod env I am getting garbage but when replicating the requests with the same inputs (I believe) to the same server I get the correct output. I can't seem to find anything indicating why I am experiencing this issue so my only assumption is there is something, somewhere in my code that is sending a different input to `generate` than I am seeing in my logs. If I was able to validate that the tgi server is or is not getting the same input I believe it is receiving then I could better debug.

### Your contribution

Happy to provide the commit if you are willing to accept this

**Comment by claudioMontanari** [comment]
Prompts should be logged (as well as other info) if you start the server with `LOG_LEVEL=debug text-generation-launcher ...`.

Hope this helps!

**Comment by sam-ulrich1** [comment]
Awesome, thank you
