### ISSUE TITLE
`FlashLlamaForCausalLM`'s using name `dense` for its mlp submodule causes error when using LoRA adapter

### ISSUE THREAD

**Issue by sadra-barikbin** [huggingface/text-generation-inference#2715]
Hi there! 🤗

`FlashLlamaForCausalLM` uses name `dense` for its MLP submodule and when user wants to employ a LoRA adapter, `get_mlp_weights` skips this submodule.

https://github.com/huggingface/text-generation-inference/blob/6e3220529df5906ae586031873b7865e9923040b/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py#L440

https://github.com/huggingface/text-generation-inference/blob/6e3220529df5906ae586031873b7865e9923040b/server/text_generation_server/utils/adapter.py#L259-L261

This causes error:
```
[rank0]: KeyError: (0, 'gate_proj')
```

This is not the case for `FlashGemma2ForCausalLM`, for example, and it works properly. When I renamed `dense` to `mlp` , llama worked as well.

**Comment by koutarou-n** [comment]
I faced the same error.
It succesfully works on release 2.3.0, but failed on 2.3.1, 2.4.0.

**Comment by sadra-barikbin** [comment]
Yes, it's fixed. Thanks.
