### ISSUE TITLE
Argument `--weights-cache-override` is not effective

### ISSUE THREAD

**Issue by comaniac** [huggingface/text-generation-inference#273]
### System Info

text-generation-inference commit: [85aa7e2](https://github.com/huggingface/text-generation-inference/commit/85aa7e2e7b02608eea04206b6cc0fa0ccced80ef)

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Clone the repo: `git clone https://huggingface.co/bigscience/bloom-560m` to `~/bloom-560m`.
2. Launch server with `--weights-cache-override`:

```
text-generation-launcher --model-id bigscience/bloom-560m \
--num-shard 2 --port 8080 \
--weights-cache-override ~/bloom-560m
```

### Expected behavior

The launcher should skip the download process, but it ignores `--weights-cache-override` and still downloads the weights to `~/.cache/huggingface/hub`.

After tracing the code, it is due to #266, which changes the logic of determining whether to download the weights. Specifically, `main` now always downloads the weights regardless `args.weights_cache_override`.  The original logic is moved to `cli.py:download_weights`. However, it can only check the environment variable `WEIGHTS_CACHE_OVERRIDE`. As a result, the environment variable `WEIGHTS_CACHE_OVERRIDE` should be updated by `args.weights_cache_override`. However, this logic lies in `main.rs:shard_manager`, which is invoked _after_ the download process.

cc @OlivierDehaene

**Comment by cipri-tom** [comment]
I believe this is still not working. 

I ran `text-generation-launcher --model-id mistralai/Mistral-7B-Instruct-v0.2 --weights-cache-override /workspace/models/` 
from inside the container and then it still wrote to the `/data` folder
