### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.models.bloom.parallel_layers

### ISSUE THREAD

**Issue by MoaazZaki** [huggingface/text-generation-inference#281]
### System Info

text-generation-launcher 0.4.0
model: llama (`TheBloke/OpenAssistant-SFT-7-Llama-30B-HF`)
Environment: AWS server (Docker)
Hardware used: CPU 
transformers 4.27.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

The module raise this on start:

open-assistant-inference-worker-1  | Traceback (most recent call last):
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/bin/text-generation-server", line 5, in <module>
open-assistant-inference-worker-1  |     from text_generation_server.cli import app
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/cli.py", line 9, in <module>
open-assistant-inference-worker-1  |     from text_generation_server import server, utils
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/server.py", line 12, in <module>
open-assistant-inference-worker-1  |     from text_generation_server.cache import Cache
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/cache.py", line 3, in <module>
open-assistant-inference-worker-1  |     from text_generation_server.models.types import Batch
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 8, in <module>
open-assistant-inference-worker-1  |     from text_generation_server.models.bloom import BLOOM, BLOOMSharded
open-assistant-inference-worker-1  |   File "/opt/miniconda/envs/text-generation/lib/python3.9/site-packages/text_generation_server/models/bloom.py", line 14, in <module>
open-assistant-inference-worker-1  |     from transformers.models.bloom.parallel_layers import (
open-assistant-inference-worker-1  | ModuleNotFoundError: No module named 'transformers.models.bloom.parallel_layers'

### Expected behavior

The initializatio works

**Comment by Narsil** [comment]
> text-generation-launcher 0.4.0

Can you try on latest ?

**Comment by Narsil** [comment]
Try `ghcr.io/huggingface/text-generation-inference:latest`.

**Comment by OlivierDehaene** [comment]
Feel free to re-open if the issue persists with `ghcr.io/huggingface/text-generation-inference:latest`
