### ISSUE TITLE
`bigcode/starcoderbase` : "unable to parse model info" error on model loading

### ISSUE THREAD

**Issue by dpfried** [huggingface/text-generation-inference#289]
### System Info

Command line:
`RUST_BACKTRACE=1 text-generation-launcher --model-id bigcode/starcoderbase --num-shard 1 --port 8080`

Version: commit `880a76e`, with a local install following the instructions [here](https://github.com/huggingface/text-generation-inference#local-install)

System info (from `text-generation-launcher --env`):
```2023-05-06T00:43:12.225254Z  INFO text_generation_launcher: Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.69.0
Commit sha: N/A
Docker label: N/A
nvidia-smi:
Fri May  5 20:43:12 2023
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                               |                      |               MIG M. |
   |===============================+======================+======================|
   |   0  RTX A6000           On   | 00000000:03:00.0 Off |                  Off |
   | 30%   31C    P8    21W / 300W |      0MiB / 48685MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+

   +-----------------------------------------------------------------------------+
   | Processes:                                                                  |
   |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
   |        ID   ID                                                   Usage      |
   |=============================================================================|
   |  No running processes found                                                 |
   +-----------------------------------------------------------------------------+
```

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Hi, my command line is
`RUST_BACKTRACE=1 text-generation-launcher --model-id bigcode/starcoderbase --num-shard 1 --port 8080`

and the error and stack trace I'm getting are

```
thread 'main' panicked at 'unable to parse model info: Error("missing field `id`", line: 1, column: 41)', router/src/main.rs:276:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: text_generation_router::get_model_info::{{closure}}
   4: text_generation_router::main::{{closure}}
             at ./router/src/main.rs:148:89
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/dfried/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at /home/dfried/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /home/dfried/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /home/dfried/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/park.rs:283:31
   9: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/dfried/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/context.rs:315:13
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/dfried/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  11: tokio::runtime::runtime::Runtime::block_on
             at /home/dfried/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.0/src/runtime/runtime.rs:304:45
  12: text_generation_router::main
             at ./router/src/main.rs:121:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
```

I also get the error above on `main`, commit `b4aa87db58ea3d87ff820b6d7abeaa20a987df00` for the `bigcode/starcoderbase` model, but on main I am able to successfully serve `bigcode/santacoder` with the command `RUST_BACKTRACE=1 text-generation-launcher --model-id bigcode/santacoder --num-shard 1 --port 8080`.

### Expected behavior

I'm expecting the model to start.

**Comment by hudengjunai** [comment]
I have encountered the same problem.

**Comment by hudengjunai** [comment]
2023-05-06T03:56:33.745526Z  INFO text_generation_launcher: Starting Webserver
2023-05-06T03:56:34.249663Z  WARN text_generation_router: router/src/main.rs:135: Could not find a fast tokenizer implementation for bigcode/starcoderbase
2023-05-06T03:56:34.249687Z  WARN text_generation_router: router/src/main.rs:138: Rust input length validation and truncation is disabled
thread 'main' panicked at 'unable to parse model info: Error("missing field `id`", line: 1, column: 41)', router/src/main.rs:276:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: text_generation_router::get_model_info::{{closure}}
   4: text_generation_router::main::{{closure}}
             at ./router/src/main.rs:148:89
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/park.rs:283:31
   9: tokio::runtime::context::BlockingRegionGuard::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/context.rs:315:13
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  11: tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/runtime.rs:304:45
  12: text_generation_router::main
             at ./router/src/main.rs:121:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-05-06T03:56:34.952096Z ERROR text_generation_launcher: Webserver Crashed
2023-05-06T03:56:34.952118Z  INFO text_generation_launcher: Shutting down shards
2023-05-06T03:56:37.187619Z  INFO text_generation_launcher: Shard 0 terminated

**Comment by hudengjunai** [comment]
![image](https://user-images.githubusercontent.com/33210026/236603000-ae39c433-64ca-4e1c-bc39-1fd0fbc2e285.png)

**Comment by hudengjunai** [comment]
perhelps because of client.get starcoderbase reversion ifo failed

**Comment by hudengjunai** [comment]
even i have huggingface-cli login with token, Still failed to get the model info

**Comment by hudengjunai** [comment]
the text-generation-inference is so tight bound to huggingface-repo

**Comment by hudengjunai** [comment]
Try https://huggingface.co/docs/huggingface_hub/package_reference/hf_api this lib.

**Comment by OlivierDehaene** [comment]
Starcoder and starcoderbase are both gated models.
You need to add your hf token as an environment variable to use them. 

`export HUGGING_FACE_HUB_TOKEN=<token>` for the cli or `-e HUGGING_FACE_HUB_TOKEN=<token>` for docker 

The error message will be improved in the future.
