### ISSUE TITLE
MPT support 

### ISSUE THREAD

**Issue by generalsvr** [huggingface/text-generation-inference#290]
### Model description

Can you add a new MPT model? This looks very promising, especially the ability to extend context length by up to 85K tokens. 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://github.com/mosaicml/llm-foundry

**Comment by vvsotnikov** [comment]
Probably a related issue: https://github.com/huggingface/transformers/issues/23174

**Comment by monuminu** [comment]
any plan on supporting mosaicml/mpt-30b-instruct support

**Comment by ccasimiro88** [comment]
I am also interested in deploying the `mosaicml/mpt-30b-chat` model. Would be really useful for the community! :pray:

**Comment by tim-a-davis** [comment]
Yes I am also interested in getting support for MPT models.  I would love to assist in any way I can.

**Comment by mantrakp2004** [comment]
+1

**Comment by alanxmay** [comment]
please🙏

**Comment by mantrakp2004** [comment]
> Yes I am also interested in getting support for MPT models.  I would love to assist in any way I can.

Hey wanna work on the implementation then we can do a pr, add me on discord mantrakp- proud Logitech controller owner

**Comment by Narsil** [comment]
https://github.com/huggingface/text-generation-inference/pull/514
