### ISSUE TITLE
Why flash llama use bf16?

### ISSUE THREAD

**Issue by frankxyy** [huggingface/text-generation-inference#295]
I find the results from flash llama inference is of type bf16. Why don't use fp16?

**Comment by Narsil** [comment]
Is there any problem to using `bf16` ?

We're moving some models to f16 btw. (Seems some kernels are doing better in f16 than bf16 in terms of numerical stability).

**Comment by frankxyy** [comment]
@Narsil  I use bf16 for infering a model, the result is worse than that of fp16. The model is trained with fp16 I think. So the dtype selected for inference need to be the same with the type in model training?

**Comment by Narsil** [comment]
>  need to be the same with the type in model training?

In general that's a good idea yes. We already moved everything to f16 (bf16 -> f16 seems resilient enough)
