### ISSUE TITLE
Pypi out of date (0.5.1)

### ISSUE THREAD

**Issue by edward-io** [huggingface/text-generation-inference#296]
### Feature request

[Pypi](https://pypi.org/project/text-generation/#history) is currently showing the latest version of `text-generation` is 0.5.1, but the most recent Github release is 0.6.0.

### Motivation

N/A

### Your contribution

N/A

**Comment by OlivierDehaene** [comment]
The python client version is [0.5.1](https://github.com/huggingface/text-generation-inference/blob/main/clients/python/pyproject.toml#L3).
