### ISSUE TITLE
Dimension mismatch after partial complete of a batch

### ISSUE THREAD

**Issue by pohunghuang-nctu** [huggingface/text-generation-inference#3]
Hi, 
    I tested the batch size == 4, once any member of batch completed, the dimensions of past key values will be split from 3 into 4, as line pointed out in below url, and in next round of "generate_token" (while doing "forward"), exception will raise.  
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation/models/causal_lm.py#L363

**Comment by OlivierDehaene** [comment]
Hello @pohunghuang-nctu,

Can you re-install Transformers using the following commands and tell me if the problem persists? Thanks!

```bash
pip uninstall transformers

cd text-generation-inference/server
make install-transformers
```

**Comment by pohunghuang-nctu** [comment]
Yes, problem resolved, thank you and sorry for late response
