### ISSUE TITLE
Request for adding OpenAssistant/pythia-12b-sft-v8-7k-steps to HF inference API.

### ISSUE THREAD

**Issue by gsaivinay** [huggingface/text-generation-inference#300]
### Feature request

Recently, OpenAssistant team release new version of Pythia 12b model `OpenAssistant/pythia-12b-sft-v8-7k-steps`. Would it be possible to replace older Pythia model with this latest release on Hugging face inference widget?

### Motivation

To interact with latest pythia moodel

### Your contribution

N/A

**Comment by OlivierDehaene** [comment]
Can you open a [discussion](https://huggingface.co/OpenAssistant/pythia-12b-sft-v8-7k-steps/discussions) on the model card instead? thanks.
