### ISSUE TITLE
Slow performance in Quantization

### ISSUE THREAD

**Issue by gsaivinay** [huggingface/text-generation-inference#309]
### System Info

When running docker image `sha-49cffad` with quantization, the time per token is around 110ms vs 18ms when running without quantization.

Model: OpenAssistant/pythia-12b-sft-v8-7k-steps
Machine: AWS EC2 g5 12xlarge
Args: 
```
model=OpenAssistant/pythia-12b-sft-v8-7k-steps
num_shard=4
volume=$PWD/hfcache

sudo docker run --gpus all --shm-size 1g \
-p 8080:80\
 -v $volume:/data ghcr.io/huggingface/text-generation-inference:sha-49cffad \
 --model-id $model --num-shard $num_shard --disable-custom-kernels \
 --quantize 
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Run above mentioned command with and without quantization.

### Expected behavior

Expecting performance would be similar for with and without `quantize` argument.

**Comment by gsaivinay** [comment]
Also noticed that GPU utilization is around 50% with quantization compared to 99% without quantization with below command.

`watch -n0.2 nvidia-smi`

**Comment by Narsil** [comment]
Yes this is known `bitsandbytes` is definitely slower at inference.

We're using gptq to get similar performance (but conversion requires some dataset). See https://github.com/huggingface/text-generation-inference/pull/267 for ugly support. 

Ideally we'd like to make it a simple switch between bitsandbytes (which doesn´t require dataset or modifying the weights substantially) and gptq (which requires both).

**Comment by gsaivinay** [comment]
Cool, really looking forward for this implementation. Would it be supported for all models or just llama type?

All these days I'm running in quantization mode, then I tried without quantization today and was mind blown seeing the performance difference. Cannot afford to always spin that big instance though.

**Comment by gsaivinay** [comment]
@Narsil - Just asking out of curiosity, there is an issue open in bitsandbytes repo [here](https://github.com/TimDettmers/bitsandbytes/issues/6), and it talks about adding `int8_threshold=0` as a parameter to improve performance by 2-3times. Is that parameter tried with this text generation server?

**Comment by Narsil** [comment]
Issue is one year old, and performance (as in downstream performance in perplexity) is not discussed. I wouldn't hold my beer on it.

also GPTQ is 4bit quantization (not 8bit).
