### ISSUE TITLE
Running a model from the Docker container without internet connectivity

### ISSUE THREAD

**Issue by seanmor5** [huggingface/text-generation-inference#311]
### Feature request

Apologies if this is already supported, I went through the source and noticed that the code mentions you can pass a local directory with a model in it as a model_id, but it seems to me that the launcher which runs when the container is started always attempts to download and convert the weights.

I would like to be able to explicitly pass `./path/to/local/dir` as model_id so it doesn't attempt to download a model.

### Motivation

I am launching the container in an environment without external routes

### Your contribution

I can look into it, but I'm not very familiar with Rust or this code base. If it's just a matter of adding documentation, I can definitely help there

**Comment by Narsil** [comment]
Try adding `-e HUGGINGFACE_OFFLINE=1` to force it into offline mode (which means it will try to read things from disk and look at the latest versions if multiple exists).

That means that your data directory needs to have the correctly formatted files (most likely downloaded *with* access to internet :))

**Comment by rodgermoore** [comment]
Did you manage to get this to work? Its just seems impossible to get this to work and debugging is difficult as you can't bash or shell into a container. I use an online docker environment to download models and copy the cache dir, then mount this to /data but no luck. -e HUGGINGFACE_OFFLINE=1 doesn't seem to do anything. Really looking for some guidance on this. Thanks.

**Comment by ai792** [comment]
Same problem, trying to make this happen.

**Comment by seanmor5** [comment]
I did indeed get this working but not in the way you might expect. I had to override the entry point of the Docker container to run /bin/bash instead. And then I ran the server, copied my model which was mounted in the suggested /data to /usr/src (for some reason it would not work from data)

Then I ran the text generation server command to launch the server, specifying the weights cache as the /usr/src directory and the model as a relative path within that. In my case the model was flan-t5-xl so I just specified the model as that.

I can post a full write up in a bit. Any attempts I had to get this to work by just running the container failed, even specifying the HF offline env variable

**Comment by rodgermoore** [comment]
> I did indeed get this working but not in the way you might expect. I had to override the entry point of the Docker container to run /bin/bash instead. And then I ran the server, copied my model which was mounted in the suggested /data to /usr/src (for some reason it would not work from data)
> 
> Then I ran the text generation server command to launch the server, specifying the weights cache as the /usr/src directory and the model as a relative path within that. In my case the model was flan-t5-xl so I just specified the model as that.
> 
> I can post a full write up in a bit. Any attempts I had to get this to work by just running the container failed, even specifying the HF offline env variable

Amazing. A write up would be amazing. It would be a great feature if the "offline" mode of the Docker container would be implemented (better).

**Comment by seanmor5** [comment]
This is quite the hack, but here's exactly what I did:

1. Downloaded a model locally and copied it over to my other restricted environment. The model directory (in my case `flan-t5-xl`) sits in `/home/ubuntu/data`
2. Started the docker container with:

```
docker run --entrypoint /bin/bash \
			-it \
			-v /home/ubuntu/data:/data \
			--gpus all \
			-p 8000:80 \
			ghcr.io/huggingface/text-generation-inference:latest
```

This will launch a shell inside the container in `usr/src`. You can verify your model is in `/data` in the container by listing the contents. You can first try launching the model from `/data`:

```
text-generation-launcher \
	--model-id flan-t5-xl \
	--quantize \
	--num-shard 1 \
	--huggingface-hub-cache /data \
	--weights-cache-override /data
```

However, for some reason that *does not* work. In my case it just hangs at the download process forever. Instead I had to run:

```
cp -r /data/flan-t5-xl/ .
```

From `/usr/src` and then run the launcher again with the cache overrides:

```
text-generation-launcher \
	--model-id flan-t5-xl \
	--quantize \
	--num-shard 1 \
	--huggingface-hub-cache /usr/src \
	--weights-cache-override /usr/src
```

This works almost instantly. You'll likely see something about the launcher converting your model to safetensors format (unless your model is already in safetensors format).

It's not clear to me why it doesn't pick up the model in `/data`, or why this won't work when just launching the container.

**Comment by rodgermoore** [comment]
> This is quite the hack, but here's exactly what I did:
> 
> Downloaded a model locally and copied it over to my other restricted environment. The model directory (in my case `flan-t5-xl`) sits in `/home/ubuntu/data`
> 
> Started the docker container with:
> 
> ```
> docker run --entrypoint /bin/bash \
> 			-it \
> 			-v /home/ubuntu/data:/data \
> 			--gpus all \
> 			-p 8000:80 \
> 			ghcr.io/huggingface/text-generation-inference:latest
> ```
> 
> This will launch a shell inside the container in `/usr/src`. You can verify your model is in `/data` in the container by listing the contents. You can first try launching the model from `/data`:
> 
> ```
> text-generation-launcher \
> 	--model-id flan-t5-xl \
> 	--quantize \
> 	--num-shard 1 \
> 	--huggingface-hub-cache /data \
> 	--weights-cache-override /data
> ```
> 
> However, for some reason that _does not_ work. In my case it just hangs at the download process forever. Instead I had to run:
> 
> ```
> cp -r /data/flan-t5-xl/ .
> ```
> 
> From `/usr/src` and then run the launcher again with the cache overrides:
> 
> ```
> text-generation-launcher \
> 	--model-id flan-t5-xl \
> 	--quantize \
> 	--num-shard 1 \
> 	--huggingface-hub-cache /usr/src \
> 	--weights-cache-override /usr/src
> ```
> 
> This works almost instantly. You'll likely see something about the launcher converting your model to safetensors format (unless your model is already in safetensors format).
> 
> It's not clear to me why it doesn't pick up the model in `/data`, or why this won't work when just launching the container.

Thank you so much, this works!

**Comment by OlivierDehaene** [comment]
I think there are some confusion in this thread because the documentation on running local models doesn't exist. You can run local models with the latest image without modifications and without using `--weights-cache-override`.

For example:

```shell
cd /data

# Make sure you have git lfs installed
git clone https://huggingface.co/google/flan-t5-xl

# note the `--network none` that makes sure that we cannot connect to hf.co inside the running container
# note the `--model-id /data/flan-t5-xl` that points to the previously download model 
docker run --rm --network none --gpus all -p 8080:80 -v /data:/data --pull always  ghcr.io/huggingface/text-generation-inference:latest --model-id /data/flan-t5-xl
```

The reason why copying to `/usr/src` worked is because it copied the model to the `/usr/src/flan-t5-xxl` directory, which was then correctly picked up by tgi as a model directory when passing the `--model-id flan-t5-xl` argument since the launcher current directory is `/usr/src`. 
If you point to `/data/flan-t5-xl` directly using `--model-id /data/flan-t5-xl`, it should work out of the box.

**Comment by andrewjmoser** [comment]
> I think there are some confusion in this thread because the documentation on running local models doesn't exist. You can run local models with the latest image without modifications and without using `--weights-cache-override`.
> 
> For example:
> 
> ```shell
> cd /data
> 
> # Make sure you have git lfs installed
> git clone https://huggingface.co/google/flan-t5-xl
> 
> # note the `--network none` that makes sure that we cannot connect to hf.co inside the running container
> # note the `--model-id /data/flan-t5-xl` that points to the previously download model 
> docker run --rm --network none --gpus all -p 8080:80 -v /data:/data --pull always  ghcr.io/huggingface/text-generation-inference:latest --model-id /data/flan-t5-xl
> ```
> 
> The reason why copying to `/usr/src` worked is because it copied the model to the `/usr/src/flan-t5-xxl` directory, which was then correctly picked up by tgi as a model directory when passing the `--model-id flan-t5-xl` argument since the launcher current directory is `/usr/src`. If you point to `/data/flan-t5-xl` directly using `--model-id /data/flan-t5-xl`, it should work out of the box.

When I run the commands as you have them listed, I am getting this error:

huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/flan-t5-xl'. Use `repo_type` argument if needed.

**Comment by YinSonglin1997** [comment]
> > I think there are some confusion in this thread because the documentation on running local models doesn't exist. You can run local models with the latest image without modifications and without using `--weights-cache-override`.
> > For example:
> > ```shell
> > cd /data
> > 
> > # Make sure you have git lfs installed
> > git clone https://huggingface.co/google/flan-t5-xl
> > 
> > # note the `--network none` that makes sure that we cannot connect to hf.co inside the running container
> > # note the `--model-id /data/flan-t5-xl` that points to the previously download model 
> > docker run --rm --network none --gpus all -p 8080:80 -v /data:/data --pull always  ghcr.io/huggingface/text-generation-inference:latest --model-id /data/flan-t5-xl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The reason why copying to `/usr/src` worked is because it copied the model to the `/usr/src/flan-t5-xxl` directory, which was then correctly picked up by tgi as a model directory when passing the `--model-id flan-t5-xl` argument since the launcher current directory is `/usr/src`. If you point to `/data/flan-t5-xl` directly using `--model-id /data/flan-t5-xl`, it should work out of the box.
> 
> When I run the commands as you have them listed, I am getting this error:
> 
> huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/flan-t5-xl'. Use `repo_type` argument if needed.

I have the same problem, have you  solved it yet?
