### ISSUE TITLE
StarCoder not working as expected 

### ISSUE THREAD

**Issue by yureikami** [huggingface/text-generation-inference#316]
### System Info

we are trying to run the star coder model from huggingface but it is always returning end of string token 
this behavior is not present when we execute the same model using hugging face pipelines. 
our configuration is as follows -> 
Nvidia-SMI
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 17%   30C    P0    58W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
| 18%   29C    P0    58W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:81:00.0 Off |                  N/A |
| 20%   31C    P0    55W / 250W |      0MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:82:00.0 Off |                  N/A |
| 23%   36C    P0    58W / 250W |      0MiB / 11264MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
cargo 1.69.0 (6e9a83356 2023-04-12)
OS version ; ubuntu 22.02
we are on the latest version 
command used  -> 
CUDA_VISIBLE_DEVICES=0,1,2,3 make run-starcoder

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

we cloned the star coder repo and adjusted the make command to work with those weights 
make file -> 
run-starcoder:
	text-generation-launcher --model-id bigcode/starcoder --port 8080 --num-shard 1

CUDA_VISIBLE_DEVICES=0,1,2,3 make run-starcoder

### Expected behavior

the server gets up but whenever we execute the call we get an EOF token nothing else

**Comment by OlivierDehaene** [comment]
Yes there was an issue with sha-a6c18c3. Use [sha-4f6d038](https://github.com/orgs/huggingface/packages/container/text-generation-inference/92435792?tag=sha-4f6d038).

**Comment by yureikami** [comment]
Hi @OlivierDehaene We are using the local setup can you point towards a specific branch if available ?
