### ISSUE TITLE
ShardedFlashLlama generates unexpected response for really long prompt

### ISSUE THREAD

**Issue by frankxyy** [huggingface/text-generation-inference#321]
Model: Llama 13b with fine-tuning

When the prompt is of length 300，the expected answer of length 200 is generated. When I add two more tokens to the prompt, the answer will be only of length 2(expected to be of length around 200).

Plus: It works well when the llama model is not sharded.

**Comment by OlivierDehaene** [comment]
Sorry but I cannot start to understand the issue from the info you provided.
Please add details (maybe use the issue template?) and feel free to re open.

**Comment by frankxyy** [comment]
@OlivierDehaene Hi , what I mean is that the output of `FlashLlama` and `ShardedFlashLlama` may not be same with the same input at some situation. The cases I found is when the input sequence length is very high.

**Comment by frankxyy** [comment]
I find that I cannot reopen this issue
