### ISSUE TITLE
Guidance on parameter tuning to avoid OOM

### ISSUE THREAD

**Issue by jimcarreer** [huggingface/text-generation-inference#322]
This is more a question, I find often when I'm trying to run / use a particular model I run into OOMs.  I'm just using consumer grade hardware at this point, I've just got a single GPU with about 8GB of memory to play with. 

Are there any resources I can be directed too for:
1. Even estimating if I can run a particular model given available hardware (I assume there are some models where it is not possible given my hardware)
2. Tuning parameters for models+hardware to avoid OOMs.

**Comment by Narsil** [comment]
Hi,

I think you can find the answer to these pretty much everywhere on the internet:

1. Look at the size of the model on disk, it's a good indication of the minimum requirements to run the model, you still need an extra GB to actually run the inference (proper calculations can be made if you want, but ballparks are usually enough).
2. you want to check `MAX_TOTAL_TOKENS` flag, which determines the maximum amount of tokens that can be run on the model (it's linear in RAM requirements so just find the highest that fits your RAM)

I'm closing this, feel free to reopen !

Thanks for your interest !
