### ISSUE TITLE
Long build time from source

### ISSUE THREAD

**Issue by bilelomrani1** [huggingface/text-generation-inference#330]
I am trying to install the server locally without Docker on an NVIDIA A100. The build command `BUILD_EXTENSIONS=True make install` seems to take a very long time (> 6hours). Is it expected? What is the typical build time?

**Comment by OlivierDehaene** [comment]
No that's not normal, especially if you are installing flash attention. You can install ninja-build to speed up build times.

**Comment by bilelomrani1** [comment]
Yes exactly, installing flash attention seems to take quiet long. Do you know how long is it expected to take approximately? Is it of the order of 12h, 24h or more?

**Comment by bilelomrani1** [comment]
Sorry, now I recall more precisely the issue that I encountered: `BUILD_EXTENSIONS=True make install` worked correctly but the server complained that the flash attention wasn't installed. So I ran `cd server && make install` and this was the part that took a long time to run.
