### ISSUE TITLE
Does it support OpenAssistant/oasst-sft-6-llama-30b?

### ISSUE THREAD

**Issue by PierrePeng** [huggingface/text-generation-inference#350]
### Model description

Hi,

I see there is a [supported_models list ](https://github.com/huggingface/text-generation-inference/blob/main/supported_models.json).

I wanna know if it works available on OpenAssistant/oasst-sft-6-llama-30b model which has been converted and stored on my local?  If YES, have any recommendations that how to run my local model for inference?

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

[OpenAssistant/oasst-sft-6-llama-30b-xor ](https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor)

**Comment by dongs0104** [comment]
1. download and convert follow as https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor
2. conver torch tensor(bin) to safetensors 
3. follow https://github.com/huggingface/text-generation-inference/issues/311
```sh
model=`model path`
num_shard=`your system size`
volume=`../model_path`  # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:0.6.0 --model-id $model --num-shard $num_shard
```

**Comment by OlivierDehaene** [comment]
Cheers @dongs0104

**Comment by PierrePeng** [comment]
> 1. download and convert follow as https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor
> 2. conver torch tensor(bin) to safetensors
> 3. follow [Running a model from the Docker container without internet connectivity #311](https://github.com/huggingface/text-generation-inference/issues/311)
> 
> ```shell
> model=`model path`
> num_shard=`your system size`
> volume=`../model_path`  # share a volume with the Docker container to avoid downloading weights every run
> 
> docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:0.6.0 --model-id $model --num-shard $num_shard
> ```

Thanks bro. Help a lot
