### ISSUE TITLE
How to support loading the model with fp16/bf16 to reduce the model size

### ISSUE THREAD

**Issue by tienthanhdhcn** [huggingface/text-generation-inference#371]
Thanks for the great work. I want to fit a LLM model into a single GPU but I can't find the option to load the model with fp16 or bf16. Is there any way we can load the model with fp16/bf16?

**Comment by OlivierDehaene** [comment]
The models are already loaded in fp16.

**Comment by tienthanhdhcn** [comment]
Thanks @OlivierDehaene , but I got OOM on a single A10 GPU with this command
`docker run --gpus all --shm-size 32g -p 8080:80 -v /home/thvu/.cache/huggingface/hub/:/data ghcr.io/huggingface/text-generation-inference:latest --num-shard 1 --model-id h2oai/h2ogpt-oasst1-512-12b `

While I can successfully do loading the model with the same A10 using HF and FP16

**Comment by OlivierDehaene** [comment]
Without device map auto?

**Comment by tienthanhdhcn** [comment]
Yes, that is, we only use a single A10 in our case.
