### ISSUE TITLE
QUESTION: LLaMA optimizations used?

### ISSUE THREAD

**Issue by SinanAkkoyun** [huggingface/text-generation-inference#380]
Hi! I wanted to know what LLaMA optimizations are being used here? It runs super fast!

**Comment by OlivierDehaene** [comment]
Right now I don't have access to hopper gpus so it will have to wait unfortunately...

**Comment by SinanAkkoyun** [comment]
@OlivierDehaene 
Lambda provides "infinite" H100 GPUs for around $2,2/h
https://lambdalabs.com/

Given the price, would you be okay with working on FP8 support?

**Comment by SinanAkkoyun** [comment]
If I can help in any way please let me know

**Comment by SinanAkkoyun** [comment]
Dear @OlivierDehaene ,

Thank you very much for all of your work on text-generation-inference!

Recognizing the effort required, I'm offering to cover the Lambda costs for a H100 instance for your use during implementation. Could you please estimate the timeline for this feature?

Thank you for considering this proposal.
Best Regards
