### ISSUE TITLE
QLora Support

### ISSUE THREAD

**Issue by sam-h-bean** [huggingface/text-generation-inference#381]
### Feature request

Add 4-bit quantization support when bitsandbytes releases.

### Motivation

Run larger models easily and performantly 

### Your contribution

I could make a PR if this is a reasonably easy first task or 2.

**Comment by gsaivinay** [comment]
Hello,

Wondering if you got any insights on what would be the inference performance of bitsandbytes 4bit compared to 8bit. Will it be any better? In my experience, 8bit is around 8x slower compared to fp16. Yet to try llama GPTQ(waiting for it be available in this server).

**Comment by schauppi** [comment]
> Hello,
> 
> Wondering if you got any insights on what would be the inference performance of bitsandbytes 4bit compared to 8bit. Will it be any better? In my experience, 8bit is around 8x slower compared to fp16. Yet to try llama GPTQ(waiting for it be available in this server).

Is it planned to support GPTQ models with this Server?

**Comment by SinanAkkoyun** [comment]
Dear @OlivierDehaene ,

Thank you very much for all of your work on text-generation-inference!

Recognizing the effort required, I'm offering to cover the Lambda costs for a H100 instance for your use during implementation. Could you please estimate the timeline for this feature?

Thank you for considering this proposal.
Best Regards

**Comment by tienthanhdhcn** [comment]
Thanks @OlivierDehaene, is there any support for LORA?

**Comment by LoopControl** [comment]
Yep, 4bit inference with bnb is super slow.

GPTQ is pretty fast though. On my hardware it's actually faster than inferencing with fp16.

There's a high-level library called Autogptq (https://github.com/PanQiWei/AutoGPTQ) that makes adding GPTQ support like just a couple lines (the original gptq-for-llama library is tougher to integrate and tends to have random breaking changes).

**Comment by gsaivinay** [comment]
> Would love to GPTQ support added


There is a PR opened for adding GPTQ support for llama #267 not sure if it will be amended to support all the other models as well. Eagerly waiting for this.
