### ISSUE TITLE
Idling calculations for pre-warmup

### ISSUE THREAD

**Issue by SinanAkkoyun** [huggingface/text-generation-inference#383]
### Feature request

Hi! When running inference, I see that my tokens/second almost go 1.5x higher when having run a very recent query. Wait for a couple of seconds and the speed is down again. I would like to issue an API call for pre-warming so that I can send a new query that instantly gets processed whilst every inference step is warmed up

### Motivation

Doing pre warming by hand slightly hurts latency and is not as pretty as built-in. The main motivation is that one has reliable and as fast as possible speed when needed.

### Your contribution

I do not know how to implement a neat solution, however I want to help where I can

**Comment by OlivierDehaene** [comment]
Sorry but I cannot provide a response without additional information about your setup. Please provide more details and context for me to better understand the problem your are facing. 
FYI, we don't have any production prometheus graphs to back up your hypothesis.

**Comment by SinanAkkoyun** [comment]
Thanks for your response. I'm running my queries on the Lambda H100 GPUs, although I noticed this behaviour with every other hardware I tested too. Basically, the generation speed is the fastest when directy querying generations one after another. When waiting a couple of seconds, the generation speed drops again for the first call after this waiting time.

All I did was to write a script that calculates the average TPS for each request and noticed that. The TPS basically drops around 5 to 7 tokens/second. This is a problem with HuggingFace Transformers in general and even happens when running the stock HF generate code.

I thought that an API call named "warmup" could help mitigate this issue by running a loop of constantly generating 1 token until a real `generate` call gets made, the loop can be broken and actual generation would be as fast as possible.
I can understand how this might has low priority, but I wanted to document the issue here nonetheless.

I hope I could get the idea across and I hope this helps clarify my issue. Let me know if you need more information.
