### ISSUE TITLE
Error response from daemon: manifest unknown: OCI index found, but Accept header does not support OCI indexes

### ISSUE THREAD

**Issue by haiasd** [huggingface/text-generation-inference#386]
### System Info

This error occurred when I pull the image

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

docker pull ghcr.io/huggingface/text-generation-inference:0.8

### Expected behavior

This error occurred when I pull the image

**Comment by OlivierDehaene** [comment]
This seems to be an issue with your setup and not with the repository.
