### ISSUE TITLE
trust_remote_code is not available in SageMaker Endpoint

### ISSUE THREAD

**Issue by monuminu** [huggingface/text-generation-inference#390]
### System Info

Hi Team , 

As i can see there is not way i can set trust_remote_code option in sagemaker_endpoint.sh

```
#!/bin/bash

if [[ -z "${HF_MODEL_ID}" ]]; then
  echo "HF_MODEL_ID must be set"
  exit 1
fi
export MODEL_ID="${HF_MODEL_ID}"

if [[ -n "${HF_MODEL_REVISION}" ]]; then
  export REVISION="${HF_MODEL_REVISION}"
fi

if [[ -n "${SM_NUM_GPUS}" ]]; then
  export NUM_SHARD="${SM_NUM_GPUS}"
fi

if [[ -n "${HF_MODEL_QUANTIZE}" ]]; then
  export QUANTIZE="${HF_MODEL_QUANTIZE}"
fi

text-generation-launcher --port 8080
```

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

```
llm_model = HuggingFaceModel(
  role=role,
  image_uri=llm_image,
  env={
    'HF_MODEL_ID': hf_model_id,
    'HF_MODEL_QUANTIZE': json.dumps(use_quantization),
    'SM_NUM_GPUS': json.dumps(number_of_gpu)
  }
)

```
This gives error for Falcon-40b

### Expected behavior

The endpoint should get created

**Comment by austinmw** [comment]
@OlivierDehaene Hi, do I currently need to build this locally, or is this latest updated docker image uploaded to a public container repository that I can pull from?

**Comment by philschmid** [comment]
We already working on releasing the new Image for SageMaker. I ll keep you posted here.

**Comment by mrwadams** [comment]
@austinmw @songfeng @OlivierDehaene 

New image is now available. See Phil's latest blog post for how to deploy Falcon 7B & 40B - https://www.philschmid.de/sagemaker-falcon-llm

**Comment by songfeng** [comment]
@Markus-Zeggel  The tgi 0.8.2 works for me. Also, make sure you update the sagemaker sdk or maybe create a new env from scratch. 


```
trust_remote_code = True

env={
    'HF_MODEL_ID': hf_model_id,
    # 'HF_MODEL_QUANTIZE': json.dumps(use_quantization),
    'SM_NUM_GPUS': json.dumps(number_of_gpu),
    'HF_MODEL_TRUST_REMOTE_CODE': json.dumps(trust_remote_code)
}
```

> Hi, I exactly followed the https://www.philschmid.de/sagemaker-falcon-llm tutorial. (The only difference is the instance type) However, I still get the error message
> 
> > Loading tiiuae/falcon-7b-instruct requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
> 
> I tried this config:
> 
> ```python
> # TGI config
> config = {
>   'HF_MODEL_ID': "tiiuae/falcon-7b-instruct", # model_id from hf.co/models
> # 'SM_NUM_GPUS': json.dumps(number_of_gpu), # Number of GPU used per replica
>   'MAX_INPUT_LENGTH': json.dumps(1024),  # Max length of input text
>   'MAX_TOTEL_TOKENS': json.dumps(2048),  # Max length of the generation (including input text)
>   'HF_MODEL_TRUST_REMOTE_CODE': "true"
> # 'HF_MODEL_QUANTIZE': "bitsandbytes", # comment in to quantize
> }
> ```
> 
> **Am I missing something?**
> 
> Is this the correct image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-tgi-inference:2.0.0-tgi0.8.2-gpu-py39-cu118-ubuntu20.04 ?
> 
> Thanks!

@Markus-Zeggel  The tgi 0.8.2 works for me. Also, make sure you update the sagemaker sdk or maybe create a new env from scratch. 


```
trust_remote_code = True

env={
    'HF_MODEL_ID': hf_model_id,
    # 'HF_MODEL_QUANTIZE': json.dumps(use_quantization),
    'SM_NUM_GPUS': json.dumps(number_of_gpu),
    'HF_MODEL_TRUST_REMOTE_CODE': json.dumps(trust_remote_code)
}
```

**Comment by gsaivinay** [comment]
Hello,

would like to know if anybody actually managed to use SSE streaming in Sagemaker using this TGI server image. Thanks.

**Comment by philschmid** [comment]
@gsaivinay sagemaker is currently not supporting SSE.

**Comment by Steven-N** [comment]
Apologies as I know this isn't the best place for it, but I wasn't sure where else to ask this... Is anyone aware if we can provide the scripts that Sagemaker needs ourselves rather than pulling from `huggingface.co/models` which occurs when you define `'HF_MODEL_ID'`? We're behind a proxy so cannot do it directly from sagemaker. We have other models that work fine in the same environment, however we saw that the falcon-7b has a few python scripts in the HF repo (https://huggingface.co/tiiuae/falcon-7b/tree/main). The models that work fine do not have these python scripts which from other research seems to be why it pulls from HF...?

**Comment by philschmid** [comment]
@Steven-N we created a blog post https://www.philschmid.de/sagemaker-llm-vpc

**Comment by yapweiyih** [comment]
@philschmid, i tried with `tiiuae/falcon-rw-1b` on `sagemaker==2.170.0`, still get the following error

```log
ValueError: Loading /opt/ml/model requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

Code to reproduce.

```python
import torch
from peft import PeftModel
from transformers import AutoTokenizer, AutoModelForCausalLM, TextStreamer


from huggingface_hub import snapshot_download
import sagemaker
import boto3
sess = sagemaker.Session()
# sagemaker session bucket -> used for uploading data, models and logs
# sagemaker will automatically create this bucket if it not exists
sagemaker_session_bucket=None
if sagemaker_session_bucket is None and sess is not None:
    # set to default bucket if a bucket name is not given
    sagemaker_session_bucket = sess.default_bucket()

try:
    role = sagemaker.get_execution_role()
except ValueError:
    iam = boto3.client('iam')
    role = iam.get_role(RoleName='sagemaker_execution_role')['Role']['Arn']


print(f"sagemaker role arn: {role}")
print(f"sagemaker session region: {sess.boto_region_name}")

MODEL_ID = "tiiuae/falcon-rw-1b"
CACHED_DIR = "../cache"
MERGE_MODEL_DIR = "merged_model_test"


model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
    # device_map="auto",
    trust_remote_code=True,
    cache_dir=CACHED_DIR,
)

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_ID,
    cache_dir=CACHED_DIR,
)


model.save_pretrained(MERGE_MODEL_DIR, safe_serialization=True)
tokenizer.save_pretrained(MERGE_MODEL_DIR, safe_serialization=True)
import os

parent_dir = os.getcwd()
# change to model dir
os.chdir(MERGE_MODEL_DIR)
# use pigz for faster and parallel compression
!tar -cf model.tar.gz --use-compress-program=pigz *
# change back to parent dir
os.chdir(parent_dir)


from sagemaker.s3 import S3Uploader

# upload model.tar.gz to s3
s3_model_uri = S3Uploader.upload(local_path=str(MERGE_MODEL_DIR + "/model.tar.gz"), desired_s3_uri=f"s3://{sess.default_bucket()}/test-model")

print(f"model uploaded to: {s3_model_uri}")


from sagemaker.huggingface import get_huggingface_llm_image_uri, HuggingFaceModel
import json

image_uri = get_huggingface_llm_image_uri("huggingface", version="0.8.2")
print(f"llm image uri: {image_uri}")

instance_type = "ml.g4dn.2xlarge"
health_check_timeout = 300
trust_remote_code = True

config = {
    "HF_MODEL_ID": "/opt/ml/model",  # path to where sagemaker stores the model
    "MAX_INPUT_LENGTH": json.dumps(2048),  # Max length of input text
    "MAX_TOTAL_TOKENS": json.dumps(3000),  # Max length of the generation (including input text)
    "HF_MODEL_TRUST_REMOTE_CODE": json.dumps(trust_remote_code)
}

# create HuggingFaceModel with the image uri
llm_model = HuggingFaceModel(
    role=role,
    image_uri=image_uri,
    model_data=s3_model_uri,
    env=config,
)

endpoint_name = sagemaker.utils.name_from_base("test")

predictor = llm_model.deploy(
    endpoint_name=endpoint_name,
    initial_instance_count=1,
    instance_type=instance_type,
    model_data_download_timeout=10 * 60,
    container_startup_health_check_timeout=10 * 60,
    wait=False,
)

print(predictor.endpoint_name)

```

**Comment by philschmid** [comment]
`falcon-rw-1b` is a different model than the 7B or 40B model.

**Comment by razasaad** [comment]
Hey team, I was able to reproduce the same error with using the new TGI 0.8.2 image with deployment of `falcon-7b` following [this](https://www.philschmid.de/sagemaker-falcon-llm) guide and setting the `'HF_MODEL_TRUST_REMOTE_CODE': json.dumps(True),`.

The only difference was the Instance Size (ml.m5.2xlarge). I can't correlate if instance size is what raises the exception of `trust_remote_code=true`.
