### ISSUE TITLE
question: how could I disable flash-attention for llama?

### ISSUE THREAD

**Issue by CoinCheung** [huggingface/text-generation-inference#391]
Hi,

I need to deploy my model on the old v100 gpus, and it seems that flash attention does not support v100 now, so I am thinking that maybe I can disable flash attention when I need to deploy with v100. How could I do this?

**Comment by dongs0104** [comment]
you can build your own image modify Dockerfile remove here
https://github.com/huggingface/text-generation-inference/blob/95d3546976e811ba462047ef8b555d9840efbfe5/Dockerfile#L90-L98

**Comment by CoinCheung** [comment]
Hi @dongs0104 ,

Thanks for telling me this, but it seems that we cannot by-pass this flash attention if we want to deploy llama, I got an error like this:

![图片](https://github.com/huggingface/text-generation-inference/assets/22693362/b3b1aa34-4563-452d-b6a0-250df086a27f)

**Comment by dongs0104** [comment]
also you can not use Sharded Model if you want sharded you can develop yourself.

check here https://github.com/OlivierDehaene/transformers/tree/text_generation_inference in `gpt_neox model`

**Comment by CoinCheung** [comment]
Then I would rather wait for flash-attention to support my device. I am closing this. Thanks for help !!!
