### ISSUE TITLE
Question: Caching in HF API?

### ISSUE THREAD

**Issue by SinanAkkoyun** [huggingface/text-generation-inference#392]
Hi! I noticed that when querying the same prompt twice with the HF APIs (guanaco-33b) it caches it and returns it immediately (virtual 400tps) whereas new requests happen with speed around 20 to 30 tps.

How can one turn this caching feature on with this text-generation-inference?

Thank you

**Comment by OlivierDehaene** [comment]
You need to add a caching mechanism above tgi using, for example, memcached or redis.

**Comment by SinanAkkoyun** [comment]
Thank you! ❤️
