### ISSUE TITLE
Error on BLOOM trained using deepspeed chat with tensor parallelism 

### ISSUE THREAD

**Issue by hyunwoongko** [huggingface/text-generation-inference#399]
I have a pre-trained model using BLOOM architecture on HF transformers. I saved this model to pytorch_model.bin. It's working well with HF transformers, and it's also working well with text-generation-inference without tensor parallelism.

And when I deploy this using k8s(gke) + text-generation-inference + tensor parallelism, the `BLOOMSharded` class can't find `lm_head.weight` tensor.

The workflow is like the following:
1. text-generation-inference converts pytorch_model.bin to safetensors format.
This is safetensors keys.
```python
from safetensors.torch import safe_open

# converted by text-generation-inference
with safe_open("model.safetensors", framework="pt", device="cpu") as f
    print(f.keys())
```
...skip...
'transformer.h.9.mlp.dense_h_to_4h.weight', 'transformer.h.9.post_attention_layernorm.bias', 'transformer.h.9.post_attention_layernorm.weight', 'transformer.h.9.self_attention.dense.bias', 'transformer.h.9.self_attention.dense.weight', 'transformer.h.9.self_attention.query_key_value.bias', 'transformer.h.9.self_attention.query_key_value.weight', 'transformer.ln_f.bias', 'transformer.ln_f.weight', `transformer.word_embeddings.weight`, 'transformer.word_embeddings_layernorm.bias', 'transformer.word_embeddings_layernorm.weight']

2. You can see `transformer.word_embeddings.weight`. this tensor must be used as `lm_head.weight`.
3. See [this code](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/bloom.py#L258), the `BLOOMSharded` class finds tied tensor with `word_embeddings.weight`, not `transformer.word_embeddings.weight`.
4. So the if statement is ignored. and finally I got error `found uninitialized parameters in model : ['lm_head.weight']`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Use BLOOM with TP + auto converting by TGI.

### Expected behavior

`if name == "word_embeddings.weight":`

This code should be changed like 

`if "word_embeddings.weight" in name:`

**Comment by hyunwoongko** [comment]
I checked existing BLOOM checkpoint in HF hub (like bigscience/bloom-560m). and the tensors were saved without `transformer.` prefix. maybe my checkpoint saved wrongly or I used old version of transformers. BTW I don't think changing `if name == "word_embeddings.weight":` to `if "word_embeddings.weight" in name:` is not problematic.

**Comment by hyunwoongko** [comment]
https://github.com/microsoft/DeepSpeedExamples/blob/master/applications/DeepSpeed-Chat/training/utils/utils.py#L60

I realized deepspeed chat saved checkpoint like `transformer.xxx.xxx`. could you change the code compatible with deepspeed chat?

**Comment by hyunwoongko** [comment]
cc @OlivierDehaene

**Comment by OlivierDehaene** [comment]
Sorry but your behaviour is not at all acceptable for this repository. Pinging me on social media is way out of bounds.
We are open to PRs if you want to get this fixed.

**Comment by hyunwoongko** [comment]
@OlivierDehaene Okay, I see.
I will open a PR to resolve this problem. Sorry.

**Comment by hyunwoongko** [comment]
https://github.com/huggingface/text-generation-inference/pull/407
I open a PR for this.
