### ISSUE TITLE
which model is best of text generation?

### ISSUE THREAD

**Issue by nishresthani** [huggingface/text-generation-inference#403]
### Feature request

I am able to run the text generation model locally via docker but the model (bigscience/bloom-560m) seems to be small size for local test and does not generate good quality response for the prompt. Which model is best for the text generation. I have noticed there are lots of models like "bigscience/bloom-7b1" which seems for translation. 
can anyone let me know which is the best model for text generation. 

### Motivation

To test the text generation for different prompts

### Your contribution

n/a

**Comment by csnelsonchu** [comment]
Currently the new leader is https://huggingface.co/tiiuae/falcon-40b
However, it seems like a couple of us are having issues running it at the moment.

**Comment by OlivierDehaene** [comment]
You can have a look at the [Huggingface LLM Leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard) to see which model is the best for each task.
