### ISSUE TITLE
CUDA Memory Exhaustion after Continuous 2-Day Runtime on H100 GPU

### ISSUE THREAD

**Issue by officialoniichat** [huggingface/text-generation-inference#409]
### System Info

After running the text generation inference container continuously with llama 13b for two days in a production environment, the system ran out of CUDA memory. This issue occurred on a server equipped with a H100 GPU.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Deploy the text generation inference container to a server with a H100 GPU with llama 13b.
Run the container in a production environment.
Continue operation for 48+ hours without interruption.
Notice the CUDA Out Of Memory error. 

### Expected behavior

The text generation inference container should be able to operate indefinitely without running out of CUDA memory, provided that it is properly managed and garbage collected.

**Comment by OlivierDehaene** [comment]
The vram is "properly managed and garbage collected". However if you receive a spike of requests and did not properly set the batching parameters for your memory budget, you will oom. The batching mechanism will add requests to the batch until it fills out its MAX_TOTAL_TOKENS. If you don t have enough vram to handle MAX_TOTAL_TOKENS, you oom.

This error should be recoverable and if it is not you should have probes on the health route that catch this kind of issues.

If you need any help setting these things up, know that we have tgi managed solutions both with sagemaker and huggingface endpoints.

Finally we have an expert acceleration program that can provide tailored advices for your use case.
