### ISSUE TITLE
`DecodeError` after `filter_batch` log at `v0.8.0`

### ISSUE THREAD

**Issue by Doohae** [huggingface/text-generation-inference#414]
### System Info

Thank you for providing the convenient LLM inference server. I am always grateful. After installing `flash attention` by make install in `v0.8.0` and running the server with `--max-concurrent-requests` set to a value greater than 1, I encountered the following error. However, when I set it to 1, the server runs without this error. Is this error related to issue #411 ?
I will close this issue right after I check if it is fixed by the issue above. Thanks

<img width="1368" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/80743307/d538a910-6621-4290-9a51-99015afcf207">

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

Steps to reproduce this behavior:
1. build with server/Makefile
2. install flash attention with server/Makefile-flash-att
3. run server with text-generation-launcher with max-concurrent-requests greater than 1

### Expected behavior

server run without error with multiple of max-concurrent-requests

**Comment by OlivierDehaene** [comment]
Can you run `make install-router` and `cd server && make gen-server` and re-try? The internal proto definition was updated and I think you are missing this change inside the python server.

**Comment by OlivierDehaene** [comment]
Generally, it's a good idea to re-run the gRPC code generation step (`make gen-server`) after every update.
