### ISSUE TITLE
Falcon-40B

### ISSUE THREAD

**Issue by nd7141** [huggingface/text-generation-inference#415]
### Model description

Is there `tiiuae/falcon-40b-instruct` in `InferenceAPIClient` that I can play with?

 I noticed there is `7b-instruct` model as well as falcon-40b-chat available in the spaces, which is powered by text-generation, so I wonder if there is an easy way to access falcon-40b-instruct from the `InferenceAPIClient` directly?

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by OlivierDehaene** [comment]
Hello!
For now, the inference API is turned off for falcon 40B variants: the costs of running this model at the scale of the inference API is too high. We are working on other solutions that might help us mitigate this cost and other variants of the model that we might serve as part of hf.co/chat.
