### ISSUE TITLE
Question about data type casting

### ISSUE THREAD

**Issue by Doohae** [huggingface/text-generation-inference#416]
Hello, again!
I just found out that all the data type for models are automatically casted to `fp16` by default when running server with cuda GPU. Same for all types of models just like the following lines.
- https://github.com/huggingface/text-generation-inference/blob/19c41824cb11ba1a3b60a2a65274d8c074383de3/server/text_generation_server/models/causal_lm.py#L459-L461

If I understood correctly, is there any reason for that? Also, is there any way I can force the model dtype into the other types (e.g. `bf16` or `fp32`) when running the server?

**Comment by OlivierDehaene** [comment]
A lot of the custom CUDA kernels that only support fp16/bf16. The reason we use fp16 is because we have found that the results are more stable. There is no way of changing this dtype as of today.
Is there any specific reason you would want to do that?

**Comment by Doohae** [comment]
Thanks for your response @OlivierDehaene ! :)
Actually I was testing my own model trained with `bf16` precision using text-generation-inference, so I was about to test my model with `bf16` rather than `fp16` precision if it's possible. In my opinion then, since the server module is installed in editable mode, manually changing the dtype to bf16 can be an alternative.

**Comment by OlivierDehaene** [comment]
> In my opinion then, since the server module is installed in editable mode, manually changing the dtype to bf16 can be an alternative.

Yes you can certainly do that. If this become an issue in the future, we will add an option but for now fp16 was always the more stable dtype for us in prod.

**Comment by Doohae** [comment]
I tested the model both for `bf16` and `fp16`. And as you said, the result for `fp16` seems more stable.
