### ISSUE TITLE
Question about running falcon in a distributed manner

### ISSUE THREAD

**Issue by nivibilla** [huggingface/text-generation-inference#417]
### System Info

Hey,

In my experience, falcon 40b breaks when using it over multiple gpus with device_map=auto. I get gibberish output unless I pass use_cache=false. I was wondering if you guys could tell me how you managed to host falcon. And if you did it on multiple gpus, how?

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

Just run the falcon 40b instruct model over 4 gpus

### Expected behavior

Legible output and speed too, the falcon model is quite slow in my experience.

**Comment by OlivierDehaene** [comment]
Hi!
You can host the 40b models with 2xA100s with the following command:

```shell
docker run --gpus '"device=0,1"' -p 8080:80 -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:sha-6abec14 --model-id tiiuae/falcon-40b-instruct --num-shard 2
```

or you can quantize with bnb and decrease the memory requirements but this will have a very large impact on latency:

```shell
docker run --gpus '"device=0"' -p 8080:80 -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:sha-6abec14 --model-id tiiuae/falcon-40b-instruct --quantize bitsandbytes
```

**Comment by nivibilla** [comment]
Thanks, I will try this and get back to you.
