### ISSUE TITLE
max_total_tokens is hardcoded to 1512 and cant be changed from SageMaker.

### ISSUE THREAD

**Issue by monuminu** [huggingface/text-generation-inference#419]
### System Info

max_total_tokens is hardcoded to 1512 and cant be changed from SageMaker.

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

If the token size exceeds 1512 it gives error.

### Expected behavior

There should be a option to increase the same using env variable.

**Comment by OlivierDehaene** [comment]
You can change the TGI parameters like max total tokens by editing the config.

For example

```python
import json
from sagemaker.huggingface import HuggingFaceModel

# sagemaker config
instance_type = "ml.g5.12xlarge"
number_of_gpu = 4
health_check_timeout = 300

# TGI config
config = {
  'HF_MODEL_ID': "tiiuae/falcon-40b-instruct", # model_id from hf.co/models
  'SM_NUM_GPUS': json.dumps(number_of_gpu), # Number of GPU used per replica
  'MAX_TOTAL_TOKENS': json.dumps(2048),  # Max length of the generation (including input text)
  'HF_MODEL_QUANTIZE': "bitsandbytes", # comment in to quantize
}

# create HuggingFaceModel
llm_model = HuggingFaceModel(
  role=role,
  image_uri=llm_image,
  env=config
)
```

**Comment by jaypinho** [comment]
@OlivierDehaene is it possible to configure this max_total_tokens variable on HF's hosted Inference Endpoints? I'm not seeing an option for this anywhere in the UI. Thanks!

**Comment by OlivierDehaene** [comment]
@philschmid, can you confirm is this is possible?

**Comment by philschmid** [comment]
@jaypinho just responded to your email its done through the UI in the advanced section. 
![Bildschirmfoto 2023-07-20 um 15 10 03](https://github.com/huggingface/text-generation-inference/assets/32632186/1524a572-f16f-49e0-8f20-b5171145decf)

**Comment by julianweng** [comment]
Hi @philschmid, are there any plans to be able to set max_batch_total_tokens or max_batch_prefill_tokens on hosted inference endpoints? Running into some OOM errors specifically related to these parameters, but upgrading instances doesn't seem necessary considering my use case.

**Comment by philschmid** [comment]
@julianweng. We haven't had request for it yet but let me add it too the backlog. We report here when it is added.
