### ISSUE TITLE
Expose GPU, CPU and memory utilization as prometheus metrics

### ISSUE THREAD

**Issue by brightsparc** [huggingface/text-generation-inference#427]
### Feature request

In addition to per request metrics such `tgi_request_count` it would be useful to have utilization metrics returned on a per interval basis similar to the way Triton Inference Server returns [GPU](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#gpu-metrics) and [CPU](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/metrics.md#gpu-metrics) metrics.

In order to archive this a [gpu_monitor](https://github.com/triton-inference-server/server/blob/main/qa/common/util.sh#L366)  that talks to `nvidia-smi` could be run on startup:
```
nvidia-smi dmon -s u $MONITOR_ID_ARG -f $MONITOR_LOG &
```
As well as collecting metrics from [/proc filesystem](https://www.kernel.org/doc/html/latest/filesystems/proc.html) such as `/proc/stat` and `/proc/meminfo` like done in [node_exporter](https://github.com/prometheus/node_exporter/blob/master/collector/cpufreq_linux.go#L50).

### Motivation

This would improve observability and potentially allow scaling infrastructure request based on these metrics.

### Your contribution

I am new to rust, but with guidance would be happy to contribute, taking inspiration from the Triton Server where possible.

**Comment by OlivierDehaene** [comment]
Hello
I don't think this is something we want to add. You should use something like the [DGCM exporter](https://docs.nvidia.com/datacenter/cloud-native/gpu-telemetry/dcgm-exporter.html#introduction) on top of tgi if you want to track GPU metrics.
