### ISSUE TITLE
How to run Swagger UI of inference server with text-generation-inference

### ISSUE THREAD

**Issue by leemgs** [huggingface/text-generation-inference#430]
### Feature request

* Swagger UI of inference server with text-generation-inference

### Motivation

* https://huggingface.github.io/text-generation-inference/

### Your contribution

I checked the address of the swagger ui running in the project of text-generation-inferce in the link below. 
* https://huggingface.github.io/text-generation-inference/

* https://github.com/huggingface/text-generation-inference 
After installing and running the inference server in the project, I was wondering if there is any documentation on how to provide these swagger ui addresses.

**Comment by OlivierDehaene** [comment]
the swagger ui is served on the `/docs` route.
For example if you are serving tgi on `localhost:3000`, you can access it at `http://localhost:3000/docs`

**Comment by leemgs** [comment]
Thanks. As you described, I can show the Swag UI by visiting http://myaipp.mooo.com:7777/**docs**/ .
