### ISSUE TITLE
FlashLlama doesn't look for safetensors files

### ISSUE THREAD

**Issue by 0x1997** [huggingface/text-generation-inference#433]
### Feature request

Add safetensors support to FlashLlama.

### Motivation

On server startup, bin files are automatically converted to safetensors format. But the FlashLlama class currently only looks for bin files. It'd be nice to avoid having to store two copies of model files.

### Your contribution

I can submit a PR.

**Comment by Narsil** [comment]
We just landed a massive rework, we should make enabling GPTQ much easier, now only `safetensors` files are read and used.

**Comment by 0x1997** [comment]
Thanks. Latest docker image works.
