### ISSUE TITLE
Simple WebUI integrating the "text-generation-inference" API 

### ISSUE THREAD

**Issue by ArnaudHureaux** [huggingface/text-generation-inference#436]
### Feature request

What is the simplest way to use this stream API inside a WebUI in local ?

Gradio / Streamlit -> how use those library to use this stream API ? Is it possible ?

HTML/JS example -> any repo to share ?

Other solutions ?

### Motivation

Get fastly a WebUI to use this stream API

### Your contribution

If i have the confirmation that it doesn't exist, i will definitely work on a WebUI

**Comment by ArnaudHureaux** [comment]
After few hours of browsing, i think that an Streamlit could do the job,

**Comment by khulaifi95** [comment]
> After few hours of browsing, i think that an Streamlit could do the job,

Hi, could you provide the details on how to handle the websocket responses and render it in the streamlit client? I find it tricky if not manually refreshing it with while True: time.sleep(0.5). Thanks.
