### ISSUE TITLE
CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by antferdom** [huggingface/text-generation-inference#437]
### System Info

**Target:** x86_64-unknown-linux-gnu
**Cargo version:** 1.69.0
**Docker label:** N/A
**CUDA driver version:** 12000
**CUDA bare metal version:** 11.8
**Pytorch CUDA version:** 2.0.1+cu118
**System's CUDA version:** 11.8
**GPU supported architectures:** ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90']
**world_size:** 8
GPU		: NVIDIA A100-SXM4-40GB
GPU		: NVIDIA A100-SXM4-40GB
GPU		: NVIDIA A100-SXM4-40GB
GPU		: NVIDIA A100-SXM4-40GB
GPU		: NVIDIA A100-SXM4-40GB
GPU		: NVIDIA A100-SXM4-40GB
GPU		: NVIDIA A100-SXM4-40GB
GPU		: NVIDIA A100-SXM4-40GB

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

In the following [comment block](https://github.com/huggingface/text-generation-inference/blob/e496c9ba5b574ce4e9d04d3b16bce67759ff0445/launcher/src/main.rs#LL62C1-L67C30) of the **launcher** (launcher/src/main.rs) it states how to handle the model allocation limiting the scope of the **world_size** via using environment variables.

There is a typo in the environment variable name `CUDA_VISIBLE_DEVICES` which is missing a ***s***.

### Expected behavior

I tried setting this variable without the expected standard format, and the world size always equals the whole set of physically connected GPUs to the VM. Therefore, I then modify the variable name to match the official standard and could correctly handle the custom allocation.

**Comment by antferdom** [comment]
It is not a bug itself, but I could not find a better categorization for the issue.

**Comment by OlivierDehaene** [comment]
Yes the doc is wrong but the behaviour is correct. Can you open a PR to correct the docs and add the "S"?

**Comment by antferdom** [comment]
Yes, it is expected behaviour as long as we use the correct environment variable name. Sorry for the tag.
