### ISSUE TITLE
Python wrapper for text-generation-benchmark utility

### ISSUE THREAD

**Issue by antferdom** [huggingface/text-generation-inference#444]
### Feature request

Control the benchmarking utility output, format and location, for running the benchmarking using system Python wrappers as `subprocess` or `pexpect`. Writing the output to a file might be sufficient.

**Hypothetical example:**
```python
ret = subprocess.run(["text-generation-benchmark",
                                        "--batch-size", "1",
                                        "--sequence-length", "10",
                                        "--decode-length", "10",
                                        "--tokenizer-name", "bigscience/mt0-xxl-mt",
                                      ],
                                     universal_newlines=True,)
```

### Motivation

The benchmark utility spawns a TUI application, which makes the interactive experimentation great, but complicates the automation of benchmarking. The app is inspired by [oha](https://github.com/hatoo/oha), but this implementation does not allow to specify any flag for disable realtime TUI, like Oha's `--no-tui`.

### Your contribution

Not contribution staged yet.

**Comment by OlivierDehaene** [comment]
I'm a bit confused. Do you want a wrapper or do you want the --no-tui option to exist?

**Comment by WeizhuoZhang-intel** [comment]
Hi @antferdom ,
I am facing the same issue because we want to setup a automation job for test-generation-benchmark. But didn't know how to use it non-interatctively. Do you have any suggestion?

**Comment by antferdom** [comment]
- [benchmarks/benchmark_serving.py](https://github.com/vllm-project/vllm/blob/d95cc0a55c55c914ad9fdb6a3a7ece282c334347/benchmarks/benchmark_serving.py)
- [benchmark/latency_throughput/bench_serving.py](https://github.com/sgl-project/sglang/blob/5d0d40d0eb8c347d8b3598f0a375696728df66c4/benchmark/latency_throughput/bench_serving.py#L220)
