### ISSUE TITLE
Exclude extraneous `.bin` files from `safetensors` conversion

### ISSUE THREAD

**Issue by lewtun** [huggingface/text-generation-inference#458]
### Feature request

When users save their model with `Trainer.save_model()` or `Trainer.push_to_hub()`, the training arguments are saved as a pickle file called `training_arguments.bin`. 

This causes a problem during the `safetensors` conversion of `torch` weights, since the `weight_hub_files()` method first downloads all files with the `.bin` extension ([link](https://github.com/huggingface/text-generation-inference/blob/5ce89059f8149eaf313c63e9ded4199670cd74bb/server/text_generation_server/cli.py#L135)). As a result, the conversion can fail, especially if users have subclassed `transformers.TrainingArguments` - see https://github.com/huggingface/hf-endpoints/issues/840 for instance. 

One simple workaround would be to have a blacklist of common files names that are excluded from the download. Alternatively, one could wrap the `safetensors` conversion in try/except block and log a warning whenever a file is skipped.

### Motivation

I stumbled across this while trying to deploy some fine-tuned `transformers` models in this issue: https://github.com/huggingface/hf-endpoints/issues/840

### Your contribution

I'd be happy to open a PR to fix this - just let me know which of the proposals you prefer (or even a third alternative)

**Comment by Narsil** [comment]
I think the first one is a very easy fix we could implement.

Today there are 3 issues about this conversion, so maybe making it a bit more robust/effective in general (and therefore not doing it brutally) might be the "better" route.

Let's see what @OlivierDehaene thinks.

**Comment by OlivierDehaene** [comment]
I think option 1 makes sense. There is already some kind of filtering happening atm as we only take files in the root dir. We can add a new rule to exclude this params file.
