### ISSUE TITLE
.bin weights not found for model

### ISSUE THREAD

**Issue by mayurtikundi12** [huggingface/text-generation-inference#466]
### System Info

i get this error after running this on docker https://huggingface.co/huggingface/falcon-40b-gptq?text=My+name+is+Lewis+and+I+like+to

huggingface_hub.utils._errors.EntryNotFoundError: No .bin weights found for model huggingface/falcon-40b-gptq and revision None.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

sudo docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:0.8 --model-id $model --num-shard $num_shard --quantize gptq

### Expected behavior

to run

**Comment by Narsil** [comment]
Hi @mayurtikundi12 You need to work with latest for this model to work.

We're going to release 0.9 soon which should work. @OlivierDehaene  (For vis)

**Comment by chintanckg** [comment]
With 1.1.0 it is not working,

```
model=sigmareaver/flan-ul2-4bit-128g-gptq

volume=$PWD/flan-ul2-4bit-128g-gptq-data

docker run --gpus all --shm-size 24g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id $model --max-total-tokens 5024 --max-input-length 4096 --num-shard 4 --max-concurrent-requests 128
```

**Comment by OlivierDehaene** [comment]
@chintanckg, add `--quantize gptq`

**Comment by parkerroan** [comment]
I am also seeing this error when loading a model by path that has safetensors and not .bin weights.

**Comment by parkerroan** [comment]
@OlivierDehaene 

https://github.com/huggingface/text-generation-inference/blob/96a982ad8fc232479384476b1596a880697cc1d0/server/text_generation_server/cli.py#L156C72-L156C72

Shouldn't this line not have hardcoded ".bin" here? I think this could be the cause of this issue.

**Comment by chumpblocckami** [comment]
Same issue with a .gguf finetuned model. Any updates?
