### ISSUE TITLE
Add option to add custom prompt generation logic and generate out processing

### ISSUE THREAD

**Issue by omrigut1** [huggingface/text-generation-inference#473]
### Feature request

Currently the container acts as a black-block without option to control the input of the generate function. In other hugging-face containers it is possible to provide custom pre-processing/ post-processing code 

### Motivation

Save the need to host additional logic of prompt generation outside of the inference endpoint. We find it very useful to host the prompt logic near the actual LLM, especially given that different models needs different prompts. 

### Your contribution

Not sure yet - I'm new to this code repository

**Comment by OlivierDehaene** [comment]
We are not intereseted in this feature sorry.
