### ISSUE TITLE
Allow for auto convert to be disabled from CLI

### ISSUE THREAD

**Issue by QLutz** [huggingface/text-generation-inference#474]
### Feature request

Allow for the `auto_convert` parameter found in the [`download_weights`](https://github.com/huggingface/text-generation-inference/blob/ece7ffa40a7e167400e57d89b8a73751d095184c/server/text_generation_server/cli.py#L75) command to be set from the CLI.

### Motivation

In many cases, the additional overhead for converting models from PyTorch bin to SafeTensors format is fairly superfluous especially in the case of custom models obtained through legacy tools.

As a sidenote, converting models by saving them with `model.save_pretrained(file_name, 'safe_serialization': True)` from Transformers yields SafeTensors which are not recognised by TGI.

### Your contribution

Quite unsure how this should be done. I'm guessing changes should be made [here](https://github.com/huggingface/text-generation-inference/blob/ece7ffa40a7e167400e57d89b8a73751d095184c/launcher/src/main.rs#L574). I am willing to try and open a PR if this seems to be a feature of interest.

**Comment by OlivierDehaene** [comment]
> As a sidenote, converting models by saving them with `model.save_pretrained(file_name, 'safe_serialization': True)` from Transformers yields SafeTensors which are not recognised by TGI.

Any examples? This is opposite to our own experiences.

For a majority of models in TGI, safetensors weights are a requirement.

**Comment by QLutz** [comment]
> Any examples? This is opposite to our own experiences.
I had been experiencing some issues when merging adapters and then saving the resulting models in SafeTensors. I cannot reproduce them on a fresh setup so I do apologise about that.

> For a majority of models in TGI, safetensors weights are a requirement.
That I did not realise. Thanks for the heads up.

Thanks for the answers overall !
