### ISSUE TITLE
Support for mosaicml/mpt-30b-instruct model

### ISSUE THREAD

**Issue by maziyarpanahi** [huggingface/text-generation-inference#491]
### Feature request

I was wondering if there will be a support for the newly released [mpt-30b-instruct](https://huggingface.co/mosaicml/mpt-30b-instruct)

### Motivation

It's not possible to use `mosaicml/mpt-30b-instruct` model:

`ValueError: sharded is not supported for AutoModel`

### Your contribution

I am not sure how you can add support for new LLM models. (if there is a step by step guide as where to start would be great and I can contribute)

**Comment by mantrakp2004** [comment]
did you try --trust-remote-code while running the docker

**Comment by tim-a-davis** [comment]
it's very slow.  This model is not supported for sharding at the moment in text-generation-inference.
> did you try --trust-remote-code while running the docker

**Comment by mantrakp2004** [comment]
Then try implementing a rudimentary implementation of it, you can use rust or js as router and Python for inference, copy the custom kernels from the repo, modify them as suitable, mpt already has an implementation for flash attention in its "remote code file" use that and batch_encode_plus while tokenizer and batch_decode, implement batching on router server and volla u have your own server ready for inference

**Comment by tim-a-davis** [comment]
> Then try implementing a rudimentary implementation of it, you can use rust or js as router and Python for inference, copy the custom kernels from the repo, modify them as suitable, mpt already has an implementation for flash attention in its "remote code file" use that and batch_encode_plus while tokenizer and batch_decode, implement batching on router server and volla u have your own server ready for inference

Maybe you could write me one as an example?

**Comment by mantrakp2004** [comment]
Am working on one right now, if you would like to help out

**Comment by SinanAkkoyun** [comment]
I am also very interested in this
I know the router side but how do you actually "on the fly" batch compute multiple requests at once with `transformers`?

**Comment by SinanAkkoyun** [comment]
(And can we expect an optimized tgi implementation soon?)

**Comment by Narsil** [comment]
Take example to other models we have done in `server/text-generation-server/models/custom_modeling/*.py` maybe ?

There's also some files in `server/text-generation-server/models/*.py`. Those are declaring the model as being flash enabled (the batching happens differently when a model supports flash).

If you success PRs are welcome !

**Comment by louis030195** [comment]
is mpt even supported https://github.com/huggingface/text-generation-inference/issues/290 ?

**Comment by Narsil** [comment]
It's supported on the "best effort basis".

I started some work to actually support it, but it means rewriting flash attention (the cuda version) with added bias, which may take some time.

**Comment by mantrakp2004** [comment]
Sad news: I didn't succeed, the mpt model is a bit different, i tried loading it but it didn't work as expected and keeps mixing up tokens. I am looking forward for your implementation Narsil, sorry for the wait.

A pre thanks (an advance thank) to narsil :D

**Comment by ankit201** [comment]
> didn't succeed, the mpt model is a bit different, i tried loading it but it didn't work as expected and keeps mixing up tokens. I am looking forward for your implementation Narsil, sorry for the wait.

Can you guide me on how you started writing the flash attention part also what are your thoughts on implementing dynamic batching for this as it only supports 1 concurrent batch for now,?
A little guidance would be really great, we can collaborate and try this out.

**Comment by ankit201** [comment]
> It's supported on the "best effort basis".
> 
> I started some work to actually support it, but it means rewriting flash attention (the cuda version) with added bias, which may take some time.

Can you guide on how you started writing the flash attention part and what are your thoughts on implementing dynamic batching for this as it only supports 1 concurrent request for now on AutoModel.
A little guidance would be really great, maybe we can collaborate and try this out.

**Comment by Narsil** [comment]
> on implementing dynamic batching for this as it only supports 1 concurrent request for now on AutoModel.

This won't  require work once we have flash attention.

**Comment by Narsil** [comment]
Because it doesn't implement the flash attention we want.

This is Triton's flash attention, which doesn't support "unpadded" batching, which is the one necessary to work nicely on TGI (removing batching, removes a LOT of issues and unnecessary memory and speeds up inference much more than flash by itself).

Flash attention actually doesn't play that big of a role in speeding things up at inference, since most of the time is spent in `decode` where it doesn't really help. But the no padding thing is extremely important.

**Comment by Narsil** [comment]
Here is the non flash version (as a temporary measure since modifying the kernel is taking more time than I anticipated: https://github.com/huggingface/text-generation-inference/pull/514

**Comment by ankit201** [comment]
> Here is the non flash version (as a temporary measure since modifying the kernel is taking more time than I anticipated: #514
> 
> This should enable sharding at least.

Many thanks for this. Looking forward to the flash class too.
Cheers!

**Comment by ConProgramming** [comment]
> Because it doesn't implement the flash attention we want.
> 
> This is Triton's flash attention, which doesn't support "unpadded" batching, which is the one necessary to work nicely on TGI (removing batching, removes a LOT of issues and unnecessary memory and speeds up inference much more than flash by itself).
> 
> Flash attention actually doesn't play that big of a role in speeding things up at inference, since most of the time is spent in `decode` where it doesn't really help. But the no padding thing is extremely important.

Triton is the only flash attention implementation that supports ALiBi, if I understand [this](https://github.com/mosaicml/llm-foundry/blob/main/TUTORIAL.md#what-are-the-different-attention-options-torch--flash--triton--for-mpt-and-which-one-should-i-use) correctly.

So for TGI, if we want to use MPT with ALiBi,  does that leave us with just the native pytorch implementation?

**Comment by OlivierDehaene** [comment]
We will add fork and add it ourselves to the flash attention cuda kernels.
