### ISSUE TITLE
How can I know the progress of the model download?

### ISSUE THREAD

**Issue by runningBolin** [huggingface/text-generation-inference#494]
The Falcon 40B model occupies nearly 90G of space, takes a long time to download, and does not know the download progress.
Is there any other way to download the model first and load it into TGI?

**Comment by Narsil** [comment]
`text-generation-server download-weights MODEL_ID` is probably what you're looking for.

You can also add the progressbar back using the env variable `HF_HUB_ENABLE_HF_TRANSFER=0`  (but download will be slower)

**Comment by pabl-o-ce** [comment]
Hi @Narsil 

Thanks for the support.

This command cli how can be installed?

Also this command can be found inside the docker container? and how set the path where download the model for example in `/data`

**Comment by Narsil** [comment]
Perfect. Closing this issue then.
