### ISSUE TITLE
Guidance acceleration

### ISSUE THREAD

**Issue by Atry** [huggingface/text-generation-inference#505]
### Feature request

[Guidance](https://github.com/microsoft/guidance) can control the generated format, which could be a nice feature if it is built-in

- Add extra parameter to `/generate` and `/generate_stream` protocol to specify a template
- Use guidance-like mask to generate tokens and pre-fill known tokens, alternately

### Motivation

See https://github.com/microsoft/guidance#guidance-acceleration-notebook 

### Your contribution

Just an idea for now

**Comment by Vinno97** [comment]
For now, won't it be better to add text-generation-inference as a supported LLM into Guidance, in the same way as it did for OpenAI's models?

**Comment by Atry** [comment]
Similar feature in another text generation project: https://github.com/ggerganov/llama.cpp/pull/1773

**Comment by Atry** [comment]
See also https://github.com/go-skynet/LocalAI/issues/354

**Comment by yubuyuabc** [comment]
> 



> Similar feature in another text generation project: [ggerganov/llama.cpp#1773](https://github.com/ggerganov/llama.cpp/pull/1773)

I wonder konw if it can or not get a stream with batch process

**Comment by OlivierDehaene** [comment]
This is one of our priority for the next release.

**Comment by KreshLaDoge** [comment]
Do you happen to have any updates on this matter?
Coming from [LMQL](https://github.com/eth-sri/lmql/issues/190)
