### ISSUE TITLE
Trouble converting HuggingFaceH4/starchat-beta GPTQ

### ISSUE THREAD

**Issue by gsaivinay** [huggingface/text-generation-inference#506]
### System Info

tgi repo commit: 70f485bf9f601b5450b00894f56e20b973d1c2e4
cargo: 1.68.2
model: HuggingFaceH4/starchat-beta GPTQ
machine: EC2 g4dn.12xlarge
GPU: 4 x T4 16GB

command: `text-generation-server quantize starchat-beta starchat-beta-q`

I've trouble converting HuggingFaceH4/starchat-beta model to GPTQ with  the above mentioned command.

```
Quantizing layer 1/40..
+------------------+--------------+------------+-----------+-------+
|       name       | weight_error | fp_inp_SNR | q_inp_SNR | time  |
+==================+==============+============+===========+=======+
| attn.c_attn                 | 1816.746     | -          | -         | 39.322 |
| attn.c_proj                  | 70.281       | -          | -         | 2.313 |
| mlp.c_fc                     | 1578.097     | -          | -         | 3.435 |




OutOfMemoryError: CUDA out of memory. Tried to allocate 2.25 GiB (GPU 0; 14.58 GiB total capacity; 12.91 GiB already allocated; 653.31 MiB free; 13.15 GiB reserved in total by PyTorch) If 
reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

I've successfully converted `NousResearch/Nous-Hermes-13b` without any issue with only one T4 GPU. 

Another question I've is that, startchat-beta model is trained with a context length of 8192. If we convert to GPTQ with 2048 length, will it affect the model performance?

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Run the command `text-generation-server quantize starchat-beta starchat-beta-q` and observe the error.

### Expected behavior

Model is successfully quantized.

**Comment by Narsil** [comment]
>  If we convert to GPTQ with 2048 length, will it affect the model performance?

Hard to say, the conversion should give you an estimate of the loss, in our experience unfortunately starchat is quite damaged after quantization.

For the out of memory, it's out of memory, how it is a bug ?
I am going to try a little to improve the quantization script, but it's hard to make it both generic (for every model out there) and efficient (less RAM used).

I am going to close this, feel free to reopen.

**Comment by gsaivinay** [comment]
> For the out of memory, it's out of memory, how it is a bug ?

Half of the total available GPU memory(total 64GB) is free, but still quantization process uses only 1st GPU memory for conversion and fails to do so.

**Comment by gsaivinay** [comment]
@Narsil  Do you think it is worth converting the model with sequence length of 8192 using a different dataset and see the model performance?

**Comment by Narsil** [comment]
> Half of the total available GPU memory(total 64GB) is free, but still quantization process uses only 1st GPU memory for conversion and fails to do so.

Really ? The script uses `low_mem_0` from accelerate, which should make GPU 0 used as little as possible... Do you maybe have `CUDA_VISIBLE_DEVICES` set which would make those other GPUs invisible for the script ?

**Comment by Narsil** [comment]
> @Narsil Do you think it is worth converting the model with sequence length of 8192 using a different dataset and see the model performance?

You can definitely try. I'm not sure that will impact the downstream performance that well though.

**Comment by gsaivinay** [comment]
> Really ? The script uses `low_mem_0` from accelerate, which should make GPU 0 used as little as possible... Do you maybe have `CUDA_VISIBLE_DEVICES` set which would make those other GPUs invisible for the script ?

The initial model load used GPU 0 very little memory while loading rest 3 with more... but as soon as conversion started, GPU 0 memory filled up and finally OOM.

**Comment by Narsil** [comment]
That means you need more GPU ram to load a single layer and actually do the conversion.

The script loads the model layer per layer, and for each layer maintains both the "natural" (f16) version and the quantized version + a lot of intermediary necessary computations.

Just use a larger GPU for the conversion. (4A10G might be enough)

**Comment by gsaivinay** [comment]
Okay I'll give it a try with g5.12xlarge, but I encountered a strange problem. since g4 instances uses Intel CPU and g5 uses AMD, TGI launcher command works fine Intel, but throws Signal 4 error on AMD. I tried re installing everything including flash attention but got same error. I'll try it again.

**Comment by Narsil** [comment]
> g5.12xlarge

I use that all the time.. odd..
