### ISSUE TITLE
Why should num_shard be a fraction of the shape of model?

### ISSUE THREAD

**Issue by calycekr** [huggingface/text-generation-inference#507]
I want to use polyglot-ko-12.8b (https://huggingface.co/EleutherAI/polyglot-ko-12.8b) with num_shard=2.

**AutoModelForCasualLM.from_pretrained('model-path', device_map='auto')** break it up into almost half and correctly loads the model onto 2 GPUs (2x RTX 4090).

But in TGI, **AssertionError: The choosen size 30003 is not compatible with sharding on 2 shards** (".../text_generation_server/utils/weights.py", line 77)

What is the difference between them?
Why should num_shard be a fraction of the shape of model?

**Comment by Narsil** [comment]
Have you figured it out ?
