### ISSUE TITLE
Question about batching dissimilar requests

### ISSUE THREAD

**Issue by pranavsharma** [huggingface/text-generation-inference#510]
How does TGI incorporate these 3 types of batching issues? Following is an excerpt from the [ORCA paper](https://www.usenix.org/system/files/osdi22-yu.pdf) (copying verbatim here):
```
There are three cases for a pair of requests where the next iteration cannot
be batched together: (1) both requests are in the initiation
phase and each has different number of input tokens (e.g.,
x3 and x4 in Figure 4); (2) both are in the increment phase
and each is processing a token at different index from each
other (x1 and x2); or (3) each request is in the different phase:
initiation or increment (x1 and x3). Recall that in order to
batch the execution of multiple requests, the execution of each
request must consist of identical operations, each consuming
identically-shaped input tensors. In the first case, the two
requests cannot be processed in a batch because the “length”
dimension of their input tensors, which is the number of input
tokens, are not equal. The requests in the second case have
difference in the tensor shape of Attention keys and values
because each processes token at different index, as shown in
Figure 1c. For the third case, we cannot batch the iterations of
different phases because they take different number of tokens
as input; an iteration of the initiation phase processes all input
tokens in parallel for efficiency, while in the increment phase
each iteration takes a single token as its input.
```

**Comment by Narsil** [comment]
This should answer your question : https://github.com/huggingface/text-generation-inference/tree/main/router#continuous-batching

If it doesn't please answer here, we'll reopen and make this doc clearer.

**Comment by Narsil** [comment]
We interleave  `prefill `(first pass) and `decode` (with past key values). That + continuously adding and removing requests on the fly.

**Comment by pranavsharma** [comment]
Ah, so the kernels support ragged batching (requests in a batch with different dimensions). Did you have to write a custom kernel to do so?

**Comment by Narsil** [comment]
No, we took `flash-attention`. Those a re not real ragged tensors, they are real tensors from torch's standpoint. The kernels uses an extra offset tensor to make the correct matmul intra batch.
