### ISSUE TITLE
the speed of shard-num=x(bigger than 1) is not better than that of shard-num=1

### ISSUE THREAD

**Issue by yangelaboy** [huggingface/text-generation-inference#515]
### System Info

Target: x86_64-unknown-linux-gnu
Cargo version: 1.69.0
Commit sha: N/A
Docker label: N/A
nvidia-smi:
Fri Jun 30 17:56:24 2023       
   +-----------------------------------------------------------------------------+
   | NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
   |-------------------------------+----------------------+----------------------+
   | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                               |                      |               MIG M. |
   |===============================+======================+======================|
   |   0  NVIDIA GeForce ...  Off  | 00000000:1B:00.0 Off |                  N/A |
   | 30%   27C    P8    17W / 350W |   3142MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
   |   1  NVIDIA GeForce ...  Off  | 00000000:1C:00.0 Off |                  N/A |
   | 30%   25C    P8    20W / 350W |   3132MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
   |   2  NVIDIA GeForce ...  Off  | 00000000:1D:00.0 Off |                  N/A |
   | 30%   27C    P8    19W / 350W |   3142MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
   |   3  NVIDIA GeForce ...  Off  | 00000000:1E:00.0 Off |                  N/A |
   | 30%   26C    P8    13W / 350W |   3142MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
   |   4  NVIDIA GeForce ...  Off  | 00000000:3D:00.0 Off |                  N/A |
   | 30%   23C    P8    21W / 350W |   3142MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
   |   5  NVIDIA GeForce ...  Off  | 00000000:3F:00.0 Off |                  N/A |
   | 30%   24C    P8    24W / 350W |   3134MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
   |   6  NVIDIA GeForce ...  Off  | 00000000:40:00.0 Off |                  N/A |
   | 30%   25C    P8    19W / 350W |   3142MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
   |   7  NVIDIA GeForce ...  Off  | 00000000:41:00.0 Off |                  N/A |
   | 30%   26C    P8    21W / 350W |   3132MiB / 24576MiB |      0%      Default |
   |                               |                      |                  N/A |
   +-------------------------------+----------------------+----------------------+
                                                                                  
   +-----------------------------------------------------------------------------+
   | Processes:                                                                  |
   |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
   |        ID   ID                                                   Usage      |
   |=============================================================================|
   |    0   N/A  N/A     73113      C   ...tion-inference/bin/python     3140MiB |
   |    1   N/A  N/A     73114      C   ...tion-inference/bin/python     3130MiB |
   |    2   N/A  N/A     73115      C   ...tion-inference/bin/python     3140MiB |
   |    3   N/A  N/A     73117      C   ...tion-inference/bin/python     3140MiB |
   |    4   N/A  N/A     73119      C   ...tion-inference/bin/python     3140MiB |
   |    5   N/A  N/A     73121      C   ...tion-inference/bin/python     3132MiB |
   |    6   N/A  N/A     73127      C   ...tion-inference/bin/python     3140MiB |
   |    7   N/A  N/A     73128      C   ...tion-inference/bin/python     3130MiB |
   +-----------------------------------------------------------------------------+
2023-06-30T09:56:24.946981Z  INFO text_generation_launcher: Args { model_id: "bigscience/bloom-560m", revision: None, sharded: None, num_shard: None, shard_offset: 0, quantize: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1000, max_total_tokens: 1512, max_batch_size: None, waiting_served_ratio: 1.2, max_batch_total_tokens: 32000, max_waiting_tokens: 20, port: 3000, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, env: true }

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Recently, I conducted an inference pressure test, but found that given the same input (input/qps), the inference speed of shard-num=2 is slightly worse than that of shard-num=1. 
**Shouldn't the inference speed be faster if the number of shards is larger?**

### Expected behavior

the inference speech of shard-num=2 is better than that of shard-num=1

**Comment by OlivierDehaene** [comment]
> Shouldn't the inference speed be faster if the number of shards is larger?

Not necessarily. It depends on the model size and the speed of the inter-connect between the GPUs.
