### ISSUE TITLE
flash attention performance?

### ISSUE THREAD

**Issue by leiwen83** [huggingface/text-generation-inference#517]
Hi,

After enable flash attention for Llama 7B, I don't see any performance improvement for inference.
Do you have any performance data for flash attention enable w/ and w/o?

Thx,
Lei

**Comment by Narsil** [comment]
Could you provide all the necessary information asked during issue creation ?

Also for this specific one, can you provide the output of `text-generation-benchmark` for both ?

I'm closing this isse, please re-open one with all the necessary information, we cannot help without them.

Flash helps, but mostly when you're actually using bs>1, it won't do much without this property.
