### ISSUE TITLE
docker manifest type is not correct

### ISSUE THREAD

**Issue by arnavsinghvi11** [huggingface/text-generation-inference#535]
### System Info

OS: Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       {.}

Docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89e8a
 Built:             Thu Jul 25 21:21:35 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89e8a
  Built:            Thu Jul 25 21:20:09 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
  
  
  Client:
 Debug Mode: false

Server:
 Containers: 140
  Running: 0
  Paused: 0
  Stopped: 140
 Images: 529
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: {.}
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: {.}
 runc version: {.}
 init version: {.}
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-50-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 56
 Total Memory: 503.5GiB
 Name: {...}
 ID: {.}
 Docker Root Dir: /lfs/0/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

Just running the default Docker command on this configuration: 
model=bigscience/bloom-560m
num_shard=2
volume=$PWD/data

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Clone repo with latest commit
2. Run provided docker command in README

Just running the default Docker command on this configuration: 
model=bigscience/bloom-560m
num_shard=2
volume=$PWD/data
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:0.9 --model-id $model --num-shard $num_shard

and I encounter this error: 
Unable to find image 'ghcr.io/huggingface/text-generation-inference:0.9' locally
0.9: Pulling from huggingface/text-generation-inference
docker: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'.

I was able to run this command on another server and would prefer to work with the Docker since my code deals with Docker primarily. Would appreciate any tips on how to fix this. Thanks!

### Expected behavior

The server should download the weights and display connected when ready to send requests.

**Comment by OlivierDehaene** [comment]
This seems to be a docker related issue, not a tgi one. My guess would be that your version of docker is way too old.
