### ISSUE TITLE
falcon-7b-instruct model unexpected text generation without flash attention

### ISSUE THREAD

**Issue by chironito** [huggingface/text-generation-inference#539]
### System Info

Version: ghcr.io/huggingface/text-generation-inference:latest
OS: Ubuntu 22.04 LTS
GPU: 1 x A100 80GB GPU on azure
![2023-07-04_14-51-20](https://github.com/huggingface/text-generation-inference/assets/86181705/3e715977-f0af-4b8e-8b04-e72537b0eed5)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

sudo docker run --gpus all -p 8080:80 -v /mnt/ext/data:/data -e USE_FLASH_ATTENTION=FALSE ghcr.io/huggingface/text-generation-inference:latest --model-id tiiuae/falcon-7b-instruct --trust-remote-code
![2023-07-04_14-29-53](https://github.com/huggingface/text-generation-inference/assets/86181705/4eac4a38-c5f5-4a4e-bd94-dd71935f37c5)

### Expected behavior

sudo docker run --gpus all -p 8080:80 -v /mnt/ext/data:/data -e USE_FLASH_ATTENTION=TRUE ghcr.io/huggingface/text-generation-inference:latest --model-id tiiuae/falcon-7b-instruct --trust-remote-code

If flash attention is switched on, we get correct generation...

![2023-07-04_14-36-53](https://github.com/huggingface/text-generation-inference/assets/86181705/aa09e578-7bd6-4600-9b2e-29a7e5af178e)

**Comment by kgnlp** [comment]
I encountered this issue as well. I assume this is related to an issue in the implementation of the kv-caching in the `modeling_RW.py` bundled with the original model, which has been reported here: https://huggingface.co/tiiuae/falcon-7b/discussions/17
The `flash-attn` implementation in this repository seems to solve this issue, but only when `flash-attn` is installed.

**Comment by flozi00** [comment]
Yeah, I can confirm that bug
The flash implementation solves it

**Comment by FionnD** [comment]
Not occurring for me, but I'm not running `--trust-remote-code` if that makes a difference.

**Comment by flozi00** [comment]
If you dont need to run trust remote code then it is using the flash attention code from this repo
