### ISSUE TITLE
Allow manually downloading and importing models

### ISSUE THREAD

**Issue by Yiannis128** [huggingface/text-generation-inference#542]
### Feature request

Allow the ability to download and import models into the data folder.

### Motivation

This is useful for air gapped servers that don't have a connection hugging face.

### Your contribution

Not familiar with the codebase. I am going to look at the code, if I am able to find out how to fix it, I'll submit a PR but don't count on it.

**Comment by OlivierDehaene** [comment]
`text-generation-server download-weights <model-id>`

**Comment by Yiannis128** [comment]
> `text-generation-server download-weights <model-id>`

Thank you for specifying this for me. I didn't notice this in any documentation. Can you please tell me how this would be possible using docker?

**Comment by OlivierDehaene** [comment]
You can modify the image entrypoint.
For example: `docker run --entrypoint text-generation-server <image> dowload-weights <model-id>`

**Comment by Yiannis128** [comment]
> You can modify the image entrypoint. For example: `docker run --entrypoint text-generation-server <image> download-weights <model-id>`

Thank you very much for the assistance, I will try this tomorrow morning :)

**Comment by Yiannis128** [comment]
> You can modify the image entrypoint. For example: `docker run --entrypoint text-generation-server <image> download-weights <model-id>`

Quick question about the usage of model-id, is it meant to be the model id of the actual model I want to use? Or is it meant to be a path to the cloned git repo?
