### ISSUE TITLE
unreasonable vram used

### ISSUE THREAD

**Issue by stupiding** [huggingface/text-generation-inference#547]
### System Info

Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: https://github.com/huggingface/text-generation-inference/commit/1da07e85aae8ce417dda3effd516691394dc31a1
Docker label: sha-1da07e8

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

#532

### Expected behavior

1. from the 1500 and 2000 token output, we can conclude that every token consumes nearly 1MB on each gpu, which is much larger than expected: 60 x 1 x 2 x 64 x 2B = 15KB
2. for the 2000 token request, the cache allocated for 500、1000、1500 seems not reachable anymore, but are never released. 
3. 0.9 docker takes much more VRAM than the previous version #532

**Comment by OlivierDehaene** [comment]
1. where is "60 x 1 x 2 x 64 x 2B = 15KB" coming from?
2. 0.9 only allocates the KV cache once.
3. It allocates the max size KV cache at warmup. In 0.8.2 the kv would have grown to the same/bigger value given your batching parameters.

**Comment by stupiding** [comment]
> 1. I am not so famaliar with LLM, but supspected kv_cache of each token consumes vram equals to "num_layer x num_head x 2 x head_dim / num_gpu x 2byte = 60 x 8 x 2 x 64 / 8 x 2B" (in my case, num_layer=60, num_head=8, head_dim=64 and num_gpu=8)
> 2. As the screenshot i pasted in the issue [unreasonable vram cache used by falcon-40b #532](https://github.com/huggingface/text-generation-inference/issues/532) , even with 0.9 the vram still increased every time

I find this [blog](https://huggingface.co/blog/falcon), where it says kv_cache vram consumed by 2048 tokens in falcon-40b is 240MB. For 8 gpus in my case, seems like 30KB per token on each gpu, larger than my calculation but still much less than 1MB.

**Comment by stupiding** [comment]
Didn't `QxK dot product in the attention layers.` equals to `1x len_prompt` ?
I don't understand too much

> I don't think torch.cuda.mem_get_info is a realible source without calling torch.cuda.mem_get_info in the server first.

 so I paste the screenshot of nvidia-smi, is nvidia-smi also not reliable?
