### ISSUE TITLE
AttributeError: 'InferenceClient' object has no attribute 'text_generation'

### ISSUE THREAD

**Issue by hazelsilver8740** [huggingface/text-generation-inference#559]
### System Info

Running using InferenceClient without specifying model-id or parameters on Hugging Face, no GPUs.

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

<img width="834" alt="Screenshot 2023-07-06 at 11 33 49 AM" src="https://github.com/huggingface/text-generation-inference/assets/64221089/2f862097-801c-4c70-a9d2-535a814fe120">

 **Steps:**
Python ver: Python 3.10.0
1. from huggingface_hub (ver==0.15.1) import InferenceClient
2. Create InferenceClient object ([Hugging Face example](https://huggingface.co/docs/huggingface_hub/v0.16.2/en/package_reference/inference_client#huggingface_hub.InferenceClient.text_generation.example))
3. Call **text_generation()** without specifying model or additional parameters

### Expected behavior

I would expect the above code to run inference and generate text response (i.e., the behaviour in the example).

Sorry if this has been solved and thank you for your help!

**Comment by Narsil** [comment]
Do you mind opening an issue directly on https://github.com/huggingface/huggingface_hub/ instead, since the issue seems to come from there ?

Thank you !
