### ISSUE TITLE
The unit of "Prefill Throughput" in text-generation-benchmark

### ISSUE THREAD

**Issue by jiguanglizipao** [huggingface/text-generation-inference#566]
According the following code of text-generation-benchmark, the unit of `Prefill Throughput` seems to be `sequences/secs` rather than `tokens/secs` in the figure. 
https://github.com/huggingface/text-generation-inference/blob/e943a294bca239e26828732dd6ab5b6f95dadd0a/benchmark/src/generation.rs#L166C8-L166C8

<img width="375" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/10060654/44bb9089-4183-4bed-9c99-85d941b5b086">

**Comment by OlivierDehaene** [comment]
The `prefill` op fills up the KV cache but also decodes the first token of the sequence. In this case, sequence/secs or tokens/secs would be equivalent.
