### ISSUE TITLE
Locally served falcon -- "no pipeline tag found for model"

### ISSUE THREAD

**Issue by hlo-world** [huggingface/text-generation-inference#568]
### System Info

falcon-40b has pipeline tag of "text-generation" [[ref](https://huggingface.co/tiiuae/falcon-40b)]

But when I serve it from a local directory, I see the logs `"no pipeline tag found for model /data/falcon-40b"`

Seems in the router, if we're using local model, it just sets pipeline tag to nothing [[ref](https://github.com/huggingface/text-generation-inference/blob/main/router/src/main.rs#L165-L170)]

This matters because when serving local LLM, return_full_text is false as a result [[ref](https://github.com/huggingface/text-generation-inference/blob/main/router/src/main.rs#L183-L190)]

### Information

- [X] Docker

### Tasks

- [x] An officially supported command

### Reproduction

Serve falcon-40b or any "text-generation" model from docker running on EKS, ECS, etc..

### Expected behavior

return_full_text is `True` when serving LLM model locally, which is the same behaviour when serving the same model downloaded from external source

**Comment by Narsil** [comment]
> "no pipeline tag found for model /data/falcon-40b"

This is just a warning, not a crash, everything should still load fine.
