### ISSUE TITLE
Support for Hosting Server on Google Colab? 

### ISSUE THREAD

**Issue by arnavsinghvi11** [huggingface/text-generation-inference#570]
### Feature request

Hi I was wondering if there would be support for running the text-generation-inference server on Colab to send requests to?

### Motivation

Since docker is not supported, I was wondering if there could be an alternative way to host sending requests. 

### Your contribution

.

**Comment by Narsil** [comment]
No this is not something that is of interest.

You could problably build the command line utility, but this is not something we're going to officially support in anyway.
