### ISSUE TITLE
GLM Model

### ISSUE THREAD

**Issue by wqh17101** [huggingface/text-generation-inference#572]
### Model description

https://github.com/THUDM/ChatGLM2-6B
https://huggingface.co/THUDM/chatglm2-6b/tree/main

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by OlivierDehaene** [comment]
Duplicate of #524

**Comment by zhanzushun** [comment]
ChatGLM3 IS a very popular model. Hope add to supported list. Thanks
