### ISSUE TITLE
Locally served falcon -- "We're not using custom kernels."

### ISSUE THREAD

**Issue by hlo-world** [huggingface/text-generation-inference#573]
### System Info

I'm serving falcon-40b locally in tgi docker container on ECS EC2. In my logs, I see these lines when it's spinning up:

`WARN shard-manager: text_generation_launcher: We're not using custom kernels.`

This line seems to only be in [neox_modeling.py#61](https://github.com/search?q=repo%3Ahuggingface%2Ftext-generation-inference+%22not+using+custom+kernels%22&type=code)

Are custom kernels available for falcon-40b? I don't see this warn log message when I'm serving falcon-40b from downloading it externally -- only when I serve from locally filesystem.

### Information

- [X] Docker

### Reproduction

G5.48xlarge

`Args { model_id: "/models/tiiuae/falcon-40b-instruct", revision: None, sharded: None, num_shard: Some(8), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 32000, max_waiting_tokens: 20, hostname: "0.0.0.0", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }`

### Expected behavior

Same kernel as serving falcon-40b from downloading it externally.

**Comment by Narsil** [comment]
Custom kernels is not used in falcon anyway, ignore tthe warning.
