### ISSUE TITLE
Is logging available?

### ISSUE THREAD

**Issue by loganlebanoff** [huggingface/text-generation-inference#577]
Is there a built-in way to log the requests and responses made to the service?

**Comment by OlivierDehaene** [comment]
You can use the LOG_LEVEL env var:

`export LOG_LEVEL="info,text_generation_router=debug"`

**Comment by loganlebanoff** [comment]
Sorry, I meant is there a way to save the requests and responses to a file/db?

**Comment by Narsil** [comment]
Use a logging agent: https://kubernetes.io/docs/concepts/cluster-administration/logging/

**Comment by loganlebanoff** [comment]
Thanks. I know Docker but I'm not familiar with Kubernetes, so it's hard for me to understand the info in that link. 

Is there a simple way to hook up a logging agent to the text-generation-service?

**Comment by Narsil** [comment]
Depends on the deployment and your cluster.
But it's not something this repo can help with, all the necessary tools exist within kube and the choice is up to you on how you want to manage/expose/filter your logs.
