### ISSUE TITLE
Remove model download dependency

### ISSUE THREAD

**Issue by jrowen** [huggingface/text-generation-inference#597]
### Feature request

This may already be supported; I just couldn't find the documentation.  There are cases where we want to run these models from an isolated environment, and it would be useful to be able to provide the model weights via a tar.gz file (stored in S3 for example).

### Motivation

Support teams who need to operate in a more restricted environment.

### Your contribution

I'd be happy to test out new features.

**Comment by OlivierDehaene** [comment]
You can already do that if you provide a local directory as model id, right?

**Comment by OlivierDehaene** [comment]
I don't think we will provide this feature.
A good warkaround (if you are deploying in an environment somewhat similar to k8s) is to have an init container download the tar.gz file from s3 and set it up in shared volume with the main tgi container.
