### ISSUE TITLE
I get the error 'TypeError: argument of type 'TrainingArguments' is not iterable' when launching docker with my local generator model.

### ISSUE THREAD

**Issue by yuri-son** [huggingface/text-generation-inference#602]
### Feature request

Hello developers, I am trying to infer a model of 13b using your inference api. 

I have a model with dtype float32, trained with multi-gpu, and it inferred fine, but when I float it with dtype float16 pytorch binary file, I get that error('TrainingArguments' is not iterable'), has anyone else encountered this?

If so, how would you suggest to solve it. Any advice would be appreciated. 

### Motivation

no

### Your contribution

no

**Comment by Narsil** [comment]
I think you're using an older version.

The loading script is tryiong to convert your training arguments into safetensors (which it cannot).
We added something to ignore those files.
