### ISSUE TITLE
0.9.1 performance does not meet expectations

### ISSUE THREAD

**Issue by zhaohb** [huggingface/text-generation-inference#603]
### System Info

text-generation-inference docker image : ghcr.io/huggingface/text-generation-inference:0.9.1 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I am using vllm benchmark program to test tgi performance, using llama-7b-hffp 16 model, test procedure reference link: https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py, we can see it will use tgi docker image loading model, I was use 0.8 version to start, and chang log shows that it doesn't support pagedattention, so I'm testing 0.9.1, but isn't showing much performance difference, and it doesn't appear to be using pagedattention, 
So, how to use pagedattetion correctly？

Here is the command to start the tgi image:
```shell
#!/bin/bash

PORT=9009
MODEL=$1
TOKENS=$2

docker run --gpus all --net=host --shm-size 10g \
           -v /data0:/data0 \
           ghcr.io/huggingface/text-generation-inference:0.9.1 \
           --model-id $MODEL \
           --sharded false  \
           --max-input-length 2048 \
           --max-total-tokens 4096 \
           --max-best-of 5 \
           --port 9009 \
           --max-concurrent-requests 5000 \
           --max-batch-total-tokens $TOKENS
```

### Expected behavior

I hope that deploying the model using tgi and being able to use pagedattention to improve inference performance

**Comment by OlivierDehaene** [comment]
What value do you use for TOKENS? What GPU do you deploy on?

**Comment by zhaohb** [comment]
python benchmark_serving.py --backend tgi --tokenizer ../../llama-7b-hf/ --dataset ShareGPT_V3_unfiltered_cleaned_split.json --request-rate 1 --port 9009

**Comment by zhaohb** [comment]
@OlivierDehaene 
thank you for your reply, I used the vllm benchmaek program with the following command:
```shell
python benchmark_serving.py --backend tgi --tokenizer .. /.. /llama-7b-hf/ --dataset ShareGPT_V3_unfiltered_cleaned_split.json --request-rate 1 --port 9009
```
It tests a random sample of 1000 inputs in ShareGPT_V3_unfiltered_cleaned_split.json. 
and I used A30.
 thank you very much.

**Comment by OlivierDehaene** [comment]
Yes but how do you start the tgi image? What argument to you give for TOKENS? If you set it to 17000 you should have a better throughput.

**Comment by AparnaAgrawal02** [comment]
hi, I have a similar issue, I am installing it locally on 1080Ti. Trying out inference of Flan-T5-large. I see the inference time on the HTTP request:  as 0.5 sec. while running the model normally on gpu takes 0.1 sec. How to set TOKENS in local installation?

**Comment by zhaohb** [comment]
I set the number of tokens to 4096, does it mean that I need to set a larger token to take advantage of 0.9.1 pagedattention？

**Comment by OlivierDehaene** [comment]
Yes. You need to either leave the default value (16000) or you can even try higher value but you might OOM.
