### ISSUE TITLE
30 minutes of waiting for shards to be ready, falcon-40b-instruct

### ISSUE THREAD

**Issue by sreeprasannar** [huggingface/text-generation-inference#607]
### System Info

 ghcr.io/huggingface/text-generation-inference:latest

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Running this on A6000 x 4 machine

```
model=tiiuae/falcon-40b-instruct #bigscience/bloom-560m
num_shard=4
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus '"device=4,5,6,7"' --net=host --cpus=".6"  -m 30G --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model --num-shard $num_shard --revision 1e7fdcc9f45d13704f3826e99937917e007cd975
```

### Expected behavior

I'd expect it to load in a few minutes? I'm not sure tbh. I can see this in `nvidia-smi`

```
|    4   N/A  N/A   1907904      C   /opt/conda/bin/python3.9        17000MiB |
|    5   N/A  N/A   1907905      C   /opt/conda/bin/python3.9        17112MiB |
|    6   N/A  N/A   1907908      C   /opt/conda/bin/python3.9        17192MiB |
|    7   N/A  N/A   1907907      C   /opt/conda/bin/python3.9        17112MiB |
```
It continues to climb so that's promising.. but I'd love to know from others if 48GBx4 is enough for `falcon-40b-instruct` and how long does it take to load?

**Comment by chiragjn** [comment]
> What the model already downloaded?
> Also, what is the speed of your disk?
> We load falcon-40b in ~1 minute usually in our setup.

Can we please get some hardware details here? :) 
Even with model already downloaded and converted to safetensors on good-quality disk, we see about 4-5 minutes of boot time

**Comment by OlivierDehaene** [comment]
30 seconds actually on a p4de.24xlarge:
- sharded on 2xA100 80GB
- disk maximum read/write throughput of 2.7 GB/s
