### ISSUE TITLE
How to make it?   How can we extend the 'max_new_tokens' from 1512 to either 4096 or 8192?

### ISSUE THREAD

**Issue by DiamondYuanqi** [huggingface/text-generation-inference#614]
### System Info

 How can we extend the 'max_new_tokens' from 1512 to either 4096 or 8192?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [X] My own modifications

### Reproduction

'max_new_tokens' from 1512 to either 4096 or 8192

### Expected behavior

'max_new_tokens' from 1512 to either 4096 or 8192

**Comment by OlivierDehaene** [comment]
It's an option from the launcher: --max-input-length controls the length in tokens of the prompt. --max-total-tokens controls the number of total tokens (tokens of the prompt + decoded tokens). 
So if you set --max-input-length to 1024 you can set --max-total-tokens to 1024 + 4096 = 5120 to handle 4096 max_new_tokens.

**Comment by DiamondYuanqi** [comment]
Thank you very much . I will try it later. 
May  i ask another question? 
How to make it that  adding the parameter 'return_num_sequences' into the arguments to enable the inference to generate more answers?

**Comment by OlivierDehaene** [comment]
You can use the best_of parameter with details and do_sample.
For example: 

```shell
curl https://api-inference.huggingface.co/models/bigcode/starcoder \
        -X POST \
        -d '{"inputs": "What is a meme?", "parameters":{"do_sample": true, "details":true, "best_of": 2}}' \
        -H "Content-Type: application/json" | json_pp
```

**Comment by DiamondYuanqi** [comment]
So crystal . Thanks
