### ISSUE TITLE
sagemaker image for 0.9.2 

### ISSUE THREAD

**Issue by nth-attempt** [huggingface/text-generation-inference#625]
### Feature request

Hi there, Any estimate on when the sagemaker images for 0.9.2 TGI would be published? Is there a pipeline to create and publish the sagemaker images automatically? thanks! 

### Motivation

N/A

### Your contribution

N/A

**Comment by timesler** [comment]
Would be great to have this. Although it's easy enough to use the images already available and change their entrypoint to `sagemaker-entrypoint.sh`, my org has security restrictions that limit us to using images from certain sources (basically only ECR repos)

**Comment by cirocavani** [comment]
Hi,

I used GitHub images to create my own for 0.9.1.

You can see the scratch in the other issue:

https://github.com/huggingface/text-generation-inference/issues/493#issuecomment-1626788288

**Comment by philschmid** [comment]
We are on it!

**Comment by abhibst** [comment]
Hi @philschmid , Any update on this issue , many thanks

**Comment by philschmid** [comment]
Yes version 0.9.3 got release friday night.

**Comment by abhibst** [comment]
Thanks @philschmid ,Kudos

**Comment by nth-attempt** [comment]
Thank you! https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-text-generation-inference-containers
