### ISSUE TITLE
Upgrade to Flash attention V2

### ISSUE THREAD

**Issue by Jmkernes** [huggingface/text-generation-inference#627]
### Feature request

The newest version of Flash Attention is now available:

press release: https://crfm.stanford.edu/2023/07/17/flash2.html
source code: https://github.com/Dao-AILab/flash-attention

### Motivation

This should be a drop-in upgrade for the current flash attention modules.

### Your contribution

Writing code.

**Comment by njhill** [comment]
@Jmkernes there's already a PR for this https://github.com/huggingface/text-generation-inference/pull/624
