### ISSUE TITLE
Rules of thumb for setting `max-batch-total-tokens` and `max-batch-prefill-tokens`

### ISSUE THREAD

**Issue by ToddMorrill** [huggingface/text-generation-inference#629]
### Feature request

Are there any rules of thumb for setting `max-batch-total-tokens` and `max-batch-prefill-tokens` besides binary search until I don't get an OOM error? I'm trying to run `tiiuae\falcon-7b` in `bfloat16` on an Nividia T4 GPU and I think I've got about 1GB of GPU memory left after the model loads. What can I pack into this? Presumably, I should understand the number of layers in the model $\ell$, the dimension of the activations $d$, and the max sequence length $k$ (which I set) to determine how big my `max-batch-total-tokens` can be, is that right? In particular, I'd take

$$M = \frac{1 \text{ GB}}{\ell\cdot d \cdot k \cdot 2 \text{ bytes}},$$

which might account for the total number of (max length) sequences I can fit in memory at once. So then maybe I can take `max-batch-total-tokens` to be $\lfloor M * k\rfloor$? So let's take Falcon-7b as an example, where $\ell=32$, $d=4,544$, and $k=2,048$, which by the formula above gives $\lfloor 1.67 \cdot 2,048\rfloor = 3,420$. In practice, I was able to push about 2,000 tokens through the model when experimenting outside of the TGI Docker container. But this seems to be nowhere near what I'm able to achieve inside the container. With v0.8.0 I was able to start the container on the T4 enabled machine without setting any of these parameters. Now with v0.9.0, it seems that the only way I can operate the container with any reasonable input/output sequence length (i.e. >256) is in a quantized setting. So either I'm doing something wrong with my settings in v0.9.0 or a change was introduced that's preventing me from using the container. Maybe you're pushing a random batch through to "warm-up" the instance to catch OOM errors during startup as opposed to during operation?

I don't quite have the right mental model for how all of these parameters interact, particularly `max-batch-prefill-tokens`. I'm happy to read documentation if it exists (I've read `launcher/src/main.rs`), and code, if necessary. Please let me know if and where I'm going wrong above.

Here's my Docker run command for reference.
```
model=tiiuae/falcon-7b
max_input_length="511"
max_total_tokens="512"
max_batch_total_tokens="512"
max_batch_prefill_tokens="512"
quantize="bitsandbytes"
volume=/home/azureuser/cloudfiles/code/Users/todd.morrill/llm/.cache # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data \
    -e MODEL_ID=$model \
    -e MAX_INPUT_LENGTH=$max_input_length \
    -e MAX_TOTAL_TOKENS=$max_total_tokens \
    -e MAX_BATCH_TOTAL_TOKENS=$max_batch_total_tokens \
    -e MAX_BATCH_PREFILL_TOKENS=$max_batch_prefill_tokens \
    -e QUANTIZE=$quantize \
    ghcr.io/huggingface/text-generation-inference:0.9
```

### Motivation

NA

### Your contribution

If there's any way for me to understand the dynamics of these parameters, I would happily document my experiences and any rules of thumb for others.

**Comment by Narsil** [comment]
> Maybe you're pushing a random batch through to "warm-up" the instance to catch OOM errors during startup as opposed to during operation

Exactly, we had lots of operational issues when our settings where not correct, and randomly failing in production because we had too much load. We feel crashing early is much better (even if a bit of a hassle to figure out the proper configuration right now, we have ideas on how to improve this)

> I'm happy to read documentation if it exists 

`text-generation-launcher --help` is the best documentation for these atm. (You can send this as entry point to docker to have it for your particular version)


> But this seems to be nowhere near what I'm able to achieve 

Memory in general is very hard to theoretically compute. For instance Attention can be MHA (classic), MQA(santacoder) GQA (falcon) which have very different memory requirements. Add on top the quantization and it becomes very hard to reason entirely statically about this.
Memory needs to be allocated contiguously too, so you're calculation will not hold in a deeply fragmented memory (PagedAttention should solve that).

I cannot give you a recipe, but 1GB is not really much leftover memory to stack requests. IMO splitting the model onto 2 T4s is likely to be beneficial here because you'd have more room to stack requests. The NCCL overhead might be compensated by the reduced compute on each card.
Just try and see, but in general when deploying we try to have as much spare room as possible to reach the COMPUTE/MEMORY boundary for our models, this is the sweet spot you want to achieve.
It should be very easy to see using `text-generation-benchmark` (look for inflection points in the graphs)

**Comment by Narsil** [comment]
See https://github.com/huggingface/text-generation-inference/pull/630/files for some steps we're taking to simplifying all of this.

**Comment by OlivierDehaene** [comment]
#630 was merged and it simplifies this process. Can you try using latest?

**Comment by ToddMorrill** [comment]
I'm using the latest and I've been setting max-batch-total-tokens through a combination of my analysis above and trial-and-error. I did bump up to a single A100 with 80GB of RAM for Falcon 7b instruct and 2 A100s with 80GB of RAM for Falcon 40 instruct. Here are the results of some load tests in case it's of interest to you. I threw random examples from the Alpaca dataset at these models using Locust for 10 minutes with up to 128 concurrent users. These models are running on Azure ML Online Endpoints with the configurations below. I'm allowing Azure to pass all requests through to `TGI` so any throttling or swamping that's occurring is from `TGI`. Any omitted settings are left as default.

**Falcon 7b instruct**
DTYPE: "bfloat16"
MAX_BATCH_TOTAL_TOKENS: "100000"
MAX_CONCURRENT_REQUESTS: 512
![image](https://github.com/huggingface/text-generation-inference/assets/12600692/9c697b5f-2076-4d99-89b6-c259509ba580)

_Error analysis_
Method | Name | Error | Occurrences
-- | -- | -- | --
POST | /generate | "ConnectionError(ProtocolError('Connection aborted.',   RemoteDisconnected('Remote end closed connection without response')))" | 247
POST | /generate | "HTTPError('424 Client Error: Failed Dependency for url:   https://<endpoint>.eastus.inference.ml.azure.com/')" | 1394
POST | /generate | 'ConnectionError(MaxRetryError("HTTPSConnectionPool(host=\'<endpoint>.eastus.inference.ml.azure.com\',   port=443): Max retries exceeded with url: / (Caused by   NewConnectionError(\'<urllib3.connection.HTTPSConnection object at   0x....>: Failed to establish a new connection: [Errno 8] nodename nor   servname provided, or not known\'))"))' | 7
POST | /generate | 'SSLError(MaxRetryError("HTTPSConnectionPool(host=\'<endpoint>.eastus.inference.ml.azure.com\',   port=443): Max retries exceeded with url: / (Caused by   SSLError(SSLEOFError(8, \'EOF occurred in violation of protocol   (_ssl.c:997)\')))"))' | 2


**Falcon 40b instruct**
DTYPE: "bfloat16"
NUM_SHARD: "2"
![timeseries](https://github.com/huggingface/text-generation-inference/assets/12600692/96b660e9-cc23-482b-a0b0-17e79f8b1700)

I'm going to keep playing around with a variety of configurations to maximize the number of concurrent users on a single server instance. I'm also measuring the total number of outstanding tokens that have been sent to the server and measuring response lengths. I imagine it would be better to analyze server performance w.r.t. token load as opposed to user load but I don't have tidy analysis for that yet.

**Comment by OlivierDehaene** [comment]
If I remember correctly, the default regime of locust suffers from coordinated omission. I would suggest using k6 with [the constant vus executor](https://k6.io/docs/using-k6/scenarios/executors/constant-vus/) instead if you want to benchmark production throughput.
