### ISSUE TITLE
Flash Attention v2

### ISSUE THREAD

**Issue by epinnock** [huggingface/text-generation-inference#631]
### Feature request

Is there a roadmap to support flash attention 2?

### Motivation

It would further speed up inference on ampere and hopper devices

### Your contribution

I can contribute in anyway needed.

**Comment by Narsil** [comment]
Thanks very much for the proposal of contribution: 

We already have an open PR for it: 
https://github.com/huggingface/text-generation-inference/issues/631

Just for potential readers, flash attention (v1 or v2) is not a big component of text-generation-inference overall speed by virtue of it's kernel internals.
Most of the time in generative models is spent in `decode` cycles (with kv cache) where as flash attention only is used in `prefill` (initial queries without kv cache). The biggest asset of flash attention is that it enables us to remove entirely `padding` which is essential when receiving very varied requests to avoid adding lots of unecessary pad tokens (and uselessly computing attention on them)

There might be other areas where you could contribute if you want to !

**Comment by epinnock** [comment]
@Narsil is the pr branch available for me to pull the link in the comment links to this issue

**Comment by Narsil** [comment]
The PR already landed on master `0.9.3` should be released soon if not already (and also has llamav2 support !)
