### ISSUE TITLE
Return total tokens generated as an http response header

### ISSUE THREAD

**Issue by brightsparc** [huggingface/text-generation-inference#637]
### Feature request

TGI returns a number of http headers that provide statistics on the computation time and performance, however the total tokens generated is not returned (only the [compute characters](https://github.com/huggingface/text-generation-inference/blob/main/router/src/server.rs#L237) from the input).

This FR is to add a new response header `X-Total-Tokens` for the value `response.generated_text.generated_tokens`.

### Motivation

Having total-tokens would provide the ability to get per-request stats without having to parse the response body, and enable implementation of dynamic rate limiting based on cumulative token generation.  This could be implemented in a proxy such as the istio [access log](https://istio.io/latest/docs/tasks/observability/logs/access-log/) envoy filter. 

### Your contribution

Since this is a simple change I can create a PR to extend the response header to include this.

**Comment by lizzzcai** [comment]
this is a very useful feature as our team are looking into it as well (mainly for metering, for rate-limiting, I think it will depends on the prompt_tokens and max_tokens in the input), to match the similar feature from azure openai [response](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#example-response-2):
```json
"usage":{"prompt_tokens":58,
"completion_tokens":68,
"total_tokens":126},
```

**Comment by brightsparc** [comment]
> this is a very useful feature as our team are looking into it as well (mainly for metering, for rate-limiting, I think it will depends on the prompt_tokens and max_tokens in the input), to match the similar feature from azure openai [response](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#example-response-2):
> 
> ```json
> "usage":{"prompt_tokens":58,
> "completion_tokens":68,
> "total_tokens":126},
> ```

The server already returns `x-compute-characters` which I think aligns with `prompt_tokens` in your above json. The [API](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate) returns `details. generated_tokens` in the json response, which we may want to return as `x-generated-tokens` instead of `x-total-tokens` which i assume would be the addition of the two.

**Comment by ansSanthoshM** [comment]
I am also looking for this feature for TGI inference for Llama2 model.

**Comment by brightsparc** [comment]
This feature has been implemented in [lorax](https://github.com/predibase/lorax)  (LoRA eXchange), a TGI fork from v0.9.4, that includes support for Multi-LORA inference.

**Comment by Narsil** [comment]
Now also supported here. https://github.com/huggingface/text-generation-inference/pull/1436

**Comment by ansSanthoshM** [comment]
Thanks for this PR.
Does this work for all LLM including Llama2 ? 
Please provide an example python code to retrive both prompt and generated token count.

**Comment by Narsil** [comment]
@ansSanthoshM Yes.

>  Please provide an example python code to retrive both prompt and generated token count.

Sorry we are not your personal coders.
Just retrieve the header `x-prompt-tokens` and `x-generated-tokens`.

**Comment by Narsil** [comment]
`curl ... -D -`  will show you the headers from curl, for Python it depends what lib you use for the http request.

**Comment by ansSanthoshM** [comment]
@Narsil  Thanks for understanding and your interest to help again.

I can get the header info using **requests.post** approach using below code, no issue with this. 

> import requests
> import time
> 
> headers = {
>     "Content-Type": "application/json",
>     'accept': 'application/json'
> }
> 
> def input_json(query):
>     data = {
>         'inputs': query,
>         'parameters': {
>             'max_new_tokens': 200,
>             'details': True,
>             "decoder_input_details": True,
>             'streaming':False,             
>                 },
>             }
>     return data
> 
> query='What is Deep Learning?'
> start_time=time.time()
> **response = requests.post('http://0.0.0.0:8080/generate', headers=headers, json=input_json(query))**
> end_time=time.time()
>
> Time_taken=end_time-start_time
> print(response.content)
> print(response.json())
> print(response.headers)
> print("LLM Response :{}".format(response.json()['generated_text']))
> print("Generated Tokens :{}".format(response.json()['details']["generated_tokens"]))
> print("Input Tokens  :{}".format(len(response.json()['details']["prefill"])))
> print("Total Tokens  :{}".format(int(response.json()['details']["generated_tokens"])+len(response.json()['details']["prefill"])))
> print("Queue Time :{} ms".format(response.headers['x-queue-time']))
> print("time-per-token :{} ms".format(response.headers['x-time-per-token']))
> print("Inference time taken :{:.1f} sec".format(float(response.headers['x-inference-time'])/1000))
> print("Total time taken :{:.1f} sec".format(Time_taken))
> print("Finish Reason :{}".format(response.json()['details']["finish_reason"]))

But in pratice, i need to use few chains, so i am using **HuggingFaceTextGenInference** API as shown in below code rather **request.post** API as in previous approach. With this approach, i don't know how to get Header Info.  I understand that this is not actually your part of work. Please guide if possible, if this is too much to ask, please ignore.


> from langchain.llms import HuggingFaceTextGenInference
> from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
> server="http://0.0.0.0:8080"   # 70B Model 
> llm= **HuggingFaceTextGenInference**(
>     inference_server_url=server,
>     max_new_tokens=100,
>     top_k=10,
>     top_p=0.95,
>     typical_p=0.95,
>     temperature=0.1,
>     repetition_penalty=1.03,
>     streaming=True,
>     #decode_input_details= True  ; Not working 
>         )
**> llm("What is Deep Learning?",
>     #return_full_text=True,
>     callbacks=[StreamingStdOutCallbackHandler()])**
>

**Comment by nikhil-weamai** [comment]
please use the endpoint url like this :   **https://xxx.cloud/v1/chat/completions**
after that you will get the token count in  response.
