### ISSUE TITLE
The performance of v0.9 is not good as v0.8

### ISSUE THREAD

**Issue by jameswu2014** [huggingface/text-generation-inference#640]
### System Info

Recently, I upgraded TGI to v0.9 from v0.8. I found the cost time of per tokens is longer than v0.8. my model is a 53B Llama model, I got about 30ms per tokens in v0.8, while, 37ms per tokens in v0.9. It is because import vllm?

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

53B llama model   v0.8 vs v0.9

### Expected behavior

v0.9 is better than v0.8

**Comment by Narsil** [comment]
Any way you could share the model location/id ? 
What hardware ?
Where/how are you measuring the difference?
