### ISSUE TITLE
auto max_batch_total_tokens OOM

### ISSUE THREAD

**Issue by flozi00** [huggingface/text-generation-inference#651]
### System Info

TGI from docker, latest version
RTX A6000 48GB

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

https://github.com/huggingface/text-generation-inference/pull/630

Since that PR is merged I am running OOM, even with small models.
The GPU is not partitioned, so other workloads are within the used Vram
It seems like that for calculation the total Vram is used, not the free Vram.
Partitioning the GPU so that the OS thinks the GPU is smaller fixes that, with shared workloads OOM occures

### Expected behavior

Use free Vram for calculation, not total GPU Ram

**Comment by OlivierDehaene** [comment]
It is not easy to get access to the amount of free VRAM. In #659, we add `--cuda-memory-fraction` to allow you to set the maximum fraction of VRAM taken by TGI.

**Comment by flozi00** [comment]
what about https://pytorch.org/docs/stable/generated/torch.cuda.mem_get_info.html#torch-cuda-mem-get-info ?

**Comment by OlivierDehaene** [comment]
Oh nice I missed this function completely. I will try it out.
