### ISSUE TITLE
Question: GPTQ Support in Inference Widgets

### ISSUE THREAD

**Issue by gsaivinay** [huggingface/text-generation-inference#652]
### Feature request

Hello,

I was wondering if there is any GPTQ related parameter we can set in the model cards so that the inference API widget will load the model in quantized mode, for example `gsaivinay/Llama-2-7b-Chat-GPTQ`.

### Motivation

Inference API widget for GPTQ models.

### Your contribution

N/A

**Comment by OlivierDehaene** [comment]
That's not on our radar for now.
