### ISSUE TITLE
Can't pull the text generation inference docker image 

### ISSUE THREAD

**Issue by adarshxs** [huggingface/text-generation-inference#657]
### System Info

I run the command 
`docker pull ghcr.io/huggingface/text-generation-inference:sha256-xxxxxxxxxxxxxxxxxxxxx467d7cf721f015b0987c956837f0e4f33e7b2.sig`

and the output is 
`Error response from daemon: Get https://ghcr.io/v2/: read tcp 10.10.5.108:33012->20.207.73.86:443: read: connection reset by peer`

is it my client side error?  

I am sshing into a local dgx machine 
`ssh -L 8888:localhost:8888 dgx-user1@10.10.x.xxx`

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

run the command 
`docker pull ghcr.io/huggingface/text-generation-inference:sha256-xxxxxxxxxxxxxxxxxxxxx467d7cf721f015b0987c956837f0e4f33e7b2.sig`

Any fixes or checks I might have to run to fix this?

### Expected behavior

download the image and then be able to run `docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:0.9 --model-id $model --num-shard $num_shard`

**Comment by OlivierDehaene** [comment]
`.sig` files in the docker registry are Cosign signatures. You need to pull `ghcr.io/huggingface/text-generation-inference:sha-5a1512c`.
