### ISSUE TITLE
GPTQ quantization of Llama-2 70b fails - works for 13b

### ISSUE THREAD

**Issue by yadamonk** [huggingface/text-generation-inference#662]
### System Info

Docker v0.9.3

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I have the following Dockerfile

```
FROM ghcr.io/huggingface/text-generation-inference:latest
RUN pip install texttable datasets
```

The following command works for the 13b version and produces a model that I can run using TGI

```
docker run \
    -it \
    --gpus all \
    --ipc=host \
    -v $(pwd):/ec2 \
    -v $volume:/data \
    -v /dev/shm:/dev/shm \
    -e HUGGING_FACE_HUB_TOKEN=$HF_HUB_TOKEN \
    -e MODEL_NAME=meta-llama/Llama-2-70b-chat-hf \
    -e OUTPUT_DIR=/ec2/models--meta-llama--Llama-2-70b-chat-hf-gptq \
    --entrypoint /bin/bash \
    tgi-quantize

text-generation-server quantize $MODEL_NAME $OUTPUT_DIR
```

For the 70b version I get the following error:

```
Quantizing layer 1/80..
+------------------+--------------+------------+-----------+-------+
|       name       | weight_error | fp_inp_SNR | q_inp_SNR | time  |
+==================+==============+============+===========+=======+
Pre hook model.layers.0
Traceback (most recent call last):

  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 207, in quantize
    quantize(

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quantize.py", line 916, in quantize
    quantizers = sequential(

  File "/opt/conda/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/gptq/quantize.py", line 696, in sequential
    outs[j] = layer(inps[j].unsqueeze(0), **extra)[0]

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 293, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(

  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "/opt/conda/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 198, in forward
    key_states = self.k_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)

RuntimeError: shape '[1, 2048, 64, 128]' is invalid for input of size 2097152
```

### Expected behavior

The command above should produce a working quantized model.

**Comment by ankit201** [comment]
Same for me

**Comment by rohanpooniwala** [comment]
I am running into the same issue when trying the same on A100s

**Comment by ankit201** [comment]
https://github.com/huggingface/text-generation-inference/pull/648

**Comment by yadamonk** [comment]
Thanks, @ankit201. Did you use a model that was already quantized?

**Comment by ankit201** [comment]
@yadamonk Yes, you can use https://huggingface.co/TheBloke/Llama-2-70B-chat-GPTQ as this is the quantised one.
The original llama-70b-chat takes 72GBx2 on A100, strangely the gptq model which is being used here just reduces vRAM usage by 10GB on each of the 2 A100, i.e 62GBx2 on A100, I'm not sure if the model is quantized efficiently or the model which I'm using from the main branch from Bloke's repo intends to use that amount of GPU. Good news is the GPU usage doesn't spike as it was doing in case of MPT when large number of users hit your server.

If you still want to quantize llama-2, I think @Narsil could shed some guiding light here.

**Comment by yadamonk** [comment]
Thank you. I'm still hoping that we will be able to run the 70b model on 4 A10G cards. @Narsil any thoughts on that?

**Comment by Narsil** [comment]
Hey you cannot shard on 4 shards the 70B unfortunately.

Not sure what the original error is, but it's simply because of shape divisibility.
GPTQ uses 8 4-bit numbers which means the shape loose a factor 8 in dimensions, which means the code will yell that the same are not divisible by 4 anymore (which True).

Working around that is possible but tremendously slow (since the kernels expects i32, everything as to be cast into at least int8, split around, copied for alignement and recasted as i32). And even then I'm not sure the kernels can handle non divisible by 8 length.

Any help on this will be appreciated. On our end, we cannot promise anything, this is not a real blocker in our deployments atm and the solution will likely be tricky at least.

**Comment by yadamonk** [comment]
Thank you @Narsil. So we need 8 GPUs to run the 70B model? Llama 1 33B happily ran on a single A10G with llama.cpp.
