### ISSUE TITLE
NotImplementedError: Sharded Llama requires Flash Attention enabled models.

### ISSUE THREAD

**Issue by Minami-su** [huggingface/text-generation-inference#663]
command:
text-generation-launcher --model-id LLaMA-13B --disable-custom-kernels --port 6006 --num-shard 2

result:
2023-07-20T12:31:14.506674Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: No module named 'vllm_cache_ops'

NotImplementedError: Sharded Llama requires Flash Attention enabled models.

**Comment by rishu931997** [comment]
Seems like you are running older version of text-generation-inference. In the later version v0.9.0, 'vllm' integrstion was added which requires it to be installed along with flash-attn.
You can pull the latest changes and then run `cd server && make install-vllm`. Re-run the launcher command.

**Comment by Minami-su** [comment]
thank you.

**Comment by Minami-su** [comment]
> Seems like you are running older version of text-generation-inference. In the later version v0.9.0, 'vllm' integration was added which requires it to be installed along with flash-attn. You can pull the latest changes and then run `cd server && make install-vllm`. Re-run the launcher command.

thank you.

**Comment by edward-io** [comment]
It would be useful to update the Makefile to install this when BUILD_EXTENSIONS=True.
