### ISSUE TITLE
allow USE_FLASH_ATTENTION env variable to be False

### ISSUE THREAD

**Issue by sarthak10193** [huggingface/text-generation-inference#667]
### Feature request

Flash attention is a hard requirement to get the inference server up and running on an A100
<img width="743" alt="Screenshot 2023-07-20 at 7 17 43 PM" src="https://github.com/huggingface/text-generation-inference/assets/8283173/63dc1901-288e-4667-80a3-42785ffdc3eb">

### Motivation

As an independent researcher/tinkerer, it would be great to democratize access to state-of-the-art models. For AWS users the inference server currently requires us to use `A100 p4d.x24large` instances which cost 33/hr. 

USE_FLASH_ATTENTION=false will understandably be slow for production use cases but will allow exploration

### Your contribution

Happy to help with a new PR and pair up

**Comment by Narsil** [comment]
Check out the code you linked `USE_FLASH_ATTENTION` already exists and will disable using flash attention.

Now not all models are coded without flash attention, and we have no intention of supporting a wide array of non flash models, so it's all best effort using transformers versions for them.

**Comment by sarthak10193** [comment]
thanks for clarifying the roadmap. @Narsil

**Comment by Narsil** [comment]
Just to make it complete, the reason is simple, without flash, we need padding, and padding adds an very big runtime cost (by forcing a lot of pad tokens to be computed each time there's a large request in combination with smaller ones).

This is very detrimental, and should really be avoided if possible.
