### ISSUE TITLE
Accessing LLAMA 2 Model 

### ISSUE THREAD

**Issue by sarathsurpur** [huggingface/text-generation-inference#668]
### Model description

Hi, I tried running the LLAMA 2 Model using this text generation inference but I am getting below error

 Error:
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 223, in get_model
    raise NotImplementedError(FLASH_ATT_ERROR_MESSAGE.format("Sharded Llama"))

NotImplementedError: Sharded Llama requires a CUDA device with capability 7.5, > 8.0 or 9.0. No compatible CUDA device found.

Gpu details:

<img width="439" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/42287472/3d3e503f-ffc7-4a64-98ae-bdc93c90668d">

Model card: daryl149/llama-2-7b-chat-hf

### Open source status

- [ ] The model implementation is available
- [X] The model weights are available

**Comment by Narsil** [comment]
If you're using unsharded model it might be able to work. Sharded requires flash for this model.
