### ISSUE TITLE
What is optimal  max batch size max sequence length (max_total_tokens) for running llama 2 70b chat  on 4 A100 80GB?

### ISSUE THREAD

**Issue by yakotoka** [huggingface/text-generation-inference#672]
This is what i have in my current config 
validation_workers: 2, max_total_tokens: 4096, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20

What do you recommend I should use to get the most out of inference for this setup?

**Comment by Narsil** [comment]
You have to test and try it for yourself.

Sorry but we cannot give user specific advice.

Read carefully the documentation is the best we can offer for now, some issues around here might help too.
