### ISSUE TITLE
Model with large context window

### ISSUE THREAD

**Issue by ArnaudHureaux** [huggingface/text-generation-inference#677]
### Model description

Hi everyone,
Do you think that's it's possible to handle a model with a large context window ? Every models proposed has small context window (<5K tokens) 
Thanks,

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by Paxosgold** [comment]
> ### Model description
> Hi everyone, Do you think that's it's possible to handle a model with a large context window ? Every models proposed has small context window (<5K tokens) Thanks,
> 
> ### Open source status
> * [x]  The model implementation is available
> * [x]  The model weights are available
> 
> ### Provide useful links for the implementation
> _No response_

Sounds like it could work

**Comment by OlivierDehaene** [comment]
Yes it is possible.
