### ISSUE TITLE
specify role parameters for llama-2 chat models

### ISSUE THREAD

**Issue by occia** [huggingface/text-generation-inference#682]
## Feature Request

Hi, I've tried using the docker to run inference server on llama chat models, e.g., `Llama-2-13b-chat-hf`. However, its [api](https://huggingface.github.io/text-generation-inference) does not provide a way to specify model parameters like `system role`.

Examples provided by llama-2 repo have showed this parameter ([link](https://github.com/facebookresearch/llama/blob/6c7fe276574e78057f917549435a2554000a876d/example_chat_completion.py#L28)).

May I know what should I do for enabling this in server api? Or have I missed sth basic?

## Motivation

This parameter is important for chat models such as `Llama-2-7b-chat-hf`, `Llama-2-13b-chat-hf`, and `Llama-2-70b-chat-hf`.

## How I run the inference server

Example command I used for running inference server:

```bash
model=/data/Llama-2-7b-chat-hf
num_shard=4
volume=$PWD/data
docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model --num-shard $num_shard
```

**Comment by OlivierDehaene** [comment]
If you look at the internal code, the llama repository re-interprets the dialogs as strings internally. These strings are what TGI expect as input to its API.
