### ISSUE TITLE
AWS Inferentia (inf1, inf2) support

### ISSUE THREAD

**Issue by OrigamiDream** [huggingface/text-generation-inference#688]
### Feature request

I can't find any guidance on integrating HuggingFace TGI and AWS Inferentia.
I've found several documents about deployment guides for individual end-to-end models, but I don't see them for these autoregressive models like CausalLM.

Therefore, I would like to request a feature to support for AWS Inferentia.

### Motivation

SageMaker is expensive and rigid, unlike Serverless.
Support for inf1 and inf2 instances would reduce the cost of cloud computing.

### Your contribution

N/A

**Comment by Narsil** [comment]
Thanks, we currently don't support it, because to the best of my knowledge there is no flash attention on inferentia, which is an important piece of TGI.

We have started some work internally for specialized hardware, but it's a sizeable amount of work.

**Comment by philschmid** [comment]
The biggest challenge with inferentia is the missing support of dynamic shapes.

**Comment by nikitajz** [comment]
This seems an AWS Neuron issue to track:
https://github.com/aws-neuron/aws-neuron-sdk/issues/564

**Comment by muhammad-asn** [comment]
https://github.com/huggingface/optimum-neuron/tree/main/text-generation-inference
Another tools from hugging face
