### ISSUE TITLE
Proxy variables not being passed to text-generation-server

### ISSUE THREAD

**Issue by nero19960329** [huggingface/text-generation-inference#69]
I have noticed that the text-generation-launcher entry point in this project uses subprocess to call the text-generation-server program, but it does not pass all the necessary environment variables. Specifically, the proxy information such as http_proxy and https_proxy are not being passed to the text-generation-server program. This prevents the proxy configuration set during docker run from being effective.

To ensure that the proxy information is properly passed to the text-generation-server program, I kindly request that the necessary environment variables be added to the entry point.

Thank you for your attention to this matter.

Related codes: 

https://github.com/huggingface/text-generation-inference/blob/68455353f5c158baf5576da6fcb670404ee0c391/launcher/src/main.rs#L121

**Comment by OlivierDehaene** [comment]
Should be fixed on main.
