### ISSUE TITLE
Running TGI docker container on a Mac M1

### ISSUE THREAD

**Issue by d4nielmeyer** [huggingface/text-generation-inference#690]
### Feature request

Hi all,
has anyone experience with getting a LLM supported by the Hugging Face module **"text-generation-inference"** up and **running in a docker container locally on a Mac M1?**

I was planning to deploy a Llama-2-7B-Chat on my local device. Although the documentation only mentions NVIDIA GPUs I was wondering whether this is also possible on my Mac? A guy on YouTube mentioned that he succeeded, but unfortunately didn't provide any details except of adding the platform flag to the docker run command. 

My command in the terminal so far is:
`docker run --gpus all --shm-size 1g -p 3000:80 -v /llama2:/data --platform linux/amd64 ghcr.io/huggingface/text-generation-inference:latest --model-d meta-llama/Llama-2-7b-chat --num-shard 1`

But it seems that it doesn't find the right GPU. The NVIDIA drivers require to have the NVIDIA Container Toolkit installed. Not sure if something similar exists for M1? Or is it because of an incorrect implementation on my part?
`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]`

### Motivation

If it's because of an incorrect implementation on my part I would really appreciate any comment/ idea that points me into the right direction; if it's just not possible yet I think it would be a nice feature as there are probably a lot of mac users out there that would benefit from a supported solution

### Your contribution

Not sure how, but of course I'd love to contribute in any way possible

**Comment by Narsil** [comment]
I don't think M1 GPU are exactly CUDA devices.

This is not intended to work on M1/M2 and probably will not work. Unless you have an external GPU connected by some means.

Closing this as M1 is not officially supported as a target and probably won't be for the foreseeable future.

There are other projects more targeted for M1 (by huggingface or others).
I'll let others comment as I might not be the most up-to-date with this.

**Comment by AlexAbades** [comment]
Hey @d4nielmeyer did you manage to go around the problem of not having a GPU to actually implement the TGI on a mac? Don't know if you tried further, but I agree with you, it will be a nice thing to have, even if it not Cuda accelerated. At least for testing in development environment.

**Comment by d4nielmeyer** [comment]
@AlexAbades No unfortunately not. Ended up renting a virtual machine.
