### ISSUE TITLE
Sagemaker - Llama 2 -70b -chat-hf - Error while downloading: Os { code: 28, kind: StorageFull, message: "No space left on device" }

### ISSUE THREAD

**Issue by monuminu** [huggingface/text-generation-inference#694]
### System Info

Hi All, How to fix issue in TGI Exception: Error while downloading: Os { code: 28, kind: StorageFull, message: "No space left on device" }

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

predictor = llm_model.deploy(
  initial_instance_count=1,
  instance_type=instance_type,
  #volume_size=400, # If using an instance with local SSD storage, volume_size must be None, e.g. p4 but not p3
  container_startup_health_check_timeout=1000, # 10 minutes to be able to load the model
  model_data_download_timeout = 3600
)

### Expected behavior

It should get deployed

**Comment by Narsil** [comment]
The issue seems pretty clear no ?

**Comment by monuminu** [comment]
released the issue is with g5 instance which is 380GB.

**Comment by OlivierDehaene** [comment]
No space left on device
