### ISSUE TITLE
INFO: pip is looking at multiple versions of grpcio-status to determine which version is compatible with other requirements. This could take a while.

### ISSUE THREAD

**Issue by taoari** [huggingface/text-generation-inference#697]
### System Info

Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: a0d55358d20cf3f86083b79765b80704ce9d8404
Docker label: N/A
nvidia-smi:
Tue Jul 25 17:10:33 2023       
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  Tesla T4                        On | 00000000:12:00.0 Off |                    0 |
   | N/A   42C    P8                9W /  70W|      2MiB / 15360MiB |      0%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+
   |   1  Tesla T4                        On | 00000000:D8:00.0 Off |                    0 |
   | N/A   78C    P0               30W /  70W|  13921MiB / 15360MiB |      0%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+
                                                                                            
   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   +---------------------------------------------------------------------------------------+

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Follow https://github.com/huggingface/text-generation-inference#local-install

### Expected behavior

Should not take so long to install

**Comment by OlivierDehaene** [comment]
This issue seems more related to pip than TGI.

**Comment by taoari** [comment]
@OlivierDehaene It would be good if TGI can specify which version of grpcio-related libraries it defaults to, otherwise, pip will try each version to test which works, this significantly slows the install process. I would rather not consider this as a pip issue, just TGI did not tell which version of grpcio it should use.

**Comment by OlivierDehaene** [comment]
The versions are pinned in the requirements.txt and pyproject.toml. At the end of day, if pip is confused I would advise you to install through poetry directly.

Also, the local install is not the recommended way of using TGI. The local install is aimed at TGI developers/maintainers.
