### ISSUE TITLE
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

### ISSUE THREAD

**Issue by Tarun3679** [huggingface/text-generation-inference#699]
### System Info

Is there a  particular way to turn off the text generation inference api? I just do ctrl+z on the terminal and when I try to run it on the same or different port again I face this issue. Is there a way to work around this issue? I did try using ubuntu options to kill the process or port. But that doesn't seem to be effective. It only works when we are able to shutdown the instance and bring it back up, Any advice on how to solve this issue?

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I think running the following command - text-generation-launcher --model-id mosaicml/mpt-30b-instruct --max-input-length 2048 --max-total-tokens 3072 --quantize bitsandbytes --num-shard 4 --port 8888 and then closing using ctrl+z and then running the same command again should reproduce the issue. 

### Expected behavior

Technically, when we close and run back again. it should work, But looks like it doesn't.

**Comment by Narsil** [comment]
Not sure about your platform

On Linux: 
Ctrl+C kills a process. 
Ctrl+Z puts it into the background.

**Comment by Tarun3679** [comment]
Could you suggest me an ideal way for now to kill the process?

**Comment by Narsil** [comment]
Ctrl+C

**Comment by Tarun3679** [comment]
The solution works, Thanks a lot Narsil!
