### ISSUE TITLE
[Question]: Webserver and GPU work on different machines

### ISSUE THREAD

**Issue by malteos** [huggingface/text-generation-inference#700]
Hi all,

thanks for this amazing project. 

Is it generally possible with the current setup to distribute the web server and GPU workload on different machine? And if so, what settings/modifications are needed to achieve this?

Best,
Malte

**Comment by Narsil** [comment]
It's possible as server and GPU connect through GPRC, however it's not something doable out of the box nor something that I would recommend.

We currently use gRPC with socket IPC, and it's only used to actually do IPC, adding some latency across nodes (machines) is imo likely to incur some unecessary latency.

But as anything performance, it should be relatively simple to try it out and see for yourself.
Here is the interesting setting: https://github.com/huggingface/text-generation-inference/blob/main/launcher/src/main.rs#L221
