### ISSUE TITLE
converting docker images to singularity

### ISSUE THREAD

**Issue by MiladInk** [huggingface/text-generation-inference#702]
### Feature request

I am trying to run tgi in a HPC cluster. I tried pulling the docker images with singularity. The problem is that in that case the custom kernels do not work and the cuda complains that `PTX is build with another version of the toolchain`. Is there any solution to this? 
I also wanted to build the image from the dockerfile but the transition from the dockerfile to singularity image is not straightforward.

What are my options? what is the problem with those custom kernels in my case?

### Motivation

Many HPCs does not let the user run docker. 

### Your contribution

I can test the suggested methods to solve the problem and later on post the steps that worked for me.

**Comment by YeechingTiger** [comment]
I am also in HPC environment. "--disable-custom-kernels" works for me. However, I don't know what the impact would be.

**Comment by Narsil** [comment]
What kind of GPU is it ? H100 ?
I'll look into this and see why it fails on some platforms. I'm guessing the kernels are built against an incompatible compute_arch

custom kernels shouldn't be necessary most of the time (there are only used for NEOX and BLOOM).

**Comment by Narsil** [comment]
Could be a duplicate of #739

**Comment by Blair-Johnson** [comment]
> ### Feature request
> 
> I am trying to run tgi in a HPC cluster. I tried pulling the docker images with singularity. The problem is that in that case the custom kernels do not work and the cuda complains that `PTX is build with another version of the toolchain`. Is there any solution to this? 
> 
> I also wanted to build the image from the dockerfile but the transition from the dockerfile to singularity image is not straightforward.
> 
> 
> 
> What are my options? what is the problem with those custom kernels in my case?
> 
> ### Motivation
> 
> Many HPCs does not let the user run docker. 
> 
> ### Your contribution
> 
> I can test the suggested methods to solve the problem and later on post the steps that worked for me. 

I've had success pulling the official docker image for my platform and then building a singularity image from the docker archive.

'''
docker pull --platform amd64 xxx
docker save xxx -o xxx.tar
singularity build xxx.sif docker-archive://xxx.tar
'''

**Comment by OlivierDehaene** [comment]
It's possible that your driver is too old. As you can see, it supports Cuda version up to 11.7 while TGI is using 11.8.
