### ISSUE TITLE
Is there an example how to quantize a model (e.g. meta-llama/Llama-2-7b-chat-hf) using the prebuilt docker image (e.g. ghcr.io/huggingface/text-generation-inference:0.9.3)

### ISSUE THREAD

**Issue by taoari** [huggingface/text-generation-inference#703]
### System Info

0.9.3

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

NA

### Expected behavior

A command to quantize a model (e.g. meta-llama/Llama-2-7b-chat-hf) using the prebuilt docker image (e.g. ghcr.io/huggingface/text-generation-inference:0.9.3)

After quantization, the model should be able to be loaded with `text-generation-inference --quantize gptq`

**Comment by taoari** [comment]
@OlivierDehaene Thanks! I got the following error with the above command:

```
ModuleNotFoundError: No module named 'texttable'
```

But I managed to run with the following updated command:

```
docker run --gpus all --shm-size 1g -v $volume:/data -e HUGGING_FACE_HUB_TOKEN=$token --entrypoint /usr/bin/env ghcr.io/huggingface/text-generation-inference:latest /bin/bash -c "pip install texttable datasets && text-generation-server quantize $model /data/$model-quantized"
```

This problem is also raised in https://github.com/huggingface/text-generation-inference/issues/576. It would be good if these two Python packages can be included in the official docker image by default.

**Comment by OlivierDehaene** [comment]
It is now. Since you don't have `--pull always` you might not be running with the latest version.

**Comment by taoari** [comment]
@OlivierDehaene Thank you so much, It works!
