### ISSUE TITLE
tgi log contains ansi

### ISSUE THREAD

**Issue by chenwenjun-github** [huggingface/text-generation-inference#706]
### System Info

k8s 1.19
text-generaton-inference 0.9.0

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I used tgi to deploy a llm model in k8s, it's normal when I exec `kubectl logs tgi` to stdout
but when I exec `kubectl logs tgi  |less` or redirect to a file, the log will decode error
![image](https://github.com/huggingface/text-generation-inference/assets/46237364/943b200f-844b-4c9d-915a-24dbc8dc6d6e)

I find it because log print by ansi for color,  can I to disable it by config?

### Expected behavior

don't print log use ansi

**Comment by OlivierDehaene** [comment]
You can use `--json-output` or the env var `JSON_OUTPUT=true` to output logs in a JSON format for easier parsing.
