### ISSUE TITLE
Not enough memory to handle 16000 total tokens with 2 prefill tokens. You need to decrease `--max-batch-total-tokens` or `--max-batch-prefill-tokens

### ISSUE THREAD

**Issue by monuminu** [huggingface/text-generation-inference#710]
### System Info

{ model_id: "/opt/ml/model", revision: None, validation_workers: 2, sharded: None, num_shard: Some(8), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_input_length: 3072, max_total_tokens: 4096, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "container-0.local", port: 8080, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

ran this on g5.48xlarge

### Expected behavior

it should run

**Comment by OlivierDehaene** [comment]
Why should it run? Have you looked at the error message?

**Comment by monuminu** [comment]
whats the ideal value for Llama2-70b ?
