### ISSUE TITLE
How to load private model in tgi in docker and difference inference performance when loading from huggingface/loading from locally directory

### ISSUE THREAD

**Issue by zch-cc** [huggingface/text-generation-inference#716]
Hi team, 
  How do we load a private model in tgi in the docker because of the access issue? 
  One solution I think is to pre-download the model and then mount the model directory and load into tgi. However, I find out there is a big performance inference gap between these two methods and could the team provide some hints on why is it? 
  
  Reproduce step: 
  Model example: bigcode/santacoder
  1. inference on 100 tokens via model-id bigcode/santacoder is 180ms
  Command: `docker run --gpus all  --shm-size 1g -p 8080:80 -v /data:/data ghcr.io/huggingface/text-generation-inference:0.9.4 --model-id bigcode/santacoder  --num-shard 1 --max-input-length 1000 --max-total-tokens 2000 --max-batch-total-tokens 4096 --max-concurrent-requests 1 --max-stop-sequences 20 --dtype float16 --trust-remote-code`

total_time="158.787824ms" validation_time="221.404µs" queue_time="48.671µs" inference_time="158.517849ms" time_per_token="7.925892ms"

  2.1 first git clone the bigcode/santacoder directory by running  `git lfs install  && git clone https://huggingface.co/bigcode/santacoder `
  2.2 running docker image loading via model-id santacoder directory. inference on 100 tokens is 280ms.  
command 
`docker run --gpus all  -v santacoder_path:/model  --shm-size 1g -p 8080:80 -v /data:/data ghcr.io/huggingface/text-generation-inference:0.9.4 --model-id /model  --num-shard 1 --max-input-length 1000 --max-total-tokens 2000 --max-batch-total-tokens 4096 --max-concurrent-requests 1 --max-stop-sequences 20 --dtype float16 --trust-remote-code`

total_time="329.15002ms" validation_time="183.883µs" queue_time="52.371µs" inference_time="328.914016ms" time_per_token="16.4457ms" seed="None"}:

For loading with local directory, it takes more time to shard  and it has one warning about  Model does not support automatic max batch total tokens.  Also the output is garbage.

Test Command for query server  `curl 127.0.0.1:8080/generate     -X POST     -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":20}}'     -H 'Content-Type: application/json
`
 I think there may be some additional steps to make model better performance but I have not realized it yet. Thanks for the help in advance!
Docker image version: ghcr.io/huggingface/text-generation-inference:0.9.4

**Comment by Narsil** [comment]
Santacoder is unfortunately a bit special as it was released with `trust_remote_code`.

We had to have a special flag for it https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/__init__.py#L95

Your local version is slow because is pass here, and is therefore using the standard slow modeling code.

**Comment by Narsil** [comment]
To fix it you can trick it by renaming your directory as starting with `bigcode/`
