### ISSUE TITLE
LongT5 support

### ISSUE THREAD

**Issue by sujithjoseph** [huggingface/text-generation-inference#717]
### Model description

Will the current T5 loader support text gen using LongT5 as well (https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/t5.py) . 

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

**Comment by Narsil** [comment]
Do you mean this : https://github.com/huggingface/transformers/tree/main/src/transformers/models/longt5 ?

It is supported like all `transformers` models in a "best effort" mode.
That means it should work, but TP sharding, flash attention are not working.
Continuous batching does work though.

In general we focus on popular models to implement fast implementations.

I am not aware a very popular longt5 at the moment. If that was the case we'd definitely do it.

(PS sorry for the delay, this issue skipped my notifications somehow)
