### ISSUE TITLE
How to make sure Flash and PagedAttention are running?

### ISSUE THREAD

**Issue by HamidShojanazeri** [huggingface/text-generation-inference#718]
### System Info

I am running the following for llamav2, and was wondering how I can make sure pagedattention and flashattention are running? any Flag to be set or they are enabled by default? 

```
docker run --gpus all --shm-size 1g -p $PORT:80 \
           -v $PWD/data:/data \
           -e HUGGING_FACE_HUB_TOKEN=$token \
           ghcr.io/huggingface/text-generation-inference:0.9.3 \
           --model-id $MODEL \
           --sharded false  \
           --max-input-length 1024 \
           --max-total-tokens 2048 \
           --max-best-of 5 \
           --max-concurrent-requests 5000 \
           --max-batch-total-tokens $TOKENS\
           --num-shard 4
           
 ```
            

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

It more of question not a bug.

### Expected behavior

just doc clarification.

**Comment by Narsil** [comment]
If you're not seeing warnings that they cannot be loaded, it means everything's working fine.

Usually (at least for llama), using sharding **requires** flash + paged attention. The fact that it works means it's ok.
