### ISSUE TITLE
beam search support

### ISSUE THREAD

**Issue by leiwen83** [huggingface/text-generation-inference#722]
### Feature request

Beam search is useful feature provided by transformer library, but it seem it is missing in TGI?
Would it be supported?

### Motivation

beam search would be helpful for response quality.

### Your contribution

I'd have a try if this feature is implemented

**Comment by Narsil** [comment]
Hi @leiwen83 

Indeed beam search is not implemented however we have a different algorithm which seems to work just as good or even better.

`best_of` taking the best of `n` potential sampling replies: https://github.com/huggingface/text-generation-inference/issues/736#issuecomment-1658791383

Is that option what you could be looking for.
It seems to perform better with current LLMs where sampling is better than greedy for most answers.

**Comment by jiguanglizipao** [comment]
I vote for Beam Search. In the case of using Page Attention, Beam Search can share one Prifill operation and save computation with long prompts.

**Comment by Quang-elec44** [comment]
@jiguanglizipao I agree with you, it seems that the argument "best_of" does not provide good results. Moreover, in the case of my model, using "do_sample" leads to unwanted results

**Comment by PawelFaron** [comment]
Would ge great to have. best_of is great but way to slow. 
With best_of=1 I have **_time_per_token="92.055402ms"_**
With best_of=2 I have **_time_per_token="320.055402ms"_**

**Comment by Narsil** [comment]
Beam search is much worse than best_of performance wise.

The timing difference you show here a surprisingly different. How did you measure ?
