### ISSUE TITLE
Running the docker image on MacOS with M2 processor

### ISSUE THREAD

**Issue by ogedayoztoprak** [huggingface/text-generation-inference#754]
I am trying to pull and run the container as said in the documentation which is:

`docker run --shm-size 1g --net=host -p 8080:80 -v $PWD/Llama-2-7b-hf:/data -e HUGGING_FACE_HUB_TOKEN=$token -e HF_HUB_ENABLE_HF_TRANSFER=0 -e CUDA_VISIBLE_DEVICES= ghcr.io/huggingface/text-generation-inference:latest --model-id NousResearch/Llama-2-7b-hf`

but it says:

```
Unable to find image 'ghcr.io/huggingface/text-generation-inference:latest' locally
latest: Pulling from huggingface/text-generation-inference
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```
When I look at the local installation instructions it seems it is possible to run TGI on MacOS but I couldn't manage to do that with that ready to use container. Thank you all in advance.

**Comment by Narsil** [comment]
MacOS x86 maybe ?

I don't think we've ever tried on M1/M2.
Just as a disclaimer, the CPU support should work, but is not optimal by any means, this repo is really optimized for GPU/multi GPU setups (where flash attention is implemented).

We might have some things to show soon for M1/M2.

**Comment by oumoukelthoum** [comment]
try 
`docker run --platform linux/x86_64 --shm-size 1g --net=host -p 8080:80 -v $PWD/Llama-2-7b-hf:/data -e HUGGING_FACE_HUB_TOKEN=$token -e HF_HUB_ENABLE_HF_TRANSFER=0 -e CUDA_VISIBLE_DEVICES= ghcr.io/huggingface/text-generation-inference:latest --model-id NousResearch/Llama-2-7b-hf`

by adding **--platform linux/x86_64** it works for me.

**Comment by merveenoyan** [comment]
Hello @ogedayoztoprak, currently only option to run TGI is through emulation support. 
torch MPS backend currently doesn't support some operations (e.g. cumsum, used in tokenizers) on MacOS 13.2, it was released for 13.3 which apple doesn't let anyone get for now.

Once it's released, you can try by adding following line under [this block](https://github.com/huggingface/text-generation-inference/blob/e58ad6dd66413ef34585348cdbac1664da391fa9/server/text_generation_server/models/causal_lm.py#L460):
```python
elif torch.backends.mps.is_available():
    device = torch.device("mps")
```
this will carry your model and inputs later to MPS so you can use torch MPS backend.

**Comment by maxyousif15** [comment]
Did you manage to get this working on a M2 macbook without using a GPU? I'm seeing the following stack trace in response to this command

```
volume=$PWD/data
model=Writer/palmyra-small
docker run --platform linux/x86_64 --shm-size 1g --net=host -p 8080:80 -v $volume:/data -e HF_HUB_ENABLE_HF_TRANSFER=0 ghcr.io/huggingface/text-generation-inference:latest --model-id $model --disable-custom-kernels
```

I am just trying to test a small model locally.

```
2023-08-14T16:27:39.124470Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-08-14T16:27:39.130290Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-08-14T16:27:49.231757Z  INFO shard-manager: text_generation_launcher: Waiting for shard to be ready... rank=0
2023-08-14T16:27:53.553493Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

/opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. " rank=0
2023-08-14T16:27:53.553778Z ERROR shard-manager: text_generation_launcher: Shard process was signaled to shutdown with signal 4 rank=0
2023-08-14T16:27:53.555290Z ERROR text_generation_launcher: Shard 0 failed to start
2023-08-14T16:27:53.555424Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart
```

**Comment by Narsil** [comment]
Indeed illegal instruction. Most likely a bug within `torch`. Hard to debug really and as said previously M2 is not really the intended platform for this (so probably many more issues along the road).

**Comment by maxyousif15** [comment]
Do you have any suggestions for testing & developing using the container? I totally understand M2 support will not be provided since it is not the intended platform but seems like the only option is renting cloud GPUs/resources even for testing & development purposes

**Comment by maxyousif15** [comment]
Is the emulation mode triggered by the `--platform` parameter? Because that is what I have tried and I was still receiving the signal 4 error. Speed is not a major concern for the local set up as we would like to test things (e.g. prompts etc). 

I have my GPU server at home but I encounter the same issue as you. Hopefully, these models will be suitable for commodity hardware at production speeds in the near future!

**Comment by Narsil** [comment]
Ahah unlikely unfortunately.

While local models are valuable, size does matter, and larger models do perform better for the foreseeable future.
If we make currently large models fit conventional hardware, we'll just make bigger models instead :).

`--platform` should work, @merveenoyan manage to make it work (not on MPS but on CPU + platform).

**Comment by maxyousif15** [comment]
That's a really interesting insight, thank you! I always believed accessibility to be the core hinderance to large-scale adoption for AI (however you define that). Anyway, my comments are probably not appropriate for this forum ...

I couldn't get the `--platform` parameter to work for me as I still receive the illegal instruction error. I am not trying to use the attached MPS GPU, only CPU. I'll keep following this repository and blogs to see if someone experiences the same issue as me and manages to solve it. Thanks again for you time.

**Comment by Narsil** [comment]
Perfect, closing this for now.
