### ISSUE TITLE
Unable to deploy upstage/Llama-2-70b-instruct-v2

### ISSUE THREAD

**Issue by monuminu** [huggingface/text-generation-inference#756]
### System Info

Hi All,

I am unable to deploy upstage/Llama-2-70b-instruct-v2 on TGI 0.9.3 , its gives safetensor error . 

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Deploy using TGI

### Expected behavior

It should be deployed

**Comment by Narsil** [comment]
Do you mind sharing the stacktrace ? Maybe try upgrading the version ?

**Comment by monuminu** [comment]
I am using 0.9.4 .



safetensors_rust.SafetensorError: Error while serializing: IoError(Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" })
--

**Comment by Narsil** [comment]
Ok you have mounted a read-only volume.

https://huggingface.co/upstage/Llama-2-70b-instruct-v2/tree/main seems to only have pickled weights (.bin). However TGI requires `safetensors` weights (makes everything much easier to work with, especially for sharding).

Try to mount a writeable volume instead. 
Alternatively use `text-generation-server download-weights upstage/Llama-2-70b-instruct-v2` to create those new files elsewhere in your stack and let the readonly volume see the new files.
