### ISSUE TITLE
This exact thing but with rabbitmq support

### ISSUE THREAD

**Issue by JamesDeAntonis** [huggingface/text-generation-inference#774]
### Feature request

Rabbitmq support instead of http

### Motivation

My team cares about having control over prioritizing certain requests. My current understanding is that there's no way to do this given the requests are all http.  Is there any way to add rabbitmq support to use instead of http?

### Your contribution

I could possibly help with this although I'm not an expert

**Comment by Narsil** [comment]
Hi @JamesDeAntonis,

Yes everything is HTTP. There is no plan of supporting rabbitMQ, you should probably have a layer on top to sort requests.
We also don't have a load balancer in here for instance, nor authentication.

We might add some gRPC support on top of HTTP to allow persistant connections, but that's probably the furthest we're going to take this, as there's a bazillion of other ways to do that kind of distribution/scheduling for which our implementations are most likely not going to be as good as native solutions.

@OlivierDehaene for visibility when he's back.

Going to close this for now please feel free to respond if you think there are other ways to go about this I didn't understand.
