### ISSUE TITLE
4 bit commit not compiled to docker

### ISSUE THREAD

**Issue by jerryMeng100** [huggingface/text-generation-inference#775]
### System Info

Hi - just a note that the 4 bit commit with bitsandbytes didn't get built into a container. It's a big and great update and want to use it right away for some cost servings on inference with nf4. 

Thanks!

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Commit not in docker registry

### Expected behavior

Commit should be in docker registry

**Comment by jerryMeng100** [comment]
Seems like aws didnt have any pods available - 

<img width="1732" alt="Screenshot 2023-08-04 at 1 29 07 PM" src="https://github.com/huggingface/text-generation-inference/assets/17575971/11ad20d1-2deb-46f0-ada0-c0ee7f07d072">

**Comment by jerryMeng100** [comment]
Tried to compile the docker image on my own and it doesn't seem to work/needs A100s for the kernels? Would appreciate another build for the latest commit if possible! Thanks.

**Comment by Narsil** [comment]
Isn't bitsandbytes supposed to be precompiled already ?

**Comment by krzim** [comment]
I was able to build this on a g4.12xlarge. I did have to set `MAX_JOBS` to a reasonable value for the system (8 is what I used I think). Building flash attention v2 can overwhelm some systems and cause an error to be thrown.

**Comment by Narsil** [comment]
I'm going to close this, bitsandbytes is not in the latest docker image.

For flashv2 being hungry and slow, yes it is. Try reducing the number of jobs it can also take too much memory and more threads is not necessarily better. (Also it doesn't seem linked to this issue)
