### ISSUE TITLE
Falcon-7b inference is slower using bitsandbytes quantization

### ISSUE THREAD

**Issue by NaamaKadosh** [huggingface/text-generation-inference#777]
### System Info

Running 1.0 container on ubuntu 20.04.6 LTS with CUDA 11.8 and one A10G GPU.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

**Falcon-7b without quntization:**
1. ``` docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0 --model-id tiiuae/falcon-7b --num-shard 1 ```
2. Using docker exec: ```text-generation-benchmark --tokenizer-name tiiuae/falcon-7b```
Result:
![Pasted Graphic 14](https://github.com/huggingface/text-generation-inference/assets/108456218/3e3cb2df-fa64-423f-908b-62441dd2dbad)

**Falcon-7b with bitsandbytes quntization:**
1. ``` docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0 --model-id tiiuae/falcon-7b --num-shard 1 --quantize bitsandbytes ```
2. Using docker exec: ```text-generation-benchmark --tokenizer-name tiiuae/falcon-7b```
Result:
![Pasted Graphic 15](https://github.com/huggingface/text-generation-inference/assets/108456218/bf74d165-d4da-4685-aaa0-82933a1d3d21)

### Expected behavior

_text-generation-benchmark_ shows lower throughput and higher latency for the quantized model.
Is this expected? should not the inference be faster for the quantized model?

Thank you!

**Comment by Narsil** [comment]
Yes it is expected with `bitsandbytes` . Especially 8bit.

In general bitsandbytes is slower than GPTQ (but it doesn't require a preprocessing quantization step to output a specific model).

**Comment by mallorbc** [comment]
bitsandbytes int4 is faster than vanilla for a batch size of 1.  Or at least it should be.

https://github.com/TimDettmers/bitsandbytes/releases/tag/0.41.0

**Comment by Narsil** [comment]
Most models do not use batchign at all (with flash attention).

There does seem a size of prompt for which bnb4bit is faster than f16, but it falls off quite rapidly. At least this is what my small benchmarks seemed to indicate.
Please benchmark your own use cases and measure live performance, this is the only way to gauge any speedup (of any feature in this repo !)
