### ISSUE TITLE
Misleading "Not enough memory" message (H100, 8-bit quantized bitsandbytes issue)

### ISSUE THREAD

**Issue by andreaskoepf** [huggingface/text-generation-inference#780]
### System Info

While trying to load a Falcon 40B model ([OpenAssistant/falcon-40b-sft-mix-1226](https://huggingface.co/OpenAssistant/falcon-40b-sft-mix-1226)) 8-bit quantized (`--quantize bitsandbytes`) we noticed that this is currently not possible on H100 machines.

On an A100 80GB it is possible to load the model with the following command: 
`text-generation-launcher --model-id OpenAssistant/falcon-40b-sft-mix-1226 -p 8080 --quantize bitsandbytes --max-input-length 1024 --max-total-tokens 2048 --max-batch-prefill-tokens 1024`

The same command on a H100 machine crashes with `RuntimeError: Not enough memory to handle 1024 prefill tokens. You need to decrease --max-batch-prefill-tokens`. Full output including Traceback: [here](https://gist.githubusercontent.com/tju01/572bf5ecedc1ece18523515da7e18c0f/raw/c07e0084d78ca58ce9bb87158e33facdff729172/h100-tgi-8bit).

While the error seems to indicate a memory problem, this is probably not the actual issue here. When tgi prints the warmup message the GPU memory usage as reported by nvidia-smi is ~45000 MiB.

The RuntimeError is thrown in [flash_causal_lm.py#L730 ](https://github.com/huggingface/text-generation-inference/blob/16fadcec5711ff232977b38c74a1c8829af6a63b/server/text_generation_server/models/flash_causal_lm.py#L730). The actual exception that causes this RuntimeError in the `self.generate_token()` call: "Exception: cublasLt ran into an error!". It could be related to https://github.com/TimDettmers/bitsandbytes/issues/599

Installation details:
The TGI installation for both A100 & H100 machines (lambda labs and runpod) was done outside docker in a python3.10 venv, commands used the installation can be found in the following [gist](https://gist.github.com/andreaskoepf/4b7f5fd913ecd924e30c3b665f3f1b47).

Loading the 40B model in 4bit quantized with `--quantize bitsandbytes-nf4` works also on a H100.

(thanks to [@tju01](https://github.com/tju01/) for cross-check on runpod machines and analysis of error.)

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Reproduction:
1. Install TGI on H100 system (e.g. use commands [here](https://gist.github.com/andreaskoepf/4b7f5fd913ecd924e30c3b665f3f1b47))
2. Execute `text-generation-launcher --model-id OpenAssistant/falcon-40b-sft-mix-1226 -p 8080 --quantize bitsandbytes --max-input-length 1024 --max-total-tokens 2048 --max-batch-prefill-tokens 1024`

Error shown:
```
text_generation_client: router/client/src/lib.rs:33: Server error: Not enough memory to handle 1024 prefill tokens.
```

### Expected behavior

Checking what type of exception was thrown and giving a helpful error message instead of always assuming that it is because of the max prefill tokens because it's sometimes not. (And of course it would be great if 8-bit quantized model would also run on a H100 but that probably needs to be resolved in bitsandbytes).

**Comment by abhinavkulkarni** [comment]
Hey @andreaskoepf,

I think we both are facing same issue with the `warmup` method of `client.rs`. I have commented here about the same: https://github.com/huggingface/text-generation-inference/issues/778#issuecomment-1667092399
