### ISSUE TITLE
Is there a way to capture the inference output through the code into a dataframe? 

### ISSUE THREAD

**Issue by Tarun3679** [huggingface/text-generation-inference#788]
### System Info

I am trying to capture this data to be concise. 

Is there a way to store this data into a dataframe? or record this data while a particular prompt is running?
![image](https://github.com/huggingface/text-generation-inference/assets/34520609/e0d805f8-3276-4c14-9153-afcc44dfbb5c)

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I need to capture the following data which recording when an inference is passed.

![image](https://github.com/huggingface/text-generation-inference/assets/34520609/a8ed4cf7-eb4c-48bb-a028-121946f7ddf8)

### Expected behavior

Any code or any way to do it>

**Comment by Narsil** [comment]
Those logs are made to be consumed with telemetry: https://github.com/huggingface/text-generation-inference#distributed-tracing
