### ISSUE TITLE
top_k should be positive instead of strictly positive?

### ISSUE THREAD

**Issue by shijie-wu** [huggingface/text-generation-inference#811]
### System Info

n/a

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

setting `top_k` to 0

### Expected behavior

the validator reject top_k == 0 while setting the default value to 0. allowing top_k == 0 would be more consistent?

https://github.com/huggingface/text-generation-inference/blob/e58ad6dd66413ef34585348cdbac1664da391fa9/router/src/validation.rs#L190-L197

**Comment by shijie-wu** [comment]
`top_k == 0` could disable top_k sampling, the same implication as the internal default value?

**Comment by Narsil** [comment]
Well it' s the same as not sending it , which is more obvious to me (especially when using the API with code and top_k could get written as `0` without you realizing.).

I'll ping @OlivierDehaene to have a second opinion on this. Closing for now to avoid the bikesheeding.

I understand the argument, I feel it's a bit better like this, but this feels like aesthetic decision to me.

I'll close for now, we can reopen if the discussion needs to happen
