### ISSUE TITLE
Unexpected results occur when using –rope-factor 2 –rope-scaling dynamic.

### ISSUE THREAD

**Issue by pandazki** [huggingface/text-generation-inference#816]
When I use -rope-factor 2 -rope-scaling dynamic to get LLaMA to achieve a 4k context length, the results are far worse on both long and short inputs than when I do not use these parameters (in the Chinese scene, some garbled text even appears). When I carefully read the code, I found the logic here to be a bit strange, it seems like it shouldn’t perform this action. I tried removing these two lines of code, and it seems to perform normally.

https://github.com/huggingface/text-generation-inference/blob/5df4c7c0d792738e0ed0fd3426770dea6d7233df/server/text_generation_server/utils/layers.py#L550

I’m not sure if my modification is correct, so I didn’t submit a PR.

**Comment by pandazki** [comment]
Got it. I'll remove the rope-scaling. Thanks a lot.😀

**Comment by Narsil** [comment]
You can try out my PR if you want see if that works better (the division definitely shouldn't be there)

**Comment by pandazki** [comment]
Yes, I have already made the modification just like you did. I just wanted to confirm whether this change is correct or not. Thank you very much for your explanation.

**Comment by Narsil** [comment]
Thnaks for  notifying !
