### ISSUE TITLE
Support models with .safetensors weights only

### ISSUE THREAD

**Issue by thomas-schillaci** [huggingface/text-generation-inference#819]
### Feature request

Enable TGI to load local models, from a shared volume, which only have .safetensors files (no .bin files).

### Motivation

Hello, thank you for your amazing work!

I'm starting llama-2 by passing this argument to docker: `--model-id /data/models--meta-llama--Llama-2-7b-hf/snapshots/3f025b66e4b78e01b4923d510818c8fe735f6f54` which works well as this folder contains .bin and .safetensors files.

However I need to migrate to revision 6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9 (latest to date) and it's corresponding folder only contains .safetensors files, which raises this error:

> 2023-08-11T11:06:26.317207Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):
>
>  File "/opt/conda/bin/text-generation-server", line 8, in <module>
>    sys.exit(app())
>
>  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 137, in download_weights
>    local_pt_files = utils.weight_files(model_id, revision, ".bin")
>
>  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/hub.py", line 90, in weight_files
>    raise FileNotFoundError(
>
>FileNotFoundError: No local weights found in /data/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9 with extension .bin
>
>
>Error: DownloadError

Ideally I'd want to start it with: `--model-id meta-llama/Llama-2-7b-hf --revision 6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9 --weights-cache-override /data` but this raises the error:

> Repo model meta-llama/Llama-2-7b-hf is gated. You must be authenticated to access it.

### Your contribution

I'd be happy to help if I can

**Comment by Narsil** [comment]
Are you sure the files are already there ? 

This should trigger: https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/cli.py#L115 if it was.

Or this: https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/cli.py#L133

Both should attempt to download safetensors files first and foremost. It will attempt to get the bin files only as a last resort.

**Comment by thomas-schillaci** [comment]
I can load it without problem with `transformers.AutoModelForCausalLM.from_pretrained("[...]/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9", trust_remote_code=True, device_map="auto")`
This folder contains the following:
- config.json
- generation_config.json
- model.safetensors.index.json
- model-00001-of-00002.safetensors
- model-00002-of-00002.safetensors
- special_tokens_map.json
- tokenizer.json
- tokenizer.model
- tokenizer_config.json

**Comment by Narsil** [comment]
It work great for me : `text-generation-launcher --model-id /data/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9/`

Could you show the output of `ls -l` of that directory ?
The safetensors files are actually symbolic links and their target might actually be missing.

**Comment by thomas-schillaci** [comment]
The directory itself is in: drwxrws--- 2 <another user from my group> <my group>
The content is:
- lrwxrwxrwx 1 <me> <my group> 52 Aug 11 11:36 config.json -> ../../blobs/34f901200fa131819b355bc4bed876c957a77a5a
- lrwxrwxrwx 1 <me> <my group> 52 Aug 11 11:36 generation_config.json -> ../../blobs/aa1b3d3486df56a0699ce90c33283b13556fb5a3
- lrwxrwxrwx 1 <me> <my group> 76 Aug 11 11:36 model-00001-of-00002.safetensors -> ../../blobs/4ec71fd53e99766de38f24753b30c9e8942630e9e576a1ba27b0ec531e87be41
- lrwxrwxrwx 1 <me> <my group> 76 Aug 11 11:36 model-00002-of-00002.safetensors -> ../../blobs/41780b5dac322ac35598737e99208d90bdc632a1ba3389ebedbb46a1d8385a7f
- lrwxrwxrwx 1 <me> <my group> 52 Aug 11 11:36 model.safetensors.index.json -> ../../blobs/8b6245796e966e50960a317e4a54aa7bf73b0186
- lrwxrwxrwx 1 <another user from my group> <my group> 52 Aug  9 17:39 special_tokens_map.json -> ../../blobs/451134b2ddc2e78555d1e857518c54b4bdc2e87d
- lrwxrwxrwx 1 <another user from my group> <my group> 52 Aug  9 17:39 tokenizer.json -> ../../blobs/a6e931b92caff4c79c5c56282f1e89569a0ae558
- lrwxrwxrwx 1 <another user from my group> <my group> 76 Aug  9 17:39 tokenizer.model -> ../../blobs/9e556afd44213b6bd1be2b850ebbbd98f5481437a8021afaf58ee7fb1818d347
- lrwxrwxrwx 1 <another user from my group> <my group> 52 Aug  9 17:39 tokenizer_config.json -> ../../blobs/2ef41cbc275000b29afe157ba487f0530b8c26dc

**Comment by thomas-schillaci** [comment]
Also I start it with `docker run`, for instance if I run:

`docker run --rm --gpus 7 -e NVIDIA_VISIBLE_DEVICES=7 --shm-size 1g -p 8085:80 --name Llama-2-7b-hf -v /data:/data ghcr.io/huggingface/text-generation-inference:1.0.0 --model-id /data/models--meta-llama--Llama-2-7b-hf/snapshots/3f025b66e4b78e01b4923d510818c8fe735f6f54 --num-shard 1 --trust-remote-code`

Everything works well, but if I change the revision, I get the error above:

`docker run --rm --gpus 7 -e NVIDIA_VISIBLE_DEVICES=7 --shm-size 1g -p 8085:80 --name Llama-2-7b-hf -v /data:/data ghcr.io/huggingface/text-generation-inference:1.0.0 --model-id /data/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9 --num-shard 1 --trust-remote-code`

**Comment by thomas-schillaci** [comment]
I just `chmod -R +rx` the 6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9 directory from the other user, and it works now, thank you for your insights!

**Comment by roshan-gopalakrishnan** [comment]
@Narsil https://github.com/huggingface/text-generation-inference/issues/819#issuecomment-1674811718
How do you launch the TGI using this command text-generation-launcher --model-id /data/models--meta-llama--Llama-2-7b-hf/snapshots/6fdf2e60f86ff2481f2241aaee459f85b5b0bbb9/ ?

**Comment by Narsil** [comment]
I open a console and paste the command it ?

I'm not sure I understand the question.
