### ISSUE TITLE
Cannot access gated repo for url https://huggingface.co/api/models/meta-llama/Llama-2-7b-chat-hf. Repo model meta-llama/Llama-2-7b-chat-hf is gated. You must be authenticated to access it.

### ISSUE THREAD

**Issue by thistleknot** [huggingface/text-generation-inference#827]
### System Info

Using a private or gated model
You have the option to utilize the HUGGING_FACE_HUB_TOKEN environment variable for configuring the token employed by text-generation-inference. This allows you to gain access to protected resources.

For example, if you want to serve the gated Llama V2 model variants:

Go to https://huggingface.co/settings/tokens
Copy your cli READ token
Export HUGGING_FACE_HUB_TOKEN=<your cli READ token>
or with Docker:

model=meta-llama/Llama-2-7b-chat-hf
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run
token=<your cli READ token>

docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.0 --model-id $model

### Information

- [X] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Using a private or gated model
You have the option to utilize the HUGGING_FACE_HUB_TOKEN environment variable for configuring the token employed by text-generation-inference. This allows you to gain access to protected resources.

For example, if you want to serve the gated Llama V2 model variants:

Go to https://huggingface.co/settings/tokens
Copy your cli READ token
Export HUGGING_FACE_HUB_TOKEN=<your cli READ token>
or with Docker:

model=meta-llama/Llama-2-7b-chat-hf
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run
token=<your cli READ token>

docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.0 --model-id $model

### Expected behavior

The docker image should be modified to use either cli auth or to work with the api key

**Comment by swapnil3597** [comment]
It seems, you are exporting env variable with name `HUGGING_FACE_HUB_TOKEN` and using `token` in docker run cmd.

Try running these commands,

```bash
model=meta-llama/Llama-2-7b-chat-hf
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run
token="<your-hf-read-token>"

docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.0 --model-id $model
```

**Comment by Narsil** [comment]
> The docker image should be modified to use either cli auth or to work with the api key

That means that you need to mount a specific location containing the token file.
In production settings, using an env variable being mounted from secrets should be the preferred solution IMHO.

In any case we're not going to change the behavior of the docker (the raw cli will read the token properly since it has access to all the disk)

**Comment by Mangosteen1226** [comment]
Excuse me, I have a question, when i Filled out the form at the end of the "Expand to review and Access" section and then i was rejected, and I didn't find out how to apply again
<img width="459" alt="885d5c1e943c732bd65d68e802982aa6" src="https://github.com/user-attachments/assets/54b9bab3-5b52-4913-9359-1aee6407718e">
