### ISSUE TITLE
4 bit quantization not available in latest version

### ISSUE THREAD

**Issue by swapnil3597** [huggingface/text-generation-inference#828]
### Feature request

In the readme it is mentioned that following flags can be added for 4-bit quantization:
`--quantize bitsandbytes-nf4` or `--quantize bitsandbytes-fp4`

But, the latest docker image, the `--quantize` flag only supports following values `bitsandbytes` and `gptq`.

How to perform 4-bit quantization for LLM?

### Motivation

Due to. huge size of Llama2-70B model, 4-bit quantization is preferred. While running Llama2-70B on A100 GPU with `--quantize bitsandbytes`, the inference time is high for longer prompts. (>10s).

### Your contribution

-

**Comment by Narsil** [comment]
There hasn't been released in a versionned release yet. [sha-a2a913e](https://github.com/orgs/huggingface/packages/container/text-generation-inference/117922119?tag=sha-a2a913e) shoud work.

**Comment by swapnil3597** [comment]
> There hasn't been released in a versionned release yet. [sha-a2a913e](https://github.com/orgs/huggingface/packages/container/text-generation-inference/117922119?tag=sha-a2a913e) shoud work.

This worked! Thanks @Narsil. Hoping it would be released officially soon.
