### ISSUE TITLE
Minimum system requirements

### ISSUE THREAD

**Issue by jackzhp** [huggingface/text-generation-inference#834]
### Feature request

Can someone please add some notes on minimum system requirements under the section "Get Started" in the readme.MD file?

thanks.

### Motivation

So people can have an idea what kind of computer is need to run this.

### Your contribution

# is GPU needed?
# minimum memory? if GPU is needed, what is the minimum CPU memory and GPU memory required?

**Comment by Narsil** [comment]
This is unfortunately impossible to answer definitively.

It depends heavily on the model you use, on what features you want/need to use.

Therefore it's really impossible in general to give minimum requirements.

We did however try to add a lot of logs giving insights when something doesn't work as to why and how to fix it when possible.
Please tell us if there's an error message we could improve. Closing in the meantime.
