### ISSUE TITLE
error[E0308]: mismatched types - when installing locally - version v1.0.1

### ISSUE THREAD

**Issue by phucdoitoan** [huggingface/text-generation-inference#840]
### System Info

The error appeared when I installed from the github repository of version v1.0.1.
I was able to install without issue for version v1.0.0

The OS is Ubuntu 20.4.
Cuda version: 11.7

Error log:

"""
....
Successfully installed bitsandbytes-0.41.1 text-generation-server-1.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
make[1]: Leaving directory '/workspace/TGI_101/text-generation-inference/server'
cd router && cargo install --path .
  Installing text-generation-router v1.0.1 (/workspace/TGI_101/text-generation-inference/router)
    Updating crates.io index
   Compiling libc v0.2.147
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling memchr v2.5.0
   Compiling once_cell v1.18.0
   Compiling pin-project-lite v0.2.12
   ...   
   Compiling axum-tracing-opentelemetry v0.10.0
   Compiling ngrok v0.12.4
   Compiling opentelemetry-proto v0.2.0
   Compiling grpc-metadata v0.1.0 (/workspace/TGI_101/text-generation-inference/router/grpc-metadata)
   Compiling opentelemetry-otlp v0.12.0
error[E0308]: mismatched types
   --> router/src/validation.rs:314:25
    |
314 |                 .decode(Vec::from(encoding.get_ids()), false)
    |                  ------ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                  |      |
    |                  |      expected `&[u32]`, found `Vec<u32>`
    |                  |      help: consider borrowing here: `&Vec::from(encoding.get_ids())`
    |                  arguments to this method are incorrect
    |
    = note: expected reference `&[u32]`
                  found struct `Vec<u32>`
note: method defined here
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokenizers-0.13.4/src/tokenizer/mod.rs:814:12
    |
814 |     pub fn decode(&self, ids: &[u32], skip_special_tokens: bool) -> Result<String> {
    |            ^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `text-generation-router` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `text-generation-router v1.0.1 (/workspace/TGI_101/text-generation-inference/router)`, intermediate artifacts can be found at `/workspace/TGI_101/text-generation-inference/target`
make: *** [Makefile:12: install-router] Error 101
"""
![Screenshot from 2023-08-14 16-49-25](https://github.com/huggingface/text-generation-inference/assets/32733308/718d103a-63a4-4e7e-b16b-bcdb16cfbf1e)

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

Just following the "Local Install" instructions.

### Expected behavior

Installed locally without error like v1.0.0

**Comment by sandwichdoge** [comment]
I'm getting the same error. I think the author of tokenizers cargo just updated it to 0.13.4 a few hours ago and broke the dependency. Strange because according to Cargo.toml it should be locked at 0.13.3:
```
router/Cargo.toml:35:tokenizers = "0.13.3"
```

**Comment by Narsil** [comment]
Cargo respects semver and will upgrade minors without looking. 

Just merged the fix: https://github.com/huggingface/text-generation-inference/pull/838

**Comment by sandwichdoge** [comment]
This breaks all previous tagged versions too. I suggest you lock down the dependency versions regardless they're minor or major for more stability.

**Comment by phucdoitoan** [comment]
Thank you guys for the help!

**Comment by Narsil** [comment]
> This breaks all previous tagged versions too. I suggest you lock down the dependency versions regardless they're minor or major for more stability.

Docker is our layer of stability for TGI.
Building from source we can modify things at will (so we can add new kernels and such).

In that particular case, you should blame the `tokenizers` maintainer which happens to be me. I maintain `tokenizers` with the idea that it's mostly being used in Python land (which for a long time it really was).

Lesson's learned about the breaking.

**Comment by Markdcle** [comment]
I have the same problem.
I would appreciate any help and successful installation.please!!!!!
![image](https://github.com/huggingface/text-generation-inference/assets/68360422/4a690439-a82d-4482-a801-3810d934527d)

**Comment by Narsil** [comment]
@Markdcle You don't share nearly enough for us to be able to help.

Please open an issue with the full template filled in.
