### ISSUE TITLE
start the service from the downloaded model

### ISSUE THREAD

**Issue by mse700** [huggingface/text-generation-inference#841]
### Feature request

Hi,

I have downloaded the model in the local machine, how can I run the project from the downloaded model?? (I do not want the docker image to download the model artefacts but using the downloaded models artefacts).

### Motivation

It would be great for cluster services, since the cluster services do not have access to world wide internet.

### Your contribution

Yes, I could share the experience in the issues

**Comment by Narsil** [comment]
Just mount the local directory `-v LOCAL_DIR:DOCKER_DIR` and point to it in the command line `--model-id DOCKER_DIR/model_dir`.

This should work just fine.

**Comment by mse700** [comment]
thank you for the answer.

I did it as pointed out. but the log of container is the following:

 INFO download: text_generation_launcher: Starting download process.

It is trying to download the model.

How can it be solved??
