### ISSUE TITLE
Support `hidden_states` Input Besides `input_ids` for Multi-Modality Models

### ISSUE THREAD

**Issue by leng-yue** [huggingface/text-generation-inference#847]
### Feature request

Extend the current API to accept `hidden_states` as an optional input parameter in addition to `input_ids`. This would support integration with multi-modality models such as LLAVA, Video Lamma, BLIP2, etc.

### Motivation

Many modern models are designed to process more than one type of data (e.g., text and images) and require inputting `hidden_states` directly. Allowing `hidden_states` as input would enable a seamless integration of these models, enhancing the overall utility of the TGI. This change aligns with the growing need for versatile, multi-modal solutions in the AI community.

### Your contribution

I believe that this is a valuable addition to the TGI. The proposed change is relatively minor but has the potential to greatly improve functionality. I'm eager to contribute and would like to make a PR to implement this feature.

**Comment by Narsil** [comment]
We're already adding multi modal models, without requiring users to send `hidden_states` directly:

https://github.com/huggingface/text-generation-inference/pull/842

The API may change at any time, this is work in progress.

**Comment by leng-yue** [comment]
Since the cost of image preprocessing is typically lower than generating LLM, enabling the specification of hidden_states directly will be beneficial for experimenting with different encoders and projections. We don't have to include vision (or audio) parts in the TGI. Instead, we can compute these embeddings from another location and simply input them into the standardTGI API (for example, LLAMA2).
