### ISSUE TITLE
Benchmark reporting of tokens/sec in the prefill stage is incorrect

### ISSUE THREAD

**Issue by tomerip** [huggingface/text-generation-inference#849]
Unless I'm understanding the reported metric incorrectly, the `Prefill Throughput` metric is wrong, because it's calculated by:
```python
batch_size / latency
```
instead of:
```python
(batch_size * sequence_length) / latency
```
As can be seen in the implementation https://github.com/huggingface/text-generation-inference/blob/05dd14fdb93f83ad5fde6d5b9cb6c21edef71aa1/benchmark/src/generation.rs#L166

For reference, the `Decode Throughput` is correct:
https://github.com/huggingface/text-generation-inference/blob/05dd14fdb93f83ad5fde6d5b9cb6c21edef71aa1/benchmark/src/generation.rs#L199

What I'm guessing is that the calculation might be intentional, but then the units should be reported as `prompts/secs` and not `tokens/secs`.

Please let me know the wanted behavior, I'll be happy to make a small PR to fix it.
In case I misunderstood, I'd love an explanation and will close the issue.

**Comment by Narsil** [comment]
the explanation is just what do we mean by "token/s".

Prefill in the end generates only a single token. No one cares about the length of the prompt, we care about how many new tokens we generate :).

Hence the metric.

Sorry if that mislead you in some way.
Decode really does several decode passes in the tool, hence the multiplication.

**Comment by tomerip** [comment]
Thanks for the quick reply and explanation!
At least in my use case, I’m usually interested in knowing how much time it will take from invocation, to the generation finishing, and since the amount of generated token is usually pretty much linear, it’s easy to use the ‘tokens/secs’ metric. However, with different prompts with variable lengths it’s harder to estimate the prefill time with the current metric.
WDYT?

**Comment by Narsil** [comment]
Yes it's perfectly normal and accurate.

However if you look at your graph you'll most likely see that the latency for prefill also depends on the amount of batching actually occurring there.

Internally we just use the decode x tokens as a good approximation of the actual total latency (it actually works provided there are enough tokens being generated)

**Comment by Narsil** [comment]
It fails on some loads where prompts are super large and dominating, but then, there isn't a good way to represent overall latency anyway (to the best of my knowledge)

**Comment by tomerip** [comment]
That's exactly one of my use cases, a very long prompt (600-1000 tokens), that only generates ~10 tokens.
It's just the first interaction with the model and then I invoke inference again with a much shorter prompt (based on the results of the first interaction), then prefill vs. decode is much more typical.
However, per (batch size, sequence length, decode length) set,  I would like to know prefill time per token and decode time per token, which currently isn't the case (of course I can calculate them myself from the reported metrics).

**Comment by Narsil** [comment]
Check the graph of `text-generation-benchmark` . It should be much more bell curved like, meaning you could extrapolate with it your actual inferences (and it's unlikely to be a linear calculation).

I will close this as the name of `tokens/s` has been made clearer I think.
