### ISSUE TITLE
Launch server with ssl and self-signed certificates

### ISSUE THREAD

**Issue by amgomezdev** [huggingface/text-generation-inference#850]
### Feature request

It's not possible to launch text-generation-inference locally with a ssl certificate. In the current version only http request is posible. It's a little bit risky for a production mode.

### Motivation

Security vulnerability. Security improvement

### Your contribution

*

**Comment by Narsil** [comment]
Do SSL on your nginx reverse proxy (or any other ingress a k8s level you might want).

It's not risky at all and this is what most products actually do.

Maintaining SSL boundary at the product level is error prone and playing catch up all the time with all the possible ways to do it, and necessary features.
