### ISSUE TITLE
low int4 inference performance with Llama-2-13b-hf 

### ISSUE THREAD

**Issue by PYNing** [huggingface/text-generation-inference#859]
### System Info

I tried to quantify model **Llama-2-13b**-hf using **bitsandbytes**, but I found that int4 inference performance is lower than fp16 inference, whether it is in A100 or 3090.
Can you tell me why and how to troubleshoot this problem. Thanks.

**TGI Version**：1.0.1（offical build）
**Docker（with other software**）：ghcr.io/huggingface/text-generation-inference:1.0.1
GPUs：3090*2，A100*2
Model：Llama-2-13b-hf 

**Test Data**
![261073654-862176ee-6b4f-48c0-a582-94f469bdfc83 (1)](https://github.com/huggingface/text-generation-inference/assets/11667149/6c216c69-5a51-4bd9-b6c9-ac87da0e4d3d)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

docker run -d --runtime=nvidia --gpus all --shm-size 16g -p 23811:80 -v /data/model:/data/model ghcr.io/huggingface/text-generation-inference:1.0.1 --model /data/model --num-shard 2 --max-total-tokens 4096 --max-input-length 3072 --quantize bitsandbytes (or bitsandbyts-nf4 or bitsandbyts-nf4)

### Expected behavior

4090 get performance like this

![1692204465035](https://github.com/huggingface/text-generation-inference/assets/11667149/d1546d59-b92a-41a0-9565-8ad88275f8f0)

which was posted on https://github.com/TimDettmers/bitsandbytes/releases

**Comment by Narsil** [comment]
Maybe ask directly on bitsandbytes ?

https://github.com/TimDettmers/bitsandbytes

Your numbers seem roughly in line with ours. `GPTQ` performs better than bnb in our settings most of the time.
BNB is very convenient if you do not have a prequantized model.

**Comment by PYNing** [comment]
Thanks for reply.
