### ISSUE TITLE
Can text-generation client add verify=False to bypass SSL certificate verification?

### ISSUE THREAD

**Issue by ibicdev** [huggingface/text-generation-inference#861]
### Feature request

Add a True/False optional parameter, `verify`, to the contructor of `Client`, which will be passed onto `requests.post(verify=verify)` calls in `clients/python/text_generation/client.py`.

### Motivation

For self-hosted tgi server without valid SSL certificate, `text_generation.Client` runs into SSL certificate errors, so it would be beneficial to be able to bypass SSL certificate verification

### Your contribution

I'd be happy to contribute if this feature is deemed useful.  It's trivial to implement.

**Comment by Narsil** [comment]
Sorry, but no this is not deemed important.

You can use raw HTTP easily, or have a correct SSL server, seems like the way to go for production.
For testing adding this should be trivial enough.
