### ISSUE TITLE
PagedAttention support for 3.3x - 3.5x higher throughput than TGI today

### ISSUE THREAD

**Issue by ReadyPlayerEmma** [huggingface/text-generation-inference#871]
### Feature request

PagedAttention redefines the new state of the art in LLM serving: it delivers up to 24x higher throughput than HuggingFace Transformers, without requiring any model architecture changes. This equates to 3.3x - 3.5x higher throughput than TGI.

You can read about the technique here: https://vllm.ai

There is an Apache-2.0 licensed implementation of it here for reference: https://github.com/vllm-project/vllm

I think that it only makes sense to implement this in order to stay competitive with the latest techniques.

### Motivation

This is a major performance improvement that would deliver up to 3.3x - 3.5x more throughput, and huge cost savings as a result.

### Your contribution

I do not have bandwidth to contribute toward this effort at this time, but I wanted to make sure this is on the project's radar. I'm sure the cost savings at HF alone would deliver more than enough savings to justify implementing this.

**Comment by ReadyPlayerEmma** [comment]
Nevermind, I see this is implemented already.

**Comment by Narsil** [comment]
https://github.com/ModelTC/lightllm You might want to add this on your radar (haven't deep dived yet to see if the claims are real)
