### ISSUE TITLE
Sagemaker deployment error for v1.0.1

### ISSUE THREAD

**Issue by mer0mingian** [huggingface/text-generation-inference#885]
### System Info

Using the Docker image on AWS Sagemaker for deploying `meta-llama/Llama-2-13b-chat-hf`, on g4dn.12xlarge instance.

CloudWatch lists this error:

> error: unexpected argument 'serve' found | error: unexpected argument 'serve' found

My assumption is that something is passed as generic argument during deployment and is directed at the wrong endpoint. Also, I cannot find the `(sagemaker-)entrypoint.sh` when attaching the container either, so maybe this is the problem. Am I missing an additional step to configure the image for use with Sagemaker?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Push the Docker image from `ghcr.io/huggingface/text-generation-inference:1.0.1` to a private ECR.
2. Use the uri for the `HuggingFaceModel` for deploying `meta-llama/Llama-2-13b-chat-hf` as in [this notebook](https://www.philschmid.de/sagemaker-llama-llm).

### Expected behavior

Based on the entrypoint created in the Dockerfile I assumed that the image is supposed to work with Docker and serve as an alternative for the Sagemaker HF DLC images.

**Comment by TJohn2017** [comment]
I'm working through the same issue @mer0mingian, please let me know if you've made any progress! I'm going to try building the Docker image myself from source and then pushing that to SageMaker. I'll let you know if that clears anything up on my end.

**Comment by jimburtoft** [comment]
@TJohn2017 Make sure you are using the `make neuronx-tgi-sagemaker` option instead of the stock Docker image
