### ISSUE TITLE
Error when I try to run text-generation-inference with a local model

### ISSUE THREAD

**Issue by OscarAGracia** [huggingface/text-generation-inference#888]
### System Info

run text-generation-inference

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I run docker with this command
docker run --shm-size 1g -p 8080:80 -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model $PWD/llama_local --disable-custom-kernels

and I have this error
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/userone/Desktop/text-generation-inference/llama_local'. Use `repo_type` argument if needed

the local directory when I store the model is /home/userone/Desktop/text-generation-inference/llama_local. I don't know why I have this error.

### Expected behavior

No error

**Comment by roshan-gopalakrishnan** [comment]
I am also getting this error and I am trying to find a solution.

**Comment by Narsil** [comment]
`docker run --shm-size 1g -p 8080:80 -v $PWD/data:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model /data/ --disable-custom-kernels`
 
 Docker sees a different filesystem from the host, you're mounting the model to `/data/` therefore you need to point the docker there.
