### ISSUE TITLE
text-generation-launcher  tool how to use multi gpu cards?

### ISSUE THREAD

**Issue by luefei** [huggingface/text-generation-inference#899]
### System Info

text-generation-launcher 1.0.0  how to use  multi gpu cards?

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

CUDA_VISIBLE_DEVICES=0,1,2,3 text-generation-launcher --model-id falcon-40b-instruct --sharded true --num-shard 1 --quantize bitsandbytes-fp4  does not used multi gpu A10 card. Error with GPU 0 OutOfMemoryError: CUDA out of memory.

### Expected behavior

Normal load the model and http post.

**Comment by Narsil** [comment]
`--num-shard 1 `  -> `--num-shard 4`
