### ISSUE TITLE
Repeated and gibberish text while inferencing on multiple GPUs

### ISSUE THREAD

**Issue by Shivampanwar** [huggingface/text-generation-inference#902]
### System Info

I am deploying LLAMA-2 70B on my EC2 instance which is g5.12xlarge. Its config is as shown below: 
![image](https://github.com/huggingface/text-generation-inference/assets/12275601/6a837313-28f3-4b5c-a2a6-64c0da5a186d)
It has four GPUs.  
Commands which I have used to run the code:
`model=meta-llama/Llama-2-70b-hf 

volume=/llama_model  

token=******

quantize=bitsandbytes 

num_shard=4 

docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8000:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id $model --quantize $quantize  --num-shard $num_shard `

When I am running the curl command like this or a similar command on Postman, I am getting this output
![image](https://github.com/huggingface/text-generation-inference/assets/12275601/b0ae944f-9423-4140-88dc-94a8d576a1a6)

It's generating repeated text. Whereas on LLAMA-7B it was giving good results on single GPU. 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Use multiple GPUs and use the following commands to run either LLAMA-70B or Falcon-40B

`model=meta-llama/Llama-2-70b-hf

volume=/llama_model  

token=*****
quantize=bitsandbytes 
num_shard=4 
docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8000:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id $model --quantize $quantize  --num-shard $num_shard` 

### Expected behavior

Simple unrepeated answer

**Comment by Narsil** [comment]
I cannot reproduce.

Is it possible one of the GPUs is actually faulty ?

**Comment by Narsil** [comment]
Oh reread the issue, the output is not gibberish, it's actually OK.

If there's quality degradation compared to the full model it's possibly normal (quantization DOES loose accuracy).

In any case I don't think there's anything wrong in TGI here.
