### ISSUE TITLE
Error when launching docker run --gpus all 

### ISSUE THREAD

**Issue by amgomezdev** [huggingface/text-generation-inference#904]
### System Info

*

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I launch:
**model=meta-llama/Llama-2-7b-chat-hf**
**volume=$PWD/data** 

**docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id $model**

**and I have this error**
**docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:**  
![error](https://github.com/huggingface/text-generation-inference/assets/30750249/196d7569-7346-44b5-8ed8-ac372cbe1327)

Nvidia Container Toolkit installed
**nvidia-ctk --version
NVIDIA Container Toolkit CLI version 1.13.5**

**nvidia-smi**
![nvidia-smi](https://github.com/huggingface/text-generation-inference/assets/30750249/85d05945-154e-410e-9c7c-0180fe03ad62)

### Expected behavior

No error

**Comment by Narsil** [comment]
You need `nvidia-docker` : https://github.com/NVIDIA/nvidia-docker.
