### ISSUE TITLE
Question about --quantize bitsandbytes-nf4 param

### ISSUE THREAD

**Issue by amgomezdev** [huggingface/text-generation-inference#912]
### System Info

*

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

In the example below, the model **Llama-2-7b-chat-hf is not quantized**. 
When I launch docker run with --quantize bitsandbytes-nf4 param, **is the model quantized at runtime? Is there any documentation about this?**

**volume=$PWD/data**
**model=meta-llama/Llama-2-7b-chat-hf**

**docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$mytoken -p 8080:80 -v $volume:/data** **ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize bitsandbytes-nf4**

thanks in advance

### Expected behavior

*

**Comment by RonanKMcGovern** [comment]
The model is downloaded in full form and then loaded to the gpu in quantized form, yes.

Unfortunately there isn't yet a way to push the model to hub in quantized form, so bitsandbytes currently takes in the full bf16 model and quantizes it.

**Comment by Narsil** [comment]
Best documentation will be here : https://github.com/TimDettmers/bitsandbytes
