### ISSUE TITLE
option to control Logit bias like chatgpt

### ISSUE THREAD

**Issue by Stealthwriter** [huggingface/text-generation-inference#913]
### Feature request

Hi, is there a possibility to use SequenceBiasLogitsProcessor which is available in transformers to control the logit bias of some tokens? 

For example I don't want the model to generate token 279 at all, in gpt4 api i can set logit_bias{279:-10} and it will not appear in the output.

here how we can do that?

### Motivation

Hi, is there a possibility to use SequenceBiasLogitsProcessor which is available in transformers to control the logit bias of some tokens? 

For example I don't want the model to generate token 279 at all, in gpt4 api i can set logit_bias{279:-10} and it will not appear in the output.

here how we can do that?

### Your contribution

Hi, is there a possibility to use SequenceBiasLogitsProcessor which is available in transformers to control the logit bias of some tokens? 

For example I don't want the model to generate token 279 at all, in gpt4 api i can set logit_bias{279:-10} and it will not appear in the output.

here how we can do that?

**Comment by amosyou** [comment]
It appears that the `text-generation-inference` API doesn't have support for `logits_processor` like in transformers. If you're able to load the model using transformers, then you can use the `suppress_tokens` argument when calling `generate` to prevent token 279 from being generated.

There's also a feature request opened [here](https://github.com/huggingface/text-generation-inference/issues/176) for implementing `suppress_tokens` in the API.

Hope this helps!
