### ISSUE TITLE
Response Difference between text-generation-inference and transformers python script

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/text-generation-inference#915]
### System Info

Are there any parts of tgi where there is stripping or sanitising of the input sequence. I searched through the code and didn't immediately see anything like that?

With the same model, and the same prompt template and temperature, I get different responses from tgi and a simple python script:

#### Python script, run in Colab. Combined prompt and response:
```
<s> <FUNCTIONS>{
    "function": "search_bing",
    "description": "Search the web for content on Bing. This allows users to search online/the internet/the web for content.",
    "arguments": [
        {
            "name": "query",
            "type": "string",
            "description": "The search query string"
        }
    ]
}</FUNCTIONS>

[INST] Search bing for the tallest mountain in Ireland [/INST]

{
   "function": "search_bing",
   "arguments": {
       "query": "tallest mountain in ireland"
   }
}</s>
```

#### tgi. Combined prompt and response:
```
<s> <FUNCTIONS>{
    "function": "search_bing",
    "description": "Search the web for content on Bing. This allows users to search online/the internet/the web for content.",
    "arguments": [
        {
            "name": "query",
            "type": "string",
            "description": "The search query string"
        }
    ]
}</FUNCTIONS>

[INST] Search bing for the tallest mountain in Ireland [/INST]


<RESPONSE>
{
    "result": {
        "search_url": "https://www.bing.com/search?q=tallest+mountain+in+Ireland",
        "search_description": "Search results for tallest mountain in Ireland on Bing"
    }
}
</RESPONSE>
```

It's as though the model I have loaded into tgi is the raw llama 2 model (not the fine tuned one for function calling).

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

#### Google Colab Approach

```
# Define a stream *with* function calling capabilities
def stream(user_prompt):
  # Define the roles and markers
    B_INST, E_INST = "[INST]", "[/INST]"
    B_FUNC, E_FUNC = "<FUNCTIONS>", "</FUNCTIONS>\n\n"

    # Format your prompt template
    prompt = f"{B_FUNC}{functionList.strip()}{E_FUNC}{B_INST} {user_prompt.strip()} {E_INST}\n\n"

    inputs = tokenizer([prompt], return_tensors="pt").to(runtimeFlag)

    streamer = TextStreamer(tokenizer)

    # Despite returning the usual output, the streamer will also print the generated text to stdout.
    _ = model.generate(**inputs, streamer=streamer, max_new_tokens=500)
```
with:
```
search_bing_metadata = {
    "function": "search_bing",
    "description": "Search the web for content on Bing. This allows users to search online/the internet/the web for content.",
    "arguments": [
        {
            "name": "query",
            "type": "string",
            "description": "The search query string"
        }
    ]
}

functionList = ''

functionList += json.dumps(search_bing_metadata, indent=4, separators=(',', ': '))

print(functionList)
```
after having loaded the model and tokenizer:
```
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True, #adds speed with minimal loss of quality.
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map=runtimeFlag,
    trust_remote_code=True,
    cache_dir=cache_dir)

tokenizer = AutoTokenizer.from_pretrained(model_id, cache_dir=cache_dir, use_fast=True) # will use the Rust fast tokenizer if available
```

#### tgi approach:
```
volume=$PWD/data

model=Trelis/Llama-2-7b-chat-hf-function-calling-v2

docker run -d --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=<token> -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.1 --model-id $model --quantize --bitsandbytes-nf4
```
and then textgen.py
```
from text_generation import Client

client = Client("http://127.0.0.1:8080")

# Read the content from input.txt
with open('input.txt', 'r') as file:
    input_content = file.read()

print("Prompt:", input_content)

generated_text = client.generate(input_content, max_new_tokens=100, temperature=0.01).generated_text

print(generated_text)
```
with input.txt as follows:
```
<s> <FUNCTIONS>{
    "function": "search_bing",
    "description": "Search the web for content on Bing. This allows users to search online/the internet/the web for content.",
    "arguments": [
        {
            "name": "query",
            "type": "string",
            "description": "The search query string"
        }
    ]
}</FUNCTIONS>

[INST] Search bing for the tallest mountain in Ireland [/INST]
```

### Expected behavior

I would expect tgi to return the same output as what I'm getting from the python script that uses transformers.

**Comment by Narsil** [comment]
There's a lot of code I do not understand here and I cannot reproduce without `functionsList.txt` it seems.

Could you try and set-up the exact code you're running in both configurations ?

No there's something going on regarding tokenization in TGI, it's very barebone. But simple extra spaces can change a lot of things. There's a missing space early between the 2 prompts you shared.

**Comment by RonanKMcGovern** [comment]
Thanks @Narsil . Appreciate you having taken a look at it.

You're right there was a missing space in the tgi example after <s> (that space is introduced by the tokenizer in the python/colab example), so I've added the space and re-run with tgi.

I've also shared above input.txt to repro the tgi example, and functionList for the colab example.

I'm not sure exactly what you mean by "set up the exact code" but hopefully the above should help.

If you've little time, could you point me to where the tokenisation is done within tgi? I was looking through the api docs and I don't see how to specify a tokenizer so there must be one chosen by default. It could simply be a difference in tokenization because that could cause differences between say a "{" and a "_{" tokenisation. Ideally I'd want to select the specific tokenizer for Llama v2.

**Comment by Narsil** [comment]
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/flash_llama.py#L40

**Comment by RonanKMcGovern** [comment]
Thanks @Narsil I took a look at a few things:

1. What tokenizer is being used? *I assume that the llama model type is being determined from the model config, so LlamaTokenizer is probably used. I don't have a vocab_file specified though, so either it's getting that from somewhere by default, or maybe the program is defaulting to some other tokenizer - I wasn't able to follow fully*

2. Is there "skip_special_tokens=True/False" causing issues. I couldn't find the exact code for where tokenization happens. I assume that special tokens are **not** added (e.g. < s >) because the response gets very confused when I don't put in < s > at the start of sentences myself. I did find that "skip_special_tokens=True" for decoding, which is fine and consistent with what I see in the output (no special tokens).

As further debug steps, I could print to console when a certain tokenizer is called. I could also log the token ids being generated (if I can find where that is happening in the code).

Appreciate you letting me know what else I might do to debug. Thanks

**Comment by RonanKMcGovern** [comment]
@Narsil would you have any further tips here. I've been getting quite a few requests for this to work with tgi. Here's a working colab notebook: https://colab.research.google.com/drive/1Ow5cQ0JNv-vXsT-apCceH6Na3b4L7JyW?usp=sharing

**Comment by Narsil** [comment]
No special arguments, everything is default:

https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/flash_causal_lm.py#L200-L202

If you want help can you give simple (reduced) scripts that showcase the differences.
Having tiny differences is perfectly fine since kernels ran are different. They should be small and linked to pretty much any componenet of the environement (torch, transformers, cuda, GPU).

**Comment by RonanKMcGovern** [comment]
Hi Narsil, I was just about to post and I realised that I have two carriage returns in different, and that made a difference to the prompt outputs... 

Thanks for your help. Closing the issue. It turns out the chat-ui side of the setup is the tricker part (as the prompt syntax is set up in a .env file). I've got [it working now](https://github.com/TrelisResearch/tgi-chat-ui-function-calling).

**Comment by Narsil** [comment]
Perfect. 

There are works to include all this prompting directly in `transformers` conf.
If you want to check it out: https://github.com/huggingface/transformers/pull/25323

Cheers.
