### ISSUE TITLE
why AsyncClient.generate is slower than Client.generate

### ISSUE THREAD

**Issue by yunll** [huggingface/text-generation-inference#916]
### System Info

docker 1.0.1

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

task = [asyncio.ensure_future(text_generate_result_async(i, data[i % len(data)])) for i in range(20)]
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.wait(task))
10s Latency

threadPool = ThreadPoolExecutor(max_workers=10, thread_name_prefix="test_")
s = time.time()
all_task = [threadPool.submit (text_generate_result, i, data[i % len(data)]) for i in range(50)]
wait (all_task, return_when=FIRST_COMPLETED)
15s Latency

### Expected behavior

。

**Comment by Narsil** [comment]
Sorry this is not enough to reproduce. Do you mind sharing something reproducible ?

**Comment by yunll** [comment]
and when Async reqeust is 50, it appears Model is overloaded. model is bloom 7B and gpu is a100 80G
<img width="287" alt="image" src="https://github.com/huggingface/text-generation-inference/assets/15276878/8aca8351-ac54-4f31-a154-ddb9aa69cabb">

**Comment by yunll** [comment]
> to

client = Client("http://127.0.0.1:9009", timeout=20)
def text_generate_result(i, prompt):
    try:
        t1 = time.time()
        client = Client("http://127.0.0.1:9009", timeout=20)
        data = client.generate(prompt = prompt, max_new_tokens=300, stop_sequences=["1"], best_of=5, do_sample=True, temperature=1.0)

        res = [data.generated_text]
        data = data.details.best_of_sequences
        for item in data:
            res.append(item.generated_text)
        t2 = time.time()
        print("=================", i, t2-t1)
        return res, prompt, t2 - t1
    except Exception as e:
        print(e)
client2 = AsyncClient("http://127.0.0.1:9009", timeout=20)
async def text_generate_result_async(i, prompt):
    try:
        t1 = time.time()
        print("---------", i)
        data = await client2.generate(prompt = prompt, max_new_tokens=300, stop_sequences=["1"], best_of=5, do_sample=True, temperature=1.0)

        res = [data.generated_text]
        data = data.details.best_of_sequences
        for item in data:
            res.append(item.generated_text)
        t2 = time.time()
        print("=================", i, t2-t1)
        return res, prompt, t2 - t1
    except Exception as e:
        print(e)

**Comment by yunll** [comment]
> Sorry this is not enough to reproduce. Do you mind sharing something reproducible ?

client = Client("http://127.0.0.1:9009", timeout=20)
def text_generate_result(i, prompt):
    try:
        t1 = time.time()
        client = Client("http://127.0.0.1:9009", timeout=20)
        data = client.generate(prompt = prompt, max_new_tokens=300, stop_sequences=["1"], best_of=5, do_sample=True, temperature=1.0)
        res = [data.generated_text]
        data = data.details.best_of_sequences
        for item in data:
            res.append(item.generated_text)
        t2 = time.time()
        print("=================", i, t2-t1)
        return res, prompt, t2 - t1
    except Exception as e:
        print(e)
client2 = AsyncClient("http://127.0.0.1:9009", timeout=20)
async def text_generate_result_async(i, prompt):
    try:
        t1 = time.time()
        print("---------", i)
        data = await client2.generate(prompt = prompt, max_new_tokens=300, stop_sequences=["1"], best_of=5, do_sample=True, temperature=1.0)
        res = [data.generated_text]
        data = data.details.best_of_sequences
        for item in data:
            res.append(item.generated_text)
        t2 = time.time()
        print("=================", i, t2-t1)
        return res, prompt, t2 - t1
    except Exception as e:
        print(e)

**Comment by OlivierDehaene** [comment]
Well in one case you are sending 10 request at the same time (`ThreadPoolExecutor(max_workers=10, ...)`) and on the other case you are sending 20 requests concurrently.
