### ISSUE TITLE
passing num_return_sequences=3 but it's not returning 3 results.

### ISSUE THREAD

**Issue by Stealthwriter** [huggingface/text-generation-inference#917]
### System Info

Hi, I want to return 3 sequences, how can I achieve that? I tried using num_return_sequences=3, but the command just ignore it. Do I have to do modification on the code to make it return 3 sequences?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

just pass num_return_sequences=3 as a parameter

### Expected behavior

it should return 3 results

**Comment by Narsil** [comment]
It is not implemented.

**Comment by Stealthwriter** [comment]
> It is not implemented.

Can you please implement it? or tell which file to work on and I can do it...
