### ISSUE TITLE
Sorting sequences before inference

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/text-generation-inference#92]
@OlivierDehaene first of all, thanks for this repository. 

I haven't dug deeper into the code. So, I apologize in advance for asking this question.

During batch inferencing, do we first sort the sequences descendingly and then perform inference? In my experience, this leads to a significantly improved runtime (c.f.: https://www.carted.com/blog/improving-dataflow-pipelines-for-text-data-processing/)?

If not, would you be open to give it a try?

**Comment by OlivierDehaene** [comment]
> Do we first sort the sequences descendingly and then perform inference?

No, we only dequeue from a FIFO queue. 
I don't think it's something we want to do here. Throughput is not our main concern, latency is. 

I think in a bigger system, with multiple replicas, this is something that could be considered with an additional routing component that would sit on top of text-generation-inference and that would route on input length to the correct replica. 

What do you think?

**Comment by sayakpaul** [comment]
Right right. @Narsil also provided some more context to me. For the current setup, it won't make sense. Thanks folks!
