### ISSUE TITLE
Old Nvidia driver compatibility

### ISSUE THREAD

**Issue by kostyamyasso2002** [huggingface/text-generation-inference#925]
### Feature request

Add CUDA compatibility package (https://docs.nvidia.com/deploy/cuda-compatibility/#installing-title) to docker image

### Motivation

There are some cases when updating Nvidia driver is impossible or very hard (for example, in large clusters). For that cases, Nvidia developed compat package. It would be perfect If it was added to official docker image.

### Your contribution

.

**Comment by Narsil** [comment]
Sorry we're not going to do that. 

This bloats the official docker image for everyone including lots of users that do not require this.
Also most actual kernels will simply not work on older cards, no matter the amount of compat.

TGI attempts to gracefully downgrade itself on older archs, but it's perfectly OK if the best possible deployments requires new cards and capacities.
