### ISSUE TITLE
Dynamic Rope Scaling broken in 1.0.2

### ISSUE THREAD

**Issue by karlbernard2** [huggingface/text-generation-inference#927]
### System Info

Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: c4422e567811051e40469551c58a8078158a6656
Docker label: sha-c4422e5
nvidia-smi:
N/A

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I was working on deploying rope scaling to a live environment, I tested 1.0.1 and everything was working great, use the opportunity to try 1.0.2 but that version isn't working and will output gibberish.

sudo docker run --gpus all -d -p 8002:80 -v /home/ubuntu/data:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --max-input-length=3900 --max-total-tokens=4096 --rope-scaling dynamic --rope-factor 2.0 --model-id TheBloke/Chronos-Hermes-13B-SuperHOT-8K-fp16

Using --rope-scaling dynamic --rope-factor 2.0  with 1.0.2 will output gibberish while 1.0.1 works

### Expected behavior

Dynamic Scaling should work

**Comment by Narsil** [comment]
@karlbernard2 Could you send something to reproduce ? I'm not able to.

I don't see what could have affected it between those releases though. (We did change llama config to support codellama, but it's not in 1.0.2 afaik).
