### ISSUE TITLE
Server error: transport error

### ISSUE THREAD

**Issue by jerryMeng100** [huggingface/text-generation-inference#931]
### System Info

I'm using TGI in a small production service, and every like 12 or so hours it crashes and restarts in a K8s environment. The last thing I see in the crashed pod is:

2023-08-27T20:45:03.167347Z ERROR batch{batch_size=6}:decode:decode{size=6}:decode{size=6}: text_generation_client: router/client/src/lib.rs:33: Server error: transport error
2023-08-27T20:45:03.167544Z ERROR batch{batch_size=6}:decode:clear_cache{batch_id=Some(5468)}:clear_cache{batch_id=Some(5468)}: text_generation_client: router/client/src/lib.rs:33: Server error: error trying to connect: Connection refused (os error 111)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Run TGI in K8s pod for extended period of time with parallel requests coming in

### Expected behavior

No crashes

**Comment by jerryMeng100** [comment]
This is running on 2xA40 on Coreweave's cloud. Not sure if it has to do with an issue with GPU networking but it's reliably the same error message every time.

**Comment by Narsil** [comment]
It's probably something cleaning up `/tmp/text-generation-server-0` socket.

You can change `--shard-uds-path` to something else to fix it most likley.

**Comment by jerryMeng100** [comment]
Hi @Narsil can you explain a bit more on what changing it would do? And why would the /tmp value not work and what value might work better?

**Comment by jerryMeng100** [comment]
Nevermind, I chatgpt'd my way to understand what was happening. Moved the uds path to /data. I think perhaps for future the default path should be moved from /tmp into /data or something of the sort since I'm guessing I'm not the only one whose environment might clean up /tmp at random times.

**Comment by Narsil** [comment]
Most likely. Even the `/tmp` cleanup seemed odd (but plausible).

**Comment by jerryMeng100** [comment]
Figured out the issue (or at least the looks of it). No crashes so far after upping the provisioned pod ram from 8GB to 16GB. The odd thing is it runs fine with 8GB for 12 hours+ but consistently crashes at that mark... I'm not sure this is stated anywhere but might be good for folks running in cloud kubernetes environments. This is a 4 bit quantized 70b model, I don't know the exact minimums for other models but would be good to investigate.

**Comment by Narsil** [comment]
Are you using bitsandbytes ? Other issues reported might indicate that it could be leaking memory indeed.

**Comment by jerryMeng100** [comment]
I made a GPTQ quant because nf4 was quite slow. Turns out it does the same transport error several hours in, and this time even 28GB of ram is not enough. Increasing to 32 to see but I do think for all quantizations it's likely leaking memory. Strangely enough once ram is over a certain value it seems to stop happening altogether.
