### ISSUE TITLE
name 'CACHE_MANAGER' is not defined

### ISSUE THREAD

**Issue by sitabulaixizawaluduo** [huggingface/text-generation-inference#933]
### System Info

text-generation-inference 1.0.1
python 3.9

when i want to warmup model directly by:
next_batch = model.batch_type.from_pb(default_pb_batch, tokenizer, torch.float16, torch.device("cuda"))
size = model.warmup(next_batch)

find error: name 'CACHE_MANAGER' is not defined
i can't find the reason

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

1 creat a FlashCausalLMBatch 
2 Initialization model (llama 13B)
3 warmup batch

### Expected behavior

can you tell me the error from where and how can i deal with it

**Comment by Narsil** [comment]
What GPU are you using. 

You're likely to be running an old GPU/cuda version that doesn't support the ops it's trying to load.

Please reopen an issue and share the entire template information suggested.
