### ISSUE TITLE
How to use fine tune model in text-generation-inference

### ISSUE THREAD

**Issue by chintanshrinath** [huggingface/text-generation-inference#934]
Hi Team
I fine tune the llama 2 13b model and using merge_and_upload() functionality, I merge the model.
How I can use this merge model using text-generation-inference.

**Following command given an error**
![image](https://github.com/huggingface/text-generation-inference/assets/7765864/22e51673-4a4f-47ba-9b06-158ec7812951)
**Error**
![image](https://github.com/huggingface/text-generation-inference/assets/7765864/00f219ea-0483-4496-af11-9ce9d949a7d2)

**Comment by Narsil** [comment]
Is it a private model ?

You need to send the token  https://github.com/huggingface/text-generation-inference#using-a-private-or-gated-model

(Alos 0.8.2 is a bit old at this point, you may want to upgrade for newer models)

**Comment by Narsil** [comment]
Local directories should be detected automatically.

Here the issue is in docker. Docker sees the location from it's local perspective.

```
volume=/datadrive/new_finetune/
model_id=/data/merged_model
```

Should work (or something along those lines). Check out https://docs.docker.com/storage/volumes/ to understand how it works.
