### ISSUE TITLE
Quantization, generation quality and memory usage

### ISSUE THREAD

**Issue by VlaTal1** [huggingface/text-generation-inference#936]
### System Info

**The full command line used that causes issues:** `docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id WizardLM/WizardCoder-15B-V1.0 --quantize bitsandbytes`
**OS:** Ubuntu 20.04.6 LTS
**Rust version:** cargo 1.71.1 (7f1d04c00 2023-07-29)
**Model being used:** [WizardLM/WizardCoder-15B-V1.0](https://huggingface.co/WizardLM/WizardCoder-15B-V1.0)
**Hardware used:** 3090TI 24GB
**The current version being used:** 1.0.2

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. You can load the model to see the difference in memoty usage between usual loading and TGI
    Usual:
    ```
    BASE_MODEL_ID = 'WizardLM/WizardCoder-15B-V1.0'
    
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID)
    model = AutoModelForCausalLM.from_pretrained(BASE_MODEL_ID,
      device_map="auto",
      trust_remote_code=True,
      return_dict=True,
      load_in_8bit=True)
    ```
    TGI:
    ```
    docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id WizardLM/WizardCoder-15B-V1.0 --quantize bitsandbytes
    ```
    With `AutoModelForCausalLM.from_pretrained` 8-bit version of model takes about 17GB VRAM, but with TGI it takes about 
    21GB VRAM
    
    Also there is something strange when I use `--quantize bitsandbytes-nf4` or `--quantize bitsandbytes-fp4` because it takes more VRAM (22454MiB to be exact compared to 21350MiB using `--quantize bitsandbytes`)

  2. There is a problem with generation quaity. Sometimes artifacts appear in the form of code repetitions, strange characters and 
      looping (for example, it reaches some port and writes 0.1.0.1.0.1.0.1 until it reaches the maximum number of tokens). This is 
      especially evident if I send several requests for processing at the same time. I tested with 10 requests at the same time.   
      The repetition penalty doesn't help much and for my purposes it often makes things worse
      Exmple of body which I send to generate endpoint:
      ```
       {
          "inputs":"Below is an instruction that describes a task. Write a response that appropriately completes the request\n\n### Instruction: create Java classes according to this PlantUML diagram:\n\n@startuml\n\nentity Book {\nid: long\nname: string\nlanguage: string\nyearOfPublishing: int\n}\n\nentity Author {\nid: long\nfirstName: string\nlastName: string\nnationality: string\n}\n\nenum Genre {\nSCIENCE_FICTION\nFANTASY\nHORROR\nTECHNICAL_WRITING\nEROTIC_FICTION\nWESTERN\nOTHER\n}\n\nBook \"1..N\" -o \"1\" Author: books\nBook \"1\" o- \"1..N\" Genre: genres\nAuthor \"1\" o- \"1..N\" Genre: genres\nBook \"1..N\" o- \"1\" Author: author\n\n@enduml\n\n### Response:",
          "parameters":{
              "max_new_tokens":600,
              "temperature": 0.1,
              "top_k": 1,
              "top_p": 0.1,
              "repetition_penalty": 1.0
          }
      }
      ```

### Expected behavior

I want to load model in 8 bit
First of all, I expect better generation quality. When I used the model with `AutoModelForCausalLM.from_pretrained` and did the inference with a batch of 10 prompts, I got responses without such artifacts
I also expect to use less VRAM because the model used to take up 4GB less memory (if possible)

**Comment by Narsil** [comment]
Ok, I just tried.

Output is indeed very bad for `--quantize bitsandbytes` but seems ok with `--quantize bitsandbytes-nf4`.
Everything seems OK on `meta-llama/Llama-2-7b-hf`.

This leads me to believe that there's just a mismatch between the model and BNB-8bit somewhere.
The error could be here, but since it works without quantization and in 4bit I'm inclined to think that it's more that somehow the 8bits quantization screws things for this particular model.

If that's true that would be extremely interesting to understand deeply (since understanding how quantization fails could lead to betterquantization schemes).

**Comment by jingli-wtbox** [comment]
i also tried `meta-llama/Llama-2-7b-hf` with `bitsandbytes` and `bitsandbytes-nf4`.  memory consumption is the same. it's around 22GB.

**Comment by VlaTal1** [comment]
And this is very surprising. I can understand the increase in memory if some additional things are loaded into memory. But there must be difference between the 15B and 7B models. And between quantized versions too

**Comment by VlaTal1** [comment]
Ok, now it's clear to me. Thank you!

I have one more question. The documentation says that the Starcoder architecture is supported. Maybe I'm wrong and I'm talking nonsense but as I understand it, WizardCoder is based on Starcoder or they just have the same architecture. In this case, will WizardCoder be loaded differently from Starcoder? If so, could you please tell me in which files are these models loading? More llikely WizardCoder are loading with `server/text_generation_server/models/causal_lm.py`, but I can`t see file for starcoder

**Comment by VlaTal1** [comment]
> Ok, now it's clear to me. Thank you!
> 
> I have one more question. The documentation says that the Starcoder architecture is supported. Maybe I'm wrong and I'm talking nonsense but as I understand it, WizardCoder is based on Starcoder or they just have the same architecture. In this case, will WizardCoder be loaded differently from Starcoder? If so, could you please tell me in which files are these models loading (if you know)? More llikely WizardCoder are loading with `server/text_generation_server/models/causal_lm.py`, but I can`t see file for starcoder

**Comment by Narsil** [comment]
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/__init__.py#L124

**Comment by Narsil** [comment]
Closing this issue since it seems resolved.

**Comment by muhammad-asn** [comment]
Seems in my case I try to load  `meta-llama/Llama-2-13b-chat-hf` in `bitsandbytes` or `bitsandbytes-nf4`  but still use more VRAM than the default model? Any ideas?

**Comment by OlivierDehaene** [comment]
TGI uses all VRAM available for batching and improving throughput. You can limit the amount of VRAM used by TGI with the `--cuda-memory-fraction` arg. 
In this case, the % of VRAM used by the model decreases when using quantization and you have more VRAM for batching.

**Comment by muhammad-asn** [comment]
I see, but I have another question, is the memory only (vram) that matters or the GPU compute capability will have better results too

Assume I ran A100 40GB vs T4 64GB
