### ISSUE TITLE
CodeLlama supports 4k context window but can't set max_new_tokens to more than 2048

### ISSUE THREAD

**Issue by skapadia-zalando** [huggingface/text-generation-inference#937]
### System Info

Running on AWS p4 instances, using the docker container

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Run the image
```
docker run --gpus 1 --shm-size 1g -p 8077:80 -v /home/skapadia/huggingface_cache:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id codellama/CodeLlama-34b-Instruct-hf
```

2. Send a request with a high number of tokens
```
curl 127.0.0.1:8077/generate \
    -X POST \
    -d '{"inputs":"...","parameters":{"max_new_tokens":1024}}' \
    -H 'Content-Type: application/json'
```

And you will see 

```
ValidationError: Input validation error: `inputs` must have less than 1024 tokens. Given: 1872
```

### Expected behavior

I will have inputs of around 3k tokens, this won't work unless there is a way to change this setting somehow

**Comment by Narsil** [comment]
`--max-input-length` and `--max-new-tokens` are the options you need to set on the server (1024 is the default).


Try running 
```
docker run --gpus 1 --shm-size 1g -p 8077:80 -v /home/skapadia/huggingface_cache:/data ghcr.io/huggingface/text-generation-inference:1.0.2  --help
```

To get more information about all the possible flags. We try to select sound defaults but it all depends on hardware + model + actual choices you want to make in your deployments.

**Comment by skapadia-zalando** [comment]
Thanks, I must have missed this in the docs
