### ISSUE TITLE
Hosted LM throws ReadTimeout error

### ISSUE THREAD

**Issue by iamseokhyun** [huggingface/text-generation-inference#942]
### System Info

Hardware: Local A100 80G * 8, Local A6000 48G * 8 HPC
CUDA version: 11.7
Model used: MPT-30B, Falcon-7B, Falcon-40B (-instruct)

I hosted the above models using official Docker image (via command in readme.md).
And I tried to use the hosted models in Python.
However, I'm getting errors for certain queries like the below.

Error type: <class 'requests.exceptions.ReadTimeout'>, Error message: HTTPConnectionPool(host='0.0.0.0', port=53334): Read timed out. (read timeout=10)

Currently, I work around this issue by inserting multiple newline or space characters into the query, but there is a 10-second delay each time an error occurs. There are also some queries that always throw an error, no matter how many meaningless characters I add.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Context: hosting falcon-7b-instruct using the official docker command in readme.md
Send request via python code using the code below:

```
from text_generation import Client
client = Client("http://0.0.0.0:53334")
input_text = """below example here"""
print(client.generate(input_text, max_new_tokens=1500, do_sample=False).generated_text)
```

## example 1
Question: Can the original name of the zucchini be typed on the top row of a QWERTY keyboard?
Answer: Let's think step by step. 

## example 2
Question: Was Morris County named after a chief justice?
Answer: Let's think step by step. 

### Expected behavior
It should return generated text.

Got the error below.
Error type: `<class 'requests.exceptions.ReadTimeout'>`, 
Error message: `HTTPConnectionPool(host='0.0.0.0', port=53334): Read timed out. (read timeout=10)`

**Comment by Narsil** [comment]
Could you share the actual logs (all of them including startup) of the deployment ?
Can you include the full command line used ?

Try to include as much information as possible so we can reproduce or detect potential issues.

Have you added the `shm` correctly ? 
Since you seem to be running local things, this may help: https://github.com/huggingface/text-generation-inference/issues/714#issuecomment-1655207099

**Comment by Narsil** [comment]
Logs?

**Comment by Narsil** [comment]
Very interesting... Can you run basic cuda commands in your docker env? Or other models using different docker usage.

Max waiting tokens is the amount of tokens you wait at the maximum being stacked on the current batch. It's a maximum added latency if you will. (shouldn't impact whatsoever what you're seeing.)

**Comment by Narsil** [comment]
Could it be some firewall setting preventing you from reaching the port?

**Comment by Narsil** [comment]
Some queries time out depending on the content ????

That's extremely odd. IMO it's just spurious error on the cards somehow (or NCCL being stuck).
Are you 100% sure it's always the same queries that create the same issues ?

> (Additionally, can increasing max waiting token increase throughput?)

Depends on the load. I wouldn't play too much with it. `text-generation-benchmark` is the goto tool to see compromises Latency vs throughput.

**Comment by Narsil** [comment]
Everything works perfectly fine in my test setup.

```bash
curl 127.0.0.1:8080/generate_stream     -X POST     -d '{"inputs":"Question: Carly is making cupcakes and brownies for her art class. She makes 2 less than three times as many brownies as cupcakes. If Carly'\''s class has five people and each person gets two treats, how many cupcakes did Carly make?\nAnswer: Let'\''s think step by step. ","parameters":{"max_new_tokens":20}}'     -H 'Content-Type: application/json'
```

In order to remove any ambiguity regarding the query.

**Comment by Narsil** [comment]
There's a few ways:

- 1 GPU is bad/faulty.
- Issue in the sampling when using shards(which you're not using here). If  2 shards don't select the same token, 1 might select EOS while the other continues running which can end up triggering deadlocks in NCCL (1 shard is waiting for the other).
- Environment is faulty. Usually NCCL ends up being the culprit, but it could be the firewall, cuda or the host cuda installation. 

Have you tried `--net=host` ?

**Comment by luoziyong** [comment]
It may be that the reply is too long, causing a timeout

You can verify it in two ways：
1. Set `max_new_tokens` to 100
2. Set `timeout` to 60 use `Client("http://0.0.0.0:54443", timeout=60)`

**Comment by Narsil** [comment]
Aren't you streaming ? Streaming time to first byte should always be relatively fast (expected order of magnitude : 1s)

**Comment by luoziyong** [comment]
> @luoziyong Your second solution did work! The cause seems to be that meaningless repetitive strings are generated for a long period of time. Thank you!
> 
> @Narsil First, thanks for the continued feedback. I was able to reproduce the error on a different CUDA version (11.8) based HPC. And the second solution provided by @luoziyong above worked. Btw, what is streaming?

Just use `generate_stream` method, it can response in push style once a token generated.

This is the example in README

```python
from text_generation import Client

client = Client("http://127.0.0.1:8080")
print(client.generate("What is Deep Learning?", max_new_tokens=20).generated_text)

text = ""
for response in client.generate_stream("What is Deep Learning?", max_new_tokens=20):
    if not response.token.special:
        text += response.token.text
print(text)
```

**Comment by luoziyong** [comment]
@iamseokhyun The performance is totally same, just two different transfer methods.
