### ISSUE TITLE
Error when executing TGI with mariiaponom/llama_7b_class_lora

### ISSUE THREAD

**Issue by OscarAGracia** [huggingface/text-generation-inference#944]
it works: https://huggingface.co/mariiaponom/llama_7b_class_lora
It does create copies though.

_Originally posted by @Narsil in https://github.com/huggingface/text-generation-inference/issues/896#issuecomment-1691770960_
         
When I launch:

**volume=$PWD/data**
**model=mariiaponom/llama_7b_class_lora**

**docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=... -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.0.2 --model-id $model --quantize bitsandbytes-nf4**

I have this error: **No local weights found in mariiaponom/llama_7b_class_lora with extension .bin**

![ErrorLaunchLorallama](https://github.com/huggingface/text-generation-inference/assets/30901024/05d9a399-7ddc-428c-9abe-c8153cb6a650)

**The same error if I try to launch a model trained with autotrain hugging face application**

**Comment by Narsil** [comment]
Try running `1.0.3` This is the version that has the fix. (It worked previously but only on CLI, not in docker)
