### ISSUE TITLE
[suggestion] `nvidia-smi` shows GPU idling at power state 2

### ISSUE THREAD

**Issue by Cyberes** [huggingface/text-generation-inference#946]
### Feature request

I checked `nvidia-smi` while TGI was idling and I saw that my GPU (A4000) was idling at P2. This is a pretty low (or, rather high) for idling as I've noticed other inference software typically idles at P8.

Further testing showed that after a few generations, the power state will sit at P2 and not switch back to P8. It would be cool if power state handling was further implemented. 

`nvidia-smi` shows that although it's at P2, the wattage is 38/140W, which means it's correctly idling but not switching to P8.

### Motivation

Better thermal management.

### Your contribution

No, sorry.

**Comment by Narsil** [comment]
TGI doesn't make any sort of power management.

This should probably be opened upstream. I don't even think torch does it. This seems like a CUDA/NVIDIA issue, no ?

**Comment by Cyberes** [comment]
Okay, I'll see what they say.
