### ISSUE TITLE
CacheManager init with k cache dim x is not correct when BLOCK_SIZE != 16

### ISSUE THREAD

**Issue by XiaoBin1992** [huggingface/text-generation-inference#949]
### System Info

text-generation-inference 0.9.4 

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

![image](https://github.com/huggingface/text-generation-inference/assets/24936821/95144615-f66c-480f-85b2-e53695a10c5d)
in vllm x = 16 / sizeof(scalar_t);
but tgi use x = self.block_size // element_size

when self.block_size != 16 it will output wrong attention result

### Expected behavior

different block_size will have similar calculation result

**Comment by OlivierDehaene** [comment]
Would you like to open a PR to fix this?
