### ISSUE TITLE
Inference speed comparison

### ISSUE THREAD

**Issue by CedricVandelaer** [huggingface/text-generation-inference#952]
### System Info

System info: TGI Docker version 1.0.3, Windows 11, RTX4090 GPU.

Hi, I'm relatively new to the "running a local llm"-scene. I was wondering how this library compares to other inferencing frameworks like llama.cpp and exllama? 

I'm also running llama.cpp on my macbook pro and inference speed seems to be about as fast for similar models as on my desktop pc with an RTX4090, which is not really what I expected. Is this library optimised to be as fast as possible already or should I rather look at other libraries? I really appreciate how easy it is to set TGI up and how I can simply use a dockerfile that I can share with my colleagues too.

Usually I use the GTPQ versions of models provided by TheBloke. Are there maybe other optimisations I should be looking at?

Sorry, I realize this is not the typical github issue, but I'm not sure where to go with my question. Thanks!

### Information

- [x] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

Run any model in TGI and compare it to a similar library.

### Expected behavior

I would expect TGI to be as fast as the other library.

**Comment by Narsil** [comment]
This library is intended to be use for deployments used by many different users typically in cloud and not local deployments.

The use of TP sharding `--num-shard` is usually very beneficial to end latency (it always depends we use `text-generation-benchmark` a lot to look at the best possible deployments).

GPTQ is currently the best 4bit scheme for precision and latency. Still not perfect and it can be slower than f16 on some configs.

Closing this.
Please use our discord or https://discuss.huggingface.co/ other more appropriate channels next time. We try to keep GH about the code and bugs/features not about general wondering.

Cheers.

**Comment by LoganDark** [comment]
> Please use our discord

Where? I can't find the link.
