### ISSUE TITLE
GPU memory understanding when hosting a model with TGI

### ISSUE THREAD

**Issue by zhangyilun** [huggingface/text-generation-inference#955]
### System Info

Running directly in `ghcr.io/huggingface/text-generation-inference:1.0.2`.

GPU info:
```
NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4
```
8x A100 40GB GPUs.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I specifically have questions regarding the GPU memory usage.

```
model=meta-llama/Llama-2-7b-chat-hf
volume=$PWD/weights
token=...

docker run \
    --gpus '"device=4"' \
    --shm-size 1g \
    -e HUGGING_FACE_HUB_TOKEN=$token \
    -p 4088:80 \
    -v $volume:/weights \
    ghcr.io/huggingface/text-generation-inference:1.0.2 \
    --model-id $model \
    --disable-custom-kernels \
    --num-shard 1
```

### Expected behaviour

Maybe it's me not fully understanding the GPU memory utilization and how the setup is working as I can't find much documentations.

With above command to host the 7b llama-2 model, and setting `num-shard 1` (probably don't need to as I'm limited to 1 GPU), the GPU device is full:
```
|    4   N/A  N/A     93051      C   /opt/conda/bin/python3.9        39399MiB |
```
Does it mean TGI will automatically create copies of the model until the GPU memory is full for inference optimization? For example, if I'm hosting the 7b model in bfloat16, it should take ~13GB of space, then does it mean it will probably host 2 instances on the same GPU (since there will be memory required during inference). But that doesn't really explain to me why the GPU is shown as full.

Any explanation or pointer to existing documentation on this behavior would be appreciated!

**Comment by luoziyong** [comment]
you can see this [936](https://github.com/huggingface/text-generation-inference/issues/936#issuecomment-1697226461)

**Comment by zhangyilun** [comment]
@luoziyong Thank you for the pointer, it makes sense. I'm wondering is there any further documentation on how exactly the memory is being used? For example, will there be extra model instances hosted if memory is allowed, and if there's a way to get that information.

**Comment by luoziyong** [comment]
You can use `cuda_memory_fraction` to limit instance memory usage, and use `--num_shard` and `CUDA_VISIBLE_DEVICES` to set how to use multiple cards for instance. 

For example:
You can use `CUDA_VISIBLE_DEVICES=0,1 text-generation-launcher... --num_shard 2` and `CUDA_VISIBLE_DEVICES=2,3 text-generation-launcher... --num_shard 2` to launch 2 copies with 2 shard each on a given machine with 4 GPUs for instance.

**Comment by zhangyilun** [comment]
@luoziyong I saw this from the documentation on `--num-shard` but I think this is particularly useful when using with multiple GPUs. I'm currently testing with only 1 GPU, so I have to set `--num-shard 1`. In this setup, the model will be loaded as a whole on the same device, and I'm pretty sure there are multiple instances loaded. I'm fine with using all GPU memory (so don't need to specify `--cuda-memory-fraction`, as it's an optimization, but I just felt clueless about the exact setup in the backend and how the GPU memory is used.

**Comment by luoziyong** [comment]
@zhangyilun How do you determine that there are multiple instances? `--num-shard` is just to set the number of shards of one instance to use multiple gpus. You can use `nvidia-smi` to see the processes running on every gpu.

**Comment by dcruiz01** [comment]
> You can use `--cuda-memory-fraction` to limit instance memory usage, and use `--num_shard` and `CUDA_VISIBLE_DEVICES` to set how to use multiple cards for instance.
> 
> For example: You can use `CUDA_VISIBLE_DEVICES=0,1 text-generation-launcher... --num_shard 2` and `CUDA_VISIBLE_DEVICES=2,3 text-generation-launcher... --num_shard 2` to launch 2 copies with 2 shard each on a given machine with 4 GPUs for instance.

@luoziyong in this example, are you still setting `--gpus all` in your `docker run` command? I'm struggling to get two TGI containers up and running on my 4xA6000 hardware.

**Comment by luoziyong** [comment]
@dcruiz01 To assign specific gpus to the docker container `docker run --gpus '"device=0,1"' `
