### ISSUE TITLE
The model output is empty while using Dynamic RoPE Scaling

### ISSUE THREAD

**Issue by Colafei0406** [huggingface/text-generation-inference#956]
Hi, First of all thanks for the contribution !!

I want to use llama-2-13b model with dynamic RoPE scaling，But when the input context length is too long , ~5742 tokens，the output is empty. 

I use the version text-generation-launcher 1.0.1

I tried running the following command: 
text-generation-launcher --model-id ./llama-2-13b --port 3001 --max-input-length=16384 --max-total-tokens=20000 --rope-scaling=dynamic --rope-factor=2.0 --max-batch-prefill-tokens=40100 

Can you tell me the possible reason?? Thanks very much

**Comment by Narsil** [comment]
Sorry Iḿ not sure, have you tried without the `rope-factor` ?

**Comment by sjzhou4** [comment]
you can go to /text-generation-inference/server/text_generation_server/utils/layers.py.  It will show calc about rope-scaling, it may in 570 lines

**Comment by Narsil** [comment]
Closing as stale
