### ISSUE TITLE
How to enter the docker image to modify the environment

### ISSUE THREAD

**Issue by Romaosir** [huggingface/text-generation-inference#959]
### System Info

dokcer image: ghcr.io/huggingface/text-generation-inference:1.0.2

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [X] My own modifications

### Reproduction

I want to enter the image to modify the environment，like: tiktoken.

`docker run -it ghcr.io/huggingface/text-generation-inference:1.0.2 /bin/bash`

I get:
error: unexpected argument '/bin/bash' found
Usage: text-generation-launcher [OPTIONS]

### Expected behavior

no error
thx!

**Comment by stefanobranco** [comment]
You should be able to do that by configuring /bin/bash as your entrypoint:

`docker run -it --entrypoint /bin/bash ghcr.io/huggingface/text-generation-inference:1.0.2`

**Comment by Narsil** [comment]
`exec -it` if you want to run on a running container.

`-e MYENV=value` to send env to docker.

I will close this since it should solve your issue.
