### ISSUE TITLE
Could not import Flash Attention enabled models: CUDA is not available

### ISSUE THREAD

**Issue by smartge3k** [huggingface/text-generation-inference#960]
### System Info

I am on the Ubuntu server of https://console.paperspace.com/ with Ampere A100 80G. 

I am trying the below 
```
model=meta-llama/Llama-2-7b-chat-hf
volume=$PWD/data 
token=<your cli READ token>

sudo docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -e  HF_HUB_ENABLE_HF_TRANSFER=0 -p 8080:80 -v $volume:/datanew ghcr.io/huggingface/text-generation-inference:latest --model-id $model
```

I have tried the command without `HF_HUB_ENABLE_HF_TRANSFER=0` as well. 

The model does run but GPU is not used at all, below is the description of my GPU.
![gpu version](https://github.com/huggingface/text-generation-inference/assets/47830955/2ab2e376-8d98-438f-97d7-10c566479723)

Below are the complete logs of:
![Untitled](https://github.com/huggingface/text-generation-inference/assets/47830955/a0852159-d260-4bf1-9c61-b9db569a2f2e)

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

sudo docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -e  HF_HUB_ENABLE_HF_TRANSFER=0 -p 8080:80 -v $volume:/datanew ghcr.io/huggingface/text-generation-inference:latest --model-id $model

### Expected behavior

Model should use the GPU

**Comment by Narsil** [comment]
Can you use a specific version `1.0.3` or use `--pull always`  (just making sure you're actually actual latest).

I'm not familiar with the platform, are you able to run any other docker with torch ?
This could be a host nvidia issue.

**Comment by smartge3k** [comment]
@Narsil I tried with 1.0.3 but it same, nothing changes. although I have tried the below 
```
import torch
print(is_cuda_available())
False
```
I cant figure out what I am doing wrong, although I have everything required, installed.

**Comment by Narsil** [comment]
It's quite hard to help here.

It could be an issue with how your provider setup cuda and out of your hands. I think you should ask them directly.

Also sometime `--net=host` helps in those situation (mostly for NCCL communication, but we never know).

**Comment by OlivierDehaene** [comment]
Your server might be missing some required host dependencies for A100s.
You need to install:

shell
```
sudo apt-get install -y datacenter-gpu-manager
sudo systemctl --now enable nvidia-dcgm

# Get major driver version with nvidia-smi
sudo apt-get install cuda-drivers-fabricmanager-<version>
sudo systemctl enable nvidia-fabricmanager
```

**Comment by akjindal53244** [comment]
@smartge3k were you able to find solution for this?

@Narsil @OlivierDehaene I have my Ubuntu 20.04 based 1x4090 GPU machine and I am also seeing the same log and GPU is not being used at all. Based on the open issues, looks like there are couple of other developers facing the same issue so it should be addressed.
