### ISSUE TITLE
Llama 2 Error (docker): model of type llama to instantiate a model of type .

### ISSUE THREAD

**Issue by LarsHill** [huggingface/text-generation-inference#961]
### System Info

I am running the recommended docker command on an Ubuntu Server with 4x A100 82GB GPUs. 

The nvidia-container-toolkit is installed and nvidia-smi shows: 
`NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2`

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

I run the following docker command:
`docker run --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=<token> -p 8080:80 -v $PWD/model_data:/
data ghcr.io/huggingface/text-generation-inference:latest --model-id meta-llama/Llama-2-13b-chat-hf --quantize bitsandbytes-nf4`

The frustrating result is that not every time the bellow error shows up. Sometimes it appears right after loading the model on the GPU and sometimes the shard suddenly crashes after X minutes when multiple queries have been processed successfully...

Error message (no full traceback is shown):
```
ERROR shard-manager: text_generation_launcher: Shard complete standard error output:                                                                                  [82/746]

You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors. rank=0
2023-08-31T11:23:04.778475Z ERROR shard-manager: text_generation_launcher: Shard process was signaled to shutdown with signal 15 rank=0
2023-08-31T11:23:04.833792Z ERROR text_generation_launcher: Shard 0 crashed
```

While googling I came across this very recent post on the huggingface forum. But so far there is no responce:
[https://discuss.huggingface.co/t/text-generation-inference-you-are-using-a-model-of-type-llama-to-instantiate-a-model-of-type/52848](https://discuss.huggingface.co/t/text-generation-inference-you-are-using-a-model-of-type-llama-to-instantiate-a-model-of-type/52848)

### Expected behavior

I would expect the error to not appear...

Thanks for your help!

**Comment by Cyberes** [comment]
Hey look, it's me!

https://github.com/huggingface/text-generation-inference/issues/929

I'm having the same issue (I'm glad I'm not the only one). I'm thinking this is linked to the underlying host, so post ALL your hardware info. Hypervisor, CPU model, etc.

**Comment by Narsil** [comment]
Here it's signal 15, which is SIGTERM. Meaning someone is killing your process.

Not sure who that is, you'd have to investigate. Unlike signal 4 (linked issue) this should come from an external process, not the OS itself.

**Comment by Cyberes** [comment]
@LarsHill Do you get the `Webserver Crashed` line?

**Comment by LarsHill** [comment]
> Here it's signal 15, which is SIGTERM. Meaning someone is killing your process.
> 
> Not sure who that is, you'd have to investigate. Unlike signal 4 (linked issue) this should come from an external process, not the OS itself.

@Narsil Thanks a lot for that pointer. It turns out another colleague was working on the server at the same time and we both didn't know about each other. He got confused by the "random" spawning of a 79GB GPU process and killed it multiple times^^

So, sorry for the false alarm. I guess this can be closed.

@Cyberes I did not get any Traceback or crashed line. I go ahead and close this issue since it seemed to be different from yours in terms of the Signal that killed the process.
