### ISSUE TITLE
Repetitive Output for Identical Queries in Llama-2 with TGI

### ISSUE THREAD

**Issue by sri-dhurkesh** [huggingface/text-generation-inference#969]
I'm currently using text generation inference with Llama-2, and I've noticed that when I provide the same query multiple times, it consistently generates the same answer each time. I'm curious to know if there's a caching mechanism implemented in the text generation inference process.

**Comment by Narsil** [comment]
No it is running greedy mode by default.

You have to ask for `temperature` and other parameters to get sampling (or `do_sample: true` for default sampling).
