### ISSUE TITLE
Create ARM container images

### ISSUE THREAD

**Issue by newUserForTesting** [huggingface/text-generation-inference#972]
### System Info

Docker run is failing on Apple M2 chip laptop. Here is the command I fired and the exception:

```
docker run --shm-size 1g -p 8080:80 -v . ghcr.io/huggingface/text-generation-inference:1.0.3 --model-id EleutherAI/pythia-1b --disable-custom-kernels

Unable to find image 'ghcr.io/huggingface/text-generation-inference:1.0.3' locally
1.0.3: Pulling from huggingface/text-generation-inference
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

Also I am looking to run custom fine tuned model saved in my local machine. Could someone please help?

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Just running the above command in the Apple M2 chip laptop.

### Expected behavior

text-generation-inference up and running in my local setup

**Comment by adiazarya100** [comment]
Same issue with the Apple M1 chip... :|

**Comment by newUserForTesting** [comment]
Could you please keep it open as feature request? Most of the developers are Apple users, it would be great help for them if you could support it?

**Comment by OlivierDehaene** [comment]
If you are a M1, M2 user you can:
- install locally
- use a remote linux box (best option IMO)
- pull the linux docker image and run in compatibility mode with `docker run --platform linux/amd64 ...`. Note however that this will be slow and should only be used for basic debugging.

We may setup an ARM CI in the future.

**Comment by awmartin** [comment]
Building locally throws the error, "CUDA_HOME environment variable is not set." Is there a workaround or recommendations on how one might contribute a working Apple Silicon build with the "mps" torch device? Here are also global imports that expect torch.cuda to be defined and working.

**Comment by fxb392** [comment]
Does tgi now support linux servers based on the arm architecture?
