### ISSUE TITLE
Memory leak and crash in long-running pod handling requests continuously

### ISSUE THREAD

**Issue by 0xymoro** [huggingface/text-generation-inference#974]
### System Info

When running TGI in a typical K8s enviornment, for quantized GPTQ or NF4 (only tested with both) and leaving the endpoint up for hours with requests coming in continuously throughout, it would eventually crash. The memory usage also seems to continue going up over time. 

For Huggingface folks @Narsil  using this for GPTQ in production: how much pod memory is allocated? Does it do this as well?

How this is different from other issues raised:
https://github.com/huggingface/text-generation-inference/issues/801
Points out on CUDA OOM. This is not a CUDA OOM, the CUDA max memory is set to 0.95 in my tests and it rather OOMs on the main pod RAM not GPU RAM. May be related, may be separate issue.

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

Use a GPTQ or NF4 model, and run it for a long time with it running continuous requests at all times. 

### Expected behavior

Not crash.

**Comment by Narsil** [comment]
What version are you running ? what hardware ? Please fill in the entire template of the issue.

Also we have never encountered the issue ourselves, despite running a few GTPQ endpoints..

**Comment by jerryMeng100** [comment]
Version 1.0.3, on 2x RTX A6000 on Coreweave. It may have to do with the sharding if you've never ran into it?

**Comment by nth-attempt** [comment]
Facing the same issue. The deployment was on Sagemaker for Llama-2-70B-chat-hf-GPTQ (4 bit). The memory utilization constantly went up until it reached 100% over the span of a day with constant requests to the endpoint. This is on v1.0.3 and g5.12xlarge (4GPU).

**Comment by wangerzi** [comment]
Same problem, version ghcr.io/huggingface/text-generation-inference:1.1.0，NVIDIA A10, SynthIA-7B-AWQ
![image](https://github.com/huggingface/text-generation-inference/assets/22190579/a87a2dc2-d2cc-4fb3-abeb-b29de16e2c38)

**Comment by A-Posthuman** [comment]
I'm also running into this problem. Not using a quantized model, just the regular openchat/openchat-3.5-0106 model. Server's memory eventually gets filled after a bit over an hour of continuous inferencing. With latest TGI version 1.3.4.

**Comment by Narsil** [comment]
It's really funny we have never seen that happening.

Something must be not flushing itself. Could be logs for instance being kept somewhere ?

**Comment by A-Posthuman** [comment]
I was running TGI (before I gave up due to this issue and switched to vllm) via the recommended docker method.

And actually to avoid logs build up I had added this to /etc/docker/daemon.json:

```
{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "log-driver": "json-file",
    "log-opts": {
        "max-size": "10m",
        "max-file": "3"
    }
}
```

Still had the mem leak. This was running on one of the more recent AWS deep learning AMIs.

**Comment by Narsil** [comment]
<img width="1207" alt="Screenshot 2024-02-01 at 09 24 38" src="https://github.com/huggingface/text-generation-inference/assets/204321/53844938-553c-4a64-8798-d567d2fc3ce9">

This is what we have.

Anything in particular in your env aside from modifying the host ? Which cloud provider, maybe some specific options in how users are querying the models ?

Anything that might help isolate and reproduce this would be welcome.

**Comment by A-Posthuman** [comment]
This was on an AWS g5.xlarge instance. The shell env vars were:

volume=$PWD/data-tgi
model=openchat/openchat-3.5-0106

command line was:

docker run --name tgi --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.4.0 --model-id $model --max-total-tokens 2048 --max-batch-prefill-tokens 7200 --max-waiting-tokens 10272 --max-input-length=2000 --cuda-memory-fraction 0.95

inference client was on a separate server, using python, huggingface_hub library, InferenceClient client

the client prompts started with the model's suggested prompt beginning "GPT4 Correct User:" and ended with the model's special token <|end_of_turn|>

the client used 8 threads to send requests like:

response = client.text_generation(prompt=prompt, stream=False, details=False, temperature=0.01, seed=42, max_new_tokens=6)
