### ISSUE TITLE
Adding mirostat sampling method

### ISSUE THREAD

**Issue by CarloNicolini** [huggingface/text-generation-inference#975]
### Feature request

The mirostat sampling method [here](https://arxiv.org/abs/2007.14966) is a way to sample new tokens according to a target cross-entropy that overcomes some of the problems of both `top_p` and `top_k` sampling methods. 

### Motivation

Currently it looks like llamacpp implements it and the resulting texts are of good quality. Is it something feasible to implement in TGI?

### Your contribution

I could be trying a first implementation of it, which does not seem too complicated.

**Comment by OlivierDehaene** [comment]
@gante, do you know this sampling method?

**Comment by gante** [comment]
@OlivierDehaene I have never heard of it 😅 We do have other entropy-based sampling methods, from [this paper](Truncation Sampling as Language Model Desmoothing). AFAIK, it has a limited number of users

**Comment by jagilley** [comment]
+1 on this request
