### ISSUE TITLE
Support for custom models

### ISSUE THREAD

**Issue by Nilabhra** [huggingface/text-generation-inference#980]
### Feature request

Currently TGI only supports models that are available in HF Hub. It would be great if people could deploy their custom built models via TGI. Is there any guide on how to do so?

### Motivation

TGI doesn't support custom model written using `transformers`. Adding this support will mean more developers can benefit from TGI.

### Your contribution

N/A

**Comment by Narsil** [comment]
IT does, you just need to use `--trust-remote-code`.

Ofc those do not benefit from flash+paged attention but it does work.

**Comment by Nilabhra** [comment]
Thanks, I'll try this out!
