### ISSUE TITLE
How can I set the tracing log level?    

### ISSUE THREAD

**Issue by GxjGit** [huggingface/text-generation-inference#984]
### System Info

How can I set the tracing log level?  I want to record the  output content  of  by tracing::debug!,  like tracing::debug!(parent: &span, "Output: {}", output_text),  but It seems to be set info level for default.  How can I set it to debug?  Thanks.

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

Default run as Readme.

### Expected behavior

No

**Comment by OlivierDehaene** [comment]
You can use the LOG_LEVEL env var to `LOG_LEVEL=info,text_generation_router=debug`.

**Comment by GxjGit** [comment]
> You can use the `LOG_LEVEL` env var to `LOG_LEVEL=info,text_generation_router=debug`.

Get.  Thanks!
