### ISSUE TITLE
Falcon 40b: Waiting for shard to be ready

### ISSUE THREAD

**Issue by Bongani** [huggingface/text-generation-inference#988]
### System Info

**Model being used:**
tiiuae/falcon-40b-instruct

**Hardware used:**
nvidia-tesla-t4 x 4
44 VCPU
120 GB CPU RAM
200 GB disk storage

**Deployment specificities:**
GCP GKE Autopilot

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

On GKE Autopilot cluster, I have a deployment yaml 
1. init container copies the model from a bucket to the node
`sh -c gcloud alpha storage cp -r gs://<mybucket>/falcon-40b-instruct /data`
2. launches the text-inference docker image
`text-generation-launcher --model-id tiiuae/falcon-40b-instruct --quantize bitsandbytes --num-shard 4 --huggingface-hub-cache /usr/src/falcon-40b-instruct --weights-cache-override /usr/src/falcon-40b-instruct`
3. The container starts and appears to be in a process of loading the model but soon hits a point where the logs show " Waiting for shard to be ready...". Then after a minute the container dies and tries to start again

I am running against 4 nvidia-tesla-t4, as I cannot seem to claim a single A100 in my region.

### Expected behavior

The docker image to work and ability to serve text inference

**Comment by kbmlcoding** [comment]
did you try using docker images? most likely this could happen if you do not have enough GPU RAM

**Comment by Narsil** [comment]
Also if the transfer speed from GS is too slow (try putting everything on a local nvme to confirm that)

**Comment by Bongani** [comment]
I ended being able to change the GPU to 2 x A100 40Gb, and finally was able to launch the service with no issue.

**Comment by Narsil** [comment]
Closing then.
