### ISSUE TITLE
[Question] How does TGI achieve very large concurrency (without queuing)?

### ISSUE THREAD

**Issue by PYNing** [huggingface/text-generation-inference#991]
Thank you for your work！

In my tests, I found that even if the **BatchSize and SeqLen are very large** (the device memory requirement is much larger than the actual total device memory), the TGI service will not crash, but will slow down. What I want to know is:

(1) Does TGI use a technology similar to offload (temporarily moving the weights and KV cache that need to be used from host memory to device memory)?

(2) If yes, is this technology implemented by TGI or other libraries of Hugging Face?

(3) If not, what technology is used to achieve this (other than queuing)?

**Comment by hahmad2008** [comment]
@PYNing are you able to enable the kv cache in TGI?
