### ISSUE TITLE
is there a way to run Phind/Phind-CodeLlama-34B-v2 ?

### ISSUE THREAD

**Issue by yairVanti** [huggingface/text-generation-inference#992]
### System Info

1.0.3 docker version
80GB memory , A100 gpu.

### Information

- [ ] Docker
- [ ] The CLI directly

### Tasks

- [ ] An officially supported command
- [ ] My own modifications

### Reproduction

when running the docker with model=Phind/Phind-CodeLlama-34B-v2 :
`sudo docker run -d --gpus all --shm-size 1g -e HUGGING_FACE_HUB_TOKEN=$token -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --max-total-tokens 4096 --max-input-length 3000 --quantize bitsandbytes --json-output --model-id $model`

i get this error 
`{"timestamp":"2023-09-07T05:54:41.266700Z","level":"ERROR","fields":{"message":"Shard complete standard error output:\n\nYou are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.\nTraceback (most recent call last):\n\n  File \"/opt/conda/bin/text-generation-server\", line 8, in <module>\n    sys.exit(app())\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py\", line 81, in serve\n    server.serve(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 184, in serve\n    asyncio.run(\n\n  File \"/opt/conda/lib/python3.9/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n\n  File \"/opt/conda/lib/python3.9/asyncio/base_events.py\", line 647, in run_until_complete\n    return future.result()\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py\", line 136, in serve_inner\n    model = get_model(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py\", line 185, in get_model\n    return FlashLlama(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_llama.py\", line 67, in __init__\n    model = FlashLlamaForCausalLM(config, weights)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py\", line 456, in __init__\n    self.model = FlashLlamaModel(config, weights)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py\", line 394, in __init__\n    [\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py\", line 395, in <listcomp>\n    FlashLlamaLayer(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py\", line 331, in __init__\n    self.self_attn = FlashLlamaAttention(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_llama_modeling.py\", line 188, in __init__\n    self.rotary_emb = PositionRotaryEmbedding.load(\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py\", line 474, in load\n    inv_freq = weights.get_tensor(f\"{prefix}.inv_freq\")\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py\", line 66, in get_tensor\n    filename, tensor_name = self.get_filename(tensor_name)\n\n  File \"/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py\", line 53, in get_filename\n    raise RuntimeError(f\"weight {tensor_name} does not exist\")\n\nRuntimeError: weight model.layers.0.self_attn.rotary_emb.inv_freq does not exist\n"},"target":"text_generation_launcher","span":{"rank":0,"name":"shard-manager"},"spans":[{"rank":0,"name":"shard-manager"}]}`

### Expected behavior

run smoothly

**Comment by dongs0104** [comment]
in docker version 1.0.3 code is change https://github.com/huggingface/text-generation-inference/blob/5485c142e87a182f2eee713a6b056ee38bd901f5/server/text_generation_server/models/custom_modeling/flash_llama_modeling.py#L193 
in my case it's work fine have to check your docker version

**Comment by Narsil** [comment]
> nv_freq = weights.get_tensor(f\"{prefix}.inv_freq\")\n\n  

You're using an old version, which doesn't work on llamav2(codellama). Just use `--pull always`
